# Generated by Django 5.2.16 on 2026-07-26 19:24

import django.contrib.postgres.fields
import django.db.models.deletion
import maru.authorization.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_scope_and_archive_guards"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=80,
                        validators=[maru.authorization.models.validate_role_code],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("version", models.PositiveIntegerField()),
                (
                    "capability_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=120),
                        size=None,
                        validators=[
                            maru.authorization.models.validate_capability_codes
                        ],
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_bundles",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "code", "-version", "id"),
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(max_length=240)),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to="events.eventedition",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role_bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="authorization.rolebundle",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "principal_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CapabilityGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capability_code",
                    models.CharField(
                        max_length=120,
                        validators=[maru.authorization.models.validate_capability_code],
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(max_length=240)),
                (
                    "delegated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegations",
                        to="authorization.capabilitygrant",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capability_grants",
                        to="events.eventedition",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capability_grants_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capability_grants",
                        to="organizations.organization",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capability_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": (
                    "organization_id",
                    "principal_id",
                    "capability_code",
                    "id",
                ),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_at__isnull", True),
                            ("expires_at__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="capability_grant_expiry_after_start",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rolebundle",
            constraint=models.UniqueConstraint(
                fields=("organization", "code", "version"),
                name="role_bundle_version_unique_within_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_at__isnull", True),
                    ("expires_at__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="role_assignment_expiry_after_start",
            ),
        ),
    ]
