# Generated by Django 5.2.16 on 2026-08-08 17:45

import django.core.validators
import django.db.models.deletion
import maru.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authorization", "0013_charity_capabilities_and_resource_kind"),
        ("events", "0009_edition_workspace_downgrade_fence"),
        ("organizations", "0013_runtime_executable_function_hardening"),
        ("workforce", "0007_structure_write_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "target_adapter_kind",
                    models.CharField(
                        choices=[
                            ("merch_submission", "Merchandise submission"),
                            ("dj_set", "DJ set"),
                            ("fursuit_dance_competition", "Fursuit Dance Competition"),
                            ("maid_cafe", "Maid Cafe"),
                            ("adult_fursuit_striptease", "Adult Fursuit Striptease"),
                            ("volunteer", "Volunteer"),
                            ("feedback", "Feedback"),
                            ("idea", "Idea"),
                            ("damage_report", "SecOps damage report"),
                            ("helper", "Time-bounded helper"),
                        ],
                        max_length=48,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, max_length=4000)),
                ("purpose", models.CharField(max_length=500)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("C1", "Internal"),
                            ("C2", "Personal"),
                            ("C3", "Restricted"),
                            ("C4", "Security critical"),
                        ],
                        default="C2",
                        max_length=2,
                    ),
                ),
                (
                    "eligibility_kind",
                    models.CharField(
                        choices=[
                            ("authenticated_person", "Authenticated person"),
                            ("edition_participant", "Edition participant"),
                            ("registered_attendee", "Registered attendee"),
                            ("confirmed_attendee", "Confirmed attendee"),
                            ("active_volunteer", "Active volunteer"),
                        ],
                        default="authenticated_person",
                        max_length=32,
                    ),
                ),
                (
                    "max_submissions_per_person",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("opens_at", models.DateTimeField()),
                ("closes_at", models.DateTimeField()),
                ("applicant_edit_until", models.DateTimeField()),
                (
                    "minimum_age",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
                (
                    "audience_policy_code",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_application_policy_code",
                                message="Use a stable versioned policy code.",
                                regex="^[a-z][a-z0-9_.:-]{2,119}$",
                            )
                        ],
                    ),
                ),
                (
                    "retention_policy_code",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_application_policy_code",
                                message="Use a stable versioned policy code.",
                                regex="^[a-z][a-z0-9_.:-]{2,119}$",
                            )
                        ],
                    ),
                ),
                (
                    "age_policy_code",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_application_policy_code",
                                message="Use a stable versioned policy code.",
                                regex="^[a-z][a-z0-9_.:-]{2,119}$",
                            )
                        ],
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "retired_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_definitions_activated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_definitions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_definitions",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_definitions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_definitions_retired",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "code", "-version", "id"),
            },
        ),
        migrations.CreateModel(
            name="ApplicationFileReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("clean", "Clean"), ("rejected", "Rejected")],
                        max_length=16,
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("media_type", models.CharField(max_length=120)),
                ("storage_key", models.CharField(max_length=500)),
                ("scanner_receipt", models.CharField(max_length=240)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_file_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_file_receipts",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_file_receipts",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationOwnerDepartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_department_links",
                        to="applications.applicationdefinition",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_application_definitions",
                        to="workforce.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationReviewerPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="named_application_review_queues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewer_people",
                        to="applications.applicationdefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationReviewerRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewer_roles",
                        to="applications.applicationdefinition",
                    ),
                ),
                (
                    "role_bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_review_queues",
                        to="authorization.rolebundle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("help_text", models.TextField(blank=True, max_length=2000)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(65535)]
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="applications.applicationdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ("definition_id", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="ApplicationQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Short text"),
                            ("long_text", "Long text"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("single_choice", "Single choice"),
                            ("multiple_choice", "Multiple choice"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("instant", "Date and time"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("url", "URL"),
                            ("address", "Address"),
                            ("person_reference", "Person reference"),
                            ("domain_reference", "Domain reference"),
                            ("safe_file", "Safety-checked file"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("help_text", models.TextField(blank=True, max_length=2000)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(65535)]
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("options", models.JSONField(blank=True, default=list)),
                ("minimum_length", models.PositiveIntegerField(blank=True, null=True)),
                ("maximum_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "minimum_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "maximum_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "maximum_choices",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "reference_kind",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_application_reference_kind",
                                message="Use a registered reference kind.",
                                regex="^[a-z][a-z0-9_.:-]{0,79}$",
                            )
                        ],
                    ),
                ),
                (
                    "source_binding",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No automatic source"),
                            ("account.display_name", "Account display name"),
                            ("registration.telegram", "Registration Telegram contact"),
                        ],
                        max_length=32,
                    ),
                ),
                ("condition", models.JSONField(blank=True, default=dict)),
                ("purpose", models.CharField(max_length=500)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("C1", "Internal"),
                            ("C2", "Personal"),
                            ("C3", "Restricted"),
                            ("C4", "Security critical"),
                        ],
                        max_length=2,
                    ),
                ),
                ("applicant_visible", models.BooleanField(default=True)),
                ("applicant_writable", models.BooleanField(default=True)),
                ("staff_visible", models.BooleanField(default=True)),
                ("staff_writable", models.BooleanField(default=False)),
                ("reviewer_visible", models.BooleanField(default=True)),
                ("public_after_approval", models.BooleanField(default=False)),
                ("api_projection", models.BooleanField(default=True)),
                (
                    "retention_policy_code",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_application_policy_code",
                                message="Use a stable versioned policy code.",
                                regex="^[a-z][a-z0-9_.:-]{2,119}$",
                            )
                        ],
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="applications.applicationdefinition",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="applications.applicationsection",
                    ),
                ),
            ],
            options={
                "ordering": ("definition_id", "section__position", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="ApplicationSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ordinal", models.PositiveSmallIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("changes_requested", "Changes requested"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="applications.applicationdefinition",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_submissions",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_submissions",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ApplicationReviewDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("start_review", "Start review"),
                            ("request_changes", "Request changes"),
                            ("accept", "Accept"),
                            ("reject", "Reject"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("changes_requested", "Changes requested"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("changes_requested", "Changes requested"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "reviewer_basis",
                    models.CharField(
                        choices=[
                            ("immutable_role", "Immutable role version"),
                            ("named_person", "Named person"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_review_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer_role_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_review_decisions",
                        to="authorization.rolebundle",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to="applications.applicationsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ("submission_id", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="ApplicationCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("definition_created", "Definition created"),
                            ("successor_created", "Successor created"),
                            ("definition_configured", "Definition configured"),
                            ("section_added", "Section added"),
                            ("question_added", "Question added"),
                            ("definition_activated", "Definition activated"),
                            ("definition_retired", "Definition retired"),
                            ("submission_started", "Submission started"),
                            ("answer_revised", "Answer revised"),
                            ("application_submitted", "Application submitted"),
                            ("review_decided", "Review decided"),
                        ],
                        max_length=32,
                    ),
                ),
                ("retry_key", models.UUIDField()),
                ("request_digest", models.CharField(max_length=64)),
                ("correlation_id", models.UUIDField()),
                ("source_channel", models.CharField(max_length=32)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("resulting_version", models.PositiveBigIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_command_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_command_receipts",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_command_receipts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="command_receipts",
                        to="applications.applicationdefinition",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="command_receipts",
                        to="applications.applicationsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ApplicationAnswerRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("question_key", models.SlugField(editable=False, max_length=80)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Short text"),
                            ("long_text", "Long text"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("single_choice", "Single choice"),
                            ("multiple_choice", "Multiple choice"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("instant", "Date and time"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("url", "URL"),
                            ("address", "Address"),
                            ("person_reference", "Person reference"),
                            ("domain_reference", "Domain reference"),
                            ("safe_file", "Safety-checked file"),
                        ],
                        editable=False,
                        max_length=32,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("C1", "Internal"),
                            ("C2", "Personal"),
                            ("C3", "Restricted"),
                            ("C4", "Security critical"),
                        ],
                        editable=False,
                        max_length=2,
                    ),
                ),
                ("value", models.JSONField(null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("applicant", "Applicant"),
                            ("staff_correction", "Staff correction"),
                            ("system_source", "Authoritative source binding"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=240)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_answer_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer_revisions",
                        to="applications.applicationquestion",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer_revisions",
                        to="applications.applicationsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ("submission_id", "question_key", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="ApplicationTargetRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adapter_kind",
                    models.CharField(
                        choices=[
                            ("merch_submission", "Merchandise submission"),
                            ("dj_set", "DJ set"),
                            ("fursuit_dance_competition", "Fursuit Dance Competition"),
                            ("maid_cafe", "Maid Cafe"),
                            ("adult_fursuit_striptease", "Adult Fursuit Striptease"),
                            ("volunteer", "Volunteer"),
                            ("feedback", "Feedback"),
                            ("idea", "Idea"),
                            ("damage_report", "SecOps damage report"),
                            ("helper", "Time-bounded helper"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_targets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_record",
                        to="applications.applicationsubmission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="applicationdefinition",
            index=models.Index(
                fields=["organization", "edition", "status", "opens_at"],
                name="app_definition_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationdefinition",
            constraint=models.UniqueConstraint(
                fields=("edition", "code", "version"),
                name="applications_definition_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("edition", "code"),
                name="applications_definition_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0), ("aggregate_version__gt", 0)),
                name="applications_definition_versions_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_submissions_per_person__gte", 1),
                    ("max_submissions_per_person__lte", 100),
                ),
                name="applications_definition_cardinality_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_age__lte", 120)),
                name="applications_definition_age_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("opens_at__lt", models.F("closes_at")),
                    ("applicant_edit_until__lte", models.F("closes_at")),
                ),
                name="applications_definition_windows_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("activated_at__isnull", True),
                        ("activated_by__isnull", True),
                        ("retired_at__isnull", True),
                        ("retired_by__isnull", True),
                        ("status", "draft"),
                    ),
                    models.Q(
                        ("activated_at__isnull", False),
                        ("activated_by__isnull", False),
                        ("retired_at__isnull", True),
                        ("retired_by__isnull", True),
                        ("status", "active"),
                    ),
                    models.Q(
                        ("activated_at__isnull", False),
                        ("activated_by__isnull", False),
                        ("retired_at__isnull", False),
                        ("retired_by__isnull", False),
                        ("status", "retired"),
                    ),
                    _connector="OR",
                ),
                name="applications_definition_lifecycle_evidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationfilereceipt",
            constraint=models.UniqueConstraint(
                fields=("organization", "storage_key"),
                name="applications_file_storage_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationfilereceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("size_bytes__gt", 0),
                    models.Q(("scanner_receipt", ""), _negated=True),
                    models.Q(("storage_key", ""), _negated=True),
                ),
                name="applications_file_evidence_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationownerdepartment",
            constraint=models.UniqueConstraint(
                fields=("definition", "department"),
                name="applications_owner_department_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationreviewerperson",
            constraint=models.UniqueConstraint(
                fields=("definition", "account"),
                name="applications_reviewer_person_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationreviewerrole",
            constraint=models.UniqueConstraint(
                fields=("definition", "role_bundle"),
                name="applications_reviewer_role_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationsection",
            constraint=models.UniqueConstraint(
                fields=("definition", "key"), name="applications_section_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationsection",
            constraint=models.UniqueConstraint(
                fields=("definition", "position"),
                name="applications_section_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationquestion",
            constraint=models.UniqueConstraint(
                fields=("definition", "key"), name="applications_question_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationquestion",
            constraint=models.UniqueConstraint(
                fields=("section", "position"),
                name="applications_question_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_length__isnull", True),
                    ("maximum_length__isnull", True),
                    ("minimum_length__lte", models.F("maximum_length")),
                    _connector="OR",
                ),
                name="applications_question_length_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_value__isnull", True),
                    ("maximum_value__isnull", True),
                    ("minimum_value__lte", models.F("maximum_value")),
                    _connector="OR",
                ),
                name="applications_question_numeric_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationsubmission",
            index=models.Index(
                fields=["organization", "edition", "state", "created_at"],
                name="app_submission_queue_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationsubmission",
            index=models.Index(
                fields=["account", "edition", "created_at"],
                name="app_submission_owner_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationsubmission",
            constraint=models.UniqueConstraint(
                fields=("definition", "account", "ordinal"),
                name="applications_submission_ordinal_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordinal__gt", 0), ("aggregate_version__gt", 0)),
                name="applications_submission_versions_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("decided_at__isnull", True),
                        ("state", "draft"),
                        ("submitted_at__isnull", True),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("decided_at__isnull", True),
                        (
                            "state__in",
                            ("submitted", "under_review", "changes_requested"),
                        ),
                        ("submitted_at__isnull", False),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("decided_at__isnull", False),
                        ("state__in", ("accepted", "rejected")),
                        ("submitted_at__isnull", False),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(("state", "withdrawn"), ("withdrawn_at__isnull", False)),
                    _connector="OR",
                ),
                name="applications_submission_state_evidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationreviewdecision",
            constraint=models.UniqueConstraint(
                fields=("submission", "sequence"),
                name="applications_review_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationreviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sequence__gt", 0), models.Q(("reason", ""), _negated=True)
                ),
                name="applications_review_evidence_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationreviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reviewer_basis", "immutable_role"),
                        ("reviewer_role_bundle__isnull", False),
                    ),
                    models.Q(
                        ("reviewer_basis", "named_person"),
                        ("reviewer_role_bundle__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="applications_review_basis_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("edition", "actor", "retry_key"),
                name="applications_command_retry_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resulting_version__gt", 0),
                    models.Q(("source_channel", ""), _negated=True),
                ),
                name="applications_command_evidence_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationanswerrevision",
            constraint=models.UniqueConstraint(
                fields=("submission", "question", "sequence"),
                name="applications_answer_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationanswerrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)),
                name="applications_answer_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationanswerrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reason", ""), ("source__in", ("applicant", "system_source"))
                    ),
                    models.Q(
                        ("source", "staff_correction"),
                        models.Q(("reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="applications_answer_staff_reason_required",
            ),
        ),
    ]
