# Generated by Django 5.2.17 on 2026-09-01 01:21
# ruff: noqa: D100, D101, E501, I001, RUF012

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import maru.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


REVERSE_PREFLIGHT_SQL = r"""
LOCK TABLE
    public.applications_applicationdefinition,
    public.applications_applicationanswerrevision,
    public.applications_applicationtargetrecord,
    public.applications_programmecall,
    public.applications_programmecalltrack,
    public.applications_programmecallformat,
    public.applications_programmecallcontributorfield,
    public.applications_programmeproposal,
    public.applications_programmeproposalselectionrevision,
    public.applications_programmeproposalcollaborator,
    public.applications_programmeproposalcollaboratortransition,
    public.applications_programmeproposalcontributorprofilerevision,
    public.applications_programmeproposalrevision,
    public.applications_programmeproposalrevisionanswer,
    public.applications_programmeproposalrevisioncontributor,
    public.applications_programmeproposalrevisionresponse,
    public.applications_programmecommandreceipt
IN ACCESS EXCLUSIVE MODE;

DO $applications_0004_reverse_preflight$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.applications_applicationdefinition
        WHERE target_adapter_kind = 'programme_item'
        LIMIT 1
    ) OR EXISTS (
        SELECT 1
        FROM public.applications_applicationanswerrevision
        WHERE source_version IS NOT NULL OR resulting_version IS NOT NULL
        LIMIT 1
    ) OR EXISTS (
        SELECT 1
        FROM public.applications_applicationtargetrecord
        WHERE adapter_kind = 'programme_item'
        LIMIT 1
    ) OR EXISTS (SELECT 1 FROM public.applications_programmecall LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.applications_programmecalltrack LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.applications_programmecallformat LIMIT 1)
       OR EXISTS (
           SELECT 1
           FROM public.applications_programmecallcontributorfield
           LIMIT 1
       )
       OR EXISTS (SELECT 1 FROM public.applications_programmeproposal LIMIT 1)
       OR EXISTS (
           SELECT 1
           FROM public.applications_programmeproposalselectionrevision
           LIMIT 1
       )
       OR EXISTS (
           SELECT 1
           FROM public.applications_programmeproposalcollaborator
           LIMIT 1
       )
       OR EXISTS (
           SELECT 1
           FROM public.applications_programmeproposalcollaboratortransition
           LIMIT 1
       )
       OR EXISTS (
           SELECT 1
           FROM public.applications_programmeproposalcontributorprofilerevision
           LIMIT 1
       )
       OR EXISTS (
           SELECT 1
           FROM public.applications_programmeproposalrevision
           LIMIT 1
       )
       OR EXISTS (
           SELECT 1
           FROM public.applications_programmeproposalrevisionanswer
           LIMIT 1
       )
       OR EXISTS (
           SELECT 1
           FROM public.applications_programmeproposalrevisioncontributor
           LIMIT 1
       )
       OR EXISTS (
           SELECT 1
           FROM public.applications_programmeproposalrevisionresponse
           LIMIT 1
       )
       OR EXISTS (
           SELECT 1
           FROM public.applications_programmecommandreceipt
           LIMIT 1
       )
    THEN
        RAISE EXCEPTION
            'Cannot remove Applications Programme schema while Programme evidence exists'
            USING ERRCODE = '23514';
    END IF;
END;
$applications_0004_reverse_preflight$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_integrity_function_execute_boundary"),
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("workforce", "0015_exact_assignment_adoption_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammeCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_collaborators",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(16),
                        ]
                    ),
                ),
                (
                    "content_policy_code",
                    models.CharField(
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_application_policy_code",
                                message="Use a stable versioned policy code.",
                                regex="^[a-z][a-z0-9_.:-]{2,119}$",
                            )
                        ],
                    ),
                ),
                (
                    "contributor_consent_policy_code",
                    models.CharField(
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_application_policy_code",
                                message="Use a stable versioned policy code.",
                                regex="^[a-z][a-z0-9_.:-]{2,119}$",
                            )
                        ],
                    ),
                ),
                (
                    "collaboration_retention_policy_code",
                    models.CharField(
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_application_policy_code",
                                message="Use a stable versioned policy code.",
                                regex="^[a-z][a-z0-9_.:-]{2,119}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "definition_id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeCallContributorField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field_code",
                    models.CharField(
                        choices=[
                            ("public_name", "Public name"),
                            ("biography", "Biography"),
                            ("pronouns", "Pronouns"),
                            ("website", "Website"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "lead_requirement",
                    models.CharField(
                        choices=[
                            ("hidden", "Hidden"),
                            ("optional", "Optional"),
                            ("required", "Required"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "collaborator_requirement",
                    models.CharField(
                        choices=[
                            ("hidden", "Hidden"),
                            ("optional", "Optional"),
                            ("required", "Required"),
                        ],
                        max_length=16,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ("call_id", "position", "field_code"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeCallFormat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("label", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, max_length=4000)),
                ("position", models.PositiveSmallIntegerField()),
                ("min_duration_minutes", models.PositiveSmallIntegerField()),
                ("default_duration_minutes", models.PositiveSmallIntegerField()),
                ("max_duration_minutes", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ("call_id", "position", "code"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeCallTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("label", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, max_length=4000)),
                ("position", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ("call_id", "position", "code"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aggregate_kind",
                    models.CharField(
                        choices=[("call", "Call"), ("proposal", "Proposal")],
                        max_length=16,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("call_created", "Call created"),
                            ("call_configured", "Call configured"),
                            ("call_activated", "Call activated"),
                            ("call_retired", "Call retired"),
                            ("call_successor_created", "Call successor created"),
                            ("proposal_started", "Proposal started"),
                            (
                                "proposal_selection_revised",
                                "Proposal selection revised",
                            ),
                            ("proposal_answer_revised", "Proposal answer revised"),
                            ("collaborator_invited", "Collaborator invited"),
                            ("collaborator_accepted", "Collaborator accepted"),
                            ("collaborator_declined", "Collaborator declined"),
                            ("collaborator_left", "Collaborator left"),
                            ("collaborator_removed", "Collaborator removed"),
                            ("collaborator_reinvited", "Collaborator reinvited"),
                            (
                                "contributor_profile_revised",
                                "Contributor profile revised",
                            ),
                            ("proposal_sealed", "Proposal sealed"),
                            ("proposal_reopened", "Proposal reopened"),
                            ("revision_acknowledged", "Revision acknowledged"),
                            ("revision_declined", "Revision declined"),
                            ("proposal_submitted", "Proposal submitted"),
                            ("proposal_withdrawn", "Proposal withdrawn"),
                        ],
                        max_length=32,
                    ),
                ),
                ("retry_key", models.UUIDField()),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_application_digest",
                                message="Use a lower-case SHA-256 digest.",
                                regex="^[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("correlation_id", models.UUIDField()),
                (
                    "source_channel",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_application_source_channel",
                                message="Use a registered lower-case source channel.",
                                regex="^[a-z][a-z0-9_-]*\\Z",
                            )
                        ],
                    ),
                ),
                ("target_id", models.UUIDField()),
                (
                    "result_kind",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("track", "Track"),
                            ("format", "Format"),
                            ("contributor_field", "Contributor field"),
                            ("proposal", "Proposal"),
                            ("selection_revision", "Selection revision"),
                            ("answer_revision", "Answer revision"),
                            ("collaborator", "Collaborator"),
                            ("collaborator_transition", "Collaborator transition"),
                            ("profile_revision", "Profile revision"),
                            ("proposal_revision", "Proposal revision"),
                            ("revision_response", "Revision response"),
                        ],
                        max_length=32,
                    ),
                ),
                ("expected_version", models.PositiveBigIntegerField()),
                ("resulting_version", models.PositiveBigIntegerField()),
            ],
            options={
                "ordering": ("edition_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sealed", "Sealed"),
                            ("submitted", "Submitted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeProposalCollaborator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("left", "Left"),
                            ("removed", "Removed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("generation", models.PositiveIntegerField()),
                ("invite_expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("proposal_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeProposalCollaboratorTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("generation", models.PositiveIntegerField()),
                (
                    "from_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("left", "Left"),
                            ("removed", "Removed"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("left", "Left"),
                            ("removed", "Removed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("invite_expires_at", models.DateTimeField(blank=True, null=True)),
                ("source_version", models.PositiveBigIntegerField()),
                ("resulting_version", models.PositiveBigIntegerField()),
            ],
            options={
                "ordering": ("collaborator_id", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeProposalContributorProfileRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("public_name", models.CharField(blank=True, max_length=160)),
                ("biography", models.TextField(blank=True, max_length=4000)),
                ("pronouns", models.CharField(blank=True, max_length=160)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("proposed_for_publication", models.BooleanField(default=False)),
                (
                    "consent_policy_code",
                    models.CharField(
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_application_policy_code",
                                message="Use a stable versioned policy code.",
                                regex="^[a-z][a-z0-9_.:-]{2,119}$",
                            )
                        ],
                    ),
                ),
                ("consent_acknowledged", models.BooleanField(default=False)),
                (
                    "digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_application_digest",
                                message="Use a lower-case SHA-256 digest.",
                                regex="^[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("source_version", models.PositiveBigIntegerField()),
                ("resulting_version", models.PositiveBigIntegerField()),
            ],
            options={
                "ordering": ("proposal_id", "account_id", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeProposalRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("definition_version", models.PositiveIntegerField()),
                ("source_version", models.PositiveBigIntegerField()),
                ("resulting_version", models.PositiveBigIntegerField()),
                (
                    "digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_application_digest",
                                message="Use a lower-case SHA-256 digest.",
                                regex="^[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("sealed_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("proposal_id", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeProposalRevisionAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_key", models.SlugField(editable=False, max_length=80)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Short text"),
                            ("long_text", "Long text"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("single_choice", "Single choice"),
                            ("multiple_choice", "Multiple choice"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("instant", "Date and time"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("url", "URL"),
                            ("address", "Address"),
                            ("person_reference", "Person reference"),
                            ("domain_reference", "Domain reference"),
                            ("safe_file", "Safety-checked file"),
                        ],
                        editable=False,
                        max_length=32,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("C1", "Internal"),
                            ("C2", "Personal"),
                            ("C3", "Restricted"),
                            ("C4", "Security critical"),
                        ],
                        editable=False,
                        max_length=2,
                    ),
                ),
            ],
            options={
                "ordering": ("revision_id", "question_key", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeProposalRevisionContributor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("lead", "Lead"), ("collaborator", "Collaborator")],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ("revision_id", "role", "account_id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeProposalRevisionResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("acknowledged", "Acknowledged"),
                            ("declined", "Declined"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_version", models.PositiveBigIntegerField()),
                ("resulting_version", models.PositiveBigIntegerField()),
                ("responded_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("revision_id", "responded_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeProposalSelectionRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("requested_duration_minutes", models.PositiveSmallIntegerField()),
                ("source_version", models.PositiveBigIntegerField()),
                ("resulting_version", models.PositiveBigIntegerField()),
            ],
            options={
                "ordering": ("proposal_id", "sequence", "id"),
            },
        ),
        migrations.AddField(
            model_name="applicationanswerrevision",
            name="resulting_version",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationanswerrevision",
            name="source_version",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicationdefinition",
            name="target_adapter_kind",
            field=models.CharField(
                choices=[
                    ("merch_submission", "Merchandise submission"),
                    ("dj_set", "DJ set"),
                    ("fursuit_dance_competition", "Fursuit Dance Competition"),
                    ("maid_cafe", "Maid Cafe"),
                    ("adult_fursuit_striptease", "Adult Fursuit Striptease"),
                    ("volunteer", "Volunteer"),
                    ("feedback", "Feedback"),
                    ("idea", "Idea"),
                    ("damage_report", "SecOps damage report"),
                    ("helper", "Time-bounded helper"),
                    ("programme_item", "Programme item"),
                ],
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="applicationtargetrecord",
            name="adapter_kind",
            field=models.CharField(
                choices=[
                    ("merch_submission", "Merchandise submission"),
                    ("dj_set", "DJ set"),
                    ("fursuit_dance_competition", "Fursuit Dance Competition"),
                    ("maid_cafe", "Maid Cafe"),
                    ("adult_fursuit_striptease", "Adult Fursuit Striptease"),
                    ("volunteer", "Volunteer"),
                    ("feedback", "Feedback"),
                    ("idea", "Idea"),
                    ("damage_report", "SecOps damage report"),
                    ("helper", "Time-bounded helper"),
                    ("programme_item", "Programme item"),
                ],
                max_length=48,
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationanswerrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("resulting_version__isnull", True),
                        ("source_version__isnull", True),
                    ),
                    models.Q(
                        (
                            "resulting_version",
                            django.db.models.expressions.CombinedExpression(
                                models.F("source_version"), "+", models.Value(1)
                            ),
                        ),
                        ("source_version__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="applications_answer_version_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationanswerrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resulting_version__isnull", False)),
                fields=("submission", "resulting_version"),
                name="applications_answer_result_version_uq",
            ),
        ),
        migrations.AddField(
            model_name="programmecall",
            name="definition",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_call",
                to="applications.applicationdefinition",
            ),
        ),
        migrations.AddField(
            model_name="programmecall",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_calls",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmecall",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_calls",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmecall",
            name="owner_department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_calls_owned",
                to="workforce.department",
            ),
        ),
        migrations.AddField(
            model_name="programmecallcontributorfield",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contributor_fields",
                to="applications.programmecall",
            ),
        ),
        migrations.AddField(
            model_name="programmecallcontributorfield",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_call_contributor_fields",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmecallcontributorfield",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_call_contributor_fields",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmecallformat",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="formats",
                to="applications.programmecall",
            ),
        ),
        migrations.AddField(
            model_name="programmecallformat",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_call_formats",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmecallformat",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_call_formats",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmecalltrack",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracks",
                to="applications.programmecall",
            ),
        ),
        migrations.AddField(
            model_name="programmecalltrack",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_call_tracks",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmecalltrack",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_call_tracks",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmecommandreceipt",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_application_command_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmecommandreceipt",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_command_receipts",
                to="applications.applicationdefinition",
            ),
        ),
        migrations.AddField(
            model_name="programmecommandreceipt",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_application_command_receipts",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmecommandreceipt",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_application_command_receipts",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmecommandreceipt",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_command_receipts",
                to="applications.applicationsubmission",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposal",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proposals",
                to="applications.programmecall",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposal",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposals",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposal",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposals",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposal",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal",
                to="applications.applicationsubmission",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcollaborator",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_collaborations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcollaborator",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_collaborators",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcollaborator",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_collaborators",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcollaborator",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collaborators",
                to="applications.programmeproposal",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcollaboratortransition",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_collaborator_transitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcollaboratortransition",
            name="collaborator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transitions",
                to="applications.programmeproposalcollaborator",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcollaboratortransition",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_collaborator_transitions",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcollaboratortransition",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_collaborator_transitions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcollaboratortransition",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collaborator_transitions",
                to="applications.programmeproposal",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcontributorprofilerevision",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_contributor_profile_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcontributorprofilerevision",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_contributor_profile_revisions_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcontributorprofilerevision",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_contributor_profile_revisions",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcontributorprofilerevision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_contributor_profile_revisions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcontributorprofilerevision",
            name="predecessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="successors",
                to="applications.programmeproposalcontributorprofilerevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalcontributorprofilerevision",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contributor_profile_revisions",
                to="applications.programmeproposal",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevision",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revisions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevision",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revisions",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revisions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevision",
            name="predecessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="successors",
                to="applications.programmeproposalrevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevision",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="applications.programmeproposal",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposal",
            name="sealed_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sealed_proposal_projections",
                to="applications.programmeproposalrevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposal",
            name="submitted_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_proposal_projections",
                to="applications.programmeproposalrevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionanswer",
            name="answer_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revision_answers",
                to="applications.applicationanswerrevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionanswer",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revision_answers",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionanswer",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revision_answers",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revision_answers",
                to="applications.applicationquestion",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionanswer",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answers",
                to="applications.programmeproposalrevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisioncontributor",
            name="accepted_transition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revision_contributors",
                to="applications.programmeproposalcollaboratortransition",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisioncontributor",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revision_contributions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisioncontributor",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revision_contributors",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisioncontributor",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revision_contributors",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisioncontributor",
            name="profile_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revision_contributors",
                to="applications.programmeproposalcontributorprofilerevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisioncontributor",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contributors",
                to="applications.programmeproposalrevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionresponse",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revision_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionresponse",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revision_responses_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionresponse",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="applications.programmeproposalrevisioncontributor",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionresponse",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revision_responses",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionresponse",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_revision_responses",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionresponse",
            name="profile_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revision_responses",
                to="applications.programmeproposalcontributorprofilerevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevisionresponse",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="applications.programmeproposalrevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalselectionrevision",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_selection_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalselectionrevision",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_selection_revisions",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalselectionrevision",
            name="format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proposal_selection_revisions",
                to="applications.programmecallformat",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalselectionrevision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_proposal_selection_revisions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalselectionrevision",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="selection_revisions",
                to="applications.programmeproposal",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalselectionrevision",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proposal_selection_revisions",
                to="applications.programmecalltrack",
            ),
        ),
        migrations.AddField(
            model_name="programmeproposalrevision",
            name="selection_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sealed_proposal_revisions",
                to="applications.programmeproposalselectionrevision",
            ),
        ),
        migrations.AddIndex(
            model_name="programmecall",
            index=models.Index(
                fields=["organization", "edition"], name="app_prg_call_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_collaborators__gte", 0), ("max_collaborators__lte", 16)
                ),
                name="applications_programme_call_collaborators_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("content_policy_code", ""), _negated=True),
                    models.Q(("contributor_consent_policy_code", ""), _negated=True),
                    models.Q(
                        ("collaboration_retention_policy_code", ""), _negated=True
                    ),
                ),
                name="applications_programme_call_policies_required",
            ),
        ),
        migrations.AddIndex(
            model_name="programmecallcontributorfield",
            index=models.Index(
                fields=["organization", "edition", "call", "position"],
                name="app_prg_field_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecallcontributorfield",
            constraint=models.UniqueConstraint(
                fields=("call", "field_code"),
                name="applications_prg_contributor_field_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecallcontributorfield",
            constraint=models.UniqueConstraint(
                fields=("call", "position"),
                name="applications_prg_contributor_position_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecallcontributorfield",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("position__gt", 0),
                    models.Q(
                        ("collaborator_requirement", "hidden"),
                        ("lead_requirement", "hidden"),
                        _negated=True,
                    ),
                ),
                name="applications_prg_contributor_field_visible",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecallcontributorfield",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "field_code__in",
                        ["public_name", "biography", "pronouns", "website"],
                    ),
                    ("lead_requirement__in", ["hidden", "optional", "required"]),
                    (
                        "collaborator_requirement__in",
                        ["hidden", "optional", "required"],
                    ),
                ),
                name="applications_prg_contributor_field_closed",
            ),
        ),
        migrations.AddIndex(
            model_name="programmecallformat",
            index=models.Index(
                fields=["organization", "edition", "call", "position"],
                name="app_prg_format_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecallformat",
            constraint=models.UniqueConstraint(
                fields=("call", "code"), name="applications_prg_format_code_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecallformat",
            constraint=models.UniqueConstraint(
                fields=("call", "position"), name="applications_prg_format_position_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecallformat",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("position__gt", 0),
                    models.Q(("label", ""), _negated=True),
                    ("min_duration_minutes__gt", 0),
                    ("default_duration_minutes__gte", models.F("min_duration_minutes")),
                    ("default_duration_minutes__lte", models.F("max_duration_minutes")),
                ),
                name="applications_prg_format_duration_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="programmecalltrack",
            index=models.Index(
                fields=["organization", "edition", "call", "position"],
                name="app_prg_track_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecalltrack",
            constraint=models.UniqueConstraint(
                fields=("call", "code"), name="applications_prg_track_code_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecalltrack",
            constraint=models.UniqueConstraint(
                fields=("call", "position"), name="applications_prg_track_position_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecalltrack",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("position__gt", 0), models.Q(("label", ""), _negated=True)
                ),
                name="applications_prg_track_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="programmecommandreceipt",
            index=models.Index(
                fields=["organization", "edition", "action", "created_at"],
                name="app_prg_command_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("edition", "actor", "retry_key"),
                name="applications_prg_command_retry_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("definition__isnull", False), ("submission__isnull", True)
                ),
                fields=("definition", "resulting_version"),
                name="applications_prg_call_command_result_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submission__isnull", False)),
                fields=("submission", "resulting_version"),
                name="applications_prg_proposal_command_result_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_version__gte", 0),
                    (
                        "resulting_version",
                        django.db.models.expressions.CombinedExpression(
                            models.F("expected_version"), "+", models.Value(1)
                        ),
                    ),
                    models.Q(("source_channel", ""), _negated=True),
                ),
                name="applications_prg_command_version_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("aggregate_kind", "call"),
                        ("definition__isnull", False),
                        ("submission__isnull", True),
                    ),
                    models.Q(
                        ("aggregate_kind", "proposal"),
                        ("definition__isnull", False),
                        ("submission__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="applications_prg_command_aggregate_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("aggregate_kind__in", ["call", "proposal"]),
                    (
                        "action__in",
                        [
                            "call_created",
                            "call_configured",
                            "call_activated",
                            "call_retired",
                            "call_successor_created",
                            "proposal_started",
                            "proposal_selection_revised",
                            "proposal_answer_revised",
                            "collaborator_invited",
                            "collaborator_accepted",
                            "collaborator_declined",
                            "collaborator_left",
                            "collaborator_removed",
                            "collaborator_reinvited",
                            "contributor_profile_revised",
                            "proposal_sealed",
                            "proposal_reopened",
                            "revision_acknowledged",
                            "revision_declined",
                            "proposal_submitted",
                            "proposal_withdrawn",
                        ],
                    ),
                    (
                        "result_kind__in",
                        [
                            "call",
                            "track",
                            "format",
                            "contributor_field",
                            "proposal",
                            "selection_revision",
                            "answer_revision",
                            "collaborator",
                            "collaborator_transition",
                            "profile_revision",
                            "proposal_revision",
                            "revision_response",
                        ],
                    ),
                ),
                name="applications_prg_command_catalogs_closed",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeproposalcollaborator",
            index=models.Index(
                fields=["organization", "edition", "proposal", "state"],
                name="app_prg_collab_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcollaborator",
            constraint=models.UniqueConstraint(
                fields=("proposal", "account"),
                name="applications_prg_collaborator_account_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcollaborator",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation__gt", 0)),
                name="applications_prg_collaborator_generation_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcollaborator",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ["invited", "accepted", "declined", "left", "removed"],
                    )
                ),
                name="applications_prg_collaborator_state_closed",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeproposalcollaboratortransition",
            index=models.Index(
                fields=["organization", "edition", "proposal", "collaborator"],
                name="app_prg_collab_hist_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcollaboratortransition",
            constraint=models.UniqueConstraint(
                fields=("collaborator", "sequence"),
                name="applications_prg_collab_transition_sequence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcollaboratortransition",
            constraint=models.UniqueConstraint(
                fields=("proposal", "resulting_version"),
                name="applications_prg_collab_transition_result_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcollaboratortransition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sequence__gt", 0),
                    ("generation__gt", 0),
                    ("source_version__gt", 0),
                    (
                        "resulting_version",
                        django.db.models.expressions.CombinedExpression(
                            models.F("source_version"), "+", models.Value(1)
                        ),
                    ),
                ),
                name="applications_prg_collab_transition_version_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcollaboratortransition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("invite_expires_at__isnull", False), ("to_state", "invited")
                    ),
                    models.Q(
                        models.Q(("to_state", "invited"), _negated=True),
                        ("invite_expires_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="applications_prg_collab_transition_expiry_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcollaboratortransition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "to_state__in",
                        ["invited", "accepted", "declined", "left", "removed"],
                    ),
                    models.Q(
                        ("from_state__isnull", True),
                        (
                            "from_state__in",
                            ["invited", "accepted", "declined", "left", "removed"],
                        ),
                        _connector="OR",
                    ),
                ),
                name="applications_prg_collab_transition_states_closed",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeproposalcontributorprofilerevision",
            index=models.Index(
                fields=["organization", "edition", "proposal", "account"],
                name="app_prg_profile_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcontributorprofilerevision",
            constraint=models.UniqueConstraint(
                fields=("proposal", "account", "sequence"),
                name="applications_prg_profile_sequence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcontributorprofilerevision",
            constraint=models.UniqueConstraint(
                fields=("proposal", "account", "digest"),
                name="applications_prg_profile_digest_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcontributorprofilerevision",
            constraint=models.UniqueConstraint(
                fields=("proposal", "resulting_version"),
                name="applications_prg_profile_result_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcontributorprofilerevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("predecessor__isnull", False)),
                fields=("proposal", "account", "predecessor"),
                name="applications_prg_profile_predecessor_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcontributorprofilerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sequence__gt", 0),
                    ("source_version__gte", 0),
                    (
                        "resulting_version",
                        django.db.models.expressions.CombinedExpression(
                            models.F("source_version"), "+", models.Value(1)
                        ),
                    ),
                    models.Q(("consent_policy_code", ""), _negated=True),
                ),
                name="applications_prg_profile_version_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalcontributorprofilerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("consent_acknowledged", True),
                        ("proposed_for_publication", True),
                    ),
                    models.Q(
                        ("biography", ""),
                        ("pronouns", ""),
                        ("proposed_for_publication", False),
                        ("public_name", ""),
                        ("website", ""),
                    ),
                    _connector="OR",
                ),
                name="applications_prg_profile_public_consent",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeproposal",
            index=models.Index(
                fields=["organization", "edition", "state"],
                name="app_prg_proposal_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("sealed_revision__isnull", True),
                        ("state", "draft"),
                        ("submitted_revision__isnull", True),
                    ),
                    models.Q(
                        ("sealed_revision__isnull", False),
                        ("state", "sealed"),
                        ("submitted_revision__isnull", True),
                    ),
                    models.Q(
                        ("sealed_revision__isnull", False),
                        ("state", "submitted"),
                        ("submitted_revision", models.F("sealed_revision")),
                        ("submitted_revision__isnull", False),
                    ),
                    ("state", "withdrawn"),
                    _connector="OR",
                ),
                name="applications_prg_proposal_pointer_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["draft", "sealed", "submitted", "withdrawn"])
                ),
                name="applications_prg_proposal_state_closed",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeproposalrevisionanswer",
            index=models.Index(
                fields=["organization", "edition", "revision"],
                name="app_prg_answer_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevisionanswer",
            constraint=models.UniqueConstraint(
                fields=("revision", "question"),
                name="applications_prg_revision_answer_question_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevisionanswer",
            constraint=models.UniqueConstraint(
                fields=("revision", "question_key"),
                name="applications_prg_revision_answer_key_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevisionanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "question_type__in",
                        [
                            "short_text",
                            "long_text",
                            "integer",
                            "decimal",
                            "boolean",
                            "single_choice",
                            "multiple_choice",
                            "date",
                            "time",
                            "instant",
                            "email",
                            "phone",
                            "url",
                            "address",
                            "person_reference",
                            "domain_reference",
                            "safe_file",
                        ],
                    ),
                    ("classification__in", ["C1", "C2", "C3", "C4"]),
                ),
                name="applications_prg_revision_answer_catalogs_closed",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeproposalrevisioncontributor",
            index=models.Index(
                fields=["organization", "edition", "revision", "role"],
                name="app_prg_rev_contrib_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevisioncontributor",
            constraint=models.UniqueConstraint(
                fields=("revision", "account"),
                name="applications_prg_revision_contributor_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevisioncontributor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "lead")),
                fields=("revision",),
                name="applications_prg_revision_one_lead_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevisioncontributor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("accepted_transition__isnull", True), ("role", "lead")),
                    models.Q(
                        ("accepted_transition__isnull", False), ("role", "collaborator")
                    ),
                    _connector="OR",
                ),
                name="applications_prg_revision_contributor_role_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevisioncontributor",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["lead", "collaborator"])),
                name="applications_prg_revision_contributor_role_closed",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeproposalrevisionresponse",
            index=models.Index(
                fields=["organization", "edition", "revision", "response"],
                name="app_prg_response_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevisionresponse",
            constraint=models.UniqueConstraint(
                fields=("revision", "contributor"),
                name="applications_prg_revision_response_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevisionresponse",
            constraint=models.UniqueConstraint(
                fields=("revision", "resulting_version"),
                name="applications_prg_response_result_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevisionresponse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_version__gt", 0),
                    (
                        "resulting_version",
                        django.db.models.expressions.CombinedExpression(
                            models.F("source_version"), "+", models.Value(1)
                        ),
                    ),
                ),
                name="applications_prg_response_version_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevisionresponse",
            constraint=models.CheckConstraint(
                condition=models.Q(("response__in", ["acknowledged", "declined"])),
                name="applications_prg_response_closed",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeproposalselectionrevision",
            index=models.Index(
                fields=["organization", "edition", "proposal", "sequence"],
                name="app_prg_select_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalselectionrevision",
            constraint=models.UniqueConstraint(
                fields=("proposal", "sequence"),
                name="applications_prg_selection_sequence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalselectionrevision",
            constraint=models.UniqueConstraint(
                fields=("proposal", "resulting_version"),
                name="applications_prg_selection_result_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalselectionrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sequence__gt", 0),
                    ("requested_duration_minutes__gt", 0),
                    ("source_version__gte", 0),
                    (
                        "resulting_version",
                        django.db.models.expressions.CombinedExpression(
                            models.F("source_version"), "+", models.Value(1)
                        ),
                    ),
                ),
                name="applications_prg_selection_version_step",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeproposalrevision",
            index=models.Index(
                fields=["organization", "edition", "proposal", "sequence"],
                name="app_prg_revision_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevision",
            constraint=models.UniqueConstraint(
                fields=("proposal", "sequence"),
                name="applications_prg_revision_sequence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevision",
            constraint=models.UniqueConstraint(
                fields=("proposal", "digest"),
                name="applications_prg_revision_digest_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevision",
            constraint=models.UniqueConstraint(
                fields=("proposal", "resulting_version"),
                name="applications_prg_revision_result_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("predecessor__isnull", False)),
                fields=("proposal", "predecessor"),
                name="applications_prg_revision_predecessor_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeproposalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sequence__gt", 0),
                    ("definition_version__gt", 0),
                    ("source_version__gt", 0),
                    (
                        "resulting_version",
                        django.db.models.expressions.CombinedExpression(
                            models.F("source_version"), "+", models.Value(1)
                        ),
                    ),
                ),
                name="applications_prg_revision_version_step",
            ),
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql=REVERSE_PREFLIGHT_SQL,
        ),
    ]
