"""Add Programme Department transition evidence and monotonic batch versions."""

# Generated by Django 5.2.17 on 2026-09-02 10:01

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Install the ownership-continuity persistence shape."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("applications", "0009_programme_import_populated_downgrade_fence"),
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("workforce", "0017_programme_import_department_fk_contract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list[object]] = [
        migrations.RemoveConstraint(
            model_name="programmecommandreceipt",
            name="applications_prg_command_catalogs_closed",
        ),
        migrations.RemoveConstraint(
            model_name="programmeimportbatch",
            name="applications_prg_imp_batch_state",
        ),
        migrations.RemoveConstraint(
            model_name="programmeimportcommandreceipt",
            name="applications_prg_imp_command_applied_count",
        ),
        migrations.RemoveConstraint(
            model_name="programmeimportpreviewrevision",
            name="applications_prg_imp_preview_bounds",
        ),
        migrations.AddField(
            model_name="programmecommandreceipt",
            name="destination_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_command_receipts_as_destination",
                to="workforce.department",
            ),
        ),
        migrations.AddField(
            model_name="programmecommandreceipt",
            name="source_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_command_receipts_as_source",
                to="workforce.department",
            ),
        ),
        migrations.AddField(
            model_name="programmeimportcommandreceipt",
            name="destination_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_import_command_receipts_as_destination",
                to="workforce.department",
            ),
        ),
        migrations.AddField(
            model_name="programmeimportcommandreceipt",
            name="source_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_import_command_receipts_as_source",
                to="workforce.department",
            ),
        ),
        migrations.AlterField(
            model_name="programmecommandreceipt",
            name="action",
            field=models.CharField(
                choices=[
                    ("call_created", "Call created"),
                    ("call_configured", "Call configured"),
                    ("call_reassigned", "Call reassigned"),
                    ("call_activated", "Call activated"),
                    ("call_retired", "Call retired"),
                    ("recovery_call_reassigned", "Recovery call reassigned"),
                    ("recovery_call_retired", "Recovery call retired"),
                    ("call_successor_created", "Call successor created"),
                    ("proposal_started", "Proposal started"),
                    ("proposal_selection_revised", "Proposal selection revised"),
                    ("proposal_answer_revised", "Proposal answer revised"),
                    ("collaborator_invited", "Collaborator invited"),
                    ("collaborator_accepted", "Collaborator accepted"),
                    ("collaborator_declined", "Collaborator declined"),
                    ("collaborator_left", "Collaborator left"),
                    ("collaborator_removed", "Collaborator removed"),
                    ("collaborator_reinvited", "Collaborator reinvited"),
                    ("contributor_profile_revised", "Contributor profile revised"),
                    ("proposal_sealed", "Proposal sealed"),
                    ("proposal_reopened", "Proposal reopened"),
                    ("revision_acknowledged", "Revision acknowledged"),
                    ("revision_declined", "Revision declined"),
                    ("proposal_submitted", "Proposal submitted"),
                    ("proposal_withdrawn", "Proposal withdrawn"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="programmeimportcommandreceipt",
            name="action",
            field=models.CharField(
                choices=[
                    ("batch_staged", "Batch staged"),
                    ("batch_reassigned", "Batch reassigned"),
                    ("batch_previewed", "Batch previewed"),
                    ("call_committed", "Call committed"),
                    ("proposal_claimed", "Proposal claimed"),
                    ("batch_discarded", "Batch discarded"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("aggregate_kind__in", ["call", "proposal"]),
                    (
                        "action__in",
                        [
                            "call_created",
                            "call_configured",
                            "call_reassigned",
                            "call_activated",
                            "call_retired",
                            "recovery_call_reassigned",
                            "recovery_call_retired",
                            "call_successor_created",
                            "proposal_started",
                            "proposal_selection_revised",
                            "proposal_answer_revised",
                            "collaborator_invited",
                            "collaborator_accepted",
                            "collaborator_declined",
                            "collaborator_left",
                            "collaborator_removed",
                            "collaborator_reinvited",
                            "contributor_profile_revised",
                            "proposal_sealed",
                            "proposal_reopened",
                            "revision_acknowledged",
                            "revision_declined",
                            "proposal_submitted",
                            "proposal_withdrawn",
                        ],
                    ),
                    (
                        "result_kind__in",
                        [
                            "call",
                            "track",
                            "format",
                            "contributor_field",
                            "proposal",
                            "selection_revision",
                            "answer_revision",
                            "collaborator",
                            "collaborator_transition",
                            "profile_revision",
                            "proposal_revision",
                            "revision_response",
                        ],
                    ),
                ),
                name="applications_prg_command_catalogs_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("action__in", ("call_reassigned", "recovery_call_reassigned")),
                        ("destination_department__isnull", False),
                        ("source_department__isnull", False),
                        models.Q(
                            ("source_department", models.F("destination_department")),
                            _negated=True,
                        ),
                    ),
                    models.Q(
                        ("action", "recovery_call_retired"),
                        ("destination_department__isnull", True),
                        ("source_department__isnull", False),
                    ),
                    models.Q(
                        models.Q(
                            (
                                "action__in",
                                (
                                    "call_reassigned",
                                    "recovery_call_reassigned",
                                    "recovery_call_retired",
                                ),
                            ),
                            _negated=True,
                        ),
                        ("destination_department__isnull", True),
                        ("source_department__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="applications_prg_command_department_transition",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeimportbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("aggregate_version__gt", 0),
                        ("discard_reason", ""),
                        ("discarded_at__isnull", True),
                        ("discarded_by__isnull", True),
                        ("state", "staged"),
                    ),
                    models.Q(
                        ("aggregate_version__gt", 1),
                        ("discarded_at__isnull", False),
                        ("discarded_by__isnull", False),
                        ("state", "discarded"),
                        models.Q(("discard_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="applications_prg_imp_batch_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeimportcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("action__in", ("call_committed", "proposal_claimed")),
                        ("applied_command_count__gte", 1),
                        ("applied_command_count__lte", 1001),
                    ),
                    models.Q(
                        (
                            "action__in",
                            (
                                "batch_staged",
                                "batch_reassigned",
                                "batch_previewed",
                                "batch_discarded",
                            ),
                        ),
                        ("applied_command_count", 0),
                    ),
                    _connector="OR",
                ),
                name="applications_prg_imp_command_applied_count",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeimportcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("action", "batch_reassigned"),
                        ("destination_department__isnull", False),
                        ("source_department__isnull", False),
                        models.Q(
                            ("source_department", models.F("destination_department")),
                            _negated=True,
                        ),
                    ),
                    models.Q(
                        models.Q(("action", "batch_reassigned"), _negated=True),
                        ("destination_department__isnull", True),
                        ("source_department__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="applications_prg_imp_command_department_transition",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeimportpreviewrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revision_number__gt", 0),
                    ("source_batch_version__gt", 0),
                    ("item_count__gte", 1),
                    ("item_count__lte", 1000),
                ),
                name="applications_prg_imp_preview_bounds",
            ),
        ),
    ]
