# Generated by Django 5.2.17 on 2026-09-05 09:54

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0012_programme_department_ownership_downgrade_fence"),
        ("audit", "0008_identity_retention_audit_uniqueness"),
        ("effects", "0003_effect_replay_receipts"),
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammeReviewCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("stage", models.PositiveSmallIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("waitlisted", "Wait-listed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision requested"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmeproposal",
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmeproposalrevision",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeReviewAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage", models.PositiveSmallIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting conflict declaration"),
                            ("active", "No conflict declared"),
                            ("recused", "Recused"),
                            ("removed", "Removed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("version", models.PositiveBigIntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmereviewcase",
                    ),
                ),
            ],
            options={
                "ordering": ("case_id", "stage", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeReviewEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveBigIntegerField()),
                ("stage", models.PositiveSmallIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("policy_created", "Create review policy"),
                            ("case_opened", "Open exact-revision review"),
                            ("reviewer_assigned", "Assign reviewer"),
                            ("conflict_cleared", "Declare no conflict"),
                            ("reviewer_recused", "Recuse self"),
                            ("reviewer_removed", "Remove reviewer"),
                            ("scored", "Submit independent scores"),
                            ("discussed", "Append peer discussion"),
                            ("moderated", "Moderate stage"),
                            ("stage_advanced", "Advance stage"),
                            ("stage_reopened", "Reopen an earlier review stage"),
                            ("decided", "Record accountable decision"),
                            ("acknowledged", "Acknowledge own decision"),
                        ],
                        max_length=24,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, max_length=2000)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmereviewassignment",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmereviewcase",
                    ),
                ),
            ],
            options={
                "ordering": ("case_id", "version"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeReviewDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("waitlisted", "Wait-listed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision requested"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(max_length=6002)),
                ("acknowledgement_required", models.BooleanField()),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmeproposalrevision",
                    ),
                ),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmereviewentry",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeDecisionAcknowledgement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmereviewdecision",
                    ),
                ),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmereviewentry",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeReviewPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveBigIntegerField()),
                ("stages", models.JSONField()),
                ("templates", models.JSONField()),
                (
                    "digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_application_digest",
                                message="Use a lower-case SHA-256 digest.",
                                regex="^[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("reason", models.TextField(max_length=2000)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmecall",
                    ),
                ),
            ],
            options={
                "ordering": ("call_id", "version"),
            },
        ),
        migrations.AddField(
            model_name="programmereviewcase",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="applications.programmereviewpolicy",
            ),
        ),
        migrations.CreateModel(
            name="ProgrammeReviewReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("retry_key", models.UUIDField()),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_application_digest",
                                message="Use a lower-case SHA-256 digest.",
                                regex="^[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("policy_created", "Create review policy"),
                            ("case_opened", "Open exact-revision review"),
                            ("reviewer_assigned", "Assign reviewer"),
                            ("conflict_cleared", "Declare no conflict"),
                            ("reviewer_recused", "Recuse self"),
                            ("reviewer_removed", "Remove reviewer"),
                            ("scored", "Submit independent scores"),
                            ("discussed", "Append peer discussion"),
                            ("moderated", "Moderate stage"),
                            ("stage_advanced", "Advance stage"),
                            ("stage_reopened", "Reopen an earlier review stage"),
                            ("decided", "Record accountable decision"),
                            ("acknowledged", "Acknowledge own decision"),
                        ],
                        max_length=24,
                    ),
                ),
                ("aggregate_id", models.UUIDField()),
                ("target_id", models.UUIDField()),
                ("expected_version", models.PositiveBigIntegerField()),
                ("resulting_version", models.PositiveBigIntegerField()),
                ("correlation_id", models.UUIDField()),
                (
                    "source_channel",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_application_source_channel",
                                message="Use a registered lower-case source channel.",
                                regex="^[a-z][a-z0-9_-]*\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "audit_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audit.auditevent",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmereviewcase",
                    ),
                ),
                (
                    "domain_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="effects.domainevent",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmereviewpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="programmereviewassignment",
            constraint=models.UniqueConstraint(
                fields=("case", "stage", "account"), name="app_prg_review_assignment_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereviewassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stage__lt", 8),
                    ("state__in", ["pending", "active", "recused", "removed"]),
                    ("version__gte", 2),
                ),
                name="app_prg_review_assignment_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereviewentry",
            constraint=models.UniqueConstraint(
                fields=("case", "version"), name="app_prg_review_entry_version_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereviewentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        [
                            "policy_created",
                            "case_opened",
                            "reviewer_assigned",
                            "conflict_cleared",
                            "reviewer_recused",
                            "reviewer_removed",
                            "scored",
                            "discussed",
                            "moderated",
                            "stage_advanced",
                            "stage_reopened",
                            "decided",
                            "acknowledged",
                        ],
                    ),
                    ("stage__lt", 8),
                    ("version__gte", 1),
                    models.Q(("action", "policy_created"), _negated=True),
                ),
                name="app_prg_review_entry_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome__in",
                        [
                            "open",
                            "waitlisted",
                            "accepted",
                            "rejected",
                            "revision_requested",
                        ],
                    ),
                    models.Q(("outcome", "open"), _negated=True),
                    models.Q(("message", ""), _negated=True),
                ),
                name="app_prg_review_decision_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmedecisionacknowledgement",
            constraint=models.UniqueConstraint(
                fields=("decision", "account"), name="app_prg_decision_ack_person_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereviewpolicy",
            constraint=models.UniqueConstraint(
                fields=("call", "version"), name="app_prg_review_policy_version_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereviewpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("version__gte", 1), models.Q(("reason", ""), _negated=True)
                ),
                name="app_prg_review_policy_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereviewcase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stage__lt", 8),
                    (
                        "state__in",
                        [
                            "open",
                            "waitlisted",
                            "accepted",
                            "rejected",
                            "revision_requested",
                        ],
                    ),
                    ("version__gte", 1),
                ),
                name="app_prg_review_case_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereviewreceipt",
            constraint=models.UniqueConstraint(
                fields=("edition", "actor", "retry_key"), name="app_prg_review_retry_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereviewreceipt",
            constraint=models.UniqueConstraint(
                fields=("aggregate_id", "resulting_version"),
                name="app_prg_review_result_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereviewreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "resulting_version",
                        django.db.models.expressions.CombinedExpression(
                            models.F("expected_version"), "+", models.Value(1)
                        ),
                    ),
                    (
                        "action__in",
                        [
                            "policy_created",
                            "case_opened",
                            "reviewer_assigned",
                            "conflict_cleared",
                            "reviewer_recused",
                            "reviewer_removed",
                            "scored",
                            "discussed",
                            "moderated",
                            "stage_advanced",
                            "stage_reopened",
                            "decided",
                            "acknowledged",
                        ],
                    ),
                    models.Q(("source_channel", ""), _negated=True),
                    models.Q(
                        models.Q(("action", "policy_created"), ("case__isnull", True)),
                        models.Q(
                            models.Q(("action", "policy_created"), _negated=True),
                            ("case__isnull", False),
                        ),
                        _connector="OR",
                    ),
                ),
                name="app_prg_review_receipt_shape",
            ),
        ),
    ]
