# Generated by Django 5.2.17 on 2026-09-06 13:38

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_programme_review_downgrade_fence"),
        ("authorization", "0025_programme_conversion_capability"),
        ("audit", "0008_identity_retention_audit_uniqueness"),
        ("effects", "0003_effect_replay_receipts"),
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("programme", "0003_downgrade_fence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammeAcceptedTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("review_version", models.PositiveBigIntegerField()),
                ("expected_programme_version", models.PositiveBigIntegerField()),
                ("resulting_programme_version", models.PositiveBigIntegerField()),
                ("retry_key", models.UUIDField()),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_application_digest",
                                message="Use a lower-case SHA-256 digest.",
                                regex="^[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("reason", models.CharField(max_length=1000)),
                ("correlation_id", models.UUIDField()),
                (
                    "source_channel",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_application_source_channel",
                                message="Use a registered lower-case source channel.",
                                regex="^[a-z][a-z0-9_-]*\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "audit_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audit.auditevent",
                    ),
                ),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmereviewdecision",
                    ),
                ),
                (
                    "domain_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="effects.domainevent",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "programme_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_transition",
                        to="programme.programmeitem",
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.programmeproposalrevision",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "actor", "retry_key"),
                        name="app_prg_conversion_retry_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("review_version__gte", 1),
                            (
                                "resulting_programme_version",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("expected_programme_version"),
                                    "+",
                                    models.Value(1),
                                ),
                            ),
                            models.Q(("reason", ""), _negated=True),
                            models.Q(("source_channel", ""), _negated=True),
                        ),
                        name="app_prg_conversion_shape",
                    ),
                ],
            },
        ),
    ]
