# Generated by Django 5.2.16 on 2026-07-28 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField(blank=True, null=True)),
                ("domain_event_id", models.UUIDField(unique=True)),
                ("message_type", models.CharField(max_length=80)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("operational", "Operational service"),
                            ("marketing", "Optional marketing"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("locale", models.CharField(max_length=35)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField(max_length=8000)),
                ("action_path", models.CharField(blank=True, max_length=500)),
                ("rendered_at", models.DateTimeField()),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-rendered_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(choices=[("email", "Email")], max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("suppressed", "Suppressed by preference"),
                            ("permanent_failed", "Permanent failure"),
                        ],
                        max_length=24,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("remote_identity", models.CharField(blank=True, max_length=160)),
                ("safe_error_code", models.CharField(blank=True, max_length=120)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="communications.notificationmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operational_email_enabled", models.BooleanField(default=True)),
                ("marketing_email_consent", models.BooleanField(default=False)),
                (
                    "marketing_consent_version",
                    models.CharField(blank=True, max_length=40),
                ),
                ("marketing_consented_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_preferences",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="notificationmessage",
            index=models.Index(
                fields=["account", "read_at", "rendered_at"],
                name="communications_inbox_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationmessage",
            index=models.Index(
                fields=["organization_id", "edition_id", "message_type"],
                name="comm_message_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["status", "last_attempt_at"], name="comm_delivery_queue_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("message", "channel"),
                name="notification_delivery_channel_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("account", "organization"),
                name="notification_preference_account_org_unique",
            ),
        ),
    ]
