# Generated by Django 5.2.16 on 2026-07-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationdelivery",
            options={"verbose_name_plural": "notification deliveries"},
        ),
    ]
