# Generated by Django 5.2.16 on 2026-07-26 19:12

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import maru.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventEdition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("live", "Live"),
                            ("closing", "Closing"),
                            ("archived", "Archived"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        max_length=63,
                        validators=[maru.core.validators.validate_time_zone],
                    ),
                ),
                (
                    "language_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=35),
                        size=None,
                        validators=[maru.core.validators.validate_language_codes],
                    ),
                ),
                (
                    "currency_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=3),
                        size=None,
                        validators=[maru.core.validators.validate_currency_codes],
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_editions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_editions",
                        to="organizations.conventionseries",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_on", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="EditionLifecycleTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("live", "Live"),
                            ("closing", "Closing"),
                            ("archived", "Archived"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("live", "Live"),
                            ("closing", "Closing"),
                            ("archived", "Archived"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor_id", models.UUIDField()),
                ("reason", models.TextField()),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_transitions",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ArchiveAmendment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_id", models.UUIDField()),
                ("reason", models.TextField()),
                ("summary", models.TextField()),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archive_amendments",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="eventedition",
            constraint=models.UniqueConstraint(
                models.F("series"),
                django.db.models.functions.text.Lower("slug"),
                name="edition_slug_unique_within_series",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventedition",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                name="edition_ends_on_or_after_starts_on",
            ),
        ),
    ]
