# Generated by Django 5.2.16 on 2026-07-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_scope_and_archive_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventedition",
            name="lifecycle_version",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
