# Generated by Django 5.2.16 on 2026-07-28 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_lifecycle_integrity_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditionClosureManifest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("generated_by_id", models.UUIDField()),
                ("generated_at", models.DateTimeField()),
                ("counts", models.JSONField()),
                ("manifest_digest", models.CharField(max_length=64)),
                ("recovery_reference", models.CharField(max_length=240)),
                (
                    "edition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closure_manifest",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EditionReadinessGate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("privacy", "Privacy"),
                            ("finance", "Finance"),
                            ("operations", "Operations"),
                            ("security", "Security"),
                            ("jurisdiction", "Jurisdiction and safeguarding"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("evidence_reference", models.CharField(max_length=240)),
                ("review_summary", models.CharField(max_length=500)),
                ("reviewed_by_id", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readiness_gates",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "code", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "code"), name="edition_readiness_gate_unique"
                    )
                ],
            },
        ),
    ]
