# Generated by Django 5.2.16 on 2026-08-01 09:04

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


_M1_ISO_CURRENCY_CODES = frozenset(
    """
    AED AFN ALL AMD ANG AOA ARS AUD AWG AZN BAM BBD BDT BGN BHD BIF BMD BND
    BOB BOV BRL BSD BTN BWP BYN BZD CAD CDF CHE CHF CHW CLF CLP CNY COP COU
    CRC CUC CUP CVE CZK DJF DKK DOP DZD EGP ERN ETB EUR FJD FKP GBP GEL GHS
    GIP GMD GNF GTQ GYD HKD HNL HRK HTG HUF IDR ILS INR IQD IRR ISK JMD JOD
    JPY KES KGS KHR KMF KPW KRW KWD KYD KZT LAK LBP LKR LRD LSL LYD MAD MDL
    MGA MKD MMK MNT MOP MRU MUR MVR MWK MXN MXV MYR MZN NAD NGN NIO NOK NPR
    NZD OMR PAB PEN PGK PHP PKR PLN PYG QAR RON RSD RUB RWF SAR SBD SCR SDG
    SEK SGD SHP SLE SLL SOS SRD SSP STN SVC SYP SZL THB TJS TMT TND TOP TRY
    TTD TWD TZS UAH UGX USD USN UYI UYU UYW UZS VED VES VND VUV WST XAF XAG
    XAU XBA XBB XBC XBD XCD XDR XOF XPD XPF XPT XSU XTS XUA XXX YER ZAR ZMW
    ZWL
    """.split()
)


def backfill_event_edition_aggregate_versions(apps, schema_editor):
    event_edition = apps.get_model("events", "EventEdition")
    table_name = schema_editor.quote_name(event_edition._meta.db_table)
    # Migration 0002 intentionally makes archived records immutable. This is
    # the one bounded upgrade-time metadata backfill that must touch those rows;
    # keep the guard disabled only around this statement and restore it even if
    # the update fails.
    schema_editor.execute(
        f"ALTER TABLE {table_name} DISABLE TRIGGER events_archived_edition_guard"
    )
    try:
        event_edition.objects.filter(
            aggregate_version__lt=models.F("lifecycle_version")
        ).update(aggregate_version=models.F("lifecycle_version"))
    finally:
        schema_editor.execute(
            f"ALTER TABLE {table_name} ENABLE TRIGGER events_archived_edition_guard"
        )


def assert_event_edition_spans_are_bounded(apps, schema_editor):
    del schema_editor
    event_edition = apps.get_model("events", "EventEdition")
    overlong_count = event_edition.objects.filter(
        ends_on__gt=models.F("starts_on") + datetime.timedelta(days=31)
    ).count()
    if overlong_count:
        raise RuntimeError(
            "Cannot add the 31-day edition-span constraint: "
            f"{overlong_count} existing edition record(s) exceed it. "
            "Correct those dates through an approved data-recovery change, "
            "then rerun this migration."
        )


def assert_event_edition_codes_are_supported(apps, schema_editor):
    del schema_editor
    event_edition = apps.get_model("events", "EventEdition")
    too_many_languages = 0
    unsupported_currencies = 0
    for language_codes, currency_codes in event_edition.objects.values_list(
        "language_codes",
        "currency_codes",
    ).iterator():
        if len(language_codes) > 16:
            too_many_languages += 1
        if len(currency_codes) > 8 or any(
            code not in _M1_ISO_CURRENCY_CODES for code in currency_codes
        ):
            unsupported_currencies += 1
    if too_many_languages or unsupported_currencies:
        raise RuntimeError(
            "Cannot apply the edition input contract: "
            f"{too_many_languages} edition record(s) exceed 16 languages and "
            f"{unsupported_currencies} record(s) exceed 8 currencies or use an "
            "unsupported ISO 4217 code. Correct them through an approved "
            "data-recovery change, then rerun this migration."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_editionclosuremanifest_editionreadinessgate"),
        ("organizations", "0006_convention_series_profile_integrity_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditionCreationReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("series_id", models.UUIDField()),
                ("actor_id", models.UUIDField()),
                ("idempotency_key", models.UUIDField()),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_edition_creation_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="eventedition",
            name="aggregate_version",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.RunPython(
            backfill_event_edition_aggregate_versions,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            assert_event_edition_spans_are_bounded,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            assert_event_edition_codes_are_supported,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="eventedition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "ends_on__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("starts_on"),
                            "+",
                            models.Value(datetime.timedelta(days=31)),
                        ),
                    )
                ),
                name="edition_span_no_more_than_31_days",
            ),
        ),
        migrations.AddField(
            model_name="editioncreationreceipt",
            name="edition",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="creation_receipt",
                to="events.eventedition",
            ),
        ),
        migrations.AddConstraint(
            model_name="editioncreationreceipt",
            constraint=models.UniqueConstraint(
                fields=("actor_id", "series_id", "idempotency_key"),
                name="edition_creation_receipt_unique",
            ),
        ),
    ]
