# Generated by Django 5.2.17 on 2026-10-09 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0019_announcements_adoption_profile"),
        ("organizations", "0015_announcements_representation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("in_review", "in_review"),
                            ("changes_requested", "changes_requested"),
                            ("approved", "approved"),
                            ("cancelled", "cancelled"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("settings_update", "settings_update"),
                            ("stop", "stop"),
                            ("resume", "resume"),
                            ("create", "create"),
                            ("revise", "revise"),
                            ("request_review", "request_review"),
                            ("approve", "approve"),
                            ("changes_requested", "changes_requested"),
                            ("record_publication", "record_publication"),
                            ("correct_publication", "correct_publication"),
                            ("withdraw_report", "withdraw_report"),
                            ("cancel", "cancel"),
                        ],
                        max_length=24,
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("request_digest", models.CharField(max_length=64)),
                ("control_sequence", models.PositiveBigIntegerField()),
                ("object_id", models.UUIDField()),
                ("resulting_version", models.PositiveBigIntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=1000)),
                ("correlation_id", models.UUIDField()),
                ("source_channel", models.CharField(max_length=80)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcement_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="announcements.announcement",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("number", models.PositiveBigIntegerField()),
                ("round_id", models.UUIDField()),
                ("headline", models.CharField(max_length=200)),
                ("body", models.TextField(max_length=8000)),
                ("language_code", models.CharField(max_length=35)),
                ("text_bytes", models.PositiveIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="announcements.announcement",
                    ),
                ),
                (
                    "base_approved_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="announcements.announcementrevision",
                    ),
                ),
                (
                    "command_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_evidence",
                        to="announcements.announcementcommandreceipt",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="organizations.organization",
                    ),
                ),
                (
                    "previous_revision",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_revision",
                        to="announcements.announcementrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("changes_requested", "Changes requested"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=1000)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "command_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_evidence",
                        to="announcements.announcementcommandreceipt",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="organizations.organization",
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to="announcements.announcementrevision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="announcement",
            name="approved_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_announcements",
                to="announcements.announcementrevision",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_announcements",
                to="announcements.announcementrevision",
            ),
        ),
        migrations.CreateModel(
            name="AnnouncementSettingsRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("number", models.PositiveBigIntegerField()),
                ("policy_name", models.CharField(max_length=200)),
                ("policy_description", models.TextField(blank=True, max_length=2000)),
                ("policy_url", models.URLField(blank=True, max_length=2000)),
                ("record_owner", models.CharField(max_length=200)),
                ("review_on", models.DateField()),
                ("channels", models.JSONField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "command_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_evidence",
                        to="announcements.announcementcommandreceipt",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="announcementrevision",
            name="settings_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="announcement_revisions",
                to="announcements.announcementsettingsrevision",
            ),
        ),
        migrations.CreateModel(
            name="AnnouncementControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField(default=0)),
                ("settings_version", models.PositiveBigIntegerField(default=0)),
                ("stopped", models.BooleanField(default=False)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="organizations.organization",
                    ),
                ),
                (
                    "current_settings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_controls",
                        to="announcements.announcementsettingsrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("channel_code", models.CharField(max_length=40)),
                ("channel_label", models.CharField(max_length=100)),
                ("channel_url", models.URLField(blank=True, max_length=2000)),
                ("language_code", models.CharField(max_length=35)),
                ("headline", models.CharField(max_length=200)),
                ("body", models.TextField(max_length=8000)),
                ("copy_digest", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "command_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_evidence",
                        to="announcements.announcementcommandreceipt",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="organizations.organization",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="announcements.announcementrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementPublicationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("withdrawn", models.BooleanField(default=False)),
                ("publication_url", models.URLField(blank=True, max_length=2000)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=1000)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "command_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_evidence",
                        to="announcements.announcementcommandreceipt",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_%(class)s",
                        to="organizations.organization",
                    ),
                ),
                (
                    "supersedes_report",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement",
                        to="announcements.announcementpublicationreport",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_reports",
                        to="announcements.announcementvariant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="announcementcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("edition", "actor", "idempotency_key"),
                name="ann_receipt_retry_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("edition", "control_sequence"), name="ann_receipt_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("control_sequence__gt", 0),
                    (
                        "operation__in",
                        (
                            "settings_update",
                            "stop",
                            "resume",
                            "create",
                            "revise",
                            "request_review",
                            "approve",
                            "changes_requested",
                            "record_publication",
                            "correct_publication",
                            "withdraw_report",
                            "cancel",
                        ),
                    ),
                    ("request_digest__regex", "^[0-9a-f]{64}$"),
                    ("resulting_version__gt", 0),
                ),
                name="ann_receipt_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decision", "approve"),
                    models.Q(
                        ("decision", "changes_requested"),
                        models.Q(("note", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ann_review_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "draft",
                            "in_review",
                            "changes_requested",
                            "approved",
                            "cancelled",
                        ),
                    ),
                    ("version__gt", 0),
                ),
                name="ann_announcement_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementsettingsrevision",
            constraint=models.UniqueConstraint(
                fields=("edition", "number"), name="ann_settings_number_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementsettingsrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("number__gt", 0),
                    models.Q(("policy_name", ""), _negated=True),
                    models.Q(("record_owner", ""), _negated=True),
                    models.Q(
                        models.Q(("policy_url", ""), _negated=True),
                        models.Q(("policy_description", ""), _negated=True),
                        _connector="OR",
                    ),
                ),
                name="ann_settings_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementrevision",
            constraint=models.UniqueConstraint(
                fields=("announcement", "number"), name="ann_revision_number_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("number__gt", 0),
                    ("text_bytes__gt", 0),
                    models.Q(("headline", ""), _negated=True),
                    models.Q(("body", ""), _negated=True),
                ),
                name="ann_revision_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementcontrol",
            constraint=models.UniqueConstraint(
                fields=("edition",), name="ann_control_edition_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementvariant",
            constraint=models.UniqueConstraint(
                fields=("revision", "channel_code", "language_code"),
                name="ann_variant_selection_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("headline", ""), _negated=True),
                    models.Q(("body", ""), _negated=True),
                    ("copy_digest__regex", "^[0-9a-f]{64}$"),
                ),
                name="ann_variant_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementpublicationreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("supersedes_report__isnull", True)),
                fields=("variant",),
                name="ann_report_initial_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementpublicationreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("supersedes_report__isnull", True), ("withdrawn", False)),
                    models.Q(
                        ("supersedes_report__isnull", False),
                        models.Q(("reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ann_report_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("announcement", "resulting_version"),
                condition=models.Q(announcement__isnull=False),
                name="ann_receipt_object_version_uq",
            ),
        ),
    ]
