# Generated by Django 5.2.16 on 2026-07-28 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registration", "0016_guardian_lifecycle_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("account_id", models.UUIDField()),
                ("public_id", models.CharField(max_length=32)),
                (
                    "token_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("replaced", "Replaced"),
                            ("revoked", "Revoked"),
                        ],
                        default="issued",
                        max_length=16,
                    ),
                ),
                ("issue_sequence", models.PositiveIntegerField()),
                ("label_snapshot", models.CharField(max_length=160)),
                ("issued_at", models.DateTimeField()),
                ("issued_by_id", models.UUIDField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_by_id", models.UUIDField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=500)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credentials",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ("registration_id", "issue_sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="CredentialEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("reprinted", "Reprinted"),
                            ("revoked", "Revoked"),
                            ("verified", "Verified"),
                            ("denied", "Denied"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("actor_kind", models.CharField(max_length=40)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("reason_code", models.CharField(max_length=80)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="accreditation.credential",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="OfflineCredentialManifest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("sequence", models.PositiveBigIntegerField()),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("generated_at", models.DateTimeField()),
                ("generated_by_id", models.UUIDField()),
                ("credential_count", models.PositiveIntegerField()),
                ("payload", models.JSONField()),
                ("payload_digest", models.CharField(max_length=64)),
                ("signature", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ("edition_id", "sequence", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition_id", "sequence"),
                        name="offline_manifest_sequence_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RelayDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("code", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=160)),
                ("signing_secret_env_var", models.CharField(max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                ("last_sequence", models.PositiveBigIntegerField(default=0)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition_id", "code"), name="relay_device_code_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OfflineCheckInOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("operation_id", models.UUIDField()),
                ("device_sequence", models.PositiveBigIntegerField()),
                ("manifest_sequence", models.PositiveBigIntegerField()),
                ("credential_public_id", models.CharField(max_length=32)),
                ("occurred_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("duplicate", "Duplicate"),
                            ("conflict", "Conflict"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=16,
                    ),
                ),
                ("safe_result_code", models.CharField(max_length=80)),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offline_operations",
                        to="accreditation.credential",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_in_operations",
                        to="accreditation.relaydevice",
                    ),
                ),
            ],
            options={
                "ordering": ("device_id", "device_sequence", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="credential",
            index=models.Index(
                fields=["organization_id", "edition_id", "status", "public_id"],
                name="accred_credential_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.UniqueConstraint(
                fields=("edition_id", "public_id"), name="credential_public_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.UniqueConstraint(
                fields=("registration", "issue_sequence"),
                name="credential_issue_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "issued")),
                fields=("registration",),
                name="one_active_credential_per_registration",
            ),
        ),
        migrations.AddIndex(
            model_name="offlinecheckinoperation",
            index=models.Index(
                fields=["organization_id", "edition_id", "outcome", "received_at"],
                name="accred_offline_conflict_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="offlinecheckinoperation",
            constraint=models.UniqueConstraint(
                fields=("device", "operation_id"),
                name="offline_operation_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="offlinecheckinoperation",
            constraint=models.UniqueConstraint(
                fields=("device", "device_sequence"),
                name="offline_device_sequence_unique",
            ),
        ),
    ]
