# Generated by Django 5.2.16 on 2026-07-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accreditation", "0002_integrity_guards"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offlinecheckinoperation",
            options={
                "ordering": ("device_id", "device_sequence", "id"),
                "verbose_name": "offline check-in operation",
                "verbose_name_plural": "offline check-in operations",
            },
        ),
    ]
