# Generated by Django 5.2.16 on 2026-08-08 17:40

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import maru.core.localization
import maru.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0009_edition_workspace_downgrade_fence"),
        ("organizations", "0013_runtime_executable_function_hardening"),
        ("workforce", "0007_structure_write_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharityPartner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("legal_name", models.CharField(max_length=240)),
                ("imprint_name", models.CharField(blank=True, max_length=240)),
                ("public_name", models.CharField(max_length=200)),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True, max_length=5000)),
                ("location_name", models.CharField(blank=True, max_length=240)),
                ("postal_address", models.TextField(blank=True, max_length=1000)),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        validators=[maru.core.localization.validate_country_code],
                    ),
                ),
                ("website_url", models.URLField(blank=True)),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter an international telephone number such as +431234567.",
                                regex="^\\+[1-9]\\d{6,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_partners_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_partners_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_partners",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "public_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="CharityPartnerMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("logo", "Logo"), ("photo", "Photo")], max_length=16
                    ),
                ),
                ("source_reference", models.CharField(max_length=1000)),
                ("public_reference", models.CharField(blank=True, max_length=1000)),
                ("owner_name", models.CharField(max_length=240)),
                ("license_basis", models.CharField(max_length=500)),
                ("usage_scope", models.CharField(max_length=500)),
                ("attribution", models.CharField(blank=True, max_length=500)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_media_references",
                        to="organizations.organization",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_references",
                        to="charities.charitypartner",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_media_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_media_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("partner_id", "kind", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CharitySelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("submitted", "Submitted"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                (
                    "publication_state",
                    models.CharField(
                        choices=[
                            ("unpublished", "Unpublished"),
                            ("published", "Published"),
                        ],
                        default="unpublished",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "publication_number",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_selections",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_selections",
                        to="organizations.organization",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_selections",
                        to="charities.charitypartner",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_selections_proposed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_selections",
                        to="workforce.department",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "partner__public_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="CharityPublicationSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("publication_number", models.PositiveIntegerField()),
                ("approved_at", models.DateTimeField()),
                ("public_name", models.CharField(max_length=200)),
                ("imprint_name", models.CharField(blank=True, max_length=240)),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("location_name", models.CharField(blank=True, max_length=240)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("website_url", models.URLField(blank=True)),
                (
                    "media_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=24
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_publications_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_publication_snapshots",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_publication_snapshots",
                        to="organizations.organization",
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_snapshots",
                        to="charities.charityselection",
                    ),
                ),
            ],
            options={
                "ordering": ("selection_id", "publication_number", "id"),
            },
        ),
        migrations.CreateModel(
            name="CharityCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("partner_create", "Create partner"),
                            ("partner_update", "Update partner"),
                            ("media_add", "Add media"),
                            ("media_approve", "Approve media"),
                            ("media_withdraw", "Withdraw media"),
                            ("selection_propose", "Propose selection"),
                            ("selection_submit", "Submit selection"),
                            ("selection_confirm", "Confirm selection"),
                            ("selection_reject", "Reject selection"),
                            ("selection_comment", "Comment on selection"),
                            ("selection_publish", "Publish selection"),
                            ("selection_withdraw", "Withdraw publication"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_charity_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("resulting_version", models.PositiveBigIntegerField()),
                ("result_object_id", models.UUIDField()),
                ("correlation_id", models.UUIDField()),
                ("source_channel", models.CharField(max_length=32)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_commands_acted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_command_receipts",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_command_receipts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="command_receipts",
                        to="charities.charitypartner",
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="command_receipts",
                        to="charities.charityselection",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CharitySelectionTimelineEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("status", "Status decision"),
                            ("private_comment", "Private comment"),
                            ("publication", "Publication decision"),
                        ],
                        max_length=24,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("proposed", "Proposed"),
                            ("submitted", "Submitted"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("proposed", "Proposed"),
                            ("submitted", "Submitted"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "from_publication_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unpublished", "Unpublished"),
                            ("published", "Published"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_publication_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unpublished", "Unpublished"),
                            ("published", "Published"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=1000)),
                ("private_comment", models.TextField(blank=True, max_length=5000)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_timeline_entries_acted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_timeline_entries",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charity_timeline_entries",
                        to="organizations.organization",
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_entries",
                        to="charities.charityselection",
                    ),
                ),
            ],
            options={
                "ordering": ("selection_id", "sequence", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="charitypartner",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                django.db.models.functions.text.Lower("slug"),
                name="charity_partner_org_slug_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="charitypartner",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="charity_partner_version_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="charitypartnermedia",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="charity_media_version_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="charitypartnermedia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("review_status", "pending"),
                        ("reviewed_at__isnull", True),
                        ("reviewed_by__isnull", True),
                    ),
                    models.Q(
                        ("review_status__in", ("approved", "withdrawn")),
                        ("reviewed_at__isnull", False),
                        ("reviewed_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="charity_media_review_evidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="charityselection",
            constraint=models.UniqueConstraint(
                fields=("edition", "partner"), name="charity_selection_edition_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="charityselection",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="charity_selection_version_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="charityselection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("publication_state", "unpublished"),
                    ("status", "confirmed"),
                    _connector="OR",
                ),
                name="charity_publish_confirmed_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="charitypublicationsnapshot",
            constraint=models.UniqueConstraint(
                fields=("selection", "publication_number"),
                name="charity_publication_number_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="charitypublicationsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("publication_number__gt", 0)),
                name="charity_publication_number_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="charitypublicationsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("media_ids__len__lte", 24)),
                name="charity_public_media_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="charitycommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("actor", "operation", "idempotency_key"),
                name="charity_command_retry_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="charitycommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("resulting_version__gt", 0)),
                name="charity_receipt_version_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="charityselectiontimelineentry",
            constraint=models.UniqueConstraint(
                fields=("selection", "sequence"), name="charity_timeline_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="charityselectiontimelineentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)),
                name="charity_timeline_sequence_pos",
            ),
        ),
    ]
