"""App-local venue routes; the project URL configuration owns mounting."""

from django.urls import path

from .api import (
    MyMaruVenueScheduleView,
    PublicVenueScheduleView,
    VenueBookingCollectionView,
    VenueBookingCommandView,
    VenueBookingDetailView,
    VenueCombinationCollectionView,
    VenueLayoutApproveView,
    VenueLayoutCollectionView,
    VenueMediaApproveView,
    VenueMediaCollectionView,
    VenueNightInventoryView,
    VenuePropertyCollectionView,
    VenuePropertyDetailView,
    VenueRoomTypeCollectionView,
    VenueSpaceAvailabilityView,
    VenueSpaceCatalogCollectionView,
    VenueSpaceScheduleView,
    VenueSpaceSelectionCollectionView,
    VenueWorkspaceCollectionView,
)
from .views import (
    my_maru_schedule_index,
    my_maru_venue_schedule,
    venue_availability_set,
    venue_booking_command,
    venue_booking_create,
    venue_booking_reschedule,
    venue_catalog_path_create,
    venue_combination_create,
    venue_edition_select,
    venue_inventory_set,
    venue_layout_add,
    venue_layout_approve,
    venue_media_add,
    venue_media_approve,
    venue_property_create,
    venue_property_create_page,
    venue_property_detail_page,
    venue_property_update,
    venue_room_type_create,
    venue_space_schedule_page,
    venue_space_select,
    venue_workspace,
)

urlpatterns = [
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/",
        venue_workspace,
        name="venue-workspace",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/new/",
        venue_property_create_page,
        name="venue-property-create-page",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/create/",
        venue_property_create,
        name="venue-property-create",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/"
        "<uuid:property_id>/",
        venue_property_detail_page,
        name="venue-property-detail-page",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/"
        "<uuid:property_id>/update/",
        venue_property_update,
        name="venue-property-update",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/"
        "<uuid:property_id>/catalog-paths/",
        venue_catalog_path_create,
        name="venue-catalog-path-create",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/"
        "<uuid:property_id>/combinations/",
        venue_combination_create,
        name="venue-combination-create",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/"
        "<uuid:property_id>/media/",
        venue_media_add,
        name="venue-media-add",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/"
        "<uuid:property_id>/media/<uuid:media_id>/approve/",
        venue_media_approve,
        name="venue-media-approve",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/"
        "<uuid:property_id>/layouts/",
        venue_layout_add,
        name="venue-layout-add",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/"
        "<uuid:property_id>/layouts/<uuid:layout_id>/approve/",
        venue_layout_approve,
        name="venue-layout-approve",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/"
        "<uuid:property_id>/room-types/",
        venue_room_type_create,
        name="venue-room-type-create",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/properties/"
        "<uuid:property_id>/night-inventory/",
        venue_inventory_set,
        name="venue-inventory-set",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/selections/",
        venue_edition_select,
        name="venue-edition-select",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/space-selections/",
        venue_space_select,
        name="venue-space-select",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/spaces/"
        "<uuid:space_selection_id>/",
        venue_space_schedule_page,
        name="venue-space-schedule-page",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/spaces/"
        "<uuid:space_selection_id>/availability/",
        venue_availability_set,
        name="venue-availability-set",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/spaces/"
        "<uuid:space_selection_id>/bookings/",
        venue_booking_create,
        name="venue-booking-create",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/spaces/"
        "<uuid:space_selection_id>/bookings/<uuid:booking_id>/reschedule/",
        venue_booking_reschedule,
        name="venue-booking-reschedule",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/venues/spaces/"
        "<uuid:space_selection_id>/bookings/<uuid:booking_id>/commands/"
        "<str:action>/",
        venue_booking_command,
        name="venue-booking-command-page",
    ),
    path(
        "my/schedule/",
        my_maru_schedule_index,
        name="my-maru-schedule-index",
    ),
    path(
        "my/organizations/<slug:organization_slug>/series/<slug:series_slug>/"
        "editions/<slug:edition_slug>/schedule/",
        my_maru_venue_schedule,
        name="my-maru-venue-schedule",
    ),
    path(
        "api/v1/public/organizations/<uuid:organization_id>/"
        "editions/<uuid:edition_id>/venue-schedule",
        PublicVenueScheduleView.as_view(),
        name="api-public-venue-schedule",
    ),
    path(
        "api/v1/my/organizations/<uuid:organization_id>/"
        "editions/<uuid:edition_id>/venue-schedule",
        MyMaruVenueScheduleView.as_view(),
        name="api-my-venue-schedule",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/venue-properties",
        VenuePropertyCollectionView.as_view(),
        name="api-venue-property-list",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/venue-properties/"
        "<uuid:property_id>",
        VenuePropertyDetailView.as_view(),
        name="api-venue-property-detail",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/venue-properties/"
        "<uuid:property_id>/space-paths",
        VenueSpaceCatalogCollectionView.as_view(),
        name="api-venue-space-catalog-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/venue-properties/"
        "<uuid:property_id>/space-combinations",
        VenueCombinationCollectionView.as_view(),
        name="api-venue-space-combination-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/venue-properties/"
        "<uuid:property_id>/media",
        VenueMediaCollectionView.as_view(),
        name="api-venue-media-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/venue-properties/"
        "<uuid:property_id>/media/<uuid:media_id>/approve",
        VenueMediaApproveView.as_view(),
        name="api-venue-media-approve",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/venue-spaces/"
        "<uuid:space_id>/layouts",
        VenueLayoutCollectionView.as_view(),
        name="api-venue-layout-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/venue-layouts/"
        "<uuid:layout_id>/approve",
        VenueLayoutApproveView.as_view(),
        name="api-venue-layout-approve",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/venue-properties/"
        "<uuid:property_id>/room-types",
        VenueRoomTypeCollectionView.as_view(),
        name="api-venue-room-type-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/accommodation-room-types/"
        "<uuid:room_type_id>/night-inventory",
        VenueNightInventoryView.as_view(),
        name="api-venue-night-inventory-set",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/venues",
        VenueWorkspaceCollectionView.as_view(),
        name="api-edition-venue-list",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/venue-spaces",
        VenueSpaceSelectionCollectionView.as_view(),
        name="api-edition-venue-space-list",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/venue-spaces/<uuid:space_selection_id>",
        VenueSpaceScheduleView.as_view(),
        name="api-edition-venue-space-detail",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/venue-spaces/<uuid:space_selection_id>/availability",
        VenueSpaceAvailabilityView.as_view(),
        name="api-edition-venue-space-availability",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/venue-spaces/<uuid:space_selection_id>/bookings",
        VenueBookingCollectionView.as_view(),
        name="api-venue-booking-list",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/venue-spaces/<uuid:space_selection_id>/bookings/"
        "<uuid:booking_id>",
        VenueBookingDetailView.as_view(),
        name="api-venue-booking-detail",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/venue-spaces/<uuid:space_selection_id>/bookings/"
        "<uuid:booking_id>/commands/<str:action>",
        VenueBookingCommandView.as_view(),
        name="api-venue-booking-command",
    ),
]
