# Generated by Django 5.2.16 on 2026-07-29 09:54

import django.core.validators
import django.db.models.deletion
import maru.core.validators
import maru.workforce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authorization", "0003_capabilitygrant_approved_by_and_more"),
        ("events", "0005_editionclosuremanifest_editionreadinessgate"),
        ("organizations", "0001_initial"),
        ("participation", "0003_alter_participationcapacity_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_departments",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_departments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="workforce.department",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "position", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="OnboardingDocumentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("version", models.PositiveIntegerField(default=1)),
                ("description", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "max_bytes",
                    models.PositiveIntegerField(
                        default=10485760,
                        validators=[
                            django.core.validators.MinValueValidator(1024),
                            django.core.validators.MaxValueValidator(10485760),
                        ],
                    ),
                ),
                (
                    "retention_notice",
                    models.CharField(
                        default="Retained only for onboarding, access, dispute, and approved post-edition recordkeeping purposes.",
                        max_length=500,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboarding_document_types_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboarding_document_types",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboarding_document_types",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "code", "-version", "id"),
            },
        ),
        migrations.CreateModel(
            name="OnboardingDocumentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("submitted", "Submitted for review"),
                            ("approved", "Approved"),
                            ("rejected", "Changes required"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("instructions", models.CharField(blank=True, max_length=1000)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField()),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to=maru.workforce.models.onboarding_document_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("byte_count", models.PositiveIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("scanner_code", models.CharField(blank=True, max_length=80)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.CharField(blank=True, max_length=500)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboarding_document_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboarding_document_requests",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboarding_document_requests",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboarding_document_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboarding_document_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="workforce.onboardingdocumenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "status", "due_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.CharField(max_length=2000)),
                (
                    "headcount",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("capacity_codes", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("open", "Open"),
                            ("filled", "Filled"),
                            ("closed", "Closed"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_positions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="workforce.department",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_positions",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_positions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_reports",
                        to="workforce.position",
                    ),
                ),
                (
                    "role_bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_positions",
                        to="authorization.rolebundle",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "department__position", "title", "id"),
            },
        ),
        migrations.CreateModel(
            name="PositionAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(max_length=500)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_assignments_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_assignments",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_assignments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "participation_capacity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_assignments",
                        to="participation.participationcapacity",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="workforce.position",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_assignments_proposed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role_assignment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_assignment",
                        to="authorization.roleassignment",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "position__title", "account_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="PositionDocumentRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_requirements",
                        to="workforce.onboardingdocumenttype",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_requirements",
                        to="workforce.position",
                    ),
                ),
            ],
            options={
                "ordering": ("position_id", "document_type__name", "id"),
            },
        ),
        migrations.CreateModel(
            name="PositionTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("version", models.PositiveIntegerField(default=1)),
                ("description", models.CharField(max_length=1000)),
                (
                    "default_headcount",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("default_capacity_codes", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_templates",
                        to="organizations.organization",
                    ),
                ),
                (
                    "role_bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_templates",
                        to="authorization.rolebundle",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "code", "-version", "id"),
            },
        ),
        migrations.AddField(
            model_name="position",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="positions",
                to="workforce.positiontemplate",
            ),
        ),
        migrations.CreateModel(
            name="VolunteerOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=2000)),
                ("applications_open_at", models.DateTimeField(blank=True, null=True)),
                ("applications_close_at", models.DateTimeField(blank=True, null=True)),
                ("visible_when_filled", models.BooleanField(default=True)),
                (
                    "position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunity",
                        to="workforce.position",
                    ),
                ),
            ],
            options={
                "ordering": ("position__edition_id", "position__title", "id"),
            },
        ),
        migrations.CreateModel(
            name="VolunteerApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("motivation", models.TextField(max_length=2000)),
                ("submitted_at", models.DateTimeField()),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.CharField(blank=True, max_length=500)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_applications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="workforce.volunteeropportunity",
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("edition", "code"),
                name="workforce_department_edition_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="onboardingdocumenttype",
            constraint=models.UniqueConstraint(
                fields=("edition", "code", "version"),
                name="workforce_document_type_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="onboardingdocumenttype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("edition", "code"),
                name="workforce_one_active_document_type",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingdocumentrequest",
            index=models.Index(
                fields=["organization", "edition", "status"],
                name="workforce_document_review_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="onboardingdocumentrequest",
            constraint=models.UniqueConstraint(
                fields=("document_type", "account"),
                name="workforce_document_request_account_type_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("proposed", "active"))),
                fields=("position", "account"),
                name="workforce_one_open_assignment_per_position_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="positiondocumentrequirement",
            constraint=models.UniqueConstraint(
                fields=("position", "document_type"),
                name="workforce_position_document_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="positiontemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "code", "version"),
                name="workforce_position_template_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("edition", "code"),
                name="workforce_position_edition_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteerapplication",
            constraint=models.UniqueConstraint(
                fields=("opportunity", "account"),
                name="workforce_one_application_per_opportunity_account",
            ),
        ),
    ]
