# Generated by Django 5.2.17 on 2026-09-09 19:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0008_identity_retention_audit_uniqueness"),
        ("effects", "0003_effect_replay_receipts"),
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("programme", "0012_staffing_downgrade_fence"),
        ("scheduling", "0006_scheduling_downgrade_fence"),
        ("workforce", "0018_programme_department_ownership_contract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammeShiftBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.PositiveBigIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "demand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_bindings",
                        to="workforce.shiftdemand",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_shift_bindings",
                        to="events.eventedition",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_bindings",
                        to="programme.programmeitem",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_bindings_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_bindings",
                        to="scheduling.schedulingoccurrence",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_shift_bindings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requirement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_binding",
                        to="programme.programmestaffingrequirement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgrammeShiftBindingRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ]
                    ),
                ),
                ("requirement_version", models.PositiveBigIntegerField()),
                ("occurrence_version", models.PositiveBigIntegerField()),
                ("demand_version", models.PositiveBigIntegerField()),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create draft demand"),
                            ("link", "Link identical draft demand"),
                            ("reconcile", "Reconcile uncommitted draft"),
                            ("successor", "Create separate successor"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "work_terms_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_structure_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "source_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_structure_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "preview_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_structure_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("reason", models.CharField(max_length=240)),
                ("retry_key", models.UUIDField()),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_structure_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("correlation_id", models.UUIDField()),
                ("source_channel", models.CharField(max_length=32)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_binding_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "audit_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_binding_revision",
                        to="audit.auditevent",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="workforce.programmeshiftbinding",
                    ),
                ),
                (
                    "cancellation_receipt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_successor_revisions",
                        to="workforce.shiftdemandcommandreceipt",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_binding_revisions",
                        to="scheduling.schedulingcandidate",
                    ),
                ),
                (
                    "candidate_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_binding_revisions",
                        to="scheduling.schedulingcandidaterevision",
                    ),
                ),
                (
                    "demand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_binding_revisions",
                        to="workforce.shiftdemand",
                    ),
                ),
                (
                    "domain_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_binding_revision",
                        to="effects.domainevent",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_binding_revisions",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_binding_revisions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_binding_revisions",
                        to="scheduling.schedulingplacementrevision",
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_successors",
                        to="workforce.shiftdemand",
                    ),
                ),
                (
                    "requirement_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workforce_binding_revisions",
                        to="programme.programmestaffingrevision",
                    ),
                ),
                (
                    "shift_receipt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_binding_revisions",
                        to="workforce.shiftdemandcommandreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ("binding_id", "sequence", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="programmeshiftbinding",
            index=models.Index(
                fields=["organization", "edition", "item"],
                name="wrk_programme_binding_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeshiftbinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1), ("version__lte", 1000)),
                name="workforce_programme_binding_version",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeshiftbindingrevision",
            index=models.Index(
                fields=["organization", "edition", "demand"],
                name="wrk_programme_revision_demand",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeshiftbindingrevision",
            constraint=models.UniqueConstraint(
                fields=("binding", "sequence"),
                name="workforce_programme_binding_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeshiftbindingrevision",
            constraint=models.UniqueConstraint(
                fields=("edition", "actor", "retry_key"),
                name="workforce_programme_binding_retry",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeshiftbindingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("demand_version__gt", 0),
                    ("occurrence_version__gt", 0),
                    ("requirement_version__gt", 0),
                    ("sequence__gte", 1),
                    ("sequence__lte", 1000),
                ),
                name="workforce_programme_binding_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeshiftbindingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("operation__in", ("create", "link", "reconcile", "successor"))
                ),
                name="workforce_programme_binding_operation",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeshiftbindingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reason", ""), _negated=True),
                    models.Q(("source_channel", ""), _negated=True),
                ),
                name="workforce_programme_binding_evidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeshiftbindingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("operation", "link"), ("shift_receipt__isnull", True)),
                    models.Q(
                        models.Q(("operation", "link"), _negated=True),
                        ("shift_receipt__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="workforce_programme_binding_shift",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeshiftbindingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("operation", "successor"), ("predecessor__isnull", False)
                    ),
                    models.Q(
                        models.Q(("operation", "successor"), _negated=True),
                        ("cancellation_receipt__isnull", True),
                        ("predecessor__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="workforce_programme_binding_predecessor",
            ),
        ),
    ]
