# Generated by Django 5.2.16 on 2026-07-29 13:45

import django.contrib.postgres.fields
import django.core.validators
import maru.core.localization
import maru.organizations.models
from django.db import migrations, models


def copy_default_languages_forward(apps, schema_editor):
    del schema_editor
    organization_model = apps.get_model("organizations", "Organization")
    for organization in organization_model.objects.all().iterator():
        code = (organization.default_language or "en").lower().split("-", 1)[0][:2]
        organization.default_language_codes = [code or "en"]
        organization.save(update_fields=("default_language_codes",))


def copy_default_languages_reverse(apps, schema_editor):
    del schema_editor
    organization_model = apps.get_model("organizations", "Organization")
    for organization in organization_model.objects.all().iterator():
        codes = list(organization.default_language_codes or ())
        organization.default_language = codes[0] if codes else "en"
        organization.save(update_fields=("default_language",))


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conventionseries",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Public contact for this convention brand.",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AddField(
            model_name="conventionseries",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Public-facing description of this recurring convention brand.",
            ),
        ),
        migrations.AddField(
            model_name="conventionseries",
            name="website_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="General organizer contact; not an account login.",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="country_code",
            field=models.CharField(
                blank=True,
                help_text="Primary operating country used only for sensible setup defaults.",
                max_length=2,
                validators=[maru.core.localization.validate_country_code],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_language_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2),
                default=maru.organizations.models.default_organization_languages,
                help_text="Ordered ISO 639-1 languages suggested for new convention editions.",
                size=None,
                validators=[maru.core.localization.validate_language_code_list],
            ),
        ),
        migrations.RunPython(
            copy_default_languages_forward,
            copy_default_languages_reverse,
        ),
        migrations.RemoveField(
            model_name="organization",
            name="default_language",
        ),
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Short organizer description for staff context and future public use.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="legal_name",
            field=models.CharField(
                blank=True,
                help_text="Optional registered legal name when it differs from the public name.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
