# Generated by Django 5.2.16 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organizer_series_localization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="lifecycle",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
