# Generated by Django 5.2.16 on 2026-07-31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organization_draft_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Optional public contact number stored in E.164 format.",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message=(
                            "Enter an international telephone number such as "
                            "+431234567."
                        ),
                        regex="^\\+[1-9]\\d{6,14}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="imprint_text",
            field=models.TextField(
                blank=True,
                help_text="Additional jurisdiction-specific public imprint wording.",
                max_length=5000,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="legal_address",
            field=models.TextField(
                blank=True,
                help_text="Formatted registered postal address for legal notices.",
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="legal_representative",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Printable representative or responsible office for the imprint."
                ),
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="registration_authority",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Public register or authority maintaining the organization record."
                ),
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="registration_identifier",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Public association, company, charity, or registry identifier."
                ),
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tax_identifier",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Tax identifier only where it belongs in the public legal profile."
                ),
                max_length=120,
            ),
        ),
    ]
