# Generated by Django 5.2.16 on 2026-08-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_organization_complete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="conventionseries",
            name="profile_version",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
