# Generated by Django 5.2.16 on 2026-07-26 19:33

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import maru.audit.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditIntegrityBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField(unique=True)),
                (
                    "previous_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_digest",
                                message="Use a lowercase SHA-256 hex digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_digest",
                                message="Use a lowercase SHA-256 hex digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("event_count", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ("sequence",),
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("occurred_at", models.DateTimeField()),
                ("principal_kind", models.CharField(max_length=40)),
                ("principal_id", models.UUIDField(blank=True, null=True)),
                ("principal_context_id", models.UUIDField(blank=True, null=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("event_edition_id", models.UUIDField(blank=True, null=True)),
                ("capability_code", models.CharField(max_length=120)),
                ("operation", models.CharField(max_length=160)),
                ("target_type", models.CharField(max_length=120)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("deny", "Deny"),
                            ("error", "Error"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason_code", models.CharField(max_length=120)),
                (
                    "obligations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=120),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "changed_fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=120),
                        default=list,
                        size=None,
                    ),
                ),
                ("correlation_id", models.UUIDField()),
                ("causation_id", models.UUIDField(blank=True, null=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                (
                    "idempotency_key_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_digest",
                                message="Use a lowercase SHA-256 hex digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("source_channel", models.CharField(max_length=40)),
                ("delegated", models.BooleanField(default=False)),
                ("elevated", models.BooleanField(default=False)),
                ("break_glass", models.BooleanField(default=False)),
                (
                    "safe_metadata",
                    models.JSONField(
                        default=dict,
                        validators=[maru.audit.models.validate_safe_metadata],
                    ),
                ),
                (
                    "retention_class",
                    models.CharField(default="security-standard", max_length=80),
                ),
                (
                    "integrity_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="audit.auditintegritybatch",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["organization_id", "occurred_at"],
                        name="audit_org_occurred_idx",
                    ),
                    models.Index(
                        fields=["principal_id", "occurred_at"],
                        name="audit_principal_occurred_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="audit_correlation_idx"
                    ),
                ],
            },
        ),
    ]
