# Generated by Django 5.2.16 on 2026-07-26 19:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_append_only_guards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="changed_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=120),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="obligations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=120),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
