# Generated by Django 5.2.16 on 2026-07-26 19:52

import maru.audit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_auditevent_changed_fields_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="safe_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[maru.audit.models.validate_safe_metadata],
            ),
        ),
    ]
