# Generated by Django 5.2.16 on 2026-07-28 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostEditionCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("account_id", models.UUIDField()),
                ("target_type", models.CharField(max_length=120)),
                ("target_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("changed_fields", models.JSONField()),
                ("reason", models.CharField(max_length=1000)),
                ("requested_by_id", models.UUIDField()),
                ("requested_at", models.DateTimeField()),
                ("decided_by_id", models.UUIDField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.CharField(blank=True, max_length=1000)),
            ],
            options={
                "ordering": ("requested_at", "id"),
                "indexes": [
                    models.Index(
                        fields=[
                            "organization_id",
                            "edition_id",
                            "target_type",
                            "target_id",
                        ],
                        name="privacy_correction_target_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("jurisdiction_code", models.CharField(max_length=40)),
                ("data_category", models.CharField(max_length=80)),
                ("version", models.PositiveIntegerField()),
                ("retention_days", models.PositiveIntegerField()),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("delete", "Delete"),
                            ("minimize", "Minimize"),
                            ("retain", "Retain with legal basis"),
                        ],
                        max_length=16,
                    ),
                ),
                ("lawful_basis", models.CharField(max_length=240)),
                ("approved_by_id", models.UUIDField()),
                ("approved_at", models.DateTimeField()),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("organization_id", "data_category", "version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organization_id",
                            "jurisdiction_code",
                            "data_category",
                            "version",
                        ),
                        name="retention_policy_version_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=(
                            "organization_id",
                            "jurisdiction_code",
                            "data_category",
                        ),
                        name="one_active_retention_policy",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DisposalReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField(blank=True, null=True)),
                ("target_type", models.CharField(max_length=120)),
                ("target_id", models.UUIDField()),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("delete", "Delete"),
                            ("minimize", "Minimize"),
                            ("retain", "Retain with legal basis"),
                        ],
                        max_length=16,
                    ),
                ),
                ("applied_at", models.DateTimeField()),
                ("applied_by_id", models.UUIDField(blank=True, null=True)),
                ("safe_result_code", models.CharField(max_length=80)),
                ("downstream_receipts", models.JSONField(default=list)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposal_receipts",
                        to="privacyops.retentionpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ("applied_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SubjectRightsRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("access", "Access"),
                            ("correction", "Correction"),
                            ("portability", "Portability"),
                            ("restriction", "Restriction"),
                            ("objection", "Objection"),
                            ("deletion", "Deletion"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("identity_check", "Identity check"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("denied", "Denied"),
                        ],
                        default="received",
                        max_length=24,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("request_summary", models.CharField(max_length=1000)),
                ("identity_verified_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("safe_outcome_summary", models.CharField(blank=True, max_length=1000)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_rights_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at", "-id"),
            },
        ),
    ]
