# Generated by Django 5.2.16 on 2026-07-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacyops", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="disposalreceipt",
            constraint=models.UniqueConstraint(
                fields=("policy", "target_type", "target_id"),
                name="privacy_disposal_target_unique",
            ),
        ),
    ]
