# Generated by Django 5.2.16 on 2026-07-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacyops", "0002_disposalreceipt_privacy_disposal_target_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposalreceipt",
            name="downstream_receipts",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
