# Generated by Django 5.2.16 on 2026-07-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("privacyops", "0004_integrity_guards"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retentionpolicy",
            options={
                "ordering": ("organization_id", "data_category", "version"),
                "verbose_name_plural": "retention policies",
            },
        ),
    ]
