# Generated by Django 5.2.16 on 2026-07-26 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DomainEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_name", models.CharField(max_length=160)),
                ("schema_version", models.PositiveSmallIntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("organization_id", models.UUIDField()),
                ("event_edition_id", models.UUIDField(blank=True, null=True)),
                ("aggregate_type", models.CharField(max_length=120)),
                ("aggregate_id", models.UUIDField()),
                ("aggregate_version", models.PositiveBigIntegerField()),
                ("payload", models.JSONField()),
                ("correlation_id", models.UUIDField()),
                ("causation_id", models.UUIDField(blank=True, null=True)),
                ("actor_kind", models.CharField(max_length=40)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                (
                    "retention_class",
                    models.CharField(default="domain-standard", max_length=80),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["organization_id", "occurred_at"],
                        name="effect_event_org_time_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="effect_event_correlation_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("aggregate_type", "aggregate_id", "aggregate_version"),
                        name="domain_event_aggregate_version_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("destination", models.CharField(max_length=120)),
                ("workload_pool", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("quarantined", "Quarantined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("available_at", models.DateTimeField()),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=8)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=120)),
                ("replay_count", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_messages",
                        to="effects.domainevent",
                    ),
                ),
            ],
            options={
                "ordering": ("available_at", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="EffectAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveIntegerField()),
                ("lease_token", models.UUIDField()),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("transient_failure", "Transient failure"),
                            ("permanent_failure", "Permanent failure"),
                            ("exhausted", "Exhausted"),
                        ],
                        max_length=30,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=120)),
                ("handler_code", models.CharField(max_length=160)),
                (
                    "outbox_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="effects.outboxmessage",
                    ),
                ),
            ],
            options={
                "ordering": ("outbox_message_id", "attempt_number"),
            },
        ),
        migrations.AddIndex(
            model_name="outboxmessage",
            index=models.Index(
                fields=["organization_id", "workload_pool", "status", "available_at"],
                name="outbox_tenant_claim_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxmessage",
            index=models.Index(
                fields=["status", "lease_expires_at"], name="outbox_expired_lease_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxmessage",
            constraint=models.UniqueConstraint(
                fields=("event", "destination"), name="outbox_event_destination_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1)),
                name="outbox_max_attempts_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__lte", models.F("max_attempts"))),
                name="outbox_attempts_within_maximum",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("claimed_at__isnull", False),
                        ("completed_at__isnull", True),
                        ("lease_expires_at__isnull", False),
                        ("lease_token__isnull", False),
                        ("status", "processing"),
                    ),
                    models.Q(
                        models.Q(("status", "processing"), _negated=True),
                        ("lease_expires_at__isnull", True),
                        ("lease_token__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="outbox_lease_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", False),
                        ("status__in", ("succeeded", "quarantined", "cancelled")),
                    ),
                    models.Q(
                        ("completed_at__isnull", True),
                        ("status__in", ("pending", "processing")),
                    ),
                    _connector="OR",
                ),
                name="outbox_completion_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="effectattempt",
            constraint=models.UniqueConstraint(
                fields=("outbox_message", "attempt_number"),
                name="effect_attempt_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="effectattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("finished_at__gte", models.F("started_at"))),
                name="effect_attempt_finished_after_start",
            ),
        ),
    ]
