"""Application-portfolio routes, included once by ``maru.urls``."""

from django.urls import path

from maru.applications.api import (
    ApplicationAnswerRevisionView,
    ApplicationDefinitionCollectionView,
    ApplicationDefinitionCommandView,
    ApplicationReviewDecisionView,
    ApplicationReviewQueueView,
    ApplicationStarterCatalogView,
    ApplicationSubmissionCreateView,
    ApplicationSubmitView,
    MyApplicationWorkspaceView,
)
from maru.applications.views import (
    application_answer_append,
    application_definition_activate,
    application_definition_configure,
    application_definition_detail,
    application_definition_retire,
    application_definition_successor,
    application_definition_workspace,
    application_question_add,
    application_review_decision,
    application_review_detail,
    application_review_workspace,
    application_section_add,
    application_starter_copy,
    application_starter_copy_page,
    application_submission_start,
    application_submit,
    my_application_detail,
    my_application_index,
    my_application_workspace,
)

urlpatterns = [
    path(
        "my/applications/",
        my_application_index,
        name="my-application-index",
    ),
    path(
        "my/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/",
        my_application_workspace,
        name="my-applications",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/",
        application_definition_workspace,
        name="application-definition-workspace",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/starters/<slug:starter_code>/copy/",
        application_starter_copy_page,
        name="application-starter-copy-page",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/starters/<slug:starter_code>/copy/submit/",
        application_starter_copy,
        name="application-starter-copy",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/definitions/<uuid:definition_id>/",
        application_definition_detail,
        name="application-definition-detail",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/definitions/<uuid:definition_id>/configure/",
        application_definition_configure,
        name="application-definition-configure",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/definitions/<uuid:definition_id>/sections/",
        application_section_add,
        name="application-section-add",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/definitions/<uuid:definition_id>/questions/",
        application_question_add,
        name="application-question-add",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/definitions/<uuid:definition_id>/activate/",
        application_definition_activate,
        name="application-definition-activate",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/definitions/<uuid:definition_id>/retire/",
        application_definition_retire,
        name="application-definition-retire",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/definitions/<uuid:definition_id>/successor/",
        application_definition_successor,
        name="application-definition-successor",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/review/",
        application_review_workspace,
        name="application-review-workspace",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/review/<uuid:submission_id>/",
        application_review_detail,
        name="application-review-detail",
    ),
    path(
        "admin/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/review/<uuid:submission_id>/decisions/",
        application_review_decision,
        name="application-review-decision",
    ),
    path(
        "my/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/definitions/<uuid:definition_id>/start/",
        application_submission_start,
        name="application-submission-start",
    ),
    path(
        "my/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/submissions/<uuid:submission_id>/",
        my_application_detail,
        name="my-application-detail",
    ),
    path(
        "my/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/submissions/<uuid:submission_id>/answers/",
        application_answer_append,
        name="application-answer-append",
    ),
    path(
        "my/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/submissions/<uuid:submission_id>/submit/",
        application_submit,
        name="application-submit",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/starters",
        ApplicationStarterCatalogView.as_view(),
        name="api-application-starters",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/definitions",
        ApplicationDefinitionCollectionView.as_view(),
        name="api-application-definitions",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/definitions/<uuid:definition_id>/commands",
        ApplicationDefinitionCommandView.as_view(),
        name="api-application-definition-command",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/me",
        MyApplicationWorkspaceView.as_view(),
        name="api-my-applications",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/definitions/<uuid:definition_id>/submissions",
        ApplicationSubmissionCreateView.as_view(),
        name="api-application-submission-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/submissions/<uuid:submission_id>/answers",
        ApplicationAnswerRevisionView.as_view(),
        name="api-application-answer-revision",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/submissions/<uuid:submission_id>/submit",
        ApplicationSubmitView.as_view(),
        name="api-application-submit",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/review-queue",
        ApplicationReviewQueueView.as_view(),
        name="api-application-review-queue",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>/applications/submissions/<uuid:submission_id>/review-decisions",
        ApplicationReviewDecisionView.as_view(),
        name="api-application-review-decision",
    ),
]
