"""App-owned catalog API and same-shell routes."""

from django.urls import path

from maru.catalog.api import (
    CatalogActivateApi,
    CatalogActivityApi,
    CatalogDetailApi,
    CatalogOrderCollectionApi,
    CatalogPaymentCreateApi,
    CatalogPaymentReconcileApi,
    CatalogProductCollectionApi,
    CatalogStockAdjustApi,
    CatalogVariantCollectionApi,
)
from maru.catalog.views import (
    activate_catalog_page,
    add_catalog_product_page,
    add_catalog_variant_page,
    adjust_catalog_stock_page,
    catalog_checkout_page,
    catalog_staff_workspace,
    complete_catalog_demo_payment_page,
    create_catalog_page,
    my_catalog_index_page,
    my_catalog_orders_page,
    my_catalog_page,
    place_catalog_order_page,
    start_catalog_hosted_payment_page,
)

urlpatterns = [
    path(
        "api/v1/catalog/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/",
        CatalogDetailApi.as_view(),
        name="catalog-api-detail",
    ),
    path(
        "api/v1/catalog/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/products/",
        CatalogProductCollectionApi.as_view(),
        name="catalog-api-products",
    ),
    path(
        "api/v1/catalog/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/products/<uuid:product_id>/variants/",
        CatalogVariantCollectionApi.as_view(),
        name="catalog-api-variants",
    ),
    path(
        "api/v1/catalog/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/activate/",
        CatalogActivateApi.as_view(),
        name="catalog-api-activate",
    ),
    path(
        "api/v1/catalog/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/variants/<uuid:variant_id>/stock-adjustments/",
        CatalogStockAdjustApi.as_view(),
        name="catalog-api-stock",
    ),
    path(
        "api/v1/catalog/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/orders/",
        CatalogOrderCollectionApi.as_view(),
        name="catalog-api-orders",
    ),
    path(
        "api/v1/catalog/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/orders/<uuid:order_id>/payments/",
        CatalogPaymentCreateApi.as_view(),
        name="catalog-api-payments",
    ),
    path(
        "api/v1/catalog/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/payment-intents/<uuid:intent_id>/reconcile/",
        CatalogPaymentReconcileApi.as_view(),
        name="catalog-api-reconcile",
    ),
    path(
        "api/v1/catalog/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/activity/",
        CatalogActivityApi.as_view(),
        name="catalog-api-activity",
    ),
    path("my/catalog/", my_catalog_index_page, name="my-catalog-index"),
    path("my/catalog/<uuid:edition_id>/", my_catalog_page, name="my-catalog"),
    path(
        "my/catalog/<uuid:edition_id>/orders/",
        my_catalog_orders_page,
        name="my-catalog-orders",
    ),
    path(
        "my/catalog/<uuid:edition_id>/orders/new/",
        place_catalog_order_page,
        name="my-catalog-order",
    ),
    path(
        "my/catalog/<uuid:edition_id>/orders/<uuid:order_id>/",
        catalog_checkout_page,
        name="my-catalog-checkout",
    ),
    path(
        "my/catalog/<uuid:edition_id>/orders/<uuid:order_id>/hosted-payment/",
        start_catalog_hosted_payment_page,
        name="my-catalog-hosted-payment",
    ),
    path(
        "my/catalog/<uuid:edition_id>/orders/<uuid:order_id>/demo-payment/",
        complete_catalog_demo_payment_page,
        name="my-catalog-demo-payment",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/catalog/",
        catalog_staff_workspace,
        name="catalog-staff-workspace",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/catalog/create/",
        create_catalog_page,
        name="catalog-create-page",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/catalog/products/new/",
        add_catalog_product_page,
        name="catalog-product-add-page",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/catalog/products/"
        "<uuid:product_id>/variants/new/",
        add_catalog_variant_page,
        name="catalog-variant-add-page",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/catalog/activate/",
        activate_catalog_page,
        name="catalog-activate-page",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/catalog/variants/"
        "<uuid:variant_id>/stock-adjustments/",
        adjust_catalog_stock_page,
        name="catalog-stock-adjust-page",
    ),
]
