# Generated by Django 5.2.16 on 2026-08-08 21:13

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import maru.core.localization
import maru.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0009_edition_workspace_downgrade_fence"),
        ("organizations", "0013_runtime_executable_function_hardening"),
        ("workforce", "0007_structure_write_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name="EditionVenueSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("local_name", models.CharField(max_length=200)),
                (
                    "public_description_override",
                    models.TextField(blank=True, max_length=2000),
                ),
                (
                    "public_contact_override",
                    models.CharField(blank=True, max_length=240),
                ),
                ("opening_restrictions", models.TextField(blank=True, max_length=2000)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_venues_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_selections",
                        to="events.eventedition",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_venues_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_venue_selections",
                        to="organizations.organization",
                    ),
                ),
                (
                    "responsible_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_venue_selections",
                        to="workforce.department",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "local_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="EditionSpaceSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("local_name", models.CharField(max_length=200)),
                ("configuration_name", models.CharField(max_length=200)),
                ("seated_capacity", models.PositiveIntegerField(default=0)),
                ("standing_capacity", models.PositiveIntegerField(default=0)),
                ("table_capacity", models.PositiveIntegerField(default=0)),
                ("fire_capacity", models.PositiveIntegerField()),
                ("public_access_info", models.TextField(blank=True, max_length=2000)),
                ("opening_restrictions", models.TextField(blank=True, max_length=2000)),
                (
                    "current_availability_version",
                    models.PositiveBigIntegerField(default=0),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="space_selections",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_space_selections",
                        to="organizations.organization",
                    ),
                ),
                (
                    "responsible_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_space_selections",
                        to="workforce.department",
                    ),
                ),
                (
                    "venue_selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="space_selections",
                        to="venues.editionvenueselection",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "local_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="VenueLayoutVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layout_code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("security", "Security"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_reference", models.CharField(max_length=1000)),
                ("approved_reference", models.CharField(blank=True, max_length=1000)),
                (
                    "checksum_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_venue_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=2000)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_layout_versions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_layouts_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_layouts_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("space_id", "layout_code", "version", "id"),
            },
        ),
        migrations.CreateModel(
            name="VenueBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("programme", "Programme"),
                            ("panel", "Panel"),
                            ("event", "Event"),
                            ("department", "Department"),
                            ("storage", "Storage"),
                            ("catering", "Catering"),
                            ("rehearsal", "Rehearsal"),
                            ("private", "Private"),
                        ],
                        max_length=16,
                    ),
                ),
                ("external_reference", models.CharField(blank=True, max_length=240)),
                ("internal_title", models.CharField(max_length=240)),
                ("public_title", models.CharField(blank=True, max_length=240)),
                ("public_description", models.TextField(blank=True, max_length=2000)),
                (
                    "capacity_mode",
                    models.CharField(
                        choices=[
                            ("seated", "Seated"),
                            ("standing", "Standing"),
                            ("table", "Table"),
                        ],
                        max_length=16,
                    ),
                ),
                ("expected_attendance", models.PositiveIntegerField()),
                ("setup_starts_at", models.DateTimeField()),
                ("effective_starts_at", models.DateTimeField()),
                ("effective_ends_at", models.DateTimeField()),
                ("teardown_ends_at", models.DateTimeField()),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("active", "Active"), ("cancelled", "Cancelled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "review_state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "publication_state",
                    models.CharField(
                        choices=[
                            ("unpublished", "Unpublished"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="unpublished",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_bookings_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_bookings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_bookings",
                        to="events.eventedition",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_bookings_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_bookings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_bookings_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_bookings",
                        to="workforce.department",
                    ),
                ),
                (
                    "space_selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="venues.editionspaceselection",
                    ),
                ),
                (
                    "public_layout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="public_bookings",
                        to="venues.venuelayoutversion",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "effective_starts_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="VenueProperty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("venue", "Venue"),
                            ("mixed", "Hotel and venue"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("legal_name", models.CharField(max_length=240)),
                ("provider_name", models.CharField(blank=True, max_length=240)),
                ("public_name", models.CharField(max_length=200)),
                ("public_description", models.TextField(blank=True, max_length=5000)),
                ("internal_notes", models.TextField(blank=True, max_length=5000)),
                ("location_name", models.CharField(max_length=240)),
                ("postal_address", models.TextField(max_length=1000)),
                (
                    "country_code",
                    models.CharField(
                        max_length=2,
                        validators=[maru.core.localization.validate_country_code],
                    ),
                ),
                ("website_url", models.URLField(blank=True)),
                ("public_contact", models.CharField(blank=True, max_length=240)),
                ("contact_name", models.CharField(blank=True, max_length=240)),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter one international telephone number.",
                                regex="^\\+[1-9]\\d{6,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_properties_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_properties_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_properties",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "public_name", "id"),
            },
        ),
        migrations.AddField(
            model_name="editionvenueselection",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="edition_selections",
                to="venues.venueproperty",
            ),
        ),
        migrations.CreateModel(
            name="AccommodationRoomType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("public_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("accessible_features", models.TextField(blank=True, max_length=2000)),
                ("minimum_occupants", models.PositiveSmallIntegerField(default=1)),
                ("maximum_occupants", models.PositiveSmallIntegerField()),
                ("provider_reference", models.CharField(blank=True, max_length=240)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accommodation_room_types",
                        to="organizations.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accommodation_room_types",
                        to="venues.venueproperty",
                    ),
                ),
            ],
            options={
                "ordering": ("property_id", "public_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="VenuePropertyMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "Photo"), ("logo", "Logo")], max_length=16
                    ),
                ),
                ("source_reference", models.CharField(max_length=1000)),
                ("public_reference", models.CharField(blank=True, max_length=1000)),
                ("owner_name", models.CharField(max_length=240)),
                ("license_basis", models.CharField(max_length=500)),
                ("usage_scope", models.CharField(max_length=500)),
                ("attribution", models.CharField(blank=True, max_length=500)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_property_media",
                        to="organizations.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_references",
                        to="venues.venueproperty",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_media_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_media_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("property_id", "kind", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="VenueSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("public_description", models.TextField(blank=True, max_length=2000)),
                ("postal_address", models.TextField(blank=True, max_length=1000)),
                ("access_facts", models.TextField(blank=True, max_length=2000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_sites",
                        to="organizations.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sites",
                        to="venues.venueproperty",
                    ),
                ),
            ],
            options={
                "ordering": ("property_id", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="VenueBuilding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("public_description", models.TextField(blank=True, max_length=2000)),
                ("access_facts", models.TextField(blank=True, max_length=2000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_buildings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buildings",
                        to="venues.venueproperty",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buildings",
                        to="venues.venuesite",
                    ),
                ),
            ],
            options={
                "ordering": ("site_id", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="VenueSpace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("function_room", "Function room"),
                            ("zone", "Zone"),
                            ("entrance", "Entrance"),
                            ("route", "Route"),
                            ("loading", "Loading area"),
                            ("storage", "Storage"),
                            ("green_room", "Green room"),
                            ("catering", "Catering space"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("public_description", models.TextField(blank=True, max_length=2000)),
                ("internal_description", models.TextField(blank=True, max_length=5000)),
                (
                    "accessibility_features",
                    models.TextField(blank=True, max_length=2000),
                ),
                ("known_barriers", models.TextField(blank=True, max_length=2000)),
                ("equipment_facts", models.TextField(blank=True, max_length=2000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spaces",
                        to="venues.venuebuilding",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_spaces",
                        to="organizations.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spaces",
                        to="venues.venueproperty",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spaces",
                        to="venues.venuesite",
                    ),
                ),
            ],
            options={
                "ordering": ("building_id", "name", "id"),
            },
        ),
        migrations.AddField(
            model_name="venuelayoutversion",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="layout_versions",
                to="venues.venuespace",
            ),
        ),
        migrations.CreateModel(
            name="VenueBookingOccupancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conflict_group",
                    models.CharField(
                        choices=[
                            ("setup_effective", "Setup and effective"),
                            ("effective_teardown", "Effective and teardown"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "occupied_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                ("booking_version", models.PositiveBigIntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occupancy_rows",
                        to="venues.venuebooking",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_booking_occupancy",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_booking_occupancy",
                        to="organizations.organization",
                    ),
                ),
                (
                    "source_space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_occupancy",
                        to="venues.venuespace",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "source_space_id",
                    "conflict_group",
                    "occupied_range",
                    "id",
                ),
            },
        ),
        migrations.AddField(
            model_name="editionspaceselection",
            name="source_space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="edition_selections",
                to="venues.venuespace",
            ),
        ),
        migrations.CreateModel(
            name="EditionSpaceMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="space_members",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_space_members",
                        to="organizations.organization",
                    ),
                ),
                (
                    "space_selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="physical_members",
                        to="venues.editionspaceselection",
                    ),
                ),
                (
                    "source_space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_physical_memberships",
                        to="venues.venuespace",
                    ),
                ),
            ],
            options={
                "ordering": ("space_selection_id", "source_space_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="VenueSpaceCombination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_space_combinations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="space_combinations",
                        to="venues.venueproperty",
                    ),
                ),
            ],
            options={
                "ordering": ("property_id", "name", "id"),
            },
        ),
        migrations.AddField(
            model_name="editionspaceselection",
            name="source_combination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="edition_selections",
                to="venues.venuespacecombination",
            ),
        ),
        migrations.CreateModel(
            name="VenueSpaceCombinationMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "combination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="venues.venuespacecombination",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_space_combination_members",
                        to="organizations.organization",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combination_memberships",
                        to="venues.venuespace",
                    ),
                ),
            ],
            options={
                "ordering": ("combination_id", "space_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="VenueSpaceConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("seated_capacity", models.PositiveIntegerField(default=0)),
                ("standing_capacity", models.PositiveIntegerField(default=0)),
                ("table_capacity", models.PositiveIntegerField(default=0)),
                ("fire_capacity", models.PositiveIntegerField()),
                (
                    "accessibility_features",
                    models.TextField(blank=True, max_length=2000),
                ),
                ("equipment_facts", models.TextField(blank=True, max_length=2000)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_space_configurations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to="venues.venuespace",
                    ),
                ),
            ],
            options={
                "ordering": ("space_id", "code", "version", "id"),
            },
        ),
        migrations.AddField(
            model_name="editionspaceselection",
            name="selected_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="edition_selections",
                to="venues.venuespaceconfiguration",
            ),
        ),
        migrations.CreateModel(
            name="AccommodationNightInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("night", models.DateField()),
                ("room_capacity", models.PositiveIntegerField()),
                ("release_at", models.DateTimeField()),
                ("provider_reference", models.CharField(blank=True, max_length=240)),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accommodation_night_inventory",
                        to="organizations.organization",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="night_inventory",
                        to="venues.accommodationroomtype",
                    ),
                ),
            ],
            options={
                "ordering": ("room_type_id", "night", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room_type", "night"),
                        name="venue_room_night_inventory_uq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EditionSpaceAvailabilityWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("availability_version", models.PositiveBigIntegerField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("opening_restriction", models.CharField(blank=True, max_length=500)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="space_availability",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_space_availability",
                        to="organizations.organization",
                    ),
                ),
                (
                    "space_selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="availability_windows",
                        to="venues.editionspaceselection",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "space_selection_id",
                    "availability_version",
                    "starts_at",
                    "id",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "space_selection",
                            "availability_version",
                            "starts_at",
                            "ends_at",
                        ),
                        name="venue_space_availability_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("starts_at__lt", models.F("ends_at"))),
                        name="venue_space_availability_order",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VenueBookingHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                ("booking_version", models.PositiveBigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("rescheduled", "Rescheduled"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("withdrawn", "Publication withdrawn"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                ("old_setup_starts_at", models.DateTimeField(blank=True, null=True)),
                (
                    "old_effective_starts_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("old_effective_ends_at", models.DateTimeField(blank=True, null=True)),
                ("old_teardown_ends_at", models.DateTimeField(blank=True, null=True)),
                ("new_setup_starts_at", models.DateTimeField(blank=True, null=True)),
                (
                    "new_effective_starts_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("new_effective_ends_at", models.DateTimeField(blank=True, null=True)),
                ("new_teardown_ends_at", models.DateTimeField(blank=True, null=True)),
                ("from_review_state", models.CharField(blank=True, max_length=16)),
                ("to_review_state", models.CharField(blank=True, max_length=16)),
                ("from_publication_state", models.CharField(blank=True, max_length=16)),
                ("to_publication_state", models.CharField(blank=True, max_length=16)),
                ("from_lifecycle", models.CharField(blank=True, max_length=16)),
                ("to_lifecycle", models.CharField(blank=True, max_length=16)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_booking_history_acted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history_entries",
                        to="venues.venuebooking",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_booking_history",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_booking_history",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("booking_id", "sequence", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "sequence"),
                        name="venue_booking_history_sequence_uq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VenueCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("property.create", "Create property"),
                            ("catalog.add", "Add catalog record"),
                            ("media.add", "Add media"),
                            ("media.review", "Review media"),
                            ("layout.add", "Add layout"),
                            ("layout.review", "Review layout"),
                            ("room_inventory.set", "Set room inventory"),
                            ("edition.select", "Select venue"),
                            ("space.select", "Select space"),
                            ("availability.set", "Set availability"),
                            ("booking.create", "Create booking"),
                            ("booking.reschedule", "Reschedule booking"),
                            ("booking.approve", "Approve booking"),
                            ("booking.publish", "Publish booking"),
                            ("booking.withdraw", "Withdraw booking"),
                            ("booking.cancel", "Cancel booking"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_venue_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("result_object_id", models.UUIDField()),
                ("resulting_version", models.PositiveBigIntegerField()),
                ("correlation_id", models.UUIDField()),
                ("source_channel", models.CharField(max_length=32)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_commands_acted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_command_receipts",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_command_receipts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actor", "operation", "idempotency_key"),
                        name="venue_command_retry_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("resulting_version__gt", 0)),
                        name="venue_receipt_version_pos",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="venuebooking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("setup_starts_at__lte", models.F("effective_starts_at")),
                    ("effective_starts_at__lt", models.F("effective_ends_at")),
                    ("effective_ends_at__lte", models.F("teardown_ends_at")),
                ),
                name="venue_booking_envelope_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuebooking",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_attendance__gt", 0)),
                name="venue_booking_attendance_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuebooking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("publication_state", "published"), _negated=True),
                    ("review_state", "approved"),
                    _connector="OR",
                ),
                name="venue_booking_publish_approved",
            ),
        ),
        migrations.AddConstraint(
            model_name="venueproperty",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                django.db.models.functions.text.Lower("slug"),
                name="venue_property_org_slug_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="venueproperty",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="venue_property_version_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="editionvenueselection",
            constraint=models.UniqueConstraint(
                fields=("edition", "property"), name="venue_edition_property_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accommodationroomtype",
            constraint=models.UniqueConstraint(
                models.F("property"),
                django.db.models.functions.text.Lower("code"),
                name="venue_room_type_property_code_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="accommodationroomtype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maximum_occupants__gte", models.F("minimum_occupants"))
                ),
                name="venue_room_type_occupancy_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuepropertymedia",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="venue_media_version_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuesite",
            constraint=models.UniqueConstraint(
                models.F("property"),
                django.db.models.functions.text.Lower("code"),
                name="venue_site_property_code_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuebuilding",
            constraint=models.UniqueConstraint(
                models.F("site"),
                django.db.models.functions.text.Lower("code"),
                name="venue_building_site_code_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuespace",
            constraint=models.UniqueConstraint(
                models.F("building"),
                django.db.models.functions.text.Lower("code"),
                name="venue_space_building_code_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuelayoutversion",
            constraint=models.UniqueConstraint(
                fields=("space", "layout_code", "version"),
                name="venue_layout_space_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuebookingoccupancy",
            constraint=models.UniqueConstraint(
                fields=("booking", "booking_version", "source_space", "conflict_group"),
                name="venue_booking_occupancy_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuebookingoccupancy",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("active", True)),
                expressions=(
                    ("source_space", "="),
                    ("conflict_group", "="),
                    ("occupied_range", "&&"),
                ),
                name="venue_booking_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="editionspacemember",
            constraint=models.UniqueConstraint(
                fields=("space_selection", "source_space"),
                name="venue_edition_space_member_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuespacecombination",
            constraint=models.UniqueConstraint(
                models.F("property"),
                django.db.models.functions.text.Lower("code"),
                name="venue_combo_property_code_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuespacecombinationmember",
            constraint=models.UniqueConstraint(
                fields=("combination", "space"), name="venue_combo_member_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="venuespaceconfiguration",
            constraint=models.UniqueConstraint(
                fields=("space", "code", "version"),
                name="venue_space_config_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuespaceconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("fire_capacity__gt", 0)),
                name="venue_config_fire_capacity_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="editionspaceselection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_combination__isnull", True),
                        ("source_space__isnull", False),
                    ),
                    models.Q(
                        ("source_combination__isnull", False),
                        ("source_space__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="venue_edition_space_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="editionspaceselection",
            constraint=models.CheckConstraint(
                condition=models.Q(("fire_capacity__gt", 0)),
                name="venue_edition_space_fire_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="editionspaceselection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_space__isnull", False)),
                fields=("edition", "source_space"),
                name="venue_edition_source_space_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="editionspaceselection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_combination__isnull", False)),
                fields=("edition", "source_combination"),
                name="venue_edition_source_combo_uq",
            ),
        ),
    ]
