# Generated by Django 5.2.17 on 2026-09-07 02:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("programme", "0009_host_downgrade_fence"),
        ("venues", "0002_venue_write_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulingCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("aggregate_version", models.PositiveBigIntegerField()),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("draft", "Draft"), ("archived", "Archived")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_candidates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingCandidateRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                ("sequence", models.PositiveBigIntegerField()),
                ("label", models.CharField(max_length=240)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("day_create", "Day Create"),
                            ("day_revise", "Day Revise"),
                            ("occurrence_create", "Occurrence Create"),
                            ("occurrence_revise", "Occurrence Revise"),
                            ("occurrence_retire", "Occurrence Retire"),
                            ("candidate_create", "Candidate Create"),
                            ("candidate_copy", "Candidate Copy"),
                            ("placement_set", "Placement Set"),
                            ("placement_remove", "Placement Remove"),
                            ("candidate_restore", "Candidate Restore"),
                            ("candidate_archive", "Candidate Archive"),
                            ("evaluation_record", "Evaluation Record"),
                            ("warning_acknowledge", "Warning Acknowledge"),
                            ("reservation_replace", "Reservation Replace"),
                            ("reservation_cancel", "Reservation Cancel"),
                        ],
                        max_length=32,
                    ),
                ),
                ("placement_count", models.PositiveIntegerField()),
                (
                    "manifest_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}\\Z", "Use a lower-case SHA-256 digest."
                            )
                        ],
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="scheduling.schedulingcandidate",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "source_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_revisions",
                        to="scheduling.schedulingcandidaterevision",
                    ),
                ),
            ],
            options={
                "ordering": ("candidate_id", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="SchedulingCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("day_create", "Day Create"),
                            ("day_revise", "Day Revise"),
                            ("occurrence_create", "Occurrence Create"),
                            ("occurrence_revise", "Occurrence Revise"),
                            ("occurrence_retire", "Occurrence Retire"),
                            ("candidate_create", "Candidate Create"),
                            ("candidate_copy", "Candidate Copy"),
                            ("placement_set", "Placement Set"),
                            ("placement_remove", "Placement Remove"),
                            ("candidate_restore", "Candidate Restore"),
                            ("candidate_archive", "Candidate Archive"),
                            ("evaluation_record", "Evaluation Record"),
                            ("warning_acknowledge", "Warning Acknowledge"),
                            ("reservation_replace", "Reservation Replace"),
                            ("reservation_cancel", "Reservation Cancel"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}\\Z", "Use a lower-case SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("control_version", models.PositiveBigIntegerField()),
                ("result_object_id", models.UUIDField()),
                ("resulting_version", models.PositiveBigIntegerField()),
                ("correlation_id", models.UUIDField()),
                ("source_channel", models.CharField(max_length=32)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingEditionControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("aggregate_version", models.PositiveBigIntegerField()),
                (
                    "edition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_control",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                (
                    "dependency_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}\\Z", "Use a lower-case SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("source_evidence", models.JSONField(default=list)),
                ("conflict_count", models.PositiveIntegerField()),
                ("is_complete", models.BooleanField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluations",
                        to="scheduling.schedulingcandidaterevision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SchedulingOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("aggregate_version", models.PositiveBigIntegerField()),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "programme_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_occurrences",
                        to="programme.programmeitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_code", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("blocker", "Blocker"),
                            ("warning", "Warning"),
                            ("unavailable", "Unavailable"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}\\Z", "Use a lower-case SHA-256 digest."
                            )
                        ],
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conflicts",
                        to="scheduling.schedulingevaluation",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conflicts",
                        to="scheduling.schedulingoccurrence",
                    ),
                ),
                (
                    "other_occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="peer_conflicts",
                        to="scheduling.schedulingoccurrence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingOccurrenceRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                ("sequence", models.PositiveBigIntegerField()),
                ("group_key", models.UUIDField(blank=True, null=True)),
                ("group_sequence", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        max_length=16,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="scheduling.schedulingoccurrence",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("occurrence_id", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="SchedulingPlacementRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capacity_mode",
                    models.CharField(
                        choices=[
                            ("seated", "Seated"),
                            ("standing", "Standing"),
                            ("table", "Table"),
                        ],
                        max_length=16,
                    ),
                ),
                ("expected_attendance", models.PositiveIntegerField()),
                ("setup_starts_at", models.DateTimeField()),
                ("effective_starts_at", models.DateTimeField()),
                ("effective_ends_at", models.DateTimeField()),
                ("teardown_ends_at", models.DateTimeField()),
                ("host_presence_count", models.PositiveSmallIntegerField()),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "introduced_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="introduced_placements",
                        to="scheduling.schedulingcandidaterevision",
                    ),
                ),
                (
                    "occurrence_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="scheduling.schedulingoccurrencerevision",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "space_selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_placements",
                        to="venues.editionspaceselection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingPlacementHostPresence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "host_relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_presences",
                        to="programme.programmehostrelationship",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="host_presences",
                        to="scheduling.schedulingplacementrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingCandidateMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="scheduling.schedulingcandidaterevision",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_memberships",
                        to="scheduling.schedulingoccurrence",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="scheduling.schedulingplacementrevision",
                    ),
                ),
            ],
            options={
                "ordering": ("revision_id", "occurrence_id"),
            },
        ),
        migrations.CreateModel(
            name="SchedulingServiceDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("aggregate_version", models.PositiveBigIntegerField()),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingServiceDayRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                ("sequence", models.PositiveBigIntegerField()),
                ("label", models.CharField(max_length=240)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("precision_minutes", models.PositiveSmallIntegerField()),
                ("edition_version", models.PositiveBigIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="scheduling.schedulingserviceday",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("day_id", "sequence"),
            },
        ),
        migrations.AddField(
            model_name="schedulingplacementrevision",
            name="day_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placements",
                to="scheduling.schedulingservicedayrevision",
            ),
        ),
        migrations.CreateModel(
            name="SchedulingWarningAcknowledgement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conflict",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acknowledgement",
                        to="scheduling.schedulingconflict",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="schedulingcandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("aggregate_version__gt", 0),
                    ("lifecycle__in", ("draft", "archived")),
                ),
                name="sch_candidate_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingcandidaterevision",
            constraint=models.UniqueConstraint(
                fields=("candidate", "sequence"), name="sch_candidate_revision_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingcandidaterevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation__in",
                        (
                            "day_create",
                            "day_revise",
                            "occurrence_create",
                            "occurrence_revise",
                            "occurrence_retire",
                            "candidate_create",
                            "candidate_copy",
                            "placement_set",
                            "placement_remove",
                            "candidate_restore",
                            "candidate_archive",
                            "evaluation_record",
                            "warning_acknowledge",
                            "reservation_replace",
                            "reservation_cancel",
                        ),
                    ),
                    ("placement_count__lte", 2000),
                    ("sequence__gt", 0),
                    models.Q(("label", ""), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="sch_candidate_revision_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("edition", "actor", "idempotency_key"),
                name="sch_command_retry_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("edition", "control_version"), name="sch_command_version_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("control_version__gt", 0),
                    (
                        "operation__in",
                        (
                            "day_create",
                            "day_revise",
                            "occurrence_create",
                            "occurrence_revise",
                            "occurrence_retire",
                            "candidate_create",
                            "candidate_copy",
                            "placement_set",
                            "placement_remove",
                            "candidate_restore",
                            "candidate_archive",
                            "evaluation_record",
                            "warning_acknowledge",
                            "reservation_replace",
                            "reservation_cancel",
                        ),
                    ),
                    ("resulting_version__gt", 0),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="sch_command_receipt_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingeditioncontrol",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="sch_control_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("aggregate_version__gt", 0),
                    ("lifecycle__in", ("active", "retired")),
                ),
                name="sch_occurrence_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingconflict",
            constraint=models.UniqueConstraint(
                fields=("evaluation", "fingerprint"), name="sch_conflict_fingerprint_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingconflict",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("severity__in", ("blocker", "warning", "unavailable"))
                ),
                name="sch_conflict_severity_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingoccurrencerevision",
            constraint=models.UniqueConstraint(
                fields=("occurrence", "sequence"), name="sch_occurrence_revision_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingoccurrencerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lifecycle__in", ("active", "retired")),
                    ("sequence__gt", 0),
                    models.Q(
                        models.Q(
                            ("group_key__isnull", True),
                            ("group_sequence__isnull", True),
                        ),
                        models.Q(
                            ("group_key__isnull", False),
                            ("group_sequence__gt", 0),
                            ("group_sequence__isnull", False),
                        ),
                        _connector="OR",
                    ),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="sch_occurrence_revision_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingplacementhostpresence",
            constraint=models.UniqueConstraint(
                fields=("placement", "host_relationship"), name="sch_placement_host_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingplacementhostpresence",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="sch_host_presence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingcandidatemember",
            constraint=models.UniqueConstraint(
                fields=("revision", "occurrence"), name="sch_manifest_occurrence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingcandidatemember",
            constraint=models.UniqueConstraint(
                fields=("revision", "placement"), name="sch_manifest_placement_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingserviceday",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="sch_day_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingservicedayrevision",
            constraint=models.UniqueConstraint(
                fields=("day", "sequence"), name="sch_day_revision_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingservicedayrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("edition_version__gt", 0),
                    ("ends_at__gt", models.F("starts_at")),
                    (
                        "precision_minutes__in",
                        (1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60),
                    ),
                    ("sequence__gt", 0),
                    models.Q(("label", ""), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="sch_day_revision_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingplacementrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capacity_mode__in", ("seated", "standing", "table")),
                    ("effective_ends_at__lte", models.F("teardown_ends_at")),
                    ("effective_starts_at__lt", models.F("effective_ends_at")),
                    ("expected_attendance__gt", 0),
                    ("host_presence_count__lte", 100),
                    ("setup_starts_at__lte", models.F("effective_starts_at")),
                ),
                name="sch_placement_envelope_shape",
            ),
        ),
    ]
