# Generated by Django 5.2.17 on 2026-09-07 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="schedulingcandidaterevision",
            name="sch_candidate_revision_shape",
        ),
        migrations.RemoveConstraint(
            model_name="schedulingcommandreceipt",
            name="sch_command_receipt_shape",
        ),
        migrations.RemoveConstraint(
            model_name="schedulingserviceday",
            name="sch_day_version_positive",
        ),
        migrations.RemoveConstraint(
            model_name="schedulingservicedayrevision",
            name="sch_day_revision_shape",
        ),
        migrations.AddField(
            model_name="schedulingserviceday",
            name="lifecycle",
            field=models.CharField(
                choices=[("active", "Active"), ("retired", "Retired")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="schedulingservicedayrevision",
            name="lifecycle",
            field=models.CharField(
                choices=[("active", "Active"), ("retired", "Retired")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="schedulingcandidaterevision",
            name="operation",
            field=models.CharField(
                choices=[
                    ("day_create", "Day Create"),
                    ("day_revise", "Day Revise"),
                    ("day_retire", "Day Retire"),
                    ("occurrence_create", "Occurrence Create"),
                    ("occurrence_revise", "Occurrence Revise"),
                    ("occurrence_retire", "Occurrence Retire"),
                    ("candidate_create", "Candidate Create"),
                    ("candidate_copy", "Candidate Copy"),
                    ("placement_set", "Placement Set"),
                    ("placement_remove", "Placement Remove"),
                    ("candidate_restore", "Candidate Restore"),
                    ("candidate_archive", "Candidate Archive"),
                    ("evaluation_record", "Evaluation Record"),
                    ("warning_acknowledge", "Warning Acknowledge"),
                    ("reservation_replace", "Reservation Replace"),
                    ("reservation_cancel", "Reservation Cancel"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="schedulingcommandreceipt",
            name="operation",
            field=models.CharField(
                choices=[
                    ("day_create", "Day Create"),
                    ("day_revise", "Day Revise"),
                    ("day_retire", "Day Retire"),
                    ("occurrence_create", "Occurrence Create"),
                    ("occurrence_revise", "Occurrence Revise"),
                    ("occurrence_retire", "Occurrence Retire"),
                    ("candidate_create", "Candidate Create"),
                    ("candidate_copy", "Candidate Copy"),
                    ("placement_set", "Placement Set"),
                    ("placement_remove", "Placement Remove"),
                    ("candidate_restore", "Candidate Restore"),
                    ("candidate_archive", "Candidate Archive"),
                    ("evaluation_record", "Evaluation Record"),
                    ("warning_acknowledge", "Warning Acknowledge"),
                    ("reservation_replace", "Reservation Replace"),
                    ("reservation_cancel", "Reservation Cancel"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingcandidaterevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation__in",
                        (
                            "day_create",
                            "day_revise",
                            "day_retire",
                            "occurrence_create",
                            "occurrence_revise",
                            "occurrence_retire",
                            "candidate_create",
                            "candidate_copy",
                            "placement_set",
                            "placement_remove",
                            "candidate_restore",
                            "candidate_archive",
                            "evaluation_record",
                            "warning_acknowledge",
                            "reservation_replace",
                            "reservation_cancel",
                        ),
                    ),
                    ("placement_count__lte", 2000),
                    ("sequence__gt", 0),
                    models.Q(("label", ""), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="sch_candidate_revision_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("control_version__gt", 0),
                    (
                        "operation__in",
                        (
                            "day_create",
                            "day_revise",
                            "day_retire",
                            "occurrence_create",
                            "occurrence_revise",
                            "occurrence_retire",
                            "candidate_create",
                            "candidate_copy",
                            "placement_set",
                            "placement_remove",
                            "candidate_restore",
                            "candidate_archive",
                            "evaluation_record",
                            "warning_acknowledge",
                            "reservation_replace",
                            "reservation_cancel",
                        ),
                    ),
                    ("resulting_version__gt", 0),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="sch_command_receipt_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingserviceday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("aggregate_version__gt", 0),
                    ("lifecycle__in", ("active", "retired")),
                ),
                name="sch_day_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingservicedayrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("edition_version__gt", 0),
                    ("ends_at__gt", models.F("starts_at")),
                    ("lifecycle__in", ("active", "retired")),
                    (
                        "precision_minutes__in",
                        (1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60),
                    ),
                    ("sequence__gt", 0),
                    models.Q(("label", ""), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="sch_day_revision_shape",
            ),
        ),
    ]
