# Generated by Django 5.2.17 on 2026-09-07 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("scheduling", "0002_service_day_retirement"),
        ("venues", "0002_venue_write_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulingReservationIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("reservation_replace", "Replace reservation"),
                            ("reservation_cancel", "Cancel reservation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("expected_booking_version", models.PositiveBigIntegerField(default=0)),
                ("target_booking_id", models.UUIDField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_intents",
                        to="scheduling.schedulingcandidaterevision",
                    ),
                ),
                (
                    "command_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_intent",
                        to="scheduling.schedulingcommandreceipt",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_intents",
                        to="scheduling.schedulingoccurrence",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_intents",
                        to="scheduling.schedulingplacementrevision",
                    ),
                ),
                (
                    "previous_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_successor_intents",
                        to="venues.venuebooking",
                    ),
                ),
                (
                    "venue_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_reservation_intent",
                        to="venues.venuecommandreceipt",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                models.Q(
                                    ("expected_booking_version", 0),
                                    ("previous_booking__isnull", True),
                                ),
                                models.Q(
                                    ("expected_booking_version__gt", 0),
                                    ("previous_booking__isnull", False),
                                ),
                                _connector="OR",
                            ),
                            models.Q(
                                models.Q(
                                    ("operation", "reservation_replace"),
                                    ("target_booking_id__isnull", False),
                                ),
                                models.Q(
                                    ("operation", "reservation_cancel"),
                                    ("previous_booking__isnull", False),
                                    ("target_booking_id__isnull", True),
                                ),
                                _connector="OR",
                            ),
                        ),
                        name="sch_reservation_intent_shape",
                    )
                ],
            },
        ),
    ]
