# Generated by Django 5.2.17 on 2026-09-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0003_scheduling_reservation_sources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulingconflict",
            name="code",
            field=models.CharField(
                choices=[
                    ("edition_unavailable", "Edition Unavailable"),
                    ("day_changed", "Day Changed"),
                    ("day_retired", "Day Retired"),
                    ("edition_bounds", "Edition Bounds"),
                    ("day_bounds", "Day Bounds"),
                    ("minute_grid", "Minute Grid"),
                    ("occurrence_changed", "Occurrence Changed"),
                    ("occurrence_retired", "Occurrence Retired"),
                    ("programme_unavailable", "Programme Unavailable"),
                    ("item_retired", "Item Retired"),
                    ("host_required", "Host Required"),
                    ("host_not_current", "Host Not Current"),
                    ("host_source_unavailable", "Host Source Unavailable"),
                    ("host_unavailable", "Host Unavailable"),
                    ("host_outside_availability", "Host Outside Availability"),
                    ("host_outside_preference", "Host Outside Preference"),
                    ("host_overlap", "Host Overlap"),
                    ("venue_unavailable", "Venue Unavailable"),
                    ("venue_inactive", "Venue Inactive"),
                    ("venue_capacity", "Venue Capacity"),
                    ("venue_availability_missing", "Venue Availability Missing"),
                    ("venue_hard_availability", "Venue Hard Availability"),
                    ("candidate_room_overlap", "Candidate Room Overlap"),
                    ("reserved_room_overlap", "Reserved Room Overlap"),
                    ("turnover_overlap", "Turnover Overlap"),
                    ("evaluation_limit", "Evaluation Limit"),
                ],
                max_length=64,
            ),
        ),
    ]
