# Generated by Django 5.2.17 on 2026-09-11 12:10
"""Add dormant exact review, captured source, artifact and publication history."""

import uuid
from typing import Any, ClassVar

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

RETAINED_MODELS = (
    "SchedulingReleaseWarningAcknowledgement",
    "SchedulingReleaseApproval",
    "SchedulingReleaseApprovalPlacement",
    "SchedulingReleaseApprovalDependency",
    "SchedulingRelease",
    "SchedulingReleaseArtifact",
    "SchedulingReleaseWithdrawal",
    "SchedulingReleasePointer",
)


def refuse_used_release_schema_downgrade(apps: Any, schema_editor: Any) -> None:
    """Retain every approval, release, withdrawal and active-pointer history."""
    retained = tuple(apps.get_model("scheduling", name) for name in RETAINED_MODELS)
    tables = sorted(
        schema_editor.quote_name(model._meta.db_table)  # noqa: SLF001 - historical model metadata
        for model in retained
    )
    schema_editor.execute(
        "LOCK TABLE " + ", ".join(tables) + " IN ACCESS EXCLUSIVE MODE"
    )
    if any(model.objects.exists() for model in retained):
        raise RuntimeError(
            "Programme release history exists; retain schema and fix forward."
        )


class Migration(migrations.Migration):
    """Keep release evidence separate and refuse populated schema removal."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("events", "0011_release_dependency_mutations"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("programme", "0016_release_dependency_mutations"),
        ("scheduling", "0009_native_release_journal_writer"),
        ("venues", "0007_release_physical_closure"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list[object]] = [
        migrations.CreateModel(
            name="SchedulingReleaseApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                (
                    "source_snapshot_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}\\Z", "Use a lower-case SHA-256 digest."
                            )
                        ],
                    ),
                ),
                (
                    "manifest_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}\\Z", "Use a lower-case SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("eligibility_policy", models.CharField(max_length=80)),
                (
                    "warning_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        size=10000,
                    ),
                ),
                ("placement_count", models.PositiveIntegerField()),
                ("dependency_count", models.PositiveIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_approvals",
                        to="scheduling.schedulingcandidaterevision",
                    ),
                ),
                (
                    "command_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_approval",
                        to="scheduling.schedulingcommandreceipt",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                ("pointer_version", models.PositiveBigIntegerField()),
                ("added_count", models.PositiveIntegerField()),
                ("changed_count", models.PositiveIntegerField()),
                ("removed_count", models.PositiveIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "command_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release",
                        to="scheduling.schedulingcommandreceipt",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "previous_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="scheduling.schedulingrelease",
                    ),
                ),
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release",
                        to="scheduling.schedulingreleaseapproval",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingReleaseApprovalPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="scheduling.schedulingreleaseapproval",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_approval_placements",
                        to="scheduling.schedulingoccurrence",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_approval_placements",
                        to="scheduling.schedulingplacementrevision",
                    ),
                ),
                (
                    "public_rendition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_release_approval_placements",
                        to="programme.programmepublicrendition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingReleaseApprovalDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("captured_generation", models.PositiveBigIntegerField()),
                (
                    "horizon",
                    models.CharField(
                        choices=[
                            ("approval_only", "Approval Only"),
                            ("operational", "Operational"),
                            ("disclosure", "Disclosure"),
                        ],
                        max_length=24,
                    ),
                ),
                ("operational_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dependencies",
                        to="scheduling.schedulingreleaseapproval",
                    ),
                ),
                (
                    "dependency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_captures",
                        to="scheduling.schedulingreleasedependencykey",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "approval_placement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dependencies",
                        to="scheduling.schedulingreleaseapprovalplacement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingReleaseArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract", models.CharField(max_length=80)),
                (
                    "sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}\\Z", "Use a lower-case SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("byte_length", models.PositiveIntegerField()),
                ("payload", models.BinaryField()),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="scheduling.schedulingrelease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingReleasePointer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveBigIntegerField()),
                (
                    "active_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_pointers",
                        to="scheduling.schedulingrelease",
                    ),
                ),
                (
                    "command_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_release_pointer",
                        to="scheduling.schedulingcommandreceipt",
                    ),
                ),
                (
                    "edition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_release_pointer",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingReleaseWarningAcknowledgement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                (
                    "source_snapshot_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}\\Z", "Use a lower-case SHA-256 digest."
                            )
                        ],
                    ),
                ),
                (
                    "finding_fingerprint",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}\\Z", "Use a lower-case SHA-256 digest."
                            )
                        ],
                    ),
                ),
                (
                    "check_code",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("programme_readiness", "Programme Readiness"),
                            ("public_copy", "Public Copy"),
                            ("hosts", "Hosts"),
                            ("physical_approval", "Physical Approval"),
                            ("physical_constraints", "Physical Constraints"),
                            ("accessibility_fit", "Accessibility Fit"),
                            ("staffing", "Staffing"),
                            ("person_conflicts", "Person Conflicts"),
                            ("rest", "Rest"),
                        ],
                        max_length=32,
                    ),
                ),
                ("finding_code", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_warning_acknowledgements",
                        to="scheduling.schedulingcandidaterevision",
                    ),
                ),
                (
                    "command_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_warning_acknowledgement",
                        to="scheduling.schedulingcommandreceipt",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_warning_acknowledgements",
                        to="scheduling.schedulingoccurrence",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "other_occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="other_release_warning_acknowledgements",
                        to="scheduling.schedulingoccurrence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingReleaseWithdrawal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                ("pointer_version", models.PositiveBigIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "command_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_withdrawal",
                        to="scheduling.schedulingcommandreceipt",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_%(class)s_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "release",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal",
                        to="scheduling.schedulingrelease",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="schedulingreleaseapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("placement_count__gte", 1), ("placement_count__lte", 2000)
                ),
                name="sch_release_approval_count",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleaseapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(("dependency_count__gte", 1)),
                name="sch_release_approval_deps",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingrelease",
            constraint=models.UniqueConstraint(
                fields=("edition", "pointer_version"),
                name="sch_release_pointer_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pointer_version__gte", 1),
                    ("pointer_version__lt", 9223372036854775807),
                ),
                name="sch_release_pointer_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("added_count__lte", 2000),
                    ("changed_count__lte", 2000),
                    ("removed_count__lte", 2000),
                ),
                name="sch_release_impact_counts",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleaseapprovalplacement",
            constraint=models.UniqueConstraint(
                fields=("approval", "occurrence"), name="sch_release_approval_occ_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleaseapprovalplacement",
            constraint=models.UniqueConstraint(
                fields=("approval", "placement"), name="sch_release_approval_place_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleaseapprovaldependency",
            constraint=models.UniqueConstraint(
                fields=("approval", "dependency", "approval_placement", "horizon"),
                name="sch_release_dependency_use_uq",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleaseapprovaldependency",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("captured_generation__gte", 1),
                    ("captured_generation__lt", 9223372036854775807),
                ),
                name="sch_release_capture_generation",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleaseapprovaldependency",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approval_placement__isnull", False),
                        ("horizon", "operational"),
                        ("operational_ends_at__isnull", False),
                    ),
                    models.Q(
                        ("horizon__in", ("approval_only", "disclosure")),
                        ("operational_ends_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="sch_release_capture_horizon",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleaseartifact",
            constraint=models.UniqueConstraint(
                fields=("release", "contract"), name="sch_release_artifact_contract_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleaseartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("contract", "programme.release.canonical@1")),
                name="sch_release_artifact_contract",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleaseartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("byte_length__gte", 1), ("byte_length__lte", 2097152)
                ),
                name="sch_release_artifact_bytes",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleasepointer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("version__gte", 1), ("version__lt", 9223372036854775807)
                ),
                name="sch_release_current_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleasewarningacknowledgement",
            constraint=models.UniqueConstraint(
                fields=(
                    "candidate_revision",
                    "source_snapshot_digest",
                    "finding_fingerprint",
                    "actor",
                ),
                name="sch_release_warning_actor_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleasewarningacknowledgement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "check_code__in",
                        (
                            "candidate",
                            "programme_readiness",
                            "public_copy",
                            "hosts",
                            "physical_approval",
                            "physical_constraints",
                            "accessibility_fit",
                            "staffing",
                            "person_conflicts",
                            "rest",
                        ),
                    )
                ),
                name="sch_release_warning_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleasewithdrawal",
            constraint=models.UniqueConstraint(
                fields=("edition", "pointer_version"),
                name="sch_release_withdraw_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingreleasewithdrawal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pointer_version__gt", 1),
                    ("pointer_version__lt", 9223372036854775807),
                ),
                name="sch_release_withdraw_version",
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop, refuse_used_release_schema_downgrade
        ),
    ]
