# Generated by Django 5.2.17 on 2026-09-13 16:21
"""Add dormant immutable exact notices and independent communication evidence."""

import uuid
from typing import Any, ClassVar

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def refuse_used_notice_schema_downgrade(apps: Any, schema_editor: Any) -> None:
    """Retain used notices and their closed receipt vocabulary for fix-forward."""
    schema_editor.execute(
        "LOCK TABLE public.scheduling_schedulingchangenotice, "
        "public.scheduling_schedulingchangenoticeevidence, "
        "public.scheduling_schedulingcommandreceipt IN ACCESS EXCLUSIVE MODE"
    )
    if (
        any(
            apps.get_model("scheduling", name).objects.exists()
            for name in ("SchedulingChangeNotice", "SchedulingChangeNoticeEvidence")
        )
        or apps.get_model("scheduling", "SchedulingCommandReceipt")
        .objects.filter(
            operation__in=(
                "change_prepare",
                "change_approve",
                "change_reject",
                "change_handoff",
                "change_acknowledge",
            )
        )
        .exists()
    ):
        raise RuntimeError(
            "Programme notice history exists; retain it and fix forward."
        )


class Migration(migrations.Migration):
    """Extend the existing receipt stream without activating a profile or writer."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("authorization", "0031_programme_change_communication_capabilities"),
        ("events", "0011_release_dependency_mutations"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("scheduling", "0020_release_recovery_fence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list[object]] = [
        migrations.CreateModel(
            name="SchedulingChangeNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                (
                    "recipient_purpose",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("work", "Work"),
                            ("room", "Room"),
                            ("department", "Department"),
                            ("edition", "Edition"),
                        ],
                        max_length=16,
                    ),
                ),
                ("recipient_target_id", models.UUIDField()),
                ("pointer_version", models.PositiveBigIntegerField()),
                (
                    "source_state",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("withdrawn", "Withdrawn"),
                            ("invalidated", "Invalidated"),
                            ("comparison_suppressed", "Comparison Suppressed"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "snapshot_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}\\Z", "Use a lower-case SHA-256 digest."
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingChangeNoticeEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=1000)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("handoff", "Handoff"),
                            ("acknowledge", "Acknowledge"),
                        ],
                        max_length=16,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="schedulingcommandreceipt",
            name="sch_command_receipt_shape",
        ),
        migrations.AlterField(
            model_name="schedulingcommandreceipt",
            name="operation",
            field=models.CharField(
                choices=[
                    ("day_create", "Day Create"),
                    ("day_revise", "Day Revise"),
                    ("day_retire", "Day Retire"),
                    ("occurrence_create", "Occurrence Create"),
                    ("occurrence_revise", "Occurrence Revise"),
                    ("occurrence_retire", "Occurrence Retire"),
                    ("candidate_create", "Candidate Create"),
                    ("candidate_copy", "Candidate Copy"),
                    ("placement_set", "Placement Set"),
                    ("placement_remove", "Placement Remove"),
                    ("candidate_restore", "Candidate Restore"),
                    ("candidate_archive", "Candidate Archive"),
                    ("evaluation_record", "Evaluation Record"),
                    ("warning_acknowledge", "Warning Acknowledge"),
                    ("reservation_replace", "Reservation Replace"),
                    ("reservation_cancel", "Reservation Cancel"),
                    ("release_warning_acknowledge", "Release Warning Acknowledge"),
                    ("release_approve", "Release Approve"),
                    ("release_publish", "Release Publish"),
                    ("release_withdraw", "Release Withdraw"),
                    ("change_prepare", "Change Prepare"),
                    ("change_approve", "Change Approve"),
                    ("change_reject", "Change Reject"),
                    ("change_handoff", "Change Handoff"),
                    ("change_acknowledge", "Change Acknowledge"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("control_version__gt", 0),
                    (
                        "operation__in",
                        (
                            "day_create",
                            "day_revise",
                            "day_retire",
                            "occurrence_create",
                            "occurrence_revise",
                            "occurrence_retire",
                            "candidate_create",
                            "candidate_copy",
                            "placement_set",
                            "placement_remove",
                            "candidate_restore",
                            "candidate_archive",
                            "evaluation_record",
                            "warning_acknowledge",
                            "reservation_replace",
                            "reservation_cancel",
                            "release_warning_acknowledge",
                            "release_approve",
                            "release_publish",
                            "release_withdraw",
                            "change_prepare",
                            "change_approve",
                            "change_reject",
                            "change_handoff",
                            "change_acknowledge",
                        ),
                    ),
                    ("resulting_version__gt", 0),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="sch_command_receipt_shape",
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenotice",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scheduling_%(class)s_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenotice",
            name="command_receipt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_notice",
                to="scheduling.schedulingcommandreceipt",
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenotice",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scheduling_%(class)s_rows",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenotice",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_notices",
                to="scheduling.schedulingoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenotice",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scheduling_%(class)s_rows",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenotice",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_change_notices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenotice",
            name="release",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_notices",
                to="scheduling.schedulingrelease",
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenoticeevidence",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scheduling_%(class)s_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenoticeevidence",
            name="command_receipt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_notice_evidence",
                to="scheduling.schedulingcommandreceipt",
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenoticeevidence",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scheduling_%(class)s_rows",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenoticeevidence",
            name="notice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence",
                to="scheduling.schedulingchangenotice",
            ),
        ),
        migrations.AddField(
            model_name="schedulingchangenoticeevidence",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scheduling_%(class)s_rows",
                to="organizations.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingchangenotice",
            constraint=models.UniqueConstraint(
                fields=(
                    "edition",
                    "recipient",
                    "recipient_purpose",
                    "recipient_target_id",
                    "release",
                    "snapshot_digest",
                ),
                name="sch_change_notice_exact_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingchangenotice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pointer_version__gt", 0),
                    (
                        "recipient_purpose__in",
                        ("host", "work", "room", "department", "edition"),
                    ),
                    ("snapshot_digest__regex", "^[0-9a-f]{64}$"),
                    (
                        "source_state__in",
                        (
                            "available",
                            "withdrawn",
                            "invalidated",
                            "comparison_suppressed",
                        ),
                    ),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="sch_change_notice_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingchangenoticeevidence",
            constraint=models.UniqueConstraint(
                fields=("notice", "sequence"), name="sch_change_evidence_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingchangenoticeevidence",
            constraint=models.UniqueConstraint(
                fields=("notice", "action"), name="sch_change_evidence_action_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingchangenoticeevidence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("action__in", ("approve", "reject"))),
                fields=("notice",),
                name="sch_change_evidence_review_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulingchangenoticeevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            ("action__in", ("approve", "reject")), ("sequence", 2)
                        ),
                        models.Q(
                            ("action__in", ("handoff", "acknowledge")),
                            ("sequence__in", (3, 4)),
                        ),
                        _connector="OR",
                    ),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="sch_change_evidence_shape",
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop, refuse_used_notice_schema_downgrade
        ),
    ]
