# Generated by Django 5.2.16 on 2026-07-27 18:28

import django.db.models.deletion
import django.db.models.functions.text
import maru.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0004_lifecycle_integrity_guards"),
        ("organizations", "0001_initial"),
        ("participation", "0003_alter_participationcapacity_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("price_minor", models.PositiveBigIntegerField(default=0)),
                ("capacity", models.PositiveIntegerField()),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "entitlement_code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("entitlement_name", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("hidden", "Hidden")],
                        default="available",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=24)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("payment_pending", "Payment pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked in"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveIntegerField(default=1, editable=False),
                ),
                ("product_name_snapshot", models.CharField(max_length=160)),
                ("price_minor_snapshot", models.PositiveBigIntegerField()),
                ("currency_snapshot", models.CharField(max_length=3)),
                ("submitted_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "participation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration",
                        to="participation.participation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="registration.admissionproduct",
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at", "reference", "id"),
            },
        ),
        migrations.CreateModel(
            name="CheckInRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("actor_id", models.UUIDField()),
                ("checked_in_at", models.DateTimeField()),
                ("method", models.CharField(default="staff_console", max_length=40)),
                ("reason", models.TextField()),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_in",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ("checked_in_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("review_required", models.BooleanField(default=True)),
                ("review_note", models.TextField(blank=True)),
                ("opens_at", models.DateTimeField()),
                ("closes_at", models.DateTimeField()),
                ("capacity", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("created_by_id", models.UUIDField()),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_configurations",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_configurations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "source_edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copied_registration_configurations",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "-version", "id"),
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="registration.registrationconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="admissionproduct",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="registration.registrationconfiguration",
            ),
        ),
        migrations.CreateModel(
            name="RegistrationQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("help_text", models.TextField(blank=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Short text"),
                            ("long_text", "Long text"),
                            ("boolean", "Yes or no"),
                            ("single_choice", "Single choice"),
                            ("multiple_choice", "Multiple choice"),
                            ("integer", "Whole number"),
                        ],
                        max_length=24,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("options", models.JSONField(blank=True, default=list)),
                ("purpose", models.CharField(max_length=240)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("attendee_and_staff", "Attendee and registration staff"),
                            ("registration_staff", "Registration staff only"),
                        ],
                        default="attendee_and_staff",
                        max_length=30,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[("C1", "Internal"), ("C2", "Personal")],
                        default="C2",
                        max_length=2,
                    ),
                ),
                ("condition_question_key", models.SlugField(blank=True, max_length=80)),
                ("condition_value", models.CharField(blank=True, max_length=120)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="registration.registrationconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("configuration_version", models.PositiveIntegerField()),
                ("schema_snapshot", models.JSONField()),
                ("answers", models.JSONField()),
                ("submitted_at", models.DateTimeField()),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ("submitted_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_by_id", models.UUIDField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_templates",
                        to="organizations.organization",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_templates",
                        to="organizations.conventionseries",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "code", "-version", "id"),
            },
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="derived_configurations",
                to="registration.registrationtemplate",
            ),
        ),
        migrations.CreateModel(
            name="RegistrationTemplateProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("price_minor", models.PositiveBigIntegerField(default=0)),
                ("capacity", models.PositiveIntegerField()),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "entitlement_code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("entitlement_name", models.CharField(max_length=160)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="registration.registrationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationTemplateQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("help_text", models.TextField(blank=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Short text"),
                            ("long_text", "Long text"),
                            ("boolean", "Yes or no"),
                            ("single_choice", "Single choice"),
                            ("multiple_choice", "Multiple choice"),
                            ("integer", "Whole number"),
                        ],
                        max_length=24,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("options", models.JSONField(blank=True, default=list)),
                ("purpose", models.CharField(max_length=240)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("attendee_and_staff", "Attendee and registration staff"),
                            ("registration_staff", "Registration staff only"),
                        ],
                        default="attendee_and_staff",
                        max_length=30,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[("C1", "Internal"), ("C2", "Personal")],
                        default="C2",
                        max_length=2,
                    ),
                ),
                ("condition_question_key", models.SlugField(blank=True, max_length=80)),
                ("condition_value", models.CharField(blank=True, max_length=120)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="registration.registrationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationTimelineEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("sequence", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=160)),
                ("summary", models.CharField(max_length=320)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("attendee_and_staff", "Attendee and staff"),
                            ("staff_only", "Registration staff only"),
                        ],
                        max_length=24,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("actor_kind", models.CharField(max_length=40)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("correlation_id", models.UUIDField()),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("provider", models.CharField(max_length=40)),
                ("provider_reference", models.CharField(max_length=120)),
                ("idempotency_key", models.UUIDField()),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("safe_result_code", models.CharField(max_length=80)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "idempotency_key"),
                        name="registration_payment_idempotency_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("provider", "provider_reference"),
                        name="registration_payment_provider_reference_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Entitlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("code", models.SlugField(max_length=80)),
                ("label_snapshot", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField()),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entitlements",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ("granted_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("registration", "code"),
                        name="registration_entitlement_code_unique",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["organization", "edition", "state", "submitted_at"],
                name="registration_staff_queue_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("edition", "account"),
                name="one_registration_per_account_and_edition",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("edition", "reference"),
                name="registration_reference_unique_within_edition",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gte", 1)),
                name="registration_aggregate_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="admissionproduct",
            constraint=models.UniqueConstraint(
                fields=("configuration", "code"),
                name="registration_product_configuration_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="admissionproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gte", 1)),
                name="registration_product_capacity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationquestion",
            constraint=models.UniqueConstraint(
                fields=("configuration", "key"),
                name="registration_question_configuration_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplate",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                django.db.models.functions.text.Lower("code"),
                models.F("version"),
                name="registration_template_code_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_at__isnull", False), ("status", "published")),
                    ("status__in", ("draft", "retired")),
                    _connector="OR",
                ),
                name="registration_template_publish_time_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationconfiguration",
            constraint=models.UniqueConstraint(
                fields=("edition", "version"),
                name="registration_configuration_edition_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("edition",),
                name="one_active_registration_configuration_per_edition",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("closes_at__gt", models.F("opens_at"))),
                name="registration_configuration_closes_after_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gte", 1)),
                name="registration_configuration_capacity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("activated_at__isnull", False), ("status", "active")),
                    ("status__in", ("draft", "retired")),
                    _connector="OR",
                ),
                name="registration_configuration_activation_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplateproduct",
            constraint=models.UniqueConstraint(
                fields=("template", "code"),
                name="registration_template_product_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplatequestion",
            constraint=models.UniqueConstraint(
                fields=("template", "key"),
                name="registration_template_question_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtimelineentry",
            constraint=models.UniqueConstraint(
                fields=("registration", "sequence"),
                name="registration_timeline_sequence_unique",
            ),
        ),
    ]
