# Generated by Django 5.2.16 on 2026-07-27 22:00

import django.core.validators
import django.db.models.deletion
import maru.core.validators
import maru.registration.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_lifecycle_integrity_guards"),
        ("organizations", "0001_initial"),
        ("registration", "0002_scope_and_immutability_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendeeRegistrationProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("real_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                ("address_line_1", models.CharField(max_length=200)),
                ("address_line_2", models.CharField(blank=True, max_length=200)),
                ("locality", models.CharField(max_length=120)),
                ("postal_code", models.CharField(max_length=32)),
                ("region", models.CharField(max_length=120)),
                ("country_code", models.CharField(max_length=2)),
                ("emergency_contact_name", models.CharField(max_length=200)),
                ("emergency_contact_phone", models.CharField(max_length=40)),
                ("phone_number", models.CharField(max_length=40)),
                ("telegram_handle", models.CharField(blank=True, max_length=64)),
                ("pronouns", models.CharField(max_length=80)),
                ("fursuit_name", models.CharField(blank=True, max_length=120)),
                ("species", models.CharField(blank=True, max_length=120)),
                (
                    "fursuit_photo",
                    models.FileField(
                        blank=True,
                        upload_to=maru.registration.models.registration_profile_photo_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("jpg", "jpeg", "png", "webp")
                            )
                        ],
                    ),
                ),
                ("directory_visible", models.BooleanField(default=False)),
                (
                    "directory_consent_version",
                    models.CharField(blank=True, max_length=40),
                ),
                ("directory_consent_at", models.DateTimeField(blank=True, null=True)),
                ("collection_notice_version", models.CharField(max_length=40)),
            ],
            options={
                "ordering": ("edition_id", "account_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationTemplateSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="minimum_age",
            field=models.PositiveSmallIntegerField(
                default=18,
                help_text="Public registration currently supports adults only. A guardian workflow is required before lowering this boundary.",
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_age__gte", 18), ("minimum_age__lte", 120)),
                name="registration_configuration_adult_age_range",
            ),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendee_registration_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendee_registration_profiles",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendee_registration_profiles",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="registration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendee_profile",
                to="registration.registration",
            ),
        ),
        migrations.AddField(
            model_name="registrationsection",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="registration.registrationconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="registrationquestion",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="registration.registrationsection",
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplatesection",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="registration.registrationtemplate",
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplatequestion",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="registration.registrationtemplatesection",
            ),
        ),
        migrations.AddIndex(
            model_name="attendeeregistrationprofile",
            index=models.Index(
                fields=["organization", "edition", "directory_visible"],
                name="registration_prof_dir_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendeeregistrationprofile",
            constraint=models.UniqueConstraint(
                fields=("edition", "account"),
                name="one_attendee_profile_per_account_and_edition",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationsection",
            constraint=models.UniqueConstraint(
                fields=("configuration", "key"),
                name="registration_section_configuration_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplatesection",
            constraint=models.UniqueConstraint(
                fields=("template", "key"),
                name="registration_template_section_key_unique",
            ),
        ),
    ]
