# Generated by Django 5.2.16 on 2026-07-28 12:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_lifecycle_integrity_guards"),
        ("organizations", "0001_initial"),
        ("participation", "0003_alter_participationcapacity_options"),
        ("registration", "0004_profile_and_section_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("payment_deadline_changed", "Payment deadline changed"),
                            ("payment_waived", "Payment waived"),
                            ("waitlist_promoted", "Waitlist place offered"),
                            ("payment_expired", "Payment reservation expired"),
                            ("registration_cancelled", "Registration cancelled"),
                        ],
                        max_length=40,
                    ),
                ),
                ("from_state", models.CharField(blank=True, max_length=24)),
                ("to_state", models.CharField(blank=True, max_length=24)),
                ("previous_deadline", models.DateTimeField(blank=True, null=True)),
                ("new_deadline", models.DateTimeField(blank=True, null=True)),
                ("amount_minor", models.PositiveBigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("actor_kind", models.CharField(max_length=40)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.CharField(max_length=500)),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("occurred_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="admissionproduct",
            name="eligibility_explanation",
            field=models.CharField(
                blank=True,
                help_text="Attendee-facing explanation for a restricted offer.",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="admissionproduct",
            name="payment_window_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional override for the edition's default payment deadline.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(43200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="admissionproduct",
            name="required_capacity_codes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional active participation-capacity codes. A person needs at least one of them to select this product.",
            ),
        ),
        migrations.AddField(
            model_name="admissionproduct",
            name="sales_close_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional product-specific closing time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admissionproduct",
            name="sales_open_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional product-specific opening time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admissionproduct",
            name="waitlist_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow an eligible person to join the waitlist when capacity is full.",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="confirmation_basis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free", "No payment required"),
                    ("provider", "Payment provider"),
                    ("waiver", "Authorized waiver"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="offered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="payment_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="waitlisted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="automatic_waitlist_promotion",
            field=models.BooleanField(
                default=True,
                help_text="Offer released places to the oldest eligible waitlist entry.",
            ),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="default_payment_window_minutes",
            field=models.PositiveIntegerField(
                default=1440,
                help_text="Time allowed to complete payment after a place is reserved or offered.",
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(43200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="waitlist_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow eligible attendees to wait when admission capacity is full.",
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplateproduct",
            name="eligibility_explanation",
            field=models.CharField(
                blank=True,
                help_text="Attendee-facing explanation for a restricted offer.",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplateproduct",
            name="payment_window_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional override for the edition's default payment deadline.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(43200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplateproduct",
            name="required_capacity_codes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional active participation-capacity codes. A person needs at least one of them to select this product.",
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplateproduct",
            name="sales_close_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional product-specific closing time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplateproduct",
            name="sales_open_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional product-specific opening time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplateproduct",
            name="waitlist_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow an eligible person to join the waitlist when capacity is full.",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="state",
            field=models.CharField(
                choices=[
                    ("waitlisted", "Waitlisted"),
                    ("payment_pending", "Payment pending"),
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked in"),
                    ("expired", "Payment expired"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["organization", "edition", "state", "payment_due_at"],
                name="registration_payment_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["product", "state", "waitlisted_at"],
                name="registration_waitlist_idx",
            ),
        ),
        migrations.AddField(
            model_name="registrationadjustment",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustments",
                to="registration.registration",
            ),
        ),
        migrations.AddIndex(
            model_name="registrationadjustment",
            index=models.Index(
                fields=["organization_id", "edition_id", "kind", "occurred_at"],
                name="registration_adjustment_idx",
            ),
        ),
    ]
