# Generated by Django 5.2.16 on 2026-07-28 13:41

import django.core.validators
import django.db.models.deletion
import maru.registration.models
import maru.registration.profile_choices
import uuid
from django.conf import settings
from django.db import migrations, models


PRONOUN_CODES_BY_LABEL = {
    "she/her": "she_her",
    "he/him": "he_him",
    "they/them": "they_them",
    "it/its": "it_its",
    "one/one's": "one_ones",
    "ae/aer": "ae_aer",
    "ey/em": "ey_em",
    "fae/faer": "fae_faer",
    "xe/xem": "xe_xem",
    "ze/hir": "ze_hir",
    "ze/zir": "ze_zir",
    "co/cos": "co_cos",
    "e/em/eir": "e_em_eir",
    "e/em/es": "e_em_es",
    "hu/hum": "hu_hum",
    "ne/nem": "ne_nem",
    "ne/nir": "ne_nir",
    "per/per": "per_per",
    "s/he/hir": "s_he_hir",
    "thon/thons": "thon_thons",
    "ve/ver": "ve_ver",
    "vi/vir": "vi_vir",
    "vi/vim": "vi_vim",
    "zhe/zher": "zhe_zher",
    "ki/kin": "ki_kin",
    "any pronouns": "any",
    "use my name": "name_only",
    "ask me": "ask_me",
}


def copy_legacy_profile_data(apps, schema_editor):
    del schema_editor
    Profile = apps.get_model("registration", "AttendeeRegistrationProfile")
    Fursuit = apps.get_model("registration", "AttendeeFursuit")
    for profile in Profile.objects.all().iterator():
        display = profile.pronouns.strip()
        code = PRONOUN_CODES_BY_LABEL.get(display.lower())
        other = ""
        if code is None:
            if display:
                code = "other"
                other = display[:80]
            else:
                code = "name_only"
                display = "Use my name"
        Profile.objects.filter(id=profile.id).update(
            pronoun_code=code,
            other_pronouns=other,
            pronouns=display,
            brings_fursuits=bool(
                profile.fursuit_name or profile.species or profile.fursuit_photo
            ),
        )
        if profile.fursuit_name or profile.species or profile.fursuit_photo:
            Fursuit.objects.create(
                profile_id=profile.id,
                registration_id=profile.registration_id,
                organization_id=profile.organization_id,
                edition_id=profile.edition_id,
                account_id=profile.account_id,
                position=0,
                name=profile.fursuit_name or "Unnamed fursuit",
                species=profile.species,
                photo=profile.fursuit_photo,
                photo_status="pending" if profile.fursuit_photo else "none",
            )


def restore_legacy_profile_data(apps, schema_editor):
    del schema_editor
    Profile = apps.get_model("registration", "AttendeeRegistrationProfile")
    Fursuit = apps.get_model("registration", "AttendeeFursuit")
    for profile in Profile.objects.all().iterator():
        fursuit = (
            Fursuit.objects.filter(profile_id=profile.id, is_active=True)
            .order_by("position", "id")
            .first()
        )
        if fursuit is not None:
            Profile.objects.filter(id=profile.id).update(
                fursuit_name=fursuit.name,
                species=fursuit.species,
                fursuit_photo=fursuit.photo,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_lifecycle_integrity_guards"),
        ("organizations", "0001_initial"),
        ("registration", "0006_registration_lifecycle_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="brings_fursuits",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="other_pronouns",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="profile_photo",
            field=models.FileField(
                blank=True,
                max_length=255,
                upload_to=maru.registration.models.registration_profile_photo_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ("jpg", "jpeg", "png", "webp")
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="profile_photo_reused_from_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="profile_photo_review_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="profile_photo_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="profile_photo_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile_photo_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="profile_photo_status",
            field=models.CharField(
                choices=[
                    ("none", "No image"),
                    ("pending", "Pending review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="pronoun_code",
            field=models.CharField(default="they_them", max_length=24),
        ),
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="spoken_language_codes",
            field=models.JSONField(
                default=list,
                validators=[
                    maru.registration.profile_choices.validate_spoken_language_codes
                ],
            ),
        ),
        migrations.CreateModel(
            name="AttendeeFursuit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("name", models.CharField(max_length=120)),
                ("species", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to=maru.registration.models.registration_fursuit_photo_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("jpg", "jpeg", "png", "webp")
                            )
                        ],
                    ),
                ),
                (
                    "photo_status",
                    models.CharField(
                        choices=[
                            ("none", "No image"),
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("photo_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("photo_review_note", models.CharField(blank=True, max_length=500)),
                ("photo_reused_from_id", models.UUIDField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendee_fursuits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendee_fursuits",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendee_fursuits",
                        to="organizations.organization",
                    ),
                ),
                (
                    "photo_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fursuit_photo_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fursuits",
                        to="registration.attendeeregistrationprofile",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendee_fursuits",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "profile_id", "position", "id"),
                "indexes": [
                    models.Index(
                        fields=["organization", "edition", "photo_status"],
                        name="reg_fursuit_review_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("profile", "position"),
                        name="one_fursuit_per_profile_position",
                    )
                ],
            },
        ),
        migrations.RunPython(
            copy_legacy_profile_data,
            restore_legacy_profile_data,
        ),
        migrations.RemoveField(
            model_name="attendeeregistrationprofile",
            name="fursuit_name",
        ),
        migrations.RemoveField(
            model_name="attendeeregistrationprofile",
            name="fursuit_photo",
        ),
        migrations.RemoveField(
            model_name="attendeeregistrationprofile",
            name="species",
        ),
    ]
