# Generated by Django 5.2.16 on 2026-07-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_attendee_fursuit_scope_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="aggregate_version",
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
    ]
