# Generated by Django 5.2.16 on 2026-07-28 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0010_attendee_profile_version_guard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("idempotency_key", models.UUIDField()),
                ("request_digest", models.CharField(max_length=64)),
                (
                    "result_state",
                    models.CharField(
                        choices=[
                            ("waitlisted", "Waitlisted"),
                            ("payment_pending", "Payment pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked in"),
                            ("expired", "Payment expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=24,
                    ),
                ),
                ("result_reference", models.CharField(max_length=24)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_command_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="command_receipts",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "edition_id", "idempotency_key"),
                        name="registration_headless_idempotency_unique",
                    )
                ],
            },
        ),
    ]
