# Generated by Django 5.2.16 on 2026-07-28 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("registration", "0011_registrationcommandreceipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProviderAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=40)),
                ("display_name", models.CharField(max_length=120)),
                ("adapter", models.CharField(max_length=40)),
                ("api_base_url", models.URLField(max_length=300)),
                ("credential_env_var", models.CharField(max_length=120)),
                ("webhook_secret_env_var", models.CharField(max_length=120)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_provider_accounts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "code", "id"),
            },
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("idempotency_key", models.UUIDField()),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "Creating"),
                            ("checkout_ready", "Checkout ready"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                            ("uncertain", "Uncertain"),
                            ("mismatch", "Mismatch"),
                            ("late", "Late success"),
                        ],
                        default="creating",
                        max_length=24,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=120)),
                ("checkout_url", models.URLField(blank=True, max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("last_provider_event_at", models.DateTimeField(blank=True, null=True)),
                ("safe_result_code", models.CharField(blank=True, max_length=80)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="registration.registration",
                    ),
                ),
                (
                    "provider_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="registration.paymentprovideraccount",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PaymentException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("provider_unavailable", "Provider unavailable"),
                            ("unknown_intent", "Unknown payment intent"),
                            ("amount_mismatch", "Amount mismatch"),
                            ("currency_mismatch", "Currency mismatch"),
                            ("late_success", "Late success"),
                            ("out_of_order", "Out-of-order provider event"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("safe_summary", models.CharField(max_length=320)),
                ("opened_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_id", models.UUIDField(blank=True, null=True)),
                ("resolution_reason", models.CharField(blank=True, max_length=500)),
                (
                    "payment_intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exceptions",
                        to="registration.paymentintent",
                    ),
                ),
                (
                    "provider_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_exceptions",
                        to="registration.paymentprovideraccount",
                    ),
                ),
            ],
            options={
                "ordering": ("-opened_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhookReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("remote_event_id", models.CharField(max_length=160)),
                ("payload_digest", models.CharField(max_length=64)),
                ("signature_timestamp", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("duplicate", "Duplicate"),
                            ("rejected", "Rejected"),
                            ("exception", "Needs review"),
                        ],
                        max_length=16,
                    ),
                ),
                ("safe_result_code", models.CharField(max_length=80)),
                (
                    "payment_intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_receipts",
                        to="registration.paymentintent",
                    ),
                ),
                (
                    "provider_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_receipts",
                        to="registration.paymentprovideraccount",
                    ),
                ),
            ],
            options={
                "ordering": ("-received_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="paymentprovideraccount",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"),
                name="payment_provider_code_unique_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["organization_id", "edition_id", "status", "created_at"],
                name="payment_intent_queue_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.UniqueConstraint(
                fields=("provider_account", "idempotency_key"),
                name="payment_intent_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_reference", ""), _negated=True),
                fields=("provider_account", "provider_reference"),
                name="payment_intent_provider_reference_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentexception",
            index=models.Index(
                fields=["organization_id", "edition_id", "status", "opened_at"],
                name="payment_exception_queue_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhookreceipt",
            index=models.Index(
                fields=["organization_id", "outcome", "received_at"],
                name="payment_webhook_review_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentwebhookreceipt",
            constraint=models.UniqueConstraint(
                fields=("provider_account", "remote_event_id"),
                name="payment_webhook_remote_event_unique",
            ),
        ),
    ]
