# Generated by Django 5.2.16 on 2026-07-28 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0012_paymentprovideraccount_paymentintent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cancel", "Cancel registration"),
                            ("refund", "Refund"),
                            ("transfer", "Transfer admission"),
                            ("product_change", "Change admission product"),
                            ("price_adjustment", "Price adjustment"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("provider_pending", "Provider pending"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="proposed",
                        max_length=24,
                    ),
                ),
                ("amount_minor", models.PositiveBigIntegerField(default=0)),
                ("currency", models.CharField(max_length=3)),
                ("target_account_id", models.UUIDField(blank=True, null=True)),
                ("target_product_id", models.UUIDField(blank=True, null=True)),
                ("requested_at", models.DateTimeField()),
                ("request_reason", models.CharField(max_length=500)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_reason", models.CharField(blank=True, max_length=500)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("safe_result_code", models.CharField(blank=True, max_length=80)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_financial_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_operations",
                        to="registration.registration",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_financial_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="FinancialLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("payment", "Provider payment"),
                            ("refund", "Refund"),
                            ("provider_fee", "Provider fee"),
                            ("dispute", "Dispute"),
                            ("chargeback", "Chargeback"),
                            ("price_adjustment", "Price adjustment"),
                            ("donation", "Donation"),
                            ("settlement", "Settlement"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inflow", "Inflow"),
                            ("outflow", "Outflow"),
                            ("noncash", "Non-cash"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("occurred_at", models.DateTimeField()),
                ("provider_reference", models.CharField(blank=True, max_length=160)),
                ("settlement_reference", models.CharField(blank=True, max_length=160)),
                ("safe_description", models.CharField(max_length=320)),
                (
                    "provider_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="registration.paymentprovideraccount",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_ledger",
                        to="registration.registration",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="registration.financialoperation",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ReceiptRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt"),
                            ("credit_note", "Credit note"),
                        ],
                        max_length=16,
                    ),
                ),
                ("document_number", models.CharField(max_length=80)),
                ("issued_at", models.DateTimeField()),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("description_snapshot", models.CharField(max_length=320)),
                (
                    "ledger_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_record",
                        to="registration.financialledgerentry",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_records",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ("issued_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SettlementBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("provider_reference", models.CharField(max_length=160)),
                ("currency", models.CharField(max_length=3)),
                ("gross_minor", models.PositiveBigIntegerField()),
                ("fee_minor", models.PositiveBigIntegerField()),
                ("refund_minor", models.PositiveBigIntegerField()),
                ("dispute_minor", models.PositiveBigIntegerField()),
                ("net_minor", models.BigIntegerField()),
                ("settled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reconciled", "Reconciled"),
                            ("exception", "Exception"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("reconciled_by_id", models.UUIDField(blank=True, null=True)),
                ("safe_result_code", models.CharField(max_length=80)),
                (
                    "provider_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_batches",
                        to="registration.paymentprovideraccount",
                    ),
                ),
            ],
            options={
                "ordering": ("-settled_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="financialoperation",
            index=models.Index(
                fields=["organization_id", "edition_id", "status", "requested_at"],
                name="reg_finance_operation_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialledgerentry",
            index=models.Index(
                fields=["organization_id", "edition_id", "currency", "occurred_at"],
                name="reg_finance_ledger_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_reference", ""), _negated=True),
                fields=("provider_account", "provider_reference", "kind"),
                name="finance_provider_movement_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="receiptrecord",
            constraint=models.UniqueConstraint(
                fields=("organization_id", "document_number"),
                name="receipt_number_unique_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementbatch",
            constraint=models.UniqueConstraint(
                fields=("provider_account", "provider_reference"),
                name="settlement_provider_reference_unique",
            ),
        ),
    ]
