# Generated by Django 5.2.16 on 2026-07-28 15:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0013_financialoperation_financialledgerentry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaSafetyReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("account_id", models.UUIDField()),
                (
                    "media_kind",
                    models.CharField(
                        choices=[
                            ("profile_photo", "Profile photo"),
                            ("fursuit_photo", "Fursuit photo"),
                        ],
                        max_length=24,
                    ),
                ),
                ("media_id", models.UUIDField()),
                ("storage_name", models.CharField(max_length=255)),
                ("original_sha256", models.CharField(max_length=64)),
                ("sanitized_sha256", models.CharField(max_length=64)),
                ("scanner_code", models.CharField(max_length=80)),
                ("decoder_version", models.CharField(max_length=40)),
                ("content_type", models.CharField(max_length=80)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("byte_count", models.PositiveIntegerField()),
                ("scanned_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("-scanned_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["media_kind", "media_id", "storage_name"],
                        name="reg_media_safety_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("media_kind", "media_id", "sanitized_sha256"),
                        name="media_safety_revision_unique",
                    )
                ],
            },
        ),
    ]
