# Generated by Django 5.2.16 on 2026-07-28 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0014_mediasafetyreceipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="state",
            field=models.CharField(
                choices=[
                    ("guardian_pending", "Guardian consent pending"),
                    ("waitlisted", "Waitlisted"),
                    ("payment_pending", "Payment pending"),
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked in"),
                    ("expired", "Payment expired"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="registrationcommandreceipt",
            name="result_state",
            field=models.CharField(
                choices=[
                    ("guardian_pending", "Guardian consent pending"),
                    ("waitlisted", "Waitlisted"),
                    ("payment_pending", "Payment pending"),
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked in"),
                    ("expired", "Payment expired"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="MinorRegistrationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False)),
                ("minor_age_threshold", models.PositiveSmallIntegerField(default=18)),
                ("guardian_notice_version", models.CharField(max_length=40)),
                ("jurisdiction_code", models.CharField(max_length=40)),
                ("review_reference", models.CharField(max_length=120)),
                ("reviewed_at", models.DateTimeField()),
                (
                    "configuration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="minor_policy",
                        to="registration.registrationconfiguration",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_minor_registration_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuardianConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                ("guardian_name", models.CharField(max_length=200)),
                ("guardian_email", models.EmailField(max_length=254)),
                ("relationship", models.CharField(max_length=80)),
                ("notice_version", models.CharField(max_length=40)),
                (
                    "token_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "guardian_name_at_decision",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_consent",
                        to="registration.registration",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_consents",
                        to="registration.minorregistrationpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ("requested_at", "id"),
                "indexes": [
                    models.Index(
                        fields=[
                            "organization_id",
                            "edition_id",
                            "status",
                            "expires_at",
                        ],
                        name="reg_guardian_consent_idx",
                    )
                ],
            },
        ),
    ]
