# Generated by Django 5.2.16 on 2026-07-28 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0016_guardian_lifecycle_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationLifecycleRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("edition_id", models.UUIDField(blank=True, null=True)),
                ("ran_at", models.DateTimeField()),
                ("expired", models.PositiveIntegerField(default=0)),
                ("inactive_cancelled", models.PositiveIntegerField(default=0)),
                ("closed_waitlist_cancelled", models.PositiveIntegerField(default=0)),
                ("promoted", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("-ran_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["edition_id", "ran_at"],
                        name="registration_lifecycle_run_idx",
                    )
                ],
            },
        ),
    ]
