# Generated by Django 5.2.16 on 2026-07-28 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0018_retention_workflow_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_minor", models.PositiveBigIntegerField()),
                (
                    "ledger_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_allocation",
                        to="registration.financialledgerentry",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="registration.settlementbatch",
                    ),
                ),
            ],
            options={
                "ordering": ("settlement_id", "ledger_entry_id"),
            },
        ),
    ]
