# Generated by Django 5.2.16 on 2026-07-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0019_settlementallocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentexception",
            name="kind",
            field=models.CharField(
                choices=[
                    ("provider_unavailable", "Provider unavailable"),
                    ("unknown_intent", "Unknown payment intent"),
                    ("amount_mismatch", "Amount mismatch"),
                    ("currency_mismatch", "Currency mismatch"),
                    ("late_success", "Late success"),
                    ("out_of_order", "Out-of-order provider event"),
                    ("dispute_review", "Dispute or chargeback review"),
                ],
                max_length=32,
            ),
        ),
    ]
