# Generated by Django 5.2.16 on 2026-07-28 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_editionclosuremanifest_editionreadinessgate"),
        ("organizations", "0001_initial"),
        ("registration", "0020_alter_paymentexception_kind"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registrationconfiguration",
            name="registration_configuration_adult_age_range",
        ),
        migrations.AlterField(
            model_name="registrationconfiguration",
            name="minimum_age",
            field=models.PositiveSmallIntegerField(
                default=18,
                help_text="Absolute minimum age. Values below 18 require an enabled, reviewed guardian policy before activation.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_age__gte", 0), ("minimum_age__lte", 120)),
                name="registration_configuration_adult_age_range",
            ),
        ),
    ]
