# Generated by Django 5.2.16 on 2026-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0021_remove_registrationconfiguration_registration_configuration_adult_age_range_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationlifecyclerun",
            name="restrictions_applied",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
