# Generated by Django 5.2.16 on 2026-07-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0024_entitlement_state_guard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkinrecord",
            options={
                "ordering": ("checked_in_at", "id"),
                "verbose_name": "check-in record",
                "verbose_name_plural": "check-in records",
            },
        ),
        migrations.AlterModelOptions(
            name="financialledgerentry",
            options={
                "ordering": ("occurred_at", "id"),
                "verbose_name_plural": "financial ledger entries",
            },
        ),
        migrations.AlterModelOptions(
            name="minorregistrationpolicy",
            options={"verbose_name_plural": "minor registration policies"},
        ),
        migrations.AlterModelOptions(
            name="registrationtimelineentry",
            options={
                "ordering": ("sequence", "id"),
                "verbose_name_plural": "registration timeline entries",
            },
        ),
        migrations.AlterModelOptions(
            name="settlementbatch",
            options={
                "ordering": ("-settled_at", "-id"),
                "verbose_name_plural": "settlement batches",
            },
        ),
    ]
