# Generated by Django 5.2.16 on 2026-07-29 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_editionclosuremanifest_editionreadinessgate"),
        ("organizations", "0001_initial"),
        ("registration", "0025_alter_checkinrecord_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendeeregistrationprofile",
            name="directory_country_code",
            field=models.CharField(
                blank=True,
                help_text="Optional country code entered specifically for the public attendee directory; it is not copied from the address automatically.",
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="attendeeregistrationprofile",
            index=models.Index(
                fields=["organization", "edition", "country_code"],
                name="registration_prof_country_idx",
            ),
        ),
    ]
