# Generated by Django 5.2.16 on 2026-07-29 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0026_attendeeregistrationprofile_directory_country_code_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="staff_submission_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="registration",
            name="submission_source",
            field=models.CharField(
                choices=[
                    ("self", "Attendee self-service"),
                    ("staff_assisted", "Staff-assisted registration"),
                ],
                default="self",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations_submitted_on_behalf",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
