# Generated by Django 5.2.16 on 2026-08-02 19:06
# ruff: noqa: N806

import hashlib
import json
import uuid
from datetime import date, datetime
from typing import ClassVar

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _json_default(value):
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    return str(value)


def _content_digest(payload):
    canonical = json.dumps(
        payload,
        default=_json_default,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _questions(question_model, *, alias, owner_field, owner_id, section_keys):
    values = (
        question_model.objects.using(alias)
        .filter(**{owner_field: owner_id})
        .order_by("position", "key", "id")
    )
    return [
        {
            "key": question.key,
            "label": question.label,
            "help_text": question.help_text,
            "field_type": question.field_type,
            "required": question.required,
            "position": question.position,
            "options": question.options,
            "purpose": question.purpose,
            "visibility": question.visibility,
            "classification": question.classification,
            "condition_question_key": question.condition_question_key,
            "condition_value": question.condition_value,
            "section_key": section_keys.get(question.section_id),
        }
        for question in values.iterator()
    ]


def _products(product_model, *, alias, owner_field, owner_id, include_status):
    values = (
        product_model.objects.using(alias)
        .filter(**{owner_field: owner_id})
        .order_by("position", "code", "id")
    )
    products = []
    for product in values.iterator():
        item = {
            "code": product.code,
            "name": product.name,
            "description": product.description,
            "price_minor": product.price_minor,
            "capacity": product.capacity,
            "position": product.position,
            "entitlement_code": product.entitlement_code,
            "entitlement_name": product.entitlement_name,
            "sales_open_at": product.sales_open_at,
            "sales_close_at": product.sales_close_at,
            "required_capacity_codes": product.required_capacity_codes,
            "eligibility_explanation": product.eligibility_explanation,
            "waitlist_enabled": product.waitlist_enabled,
            "payment_window_minutes": product.payment_window_minutes,
        }
        if include_status:
            item["status"] = product.status
        products.append(item)
    return products


def _sections(section_model, *, alias, owner_field, owner_id):
    sections = list(
        section_model.objects.using(alias)
        .filter(**{owner_field: owner_id})
        .order_by("position", "key", "id")
    )
    payload = [
        {
            "key": section.key,
            "title": section.title,
            "description": section.description,
            "position": section.position,
        }
        for section in sections
    ]
    return payload, {section.id: section.key for section in sections}


def backfill_page10_registration_schema(apps, schema_editor):
    """Record only observable legacy state; do not invent command history."""

    alias = schema_editor.connection.alias
    Template = apps.get_model("registration", "RegistrationTemplate")
    TemplateSection = apps.get_model("registration", "RegistrationTemplateSection")
    TemplateQuestion = apps.get_model("registration", "RegistrationTemplateQuestion")
    TemplateProduct = apps.get_model("registration", "RegistrationTemplateProduct")
    Configuration = apps.get_model("registration", "RegistrationConfiguration")
    Section = apps.get_model("registration", "RegistrationSection")
    Question = apps.get_model("registration", "RegistrationQuestion")
    Product = apps.get_model("registration", "AdmissionProduct")
    MinorPolicy = apps.get_model("registration", "MinorRegistrationPolicy")
    ProfileField = apps.get_model("registration", "RegistrationProfileExtensionField")
    SetupControl = apps.get_model("registration", "RegistrationSetupControl")
    CatalogControl = apps.get_model(
        "registration", "RegistrationTemplateCatalogControl"
    )

    template_digests = {}
    for template in Template.objects.using(alias).order_by("id").iterator():
        sections, section_keys = _sections(
            TemplateSection,
            alias=alias,
            owner_field="template_id",
            owner_id=template.id,
        )
        payload = {
            "contract": "maru.registration-template-content.v1",
            "code": template.code,
            "name": template.name,
            "description": template.description,
            "version": template.version,
            "sections": sections,
            "questions": _questions(
                TemplateQuestion,
                alias=alias,
                owner_field="template_id",
                owner_id=template.id,
                section_keys=section_keys,
            ),
            "products": _products(
                TemplateProduct,
                alias=alias,
                owner_field="template_id",
                owner_id=template.id,
                include_status=False,
            ),
        }
        digest = _content_digest(payload)
        template_digests[template.id] = (template.version, digest)
        Template.objects.using(alias).filter(pk=template.id).update(
            content_digest=digest,
            provenance_status="legacy_unknown",
        )

    for configuration in Configuration.objects.using(alias).order_by("id").iterator():
        sections, section_keys = _sections(
            Section,
            alias=alias,
            owner_field="configuration_id",
            owner_id=configuration.id,
        )
        policy = (
            MinorPolicy.objects.using(alias)
            .filter(configuration_id=configuration.id)
            .first()
        )
        policy_payload = None
        if policy is not None:
            policy_payload = {
                "enabled": policy.enabled,
                "minor_age_threshold": policy.minor_age_threshold,
                "guardian_notice_version": policy.guardian_notice_version,
                "jurisdiction_code": policy.jurisdiction_code,
                "review_reference": policy.review_reference,
            }
        payload = {
            "contract": "maru.registration-configuration-content.v1",
            "name": configuration.name,
            "schema_version": configuration.version,
            "opens_at": configuration.opens_at,
            "closes_at": configuration.closes_at,
            "capacity": configuration.capacity,
            "currency": configuration.currency,
            "minimum_age": configuration.minimum_age,
            "default_payment_window_minutes": (
                configuration.default_payment_window_minutes
            ),
            "waitlist_enabled": configuration.waitlist_enabled,
            "automatic_waitlist_promotion": (
                configuration.automatic_waitlist_promotion
            ),
            "sections": sections,
            "questions": _questions(
                Question,
                alias=alias,
                owner_field="configuration_id",
                owner_id=configuration.id,
                section_keys=section_keys,
            ),
            "products": _products(
                Product,
                alias=alias,
                owner_field="configuration_id",
                owner_id=configuration.id,
                include_status=True,
            ),
            "minor_policy": policy_payload,
        }
        updates = {
            "content_digest": _content_digest(payload),
            "origin": "legacy_existing",
            "provenance_status": "legacy_unknown",
        }
        if configuration.source_template_id in template_digests:
            source_version, source_digest = template_digests[
                configuration.source_template_id
            ]
            updates.update(
                origin="published_template",
                source_version=source_version,
                source_content_digest=source_digest,
            )
        elif configuration.source_edition_id is not None:
            updates["origin"] = "prior_edition"
        Configuration.objects.using(alias).filter(pk=configuration.id).update(**updates)

    populated_scopes = set(
        Configuration.objects.using(alias).values_list("organization_id", "edition_id")
    )
    populated_scopes.update(
        ProfileField.objects.using(alias).values_list("organization_id", "edition_id")
    )
    for organization_id, edition_id in sorted(
        populated_scopes,
        key=lambda scope: (str(scope[0]), str(scope[1])),
    ):
        SetupControl.objects.using(alias).create(
            organization_id=organization_id,
            edition_id=edition_id,
            origin="legacy_existing",
            provenance_status="legacy_unknown",
            aggregate_version=1,
        )

    populated_organizations = (
        Template.objects.using(alias)
        .values_list("organization_id", flat=True)
        .distinct()
    )
    for organization_id in populated_organizations.iterator():
        CatalogControl.objects.using(alias).create(
            organization_id=organization_id,
            provenance_status="legacy_unknown",
            aggregate_version=1,
        )


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("events", "0009_edition_workspace_downgrade_fence"),
        ("organizations", "0013_runtime_executable_function_hardening"),
        ("registration", "0031_idn011_convention_subject_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list[object]] = [
        migrations.CreateModel(
            name="RegistrationSetupCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("setup_started", "Setup started"),
                            ("successor_started", "Successor started"),
                            ("configuration_reviewed", "Configuration reviewed"),
                            ("configuration_activated", "Configuration activated"),
                            ("configuration_retired", "Configuration retired"),
                            ("section_created", "Section created"),
                            ("section_updated", "Section updated"),
                            ("section_moved", "Section moved"),
                            ("section_deleted", "Section deleted"),
                            ("question_created", "Question created"),
                            ("question_updated", "Question updated"),
                            ("question_moved", "Question moved"),
                            ("question_deleted", "Question deleted"),
                            ("product_created", "Product created"),
                            ("product_updated", "Product updated"),
                            ("product_moved", "Product moved"),
                            ("product_deleted", "Product deleted"),
                            ("minor_policy_updated", "Minor policy updated"),
                            ("profile_field_created", "Profile field created"),
                            ("profile_field_updated", "Profile field updated"),
                            ("profile_field_reviewed", "Profile field reviewed"),
                            ("profile_field_activated", "Profile field activated"),
                            ("profile_field_retired", "Profile field retired"),
                        ],
                        max_length=32,
                    ),
                ),
                ("resulting_version", models.PositiveBigIntegerField()),
                ("reason", models.CharField(max_length=500)),
                ("correlation_id", models.UUIDField()),
                ("source_channel", models.CharField(max_length=32)),
                ("retry_key", models.UUIDField(blank=True, null=True)),
                (
                    "request_digest",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_registration_setup_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "resulting_version", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationSetupCommandTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("configuration", "Configuration"),
                            ("section", "Section"),
                            ("question", "Question"),
                            ("product", "Product"),
                            ("minor_policy", "Minor policy"),
                            ("profile_field", "Profile field"),
                        ],
                        max_length=24,
                    ),
                ),
                ("target_id", models.UUIDField()),
                (
                    "change_kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("moved", "Moved"),
                            ("reviewed", "Reviewed"),
                            ("activated", "Activated"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "target_schema_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "content_digest",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_registration_setup_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("receipt_id", "target_kind", "target_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationSetupControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("legacy_existing", "Legacy existing"),
                            ("blank", "Blank"),
                            ("published_template", "Published template"),
                            ("prior_edition", "Prior edition"),
                            ("successor", "Successor"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "provenance_status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("legacy_unknown", "Legacy unknown"),
                        ],
                        default="legacy_unknown",
                        editable=False,
                        max_length=24,
                    ),
                ),
                ("aggregate_version", models.PositiveBigIntegerField()),
            ],
            options={
                "ordering": ("organization_id", "edition_id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationTemplateCatalogCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("template_created", "Template created"),
                            ("template_updated", "Template updated"),
                            ("template_published", "Template published"),
                            ("template_retired", "Template retired"),
                            ("section_created", "Section created"),
                            ("section_updated", "Section updated"),
                            ("section_moved", "Section moved"),
                            ("section_deleted", "Section deleted"),
                            ("question_created", "Question created"),
                            ("question_updated", "Question updated"),
                            ("question_moved", "Question moved"),
                            ("question_deleted", "Question deleted"),
                            ("product_created", "Product created"),
                            ("product_updated", "Product updated"),
                            ("product_moved", "Product moved"),
                            ("product_deleted", "Product deleted"),
                        ],
                        max_length=32,
                    ),
                ),
                ("resulting_version", models.PositiveBigIntegerField()),
                ("reason", models.CharField(max_length=500)),
                ("correlation_id", models.UUIDField()),
                ("source_channel", models.CharField(max_length=32)),
                ("retry_key", models.UUIDField(blank=True, null=True)),
                (
                    "request_digest",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_registration_setup_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "resulting_version", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationTemplateCatalogCommandTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("template", "Template"),
                            ("section", "Section"),
                            ("question", "Question"),
                            ("product", "Product"),
                        ],
                        max_length=24,
                    ),
                ),
                ("target_id", models.UUIDField()),
                (
                    "change_kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("moved", "Moved"),
                            ("reviewed", "Reviewed"),
                            ("activated", "Activated"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "target_schema_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "content_digest",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_registration_setup_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("receipt_id", "target_kind", "target_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationTemplateCatalogControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("aggregate_version", models.PositiveBigIntegerField()),
                (
                    "provenance_status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("legacy_unknown", "Legacy unknown"),
                        ],
                        default="legacy_unknown",
                        editable=False,
                        max_length=24,
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id",),
            },
        ),
        migrations.AddField(
            model_name="admissionproduct",
            name="created_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="admissionproduct",
            name="last_changed_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="minorregistrationpolicy",
            name="created_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="minorregistrationpolicy",
            name="last_changed_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="content_digest",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_registration_setup_digest",
                        message="Use a lowercase SHA-256 digest.",
                        regex="^[0-9a-f]{64}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="created_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="last_changed_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="origin",
            field=models.CharField(
                choices=[
                    ("legacy_existing", "Legacy existing"),
                    ("blank", "Blank"),
                    ("published_template", "Published template"),
                    ("prior_edition", "Prior edition"),
                    ("successor", "Successor"),
                ],
                default="legacy_existing",
                editable=False,
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="provenance_status",
            field=models.CharField(
                choices=[
                    ("complete", "Complete"),
                    ("legacy_unknown", "Legacy unknown"),
                ],
                default="legacy_unknown",
                editable=False,
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="source_configuration",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="successor_configurations",
                to="registration.registrationconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="source_content_digest",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_registration_setup_digest",
                        message="Use a lowercase SHA-256 digest.",
                        regex="^[0-9a-f]{64}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="source_imported_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="source_imported_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_configuration_imports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registrationconfiguration",
            name="source_version",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationprofileextensionfield",
            name="created_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationprofileextensionfield",
            name="last_changed_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationquestion",
            name="created_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationquestion",
            name="last_changed_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationsection",
            name="created_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationsection",
            name="last_changed_in_setup_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationtemplate",
            name="content_digest",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_registration_setup_digest",
                        message="Use a lowercase SHA-256 digest.",
                        regex="^[0-9a-f]{64}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplate",
            name="created_in_catalog_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationtemplate",
            name="last_changed_in_catalog_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationtemplate",
            name="provenance_status",
            field=models.CharField(
                choices=[
                    ("complete", "Complete"),
                    ("legacy_unknown", "Legacy unknown"),
                ],
                default="legacy_unknown",
                editable=False,
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplateproduct",
            name="created_in_catalog_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationtemplateproduct",
            name="last_changed_in_catalog_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationtemplatequestion",
            name="created_in_catalog_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationtemplatequestion",
            name="last_changed_in_catalog_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationtemplatesection",
            name="created_in_catalog_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="registrationtemplatesection",
            name="last_changed_in_catalog_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="registrationconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("created_in_setup_version__isnull", True),
                        ("created_in_setup_version__gt", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("last_changed_in_setup_version__isnull", True),
                        ("last_changed_in_setup_version__gt", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("created_in_setup_version__isnull", True),
                        (
                            "last_changed_in_setup_version__gte",
                            models.F("created_in_setup_version"),
                        ),
                        _connector="OR",
                    ),
                ),
                name="reg_configuration_setup_versions_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_version__isnull", True),
                    ("source_version__gt", 0),
                    _connector="OR",
                ),
                name="reg_configuration_source_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("created_in_catalog_version__isnull", True),
                        ("created_in_catalog_version__gt", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("last_changed_in_catalog_version__isnull", True),
                        ("last_changed_in_catalog_version__gt", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("created_in_catalog_version__isnull", True),
                        (
                            "last_changed_in_catalog_version__gte",
                            models.F("created_in_catalog_version"),
                        ),
                        _connector="OR",
                    ),
                ),
                name="reg_template_catalog_versions_valid",
            ),
        ),
        migrations.AddField(
            model_name="registrationsetupcommandreceipt",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_setup_commands_acted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registrationsetupcommandreceipt",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_setup_command_receipts",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="registrationsetupcommandreceipt",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_setup_command_receipts",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="registrationsetupcommandtarget",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="targets",
                to="registration.registrationsetupcommandreceipt",
            ),
        ),
        migrations.AddField(
            model_name="registrationsetupcontrol",
            name="edition",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_setup_control",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="registrationsetupcontrol",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_setup_controls",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="registrationsetupcommandreceipt",
            name="setup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="command_receipts",
                to="registration.registrationsetupcontrol",
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplatecatalogcommandreceipt",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_template_catalog_commands_acted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplatecatalogcommandreceipt",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_template_catalog_command_receipts",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplatecatalogcommandtarget",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="targets",
                to="registration.registrationtemplatecatalogcommandreceipt",
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplatecatalogcontrol",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_template_catalog_control",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="registrationtemplatecatalogcommandreceipt",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="command_receipts",
                to="registration.registrationtemplatecatalogcontrol",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationsetupcommandtarget",
            constraint=models.UniqueConstraint(
                fields=("receipt", "target_kind", "target_id"),
                name="registration_setup_receipt_target_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationsetupcommandtarget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_schema_version__isnull", True),
                    ("target_schema_version__gt", 0),
                    _connector="OR",
                ),
                name="reg_setup_target_schema_ver_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="registrationsetupcontrol",
            index=models.Index(
                fields=["organization", "edition"], name="registration_setup_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationsetupcontrol",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="registration_setup_version_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="registrationsetupcommandreceipt",
            index=models.Index(
                fields=["organization", "edition", "resulting_version"],
                name="reg_setup_rcpt_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registrationsetupcommandreceipt",
            index=models.Index(
                fields=["edition", "action", "created_at"],
                name="reg_setup_receipt_action_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationsetupcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("setup", "resulting_version"),
                name="registration_setup_receipt_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationsetupcommandreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("retry_key__isnull", False)),
                fields=("edition", "actor", "retry_key"),
                name="registration_setup_retry_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationsetupcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("resulting_version__gt", 0)),
                name="registration_setup_receipt_ver_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationsetupcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reason", ""), _negated=True),
                    models.Q(("source_channel", ""), _negated=True),
                ),
                name="registration_setup_receipt_evidence_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplatecatalogcommandtarget",
            constraint=models.UniqueConstraint(
                fields=("receipt", "target_kind", "target_id"),
                name="reg_template_receipt_target_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplatecatalogcommandtarget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_schema_version__isnull", True),
                    ("target_schema_version__gt", 0),
                    _connector="OR",
                ),
                name="reg_template_target_schema_ver_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplatecatalogcontrol",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="reg_template_catalog_version_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="registrationtemplatecatalogcommandreceipt",
            index=models.Index(
                fields=["organization", "action", "created_at"],
                name="reg_tpl_rcpt_action_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplatecatalogcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("catalog", "resulting_version"),
                name="reg_template_receipt_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplatecatalogcommandreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("retry_key__isnull", False)),
                fields=("organization", "actor", "retry_key"),
                name="reg_template_retry_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplatecatalogcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("resulting_version__gt", 0)),
                name="reg_template_receipt_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationtemplatecatalogcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reason", ""), _negated=True),
                    models.Q(("source_channel", ""), _negated=True),
                ),
                name="reg_template_receipt_evidence_nonblank",
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE registration_registrationtemplate DISABLE TRIGGER "
                "registration_template_scope_and_version_guard; "
                "ALTER TABLE registration_registrationconfiguration DISABLE TRIGGER "
                "registration_configuration_scope_and_version_guard;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(
            backfill_page10_registration_schema,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE registration_registrationtemplate ENABLE TRIGGER "
                "registration_template_scope_and_version_guard; "
                "ALTER TABLE registration_registrationconfiguration ENABLE TRIGGER "
                "registration_configuration_scope_and_version_guard;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
