# Generated by Django 5.2.16 on 2026-08-03

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("registration", "0032_page10_registration_setup_schema"),
    ]

    operations: ClassVar[list[object]] = [
        migrations.AlterField(
            model_name="registrationsetupcommandreceipt",
            name="action",
            field=models.CharField(
                choices=[
                    ("setup_started", "Setup started"),
                    ("successor_started", "Successor started"),
                    ("configuration_reviewed", "Configuration reviewed"),
                    ("configuration_activated", "Configuration activated"),
                    ("configuration_retired", "Configuration retired"),
                    ("section_created", "Section created"),
                    ("section_updated", "Section updated"),
                    ("section_moved", "Section moved"),
                    ("section_deleted", "Section deleted"),
                    ("question_created", "Question created"),
                    ("question_updated", "Question updated"),
                    ("question_moved", "Question moved"),
                    ("question_deleted", "Question deleted"),
                    ("product_created", "Product created"),
                    ("product_updated", "Product updated"),
                    ("product_moved", "Product moved"),
                    ("product_deleted", "Product deleted"),
                    ("minor_policy_created", "Minor policy created"),
                    ("minor_policy_updated", "Minor policy updated"),
                    ("minor_policy_removed", "Minor policy removed"),
                    ("profile_field_created", "Profile field created"),
                    ("profile_field_updated", "Profile field updated"),
                    ("profile_field_moved", "Profile field moved"),
                    ("profile_field_reviewed", "Profile field reviewed"),
                    ("profile_field_activated", "Profile field activated"),
                    ("profile_field_retired", "Profile field retired"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="minorregistrationpolicy",
            name="guardian_notice_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="minorregistrationpolicy",
            name="jurisdiction_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="minorregistrationpolicy",
            name="review_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
