# Generated by Django 5.2.16 on 2026-08-03

from collections.abc import Sequence
from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation

FORWARD_FIELD_GUARD_SQL = """
CREATE OR REPLACE FUNCTION maru_guard_registration_profile_extension_field()
RETURNS trigger AS $$
DECLARE
    edition_organization uuid;
    prior_edition uuid;
    prior_key varchar;
    prior_version integer;
    prior_status varchar;
    current_max_version integer;
    definition_changed boolean;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'profile extension fields use retirement, not deletion'
            USING ERRCODE = '23514';
    END IF;

    SELECT organization_id INTO edition_organization
      FROM events_eventedition WHERE id = NEW.edition_id;
    IF edition_organization IS NULL
       OR edition_organization != NEW.organization_id
    THEN
        RAISE EXCEPTION 'profile extension field scope mismatch'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.supersedes_id IS NOT NULL THEN
        SELECT edition_id, key, version, status
          INTO prior_edition, prior_key, prior_version, prior_status
          FROM registration_registrationprofileextensionfield
         WHERE id = NEW.supersedes_id;
        SELECT max(version)
          INTO current_max_version
          FROM registration_registrationprofileextensionfield
         WHERE edition_id = NEW.edition_id
           AND key = NEW.key;
        IF prior_edition IS NULL
           OR prior_edition != NEW.edition_id
           OR prior_key != NEW.key
           OR prior_version >= NEW.version
           OR (
               TG_OP = 'INSERT'
               AND (
                   prior_status != 'active'
                   OR NEW.version != COALESCE(current_max_version, 0) + 1
               )
           )
        THEN
            RAISE EXCEPTION 'invalid superseded profile extension field'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    IF NEW.review_status = 'approved' THEN
        IF NEW.approved_by_id IS NULL
           OR NEW.approved_at IS NULL
           OR NEW.approved_at > statement_timestamp()
        THEN
            RAISE EXCEPTION 'profile extension approval evidence is incomplete'
                USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.approved_by_id IS NOT NULL OR NEW.approved_at IS NOT NULL THEN
        RAISE EXCEPTION 'unapproved profile extension has approval evidence'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.status = 'active' AND NEW.review_status != 'approved' THEN
        RAISE EXCEPTION 'active profile extension field lacks approval'
            USING ERRCODE = '23514';
    END IF;

    IF TG_OP = 'UPDATE'
       AND (
           NEW.source_template_id IS DISTINCT FROM OLD.source_template_id
           OR NEW.source_prior_edition_id
              IS DISTINCT FROM OLD.source_prior_edition_id
       )
    THEN
        RAISE EXCEPTION 'profile extension source binding is immutable'
            USING ERRCODE = '23514';
    END IF;

    IF TG_OP = 'UPDATE' AND OLD.status = 'retired' THEN
        RAISE EXCEPTION 'retired profile extension fields are immutable'
            USING ERRCODE = '23514';
    ELSIF TG_OP = 'UPDATE' AND OLD.status = 'active' THEN
        IF NEW.status != 'retired'
           OR NEW.last_changed_in_setup_version IS NULL
           OR NEW.last_changed_in_setup_version
              <= COALESCE(OLD.last_changed_in_setup_version, 0)
           OR (
               to_jsonb(NEW)
               - 'status'
               - 'last_changed_in_setup_version'
               - 'updated_at'
               IS DISTINCT FROM
               to_jsonb(OLD)
               - 'status'
               - 'last_changed_in_setup_version'
               - 'updated_at'
           )
        THEN
            RAISE EXCEPTION 'active profile extension fields are immutable'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_OP = 'UPDATE'
          AND OLD.status = 'draft'
          AND OLD.review_status = 'approved'
    THEN
        IF NEW.review_status = 'approved'
           AND (
               NEW.approved_by_id IS DISTINCT FROM OLD.approved_by_id
               OR NEW.approved_at IS DISTINCT FROM OLD.approved_at
           )
        THEN
            RAISE EXCEPTION 'profile extension approval evidence is immutable'
                USING ERRCODE = '23514';
        END IF;
        definition_changed := (
            to_jsonb(NEW)
            - 'status'
            - 'review_status'
            - 'approved_by_id'
            - 'approved_at'
            - 'last_changed_in_setup_version'
            - 'updated_at'
            IS DISTINCT FROM
            to_jsonb(OLD)
            - 'status'
            - 'review_status'
            - 'approved_by_id'
            - 'approved_at'
            - 'last_changed_in_setup_version'
            - 'updated_at'
        );
        IF definition_changed
           AND (
               NEW.review_status != 'pending'
               OR NEW.approved_by_id IS NOT NULL
               OR NEW.approved_at IS NOT NULL
           )
        THEN
            RAISE EXCEPTION 'profile extension edit must reset approval'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


REVERSE_FIELD_GUARD_SQL = """
CREATE OR REPLACE FUNCTION maru_guard_registration_profile_extension_field()
RETURNS trigger AS $$
DECLARE
    edition_organization uuid;
    prior_edition uuid;
    prior_key varchar;
    prior_version integer;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'profile extension fields use retirement, not deletion'
            USING ERRCODE = '23514';
    END IF;
    SELECT organization_id INTO edition_organization
      FROM events_eventedition WHERE id = NEW.edition_id;
    IF edition_organization IS NULL
       OR edition_organization != NEW.organization_id
    THEN
        RAISE EXCEPTION 'profile extension field scope mismatch'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.supersedes_id IS NOT NULL THEN
        SELECT edition_id, key, version
          INTO prior_edition, prior_key, prior_version
          FROM registration_registrationprofileextensionfield
         WHERE id = NEW.supersedes_id;
        IF prior_edition IS NULL
           OR prior_edition != NEW.edition_id
           OR prior_key != NEW.key
           OR prior_version >= NEW.version
        THEN
            RAISE EXCEPTION 'invalid superseded profile extension field'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    IF NEW.status = 'active'
       AND (
           NEW.review_status != 'approved'
           OR NEW.approved_by_id IS NULL
           OR NEW.approved_at IS NULL
       )
    THEN
        RAISE EXCEPTION 'active profile extension field lacks approval'
            USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status = 'active' THEN
        IF NEW.status != 'retired'
           OR (
               to_jsonb(NEW) - 'status' - 'updated_at'
               != to_jsonb(OLD) - 'status' - 'updated_at'
           )
        THEN
            RAISE EXCEPTION 'active profile extension fields are immutable'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


FORWARD_EVIDENCE_GUARD_SQL = """
CREATE OR REPLACE FUNCTION public.maru_guard_registration_setup_evidence_immutable()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'TRUNCATE'
       AND public.maru_authority_provenance_test_reset_allowed()
    THEN
        RETURN NULL;
    END IF;
    RAISE EXCEPTION 'registration setup command evidence is append-only'
        USING ERRCODE = '23514';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp;

REVOKE ALL ON FUNCTION public.maru_guard_registration_setup_evidence_immutable()
FROM PUBLIC;

DROP TRIGGER IF EXISTS registration_setup_receipt_immutable
ON registration_registrationsetupcommandreceipt;
CREATE TRIGGER registration_setup_receipt_immutable
BEFORE UPDATE OR DELETE ON registration_registrationsetupcommandreceipt
FOR EACH ROW EXECUTE FUNCTION maru_guard_registration_setup_evidence_immutable();

DROP TRIGGER IF EXISTS registration_setup_receipt_no_truncate
ON registration_registrationsetupcommandreceipt;
CREATE TRIGGER registration_setup_receipt_no_truncate
BEFORE TRUNCATE ON registration_registrationsetupcommandreceipt
FOR EACH STATEMENT EXECUTE FUNCTION maru_guard_registration_setup_evidence_immutable();

DROP TRIGGER IF EXISTS registration_setup_target_immutable
ON registration_registrationsetupcommandtarget;
CREATE TRIGGER registration_setup_target_immutable
BEFORE UPDATE OR DELETE ON registration_registrationsetupcommandtarget
FOR EACH ROW EXECUTE FUNCTION maru_guard_registration_setup_evidence_immutable();

DROP TRIGGER IF EXISTS registration_setup_target_no_truncate
ON registration_registrationsetupcommandtarget;
CREATE TRIGGER registration_setup_target_no_truncate
BEFORE TRUNCATE ON registration_registrationsetupcommandtarget
FOR EACH STATEMENT EXECUTE FUNCTION maru_guard_registration_setup_evidence_immutable();
"""


FORWARD_PROVENANCE_GUARD_SQL = """
CREATE OR REPLACE FUNCTION maru_guard_registration_profile_extension_provenance()
RETURNS trigger AS $$
DECLARE
    target_organization uuid;
    target_series uuid;
    target_start date;
    template_organization uuid;
    template_series uuid;
    template_status varchar;
    source_organization uuid;
    source_start date;
BEGIN
    IF NEW.source_template_id IS NOT NULL
       AND NEW.source_prior_edition_id IS NOT NULL
    THEN
        RAISE EXCEPTION 'profile extension provenance must use one source'
            USING ERRCODE = '23514';
    END IF;

    SELECT organization_id, series_id, starts_on
      INTO target_organization, target_series, target_start
      FROM events_eventedition
     WHERE id = NEW.edition_id;

    IF NEW.source_template_id IS NOT NULL THEN
        SELECT organization_id, series_id, status
          INTO template_organization, template_series, template_status
          FROM registration_registrationtemplate
         WHERE id = NEW.source_template_id;
        IF template_organization IS NULL
           OR template_organization != target_organization
           OR (template_series IS NOT NULL AND template_series != target_series)
           OR template_status NOT IN ('published', 'retired')
           OR (
               template_status = 'retired'
               AND (
                   TG_OP != 'UPDATE'
                   OR NEW.source_template_id IS DISTINCT FROM OLD.source_template_id
               )
           )
        THEN
            RAISE EXCEPTION 'invalid profile extension template provenance'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    IF NEW.source_prior_edition_id IS NOT NULL THEN
        SELECT organization_id, starts_on
          INTO source_organization, source_start
          FROM events_eventedition
         WHERE id = NEW.source_prior_edition_id;
        IF source_organization IS NULL
           OR source_organization != target_organization
           OR NEW.source_prior_edition_id = NEW.edition_id
           OR (
               (
                   TG_OP != 'UPDATE'
                   OR NEW.source_prior_edition_id
                      IS DISTINCT FROM OLD.source_prior_edition_id
               )
               AND source_start >= target_start
           )
        THEN
            RAISE EXCEPTION 'invalid profile extension edition provenance'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


REVERSE_PROVENANCE_GUARD_SQL = """
CREATE OR REPLACE FUNCTION maru_guard_registration_profile_extension_provenance()
RETURNS trigger AS $$
DECLARE
    target_organization uuid;
    target_series uuid;
    target_start date;
    template_organization uuid;
    template_series uuid;
    template_status varchar;
    source_organization uuid;
    source_start date;
BEGIN
    IF NEW.source_template_id IS NOT NULL
       AND NEW.source_prior_edition_id IS NOT NULL
    THEN
        RAISE EXCEPTION 'profile extension provenance must use one source'
            USING ERRCODE = '23514';
    END IF;

    SELECT organization_id, series_id, starts_on
      INTO target_organization, target_series, target_start
      FROM events_eventedition
     WHERE id = NEW.edition_id;

    IF NEW.source_template_id IS NOT NULL THEN
        SELECT organization_id, series_id, status
          INTO template_organization, template_series, template_status
          FROM registration_registrationtemplate
         WHERE id = NEW.source_template_id;
        IF template_organization IS NULL
           OR template_organization != target_organization
           OR (
               template_series IS NOT NULL
               AND template_series != target_series
           )
           OR template_status != 'published'
        THEN
            RAISE EXCEPTION 'invalid profile extension template provenance'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    IF NEW.source_prior_edition_id IS NOT NULL THEN
        SELECT organization_id, starts_on
          INTO source_organization, source_start
          FROM events_eventedition
         WHERE id = NEW.source_prior_edition_id;
        IF source_organization IS NULL
           OR source_organization != target_organization
           OR NEW.source_prior_edition_id = NEW.edition_id
           OR source_start >= target_start
        THEN
            RAISE EXCEPTION 'invalid profile extension edition provenance'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


REVERSE_EVIDENCE_GUARD_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM registration_registrationsetupcommandreceipt
         WHERE action = 'profile_field_successor_started'
    ) OR EXISTS (
        SELECT 1
          FROM registration_registrationprofileextensionfield
         WHERE supersedes_id IS NOT NULL
    ) THEN
        RAISE EXCEPTION
            'cannot reverse populated profile lifecycle; use fix-forward recovery'
            USING ERRCODE = '55000';
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS registration_setup_target_no_truncate
ON registration_registrationsetupcommandtarget;
DROP TRIGGER IF EXISTS registration_setup_target_immutable
ON registration_registrationsetupcommandtarget;
DROP TRIGGER IF EXISTS registration_setup_receipt_no_truncate
ON registration_registrationsetupcommandreceipt;
DROP TRIGGER IF EXISTS registration_setup_receipt_immutable
ON registration_registrationsetupcommandreceipt;
DROP FUNCTION IF EXISTS public.maru_guard_registration_setup_evidence_immutable();
"""


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("authorization", "0007_authority_provenance_activation_guards"),
        ("registration", "0033_page10_definition_command_actions"),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.AlterField(
            model_name="registrationsetupcommandreceipt",
            name="action",
            field=models.CharField(
                choices=[
                    ("setup_started", "Setup started"),
                    ("successor_started", "Successor started"),
                    ("configuration_reviewed", "Configuration reviewed"),
                    ("configuration_activated", "Configuration activated"),
                    ("configuration_retired", "Configuration retired"),
                    ("section_created", "Section created"),
                    ("section_updated", "Section updated"),
                    ("section_moved", "Section moved"),
                    ("section_deleted", "Section deleted"),
                    ("question_created", "Question created"),
                    ("question_updated", "Question updated"),
                    ("question_moved", "Question moved"),
                    ("question_deleted", "Question deleted"),
                    ("product_created", "Product created"),
                    ("product_updated", "Product updated"),
                    ("product_moved", "Product moved"),
                    ("product_deleted", "Product deleted"),
                    ("minor_policy_created", "Minor policy created"),
                    ("minor_policy_updated", "Minor policy updated"),
                    ("minor_policy_removed", "Minor policy removed"),
                    ("profile_field_created", "Profile field created"),
                    ("profile_field_updated", "Profile field updated"),
                    ("profile_field_moved", "Profile field moved"),
                    ("profile_field_reviewed", "Profile field reviewed"),
                    ("profile_field_activated", "Profile field activated"),
                    (
                        "profile_field_successor_started",
                        "Profile field successor started",
                    ),
                    ("profile_field_retired", "Profile field retired"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationprofileextensionfield",
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(("supersedes__isnull", False))
                    & ~models.Q(("status", "retired"))
                ),
                fields=("supersedes",),
                name="registration_one_open_profile_extension_successor",
            ),
        ),
        migrations.RunSQL(
            FORWARD_FIELD_GUARD_SQL
            + FORWARD_PROVENANCE_GUARD_SQL
            + FORWARD_EVIDENCE_GUARD_SQL,
            reverse_sql=(
                REVERSE_EVIDENCE_GUARD_SQL
                + REVERSE_PROVENANCE_GUARD_SQL
                + REVERSE_FIELD_GUARD_SQL
            ),
        ),
    ]
