# Generated by Django 5.2.16 on 2026-08-03

import uuid
from collections.abc import Sequence
from typing import ClassVar

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.operations.base import Operation

import maru.core.validators

FORWARD_BACKFILL_SQL = r"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM public.registration_registrationprofileextensionvaluerevision
         GROUP BY registration_id, field_key
        HAVING min(sequence) != 1
            OR max(sequence) != count(*)
            OR count(DISTINCT sequence) != count(*)
    ) THEN
        RAISE EXCEPTION
            'cannot backfill noncontiguous profile-value revision history'
            USING ERRCODE = '55000';
    END IF;
    IF EXISTS (
        SELECT 1
          FROM public.registration_registrationprofileextensionvaluerevision
               AS revision
          JOIN public.registration_registration AS registration
            ON registration.id = revision.registration_id
          JOIN public.registration_registrationprofileextensionfield AS field
            ON field.id = revision.field_id
         WHERE NOT (
             (
                 revision.actor_id = registration.account_id
                 AND field.attendee_visible IS TRUE
                 AND field.writer_policy IN ('attendee', 'attendee_and_staff')
                 AND revision.reason = ''
             )
             OR (
                 revision.actor_id != registration.account_id
                 AND field.writer_policy IN (
                     'registration_staff',
                     'attendee_and_staff'
                 )
                 AND revision.reason = btrim(
                     revision.reason,
                     U&'\0009\000A\000B\000C\000D\001C\001D\001E\001F\0020\0085\00A0\1680\2000\2001\2002\2003\2004\2005\2006\2007\2008\2009\200A\2028\2029\202F\205F\3000'
                 )
                 AND revision.reason != ''
             )
         )
    ) THEN
        RAISE EXCEPTION
            'cannot backfill profile-value history with invalid writer policy'
            USING ERRCODE = '55000';
    END IF;
    IF EXISTS (
        SELECT 1
          FROM public.registration_registrationprofileextensionvaluerevision
         WHERE source_channel !~ '^[a-z][a-z0-9_-]{0,31}$'
    ) THEN
        RAISE EXCEPTION
            'cannot backfill profile-value history with invalid source channel'
            USING ERRCODE = '55000';
    END IF;
    IF EXISTS (
        SELECT 1
          FROM public.registration_registrationprofileextensionvaluerevision
               AS revision
          JOIN public.registration_registrationprofileextensionfield AS field
            ON field.id = revision.field_id
         WHERE field.status NOT IN ('active', 'retired')
    ) THEN
        RAISE EXCEPTION
            'cannot backfill profile-value history against a draft profile field'
            USING ERRCODE = '55000';
    END IF;
    IF EXISTS (
        SELECT 1
          FROM public.registration_registrationprofileextensionvaluerevision
               AS revision
          JOIN public.registration_registrationprofileextensionfield AS field
            ON field.id = revision.field_id
         WHERE octet_length(convert_to(revision.value::text, 'UTF8')) > 16384
            OR (
                CASE field.field_type
                    WHEN 'short_text' THEN
                        jsonb_typeof(revision.value) = 'string'
                        AND char_length(revision.value #>> '{}') <= 500
                        AND (revision.value #>> '{}') = btrim(
                            revision.value #>> '{}',
                            U&'\0009\000A\000B\000C\000D\001C\001D\001E\001F\0020\0085\00A0\1680\2000\2001\2002\2003\2004\2005\2006\2007\2008\2009\200A\2028\2029\202F\205F\3000'
                        )
                        AND (
                            NOT field.required
                            OR (revision.value #>> '{}') != ''
                        )
                    WHEN 'long_text' THEN
                        jsonb_typeof(revision.value) = 'string'
                        AND char_length(revision.value #>> '{}') <= 4000
                        AND (revision.value #>> '{}') = btrim(
                            revision.value #>> '{}',
                            U&'\0009\000A\000B\000C\000D\001C\001D\001E\001F\0020\0085\00A0\1680\2000\2001\2002\2003\2004\2005\2006\2007\2008\2009\200A\2028\2029\202F\205F\3000'
                        )
                        AND (
                            NOT field.required
                            OR (revision.value #>> '{}') != ''
                        )
                    WHEN 'boolean' THEN
                        jsonb_typeof(revision.value) = 'boolean'
                    WHEN 'integer' THEN
                        CASE
                            WHEN jsonb_typeof(revision.value) != 'number'
                            THEN FALSE
                            ELSE
                                (revision.value #>> '{}')::numeric = trunc(
                                    (revision.value #>> '{}')::numeric
                                )
                                AND (revision.value #>> '{}')::numeric
                                    BETWEEN -2147483648 AND 2147483647
                        END
                    WHEN 'single_choice' THEN
                        jsonb_typeof(revision.value) = 'string'
                        AND field.options ? (revision.value #>> '{}')
                    WHEN 'multiple_choice' THEN
                        CASE
                            WHEN jsonb_typeof(revision.value) != 'array'
                            THEN FALSE
                            ELSE
                                jsonb_array_length(revision.value) <= 64
                                AND (
                                    NOT field.required
                                    OR jsonb_array_length(revision.value) > 0
                                )
                                AND NOT EXISTS (
                                    SELECT 1
                                      FROM jsonb_array_elements(
                                          revision.value
                                      ) AS item(value)
                                     WHERE jsonb_typeof(item.value) != 'string'
                                        OR NOT (
                                            field.options
                                            ? (item.value #>> '{}')
                                        )
                                )
                                AND (
                                    SELECT count(*) = count(DISTINCT item.value)
                                      FROM jsonb_array_elements_text(
                                          revision.value
                                      ) AS item(value)
                                )
                        END
                    ELSE FALSE
                END
            ) IS NOT TRUE
    ) THEN
        RAISE EXCEPTION
            'cannot backfill profile-value history incompatible with field definition'
            USING ERRCODE = '55000';
    END IF;
END;
$$;

WITH ranked AS (
    SELECT revision.*,
           min(revision.created_at) OVER (
               PARTITION BY revision.registration_id, revision.field_key
           ) AS first_created_at,
           row_number() OVER (
               PARTITION BY revision.registration_id, revision.field_key
               ORDER BY revision.sequence DESC, revision.id DESC
           ) AS row_number
      FROM registration_registrationprofileextensionvaluerevision AS revision
)
INSERT INTO registration_registrationprofileextensionvaluecontrol (
    id,
    created_at,
    updated_at,
    organization_id,
    edition_id,
    field_key,
    current_sequence,
    latest_revision_id,
    registration_id
)
SELECT (
           md5(
               'maru-profile-value-control:'
               || ranked.registration_id::text
               || ':'
               || ranked.field_key
           )
       )::uuid,
       ranked.first_created_at,
       ranked.created_at,
       ranked.organization_id,
       ranked.edition_id,
       ranked.field_key,
       ranked.sequence,
       ranked.id,
       ranked.registration_id
  FROM ranked
 WHERE ranked.row_number = 1;
"""


FORWARD_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.maru_guard_registration_profile_value_immutable()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'TRUNCATE'
       AND public.maru_authority_provenance_test_reset_allowed()
    THEN
        RETURN NULL;
    END IF;
    RAISE EXCEPTION 'registration profile-value evidence is append-only'
        USING ERRCODE = '23514';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp;

REVOKE ALL ON FUNCTION public.maru_guard_registration_profile_value_immutable()
FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.maru_guard_registration_profile_value_revision_v2()
RETURNS trigger AS $$
DECLARE
    registration_organization uuid;
    registration_edition uuid;
    field_organization uuid;
    field_edition uuid;
    stable_key varchar;
    field_status varchar;
    field_type varchar;
    field_options jsonb;
    field_required boolean;
    next_sequence integer;
    database_now timestamptz;
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        RAISE EXCEPTION 'profile extension value revisions are append-only'
            USING ERRCODE = '23514';
    END IF;
    database_now := statement_timestamp();
    SELECT organization_id, edition_id
      INTO registration_organization, registration_edition
      FROM public.registration_registration
     WHERE id = NEW.registration_id;
    SELECT field.organization_id, field.edition_id, field.key, field.status,
           field.field_type, field.options, field.required
      INTO field_organization, field_edition, stable_key, field_status,
           field_type, field_options, field_required
      FROM public.registration_registrationprofileextensionfield AS field
     WHERE field.id = NEW.field_id;
    SELECT COALESCE(max(sequence), 0) + 1
      INTO next_sequence
      FROM public.registration_registrationprofileextensionvaluerevision
     WHERE registration_id = NEW.registration_id
       AND field_key = NEW.field_key;
    IF registration_organization IS NULL
       OR registration_organization != NEW.organization_id
       OR registration_edition != NEW.edition_id
       OR field_organization != NEW.organization_id
       OR field_edition != NEW.edition_id
       OR stable_key != NEW.field_key
       OR field_status != 'active'
       OR NEW.sequence != next_sequence
       OR NEW.source_channel !~ '^[a-z][a-z0-9_-]{0,31}$'
       OR length(NEW.reason) > 500
       OR NEW.reason != btrim(
           NEW.reason,
           U&'\0009\000A\000B\000C\000D\001C\001D\001E\001F\0020\0085\00A0\1680\2000\2001\2002\2003\2004\2005\2006\2007\2008\2009\200A\2028\2029\202F\205F\3000'
       )
       OR octet_length(convert_to(NEW.value::text, 'UTF8')) > 16384
       OR (
           CASE field_type
               WHEN 'short_text' THEN
                   jsonb_typeof(NEW.value) = 'string'
                   AND char_length(NEW.value #>> '{}') <= 500
                   AND (NEW.value #>> '{}') = btrim(
                       NEW.value #>> '{}',
                       U&'\0009\000A\000B\000C\000D\001C\001D\001E\001F\0020\0085\00A0\1680\2000\2001\2002\2003\2004\2005\2006\2007\2008\2009\200A\2028\2029\202F\205F\3000'
                   )
                   AND (NOT field_required OR (NEW.value #>> '{}') != '')
               WHEN 'long_text' THEN
                   jsonb_typeof(NEW.value) = 'string'
                   AND char_length(NEW.value #>> '{}') <= 4000
                   AND (NEW.value #>> '{}') = btrim(
                       NEW.value #>> '{}',
                       U&'\0009\000A\000B\000C\000D\001C\001D\001E\001F\0020\0085\00A0\1680\2000\2001\2002\2003\2004\2005\2006\2007\2008\2009\200A\2028\2029\202F\205F\3000'
                   )
                   AND (NOT field_required OR (NEW.value #>> '{}') != '')
               WHEN 'boolean' THEN jsonb_typeof(NEW.value) = 'boolean'
               WHEN 'integer' THEN
                   CASE
                       WHEN jsonb_typeof(NEW.value) != 'number' THEN FALSE
                       ELSE
                           (NEW.value #>> '{}')::numeric = trunc(
                               (NEW.value #>> '{}')::numeric
                           )
                           AND (NEW.value #>> '{}')::numeric
                               BETWEEN -2147483648 AND 2147483647
                   END
               WHEN 'single_choice' THEN
                   jsonb_typeof(NEW.value) = 'string'
                   AND field_options ? (NEW.value #>> '{}')
               WHEN 'multiple_choice' THEN
                   CASE
                       WHEN jsonb_typeof(NEW.value) != 'array' THEN FALSE
                       ELSE
                           jsonb_array_length(NEW.value) <= 64
                           AND (
                               NOT field_required
                               OR jsonb_array_length(NEW.value) > 0
                           )
                           AND NOT EXISTS (
                               SELECT 1
                                 FROM jsonb_array_elements(NEW.value) AS item(value)
                                WHERE jsonb_typeof(item.value) != 'string'
                                   OR NOT (field_options ? (item.value #>> '{}'))
                           )
                           AND (
                               SELECT count(*) = count(DISTINCT item.value)
                                 FROM jsonb_array_elements_text(NEW.value)
                                      AS item(value)
                           )
                   END
               ELSE FALSE
           END
       ) IS NOT TRUE
    THEN
        RAISE EXCEPTION 'invalid profile extension value append'
            USING ERRCODE = '23514';
    END IF;
    NEW.created_at := database_now;
    NEW.updated_at := database_now;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp;

REVOKE ALL ON FUNCTION public.maru_guard_registration_profile_value_revision_v2()
FROM PUBLIC;

DROP TRIGGER IF EXISTS registration_profile_extension_value_guard
ON public.registration_registrationprofileextensionvaluerevision;
DROP FUNCTION IF EXISTS
public.maru_guard_registration_profile_extension_value();
CREATE TRIGGER registration_profile_extension_value_guard
BEFORE INSERT OR UPDATE OR DELETE
ON public.registration_registrationprofileextensionvaluerevision
FOR EACH ROW
EXECUTE FUNCTION public.maru_guard_registration_profile_value_revision_v2();

DROP TRIGGER IF EXISTS registration_profile_value_revision_no_truncate
ON public.registration_registrationprofileextensionvaluerevision;
CREATE TRIGGER registration_profile_value_revision_no_truncate
BEFORE TRUNCATE
ON public.registration_registrationprofileextensionvaluerevision
FOR EACH STATEMENT
EXECUTE FUNCTION public.maru_guard_registration_profile_value_immutable();

CREATE OR REPLACE FUNCTION public.maru_guard_registration_profile_value_control()
RETURNS trigger AS $$
DECLARE
    registration_organization uuid;
    registration_edition uuid;
    revision_registration uuid;
    revision_organization uuid;
    revision_edition uuid;
    revision_key varchar;
    revision_sequence integer;
    database_now timestamptz;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'registration profile-value controls are durable'
            USING ERRCODE = '23514';
    END IF;
    database_now := statement_timestamp();
    SELECT organization_id, edition_id
      INTO registration_organization, registration_edition
      FROM public.registration_registration
     WHERE id = NEW.registration_id;
    IF NEW.latest_revision_id IS NOT NULL THEN
        SELECT registration_id, organization_id, edition_id, field_key, sequence
          INTO revision_registration, revision_organization, revision_edition,
               revision_key, revision_sequence
          FROM public.registration_registrationprofileextensionvaluerevision
         WHERE id = NEW.latest_revision_id;
    END IF;
    IF registration_organization IS NULL
       OR registration_organization != NEW.organization_id
       OR registration_edition != NEW.edition_id
       OR (
           NEW.current_sequence = 0
           AND NEW.latest_revision_id IS NOT NULL
       )
       OR (
           NEW.current_sequence > 0
           AND (
               revision_registration IS NULL
               OR revision_registration != NEW.registration_id
               OR revision_organization != NEW.organization_id
               OR revision_edition != NEW.edition_id
               OR revision_key != NEW.field_key
               OR revision_sequence != NEW.current_sequence
           )
       )
       OR (
           TG_OP = 'UPDATE'
           AND (
               NEW.registration_id != OLD.registration_id
               OR NEW.organization_id != OLD.organization_id
               OR NEW.edition_id != OLD.edition_id
               OR NEW.field_key != OLD.field_key
               OR NEW.current_sequence != OLD.current_sequence + 1
               OR NEW.latest_revision_id IS NOT DISTINCT FROM OLD.latest_revision_id
           )
       )
    THEN
        RAISE EXCEPTION 'invalid registration profile-value control transition'
            USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'INSERT' THEN
        NEW.created_at := database_now;
    ELSE
        NEW.created_at := OLD.created_at;
    END IF;
    NEW.updated_at := database_now;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp;

REVOKE ALL ON FUNCTION public.maru_guard_registration_profile_value_control()
FROM PUBLIC;

CREATE TRIGGER registration_profile_value_control_guard
BEFORE INSERT OR UPDATE OR DELETE
ON public.registration_registrationprofileextensionvaluecontrol
FOR EACH ROW
EXECUTE FUNCTION public.maru_guard_registration_profile_value_control();

CREATE TRIGGER registration_profile_value_control_no_truncate
BEFORE TRUNCATE
ON public.registration_registrationprofileextensionvaluecontrol
FOR EACH STATEMENT
EXECUTE FUNCTION public.maru_guard_registration_profile_value_immutable();

CREATE OR REPLACE FUNCTION
public.maru_assert_registration_profile_value_control_complete()
RETURNS trigger AS $$
DECLARE
    complete_count integer;
BEGIN
    SELECT count(*)
      INTO complete_count
      FROM public.registration_registrationprofileextensionvaluecontrol AS control
      JOIN public.registration_registrationprofileextensionvaluerevision AS revision
        ON revision.id = control.latest_revision_id
       AND revision.registration_id = control.registration_id
       AND revision.organization_id = control.organization_id
       AND revision.edition_id = control.edition_id
       AND revision.field_key = control.field_key
       AND revision.sequence = control.current_sequence
     WHERE control.id = NEW.id
       AND control.current_sequence > 0;
    IF complete_count != 1 THEN
        RAISE EXCEPTION 'registration profile-value control is incomplete'
            USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp;

REVOKE ALL ON FUNCTION
public.maru_assert_registration_profile_value_control_complete()
FROM PUBLIC;

CREATE CONSTRAINT TRIGGER registration_profile_value_control_complete
AFTER INSERT OR UPDATE
ON public.registration_registrationprofileextensionvaluecontrol
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION
public.maru_assert_registration_profile_value_control_complete();

CREATE OR REPLACE FUNCTION public.maru_guard_registration_profile_value_receipt()
RETURNS trigger AS $$
DECLARE
    registration_account uuid;
    control_sequence integer;
    control_revision uuid;
    control_registration uuid;
    control_organization uuid;
    control_edition uuid;
    control_key varchar;
    revision_registration uuid;
    revision_organization uuid;
    revision_edition uuid;
    revision_field uuid;
    revision_actor uuid;
    revision_key varchar;
    revision_sequence integer;
    revision_reason varchar;
    revision_source varchar;
    revision_value jsonb;
    canonical_field_key varchar;
    field_version integer;
    field_visibility boolean;
    field_writer varchar;
    audit_count integer;
    event_count integer;
    computed_request_digest text;
    database_now timestamptz;
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        RAISE EXCEPTION 'registration profile-value command receipts are immutable'
            USING ERRCODE = '23514';
    END IF;
    database_now := statement_timestamp();
    SELECT account_id
      INTO registration_account
      FROM public.registration_registration
     WHERE id = NEW.registration_id
       AND organization_id = NEW.organization_id
       AND edition_id = NEW.edition_id;
    SELECT control.current_sequence, control.latest_revision_id,
           control.registration_id, control.organization_id,
           control.edition_id, control.field_key
      INTO control_sequence, control_revision, control_registration,
           control_organization, control_edition, control_key
      FROM public.registration_registrationprofileextensionvaluecontrol AS control
     WHERE control.id = NEW.control_id;
    SELECT revision.registration_id, revision.organization_id,
           revision.edition_id, revision.field_id, revision.actor_id,
           revision.field_key, revision.sequence, revision.reason,
           revision.source_channel, revision.value
      INTO revision_registration, revision_organization, revision_edition,
           revision_field, revision_actor, revision_key, revision_sequence,
           revision_reason, revision_source, revision_value
      FROM public.registration_registrationprofileextensionvaluerevision AS revision
     WHERE revision.id = NEW.revision_id;
    SELECT field.key, field.version, field.attendee_visible, field.writer_policy
      INTO canonical_field_key, field_version, field_visibility, field_writer
      FROM public.registration_registrationprofileextensionfield AS field
     WHERE field.id = NEW.field_id
       AND field.organization_id = NEW.organization_id
       AND field.edition_id = NEW.edition_id;
    IF registration_account IS NULL
       OR control_registration != NEW.registration_id
       OR control_organization != NEW.organization_id
       OR control_edition != NEW.edition_id
       OR control_key != canonical_field_key
       OR control_sequence != NEW.result_sequence
       OR control_revision != NEW.revision_id
       OR revision_registration != NEW.registration_id
       OR revision_organization != NEW.organization_id
       OR revision_edition != NEW.edition_id
       OR revision_field != NEW.field_id
       OR revision_actor != NEW.actor_id
       OR revision_key != canonical_field_key
       OR revision_sequence != NEW.result_sequence
       OR NEW.result_sequence != NEW.expected_sequence + 1
       OR NEW.request_digest !~ '^[0-9a-f]{64}$'
       OR NEW.source_channel !~ '^[a-z][a-z0-9_-]{0,31}$'
       OR revision_source != NEW.source_channel
       OR (
           NEW.writer_kind = 'owner'
           AND (
               registration_account != NEW.actor_id
               OR NOT field_visibility
               OR field_writer NOT IN ('attendee', 'attendee_and_staff')
               OR revision_reason != ''
           )
       )
       OR (
           NEW.writer_kind = 'staff'
           AND (
               registration_account = NEW.actor_id
               OR field_writer NOT IN ('registration_staff', 'attendee_and_staff')
               OR revision_reason = ''
           )
       )
       OR NEW.writer_kind NOT IN ('owner', 'staff')
    THEN
        RAISE EXCEPTION 'invalid registration profile-value command receipt'
            USING ERRCODE = '23514';
    END IF;
    SELECT encode(
               sha256(
                   convert_to(
                       jsonb_build_object(
                           'actor_id', NEW.actor_id::text,
                           'contract',
                               'maru.registration-profile-extension-value-command.v2',
                           'edition_id', NEW.edition_id::text,
                           'expected_sequence', NEW.expected_sequence,
                           'field_id', NEW.field_id::text,
                           'organization_id', NEW.organization_id::text,
                           'reason', revision_reason,
                           'registration_id', NEW.registration_id::text,
                           'source_channel', revision_source,
                           'value', revision_value
                       )::text,
                       'UTF8'
                   )
               ),
               'hex'
           )
      INTO computed_request_digest;
    IF NEW.request_digest != computed_request_digest THEN
        RAISE EXCEPTION 'registration profile-value request digest is invalid'
            USING ERRCODE = '23514';
    END IF;
    SELECT count(*)
      INTO audit_count
      FROM public.audit_auditevent AS audit
     WHERE audit.principal_kind = 'account'
       AND audit.principal_id = NEW.actor_id
       AND audit.organization_id = NEW.organization_id
       AND audit.event_edition_id = NEW.edition_id
       AND audit.capability_code = CASE
               WHEN NEW.writer_kind = 'owner'
               THEN 'registration.manage_self_profile'
               ELSE 'registration.update_profile_extensions'
           END
       AND audit.operation = 'registration.profile_extension.value_append'
       AND audit.target_type = 'registration.profile_extension_value_revision'
       AND audit.target_id = NEW.revision_id
       AND audit.outcome = 'allow'
       AND audit.correlation_id = NEW.correlation_id
       AND audit.changed_fields = ARRAY['current_value']::varchar[]
       AND audit.source_channel = NEW.source_channel;
    SELECT count(*)
      INTO event_count
      FROM public.effects_domainevent AS event
      JOIN public.effects_outboxmessage AS outbox
        ON outbox.event_id = event.id
       AND outbox.destination = 'internal'
     WHERE event.event_name = 'registration.profile_extension.value_appended.v1'
       AND event.schema_version = 1
       AND event.organization_id = NEW.organization_id
       AND event.event_edition_id = NEW.edition_id
       AND event.aggregate_type = 'registration.profile_extension_value'
       AND event.aggregate_id = NEW.control_id
       AND event.aggregate_version = NEW.result_sequence
       AND event.correlation_id = NEW.correlation_id
       AND event.actor_kind = 'account'
       AND event.actor_id = NEW.actor_id
       AND event.payload = jsonb_build_object(
           'field_id', NEW.field_id::text,
           'field_version', field_version::text,
           'registration_id', NEW.registration_id::text,
           'sequence', NEW.result_sequence::text,
           'writer_kind', NEW.writer_kind
       );
    IF audit_count != 1 OR event_count != 1 THEN
        RAISE EXCEPTION 'registration profile-value command evidence is incomplete'
            USING ERRCODE = '23514';
    END IF;
    NEW.created_at := database_now;
    NEW.updated_at := database_now;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp;

REVOKE ALL ON FUNCTION public.maru_guard_registration_profile_value_receipt()
FROM PUBLIC;

CREATE TRIGGER registration_profile_value_receipt_guard
BEFORE INSERT OR UPDATE OR DELETE
ON public.registration_registrationprofileextensionvaluecommandreceipt
FOR EACH ROW
EXECUTE FUNCTION public.maru_guard_registration_profile_value_receipt();

CREATE TRIGGER registration_profile_value_receipt_no_truncate
BEFORE TRUNCATE
ON public.registration_registrationprofileextensionvaluecommandreceipt
FOR EACH STATEMENT
EXECUTE FUNCTION public.maru_guard_registration_profile_value_immutable();

CREATE OR REPLACE FUNCTION
public.maru_assert_registration_profile_value_revision_evidence()
RETURNS trigger AS $$
DECLARE
    evidence_count integer;
BEGIN
    SELECT count(*)
      INTO evidence_count
      FROM public.registration_registrationprofileextensionvaluecommandreceipt
           AS receipt
      JOIN public.registration_registrationprofileextensionvaluecontrol AS control
        ON control.id = receipt.control_id
     WHERE receipt.revision_id = NEW.id
       AND receipt.registration_id = NEW.registration_id
       AND receipt.organization_id = NEW.organization_id
       AND receipt.edition_id = NEW.edition_id
       AND receipt.field_id = NEW.field_id
       AND receipt.actor_id = NEW.actor_id
       AND receipt.result_sequence = NEW.sequence
       AND receipt.source_channel = NEW.source_channel
       AND control.registration_id = NEW.registration_id
       AND control.field_key = NEW.field_key
       AND control.current_sequence >= NEW.sequence
       AND (
           control.current_sequence != NEW.sequence
           OR control.latest_revision_id = NEW.id
       );
    IF evidence_count != 1 THEN
        RAISE EXCEPTION 'profile extension value revision lacks command evidence'
            USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp;

REVOKE ALL ON FUNCTION public.maru_assert_registration_profile_value_revision_evidence()
FROM PUBLIC;

CREATE CONSTRAINT TRIGGER registration_profile_value_revision_evidence
AFTER INSERT
ON public.registration_registrationprofileextensionvaluerevision
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.maru_assert_registration_profile_value_revision_evidence();
"""


REVERSE_GUARD_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM public.registration_registrationprofileextensionvaluecommandreceipt
    ) THEN
        RAISE EXCEPTION
            'cannot reverse populated profile-value commands; use fix-forward recovery'
            USING ERRCODE = '55000';
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS registration_profile_value_revision_evidence
ON public.registration_registrationprofileextensionvaluerevision;
DROP TRIGGER IF EXISTS registration_profile_value_control_complete
ON public.registration_registrationprofileextensionvaluecontrol;
DROP TRIGGER IF EXISTS registration_profile_value_receipt_no_truncate
ON public.registration_registrationprofileextensionvaluecommandreceipt;
DROP TRIGGER IF EXISTS registration_profile_value_receipt_guard
ON public.registration_registrationprofileextensionvaluecommandreceipt;
DROP TRIGGER IF EXISTS registration_profile_value_control_no_truncate
ON public.registration_registrationprofileextensionvaluecontrol;
DROP TRIGGER IF EXISTS registration_profile_value_control_guard
ON public.registration_registrationprofileextensionvaluecontrol;
DROP TRIGGER IF EXISTS registration_profile_value_revision_no_truncate
ON public.registration_registrationprofileextensionvaluerevision;
DROP TRIGGER IF EXISTS registration_profile_extension_value_guard
ON public.registration_registrationprofileextensionvaluerevision;
DROP FUNCTION IF EXISTS
public.maru_assert_registration_profile_value_revision_evidence();
DROP FUNCTION IF EXISTS
public.maru_assert_registration_profile_value_control_complete();
DROP FUNCTION IF EXISTS public.maru_guard_registration_profile_value_receipt();
DROP FUNCTION IF EXISTS public.maru_guard_registration_profile_value_control();
DROP FUNCTION IF EXISTS public.maru_guard_registration_profile_value_revision_v2();
DROP FUNCTION IF EXISTS public.maru_guard_registration_profile_value_immutable();

CREATE OR REPLACE FUNCTION public.maru_guard_registration_profile_extension_value()
RETURNS trigger AS $$
DECLARE
    registration_organization uuid;
    registration_edition uuid;
    field_organization uuid;
    field_edition uuid;
    stable_key varchar;
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        RAISE EXCEPTION 'profile extension value revisions are append-only'
            USING ERRCODE = '23514';
    END IF;
    SELECT organization_id, edition_id
      INTO registration_organization, registration_edition
      FROM public.registration_registration WHERE id = NEW.registration_id;
    SELECT organization_id, edition_id, key
      INTO field_organization, field_edition, stable_key
      FROM public.registration_registrationprofileextensionfield
     WHERE id = NEW.field_id;
    IF registration_organization IS NULL
       OR registration_organization != NEW.organization_id
       OR registration_edition != NEW.edition_id
       OR field_organization != NEW.organization_id
       OR field_edition != NEW.edition_id
       OR stable_key != NEW.field_key
    THEN
        RAISE EXCEPTION 'profile extension value scope mismatch'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER registration_profile_extension_value_guard
BEFORE INSERT OR UPDATE OR DELETE
ON public.registration_registrationprofileextensionvaluerevision
FOR EACH ROW
EXECUTE FUNCTION public.maru_guard_registration_profile_extension_value();
"""


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("authorization", "0011_registration_profile_extension_capabilities"),
        ("registration", "0035_configuration_source_binding_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[Sequence[Operation]] = [
        migrations.CreateModel(
            name="RegistrationProfileExtensionValueControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                (
                    "field_key",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                ("current_sequence", models.PositiveIntegerField(default=0)),
                (
                    "latest_revision",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_control",
                        to=("registration.registrationprofileextensionvaluerevision"),
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile_extension_value_controls",
                        to="registration.registration",
                    ),
                ),
            ],
            options={"ordering": ("registration_id", "field_key", "id")},
        ),
        migrations.CreateModel(
            name="RegistrationProfileExtensionValueCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("edition_id", models.UUIDField()),
                (
                    "writer_kind",
                    models.CharField(
                        choices=[
                            ("owner", "Registration owner"),
                            ("staff", "Authorized registration staff"),
                        ],
                        max_length=8,
                    ),
                ),
                ("retry_key", models.UUIDField()),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_registration_setup_digest",
                                message="Use a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("expected_sequence", models.PositiveIntegerField()),
                ("result_sequence", models.PositiveIntegerField()),
                ("correlation_id", models.UUIDField()),
                ("request_id", models.UUIDField(blank=True, null=True)),
                (
                    "source_channel",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_profile_extension_value_source",
                                message="Use one registered source channel.",
                                regex="^[a-z][a-z0-9_-]{0,31}$",
                            )
                        ],
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name=(
                            "registration_profile_extension_value_command_receipts"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="value_command_receipts",
                        to="registration.registrationprofileextensionfield",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile_extension_value_command_receipts",
                        to="registration.registration",
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="command_receipt",
                        to=("registration.registrationprofileextensionvaluerevision"),
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="command_receipts",
                        to="registration.registrationprofileextensionvaluecontrol",
                    ),
                ),
            ],
            options={"ordering": ("registration_id", "result_sequence", "id")},
        ),
        migrations.AddIndex(
            model_name="registrationprofileextensionvaluecontrol",
            index=models.Index(
                fields=["organization_id", "edition_id", "registration"],
                name="reg_prof_val_ctrl_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationprofileextensionvaluecontrol",
            constraint=models.UniqueConstraint(
                fields=("registration", "field_key"),
                name="reg_profile_value_control_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationprofileextensionvaluecontrol",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(current_sequence=0, latest_revision__isnull=True)
                    | models.Q(
                        current_sequence__gt=0,
                        latest_revision__isnull=False,
                    )
                ),
                name="reg_profile_value_control_pointer_complete",
            ),
        ),
        migrations.AddIndex(
            model_name="registrationprofileextensionvaluecommandreceipt",
            index=models.Index(
                fields=["organization_id", "edition_id", "registration"],
                name="reg_prof_val_rcpt_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationprofileextensionvaluecommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("actor", "registration", "retry_key"),
                name="reg_profile_value_retry_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationprofileextensionvaluecommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("control", "result_sequence"),
                name="reg_profile_value_receipt_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationprofileextensionvaluecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(result_sequence=models.F("expected_sequence") + 1),
                name="reg_profile_value_receipt_sequence_exact",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationprofileextensionvaluecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    source_channel__regex="^[a-z][a-z0-9_-]{0,31}$"
                ),
                name="reg_profile_value_receipt_source_valid",
            ),
        ),
        migrations.RunSQL(FORWARD_BACKFILL_SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name="registrationprofileextensionvaluerevision",
            name="source_channel",
            field=models.CharField(
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_profile_extension_value_source",
                        message="Use one registered source channel.",
                        regex="^[a-z][a-z0-9_-]{0,31}$",
                    )
                ],
            ),
        ),
        migrations.RunSQL(FORWARD_GUARD_SQL, reverse_sql=REVERSE_GUARD_SQL),
    ]
