# Generated by Django 5.2.14 on 2026-05-17 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=160)),
                ('panel_title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'project_name', 'panel_title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_unlocked', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('fursuit_name', models.CharField(blank=True, max_length=120)),
                ('telegram', models.CharField(blank=True, max_length=120)),
                ('discord', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Board', 'Board'), ('Event Manager', 'Event Manager'), ('Security', 'Security'), ('Fursuit Support', 'Fursuit Support'), ('Themeing', 'Themeing'), ('Host', 'Host'), ('Volunteer', 'Volunteer'), ('Registered User', 'Registered User')], max_length=64)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.accessgrant')),
            ],
            options={
                'ordering': ['grant__email', 'role'],
                'constraints': [models.UniqueConstraint(fields=('grant', 'role'), name='unique_role_per_access_grant')],
            },
        ),
    ]
