# Generated by Django 5.2.14 on 2026-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fursuit_picture',
            field=models.ImageField(blank=True, upload_to='profiles/fursuit-pictures/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profiles/profile-pictures/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_contact_handles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_fursuit_picture',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_profile_publicly',
            field=models.BooleanField(default=False),
        ),
    ]
