# Generated by Django 5.2.14 on 2026-05-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_fursuit_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
