# Generated by Django 5.2.14 on 2026-05-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accessgrantauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgrant',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accessgrantauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('profile_locked', 'Profile locked'), ('profile_unlocked', 'Profile unlocked'), ('updated', 'Updated')], max_length=32),
        ),
    ]
