# Generated by Django 5.2.14 on 2026-05-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_contact_and_convention_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('he/him', 'he/him'), ('she/her', 'she/her'), ('they/them', 'they/them'), ('he/they', 'he/they'), ('she/they', 'she/they'), ('any pronouns', 'any pronouns'), ('ask me', 'ask me')], max_length=40),
        ),
    ]
