# Generated by Django 5.2.14 on 2026-05-21 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_pronouns'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTileColorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('attendee_type', 'Attendee type'), ('convention_role', 'Volunteer or convention role')], max_length=32)),
                ('target_value', models.CharField(max_length=80)),
                ('background_color', models.CharField(default='#f4f7fb', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a hex color like #f0f7ff.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('text_color', models.CharField(default='#1f2937', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a hex color like #f0f7ff.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('priority', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'target_type', 'target_value'],
                'constraints': [models.UniqueConstraint(fields=('target_type', 'target_value'), name='unique_user_tile_color_target')],
            },
        ),
    ]
