# Generated by Django 5.2.14 on 2026-05-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_tile_color_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconventionprofile',
            name='volunteer_type',
            field=models.CharField(choices=[('None', 'None'), ('Volunteer', 'Volunteer'), ('Deputy', 'Deputy'), ('Lead', 'Lead'), ('Board Member', 'Board Member')], default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='usertilecolorrule',
            name='target_type',
            field=models.CharField(choices=[('attendee_type', 'Attendee type'), ('volunteer_type', 'Volunteer type')], max_length=32),
        ),
    ]
