# Generated by Django 5.2.14 on 2026-05-21 19:59

from django.db import migrations, models


def migrate_existing_tile_rule_area(apps, schema_editor):
    UserTileColorRule = apps.get_model("accounts", "UserTileColorRule")
    UserTileColorRule.objects.filter(target_type="volunteer_type").update(
        applies_to="interior"
    )
    for rule in UserTileColorRule.objects.filter(target_type="attendee_type"):
        rule.applies_to = "edge"
        rule.background_color = rule.text_color
        rule.save(update_fields=["applies_to", "background_color"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_volunteer_type_tile_layers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertilecolorrule',
            options={'ordering': ['-priority', 'target_type', 'target_value', 'applies_to']},
        ),
        migrations.RemoveConstraint(
            model_name='usertilecolorrule',
            name='unique_user_tile_color_target',
        ),
        migrations.AddField(
            model_name='usertilecolorrule',
            name='applies_to',
            field=models.CharField(choices=[('edge', 'Tile edge'), ('interior', 'Tile interior')], default='interior', max_length=24),
        ),
        migrations.RunPython(
            migrate_existing_tile_rule_area,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='usertilecolorrule',
            constraint=models.UniqueConstraint(fields=('target_type', 'target_value', 'applies_to'), name='unique_user_tile_color_target'),
        ),
    ]
