# Generated by Django 5.2.14 on 2026-05-23 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from maru.accounts.access_config import (
    DEFAULT_BENEFITS,
    DEFAULT_LABELS,
    DEFAULT_ROLE_PRESETS,
    DEFAULT_STATUS_BENEFIT_GRANTS,
)
from maru.domain import FursuiterStatus


def seed_default_access_configuration(apps, schema_editor):
    RoleDefinition = apps.get_model("accounts", "RoleDefinition")
    AccessBenefit = apps.get_model("accounts", "AccessBenefit")
    StatusBenefitGrant = apps.get_model("accounts", "StatusBenefitGrant")
    LabelOverride = apps.get_model("accounts", "LabelOverride")

    for preset in DEFAULT_ROLE_PRESETS:
        RoleDefinition.objects.update_or_create(
            project=None,
            key=preset["key"],
            defaults={
                "active": True,
                "description": preset["description"],
                "name": preset["name"],
                "permissions": list(preset["permissions"]),
                "system_default": True,
            },
        )

    benefit_by_key = {}
    for benefit in DEFAULT_BENEFITS:
        benefit_obj, _ = AccessBenefit.objects.update_or_create(
            project=None,
            key=benefit["key"],
            defaults={
                "active": True,
                "description": benefit["description"],
                "label": benefit["label"],
                "target": benefit["target"],
            },
        )
        benefit_by_key[benefit_obj.key] = benefit_obj

    for ticket_level, benefit_key in DEFAULT_STATUS_BENEFIT_GRANTS:
        StatusBenefitGrant.objects.get_or_create(
            project=None,
            status_type="ticket_level",
            status_value=ticket_level,
            benefit=benefit_by_key[benefit_key],
        )
    StatusBenefitGrant.objects.get_or_create(
        project=None,
        status_type="fursuiter_status",
        status_value=FursuiterStatus.APPROVED.value,
        benefit=benefit_by_key["fursuit-lounge"],
    )

    for key, label in DEFAULT_LABELS.items():
        LabelOverride.objects.update_or_create(
            project=None,
            key=key.replace(".", "-").replace("_", "-"),
            defaults={"label": label},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_tile_color_rule_area'),
        ('projects', '0016_alter_exportaccesslog_export_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userconventionprofile',
            name='fursuit_species',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userconventionprofile',
            name='fursuiter_status',
            field=models.CharField(choices=[('not_requested', 'not_requested'), ('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='not_requested', max_length=40),
        ),
        migrations.AddField(
            model_name='userconventionprofile',
            name='ticket_level_selected',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Sponsor', 'Sponsor'), ('Super Sponsor', 'Super Sponsor'), ('Infinity', 'Infinity')], default='Pending', max_length=40),
        ),
        migrations.AddField(
            model_name='userconventionprofile',
            name='ticket_level_verified',
            field=models.CharField(blank=True, choices=[('', 'Not verified'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Sponsor', 'Sponsor'), ('Super Sponsor', 'Super Sponsor'), ('Infinity', 'Infinity')], max_length=40),
        ),
        migrations.CreateModel(
            name='AccessBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('target', models.CharField(choices=[('space_access', 'space_access'), ('check_in', 'check_in'), ('export', 'export')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='accounts.accessbenefit')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_benefits', to='projects.project')),
            ],
            options={
                'ordering': ['project__opens_at', 'label'],
            },
        ),
        migrations.CreateModel(
            name='AccessConfigurationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_key', models.CharField(blank=True, max_length=160)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_configuration_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_configuration_audit_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabelOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('label', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_overrides', to='projects.project')),
            ],
            options={
                'ordering': ['project__opens_at', 'key'],
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('system_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='accounts.roledefinition')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_definitions', to='projects.project')),
            ],
            options={
                'ordering': ['project__opens_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
                ('role_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.roledefinition')),
            ],
            options={
                'ordering': ['project__opens_at', 'role_definition__name', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='StatusBenefitGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('ticket_level', 'Ticket level'), ('fursuiter_status', 'Fursuiter status')], max_length=40)),
                ('status_value', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_grants', to='accounts.accessbenefit')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_benefit_grants', to='projects.project')),
            ],
            options={
                'ordering': ['project__opens_at', 'status_type', 'status_value'],
            },
        ),
        migrations.AddConstraint(
            model_name='accessbenefit',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'key'), name='unique_project_access_benefit_key'),
        ),
        migrations.AddConstraint(
            model_name='accessbenefit',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('key',), name='unique_global_access_benefit_key'),
        ),
        migrations.AddConstraint(
            model_name='labeloverride',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'key'), name='unique_project_label_override_key'),
        ),
        migrations.AddConstraint(
            model_name='labeloverride',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('key',), name='unique_global_label_override_key'),
        ),
        migrations.AddConstraint(
            model_name='roledefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'key'), name='unique_project_role_definition_key'),
        ),
        migrations.AddConstraint(
            model_name='roledefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('key',), name='unique_global_role_definition_key'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'project', 'role_definition'), name='unique_project_role_assignment'),
        ),
        migrations.AddConstraint(
            model_name='statusbenefitgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'status_type', 'status_value', 'benefit'), name='unique_project_status_benefit_grant'),
        ),
        migrations.AddConstraint(
            model_name='statusbenefitgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('status_type', 'status_value', 'benefit'), name='unique_global_status_benefit_grant'),
        ),
        migrations.RunPython(
            seed_default_access_configuration,
            migrations.RunPython.noop,
        ),
    ]
