# Generated by Django 5.2.14 on 2026-06-07 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userconventionprofile_fursuit_species_and_more'),
        ('projects', '0017_projectarchivesnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertilecolorrule',
            options={'ordering': ['project__opens_at', '-priority', 'target_type', 'target_value', 'applies_to']},
        ),
        migrations.RemoveConstraint(
            model_name='usertilecolorrule',
            name='unique_user_tile_color_target',
        ),
        migrations.AddField(
            model_name='usertilecolorrule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tile_color_rules', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='usertilecolorrule',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'target_type', 'target_value', 'applies_to'), name='unique_project_user_tile_color_target'),
        ),
        migrations.AddConstraint(
            model_name='usertilecolorrule',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('target_type', 'target_value', 'applies_to'), name='unique_global_user_tile_color_target'),
        ),
    ]
