# Generated by Django 5.2.14 on 2026-06-29 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_usertilecolorrule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='accounts.volunteergroup')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Lead', 'Lead'), ('Deputy', 'Deputy'), ('Volunteer', 'Volunteer')], default='Volunteer', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.volunteergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group__title', 'role', 'user__email'],
            },
        ),
        migrations.AddField(
            model_name='volunteergroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='volunteer_groups', through='accounts.VolunteerMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='volunteermembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_volunteer_membership'),
        ),
    ]
