# Generated by Django 5.2.14 on 2026-06-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_volunteergroup_volunteermembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermembership',
            name='custom_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='volunteermembership',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
    ]
