# Generated by Django 5.2.14 on 2026-05-17 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('timezone', models.CharField(max_length=64)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['opens_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='projects.project')),
            ],
            options={
                'ordering': ['project__opens_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='projects.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_combinations', to='projects.hotel')),
                ('rooms', models.ManyToManyField(blank=True, related_name='combinations', to='projects.room')),
            ],
            options={
                'ordering': ['hotel__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120)),
                ('kind', models.CharField(choices=[('event_submission', 'event_submission'), ('volunteer_registration', 'volunteer_registration'), ('dj_application', 'dj_application'), ('dance_competition', 'dance_competition'), ('generic_application', 'generic_application')], max_length=64)),
                ('accepts_reopen_requests', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='projects.project')),
            ],
            options={
                'ordering': ['project__opens_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=240)),
                ('field_type', models.CharField(max_length=80)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='projects.subproject')),
            ],
            options={
                'ordering': ['subproject__name', 'position', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_hotel_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='unique_room_name_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='roomcombination',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='unique_room_combination_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='subproject',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='unique_subproject_slug_per_project'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('subproject', 'label'), name='unique_form_label_per_subproject'),
        ),
    ]
