# Generated by Django 5.2.14 on 2026-05-17 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_application_applicationversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timetable_round',
            field=models.CharField(choices=[('private_placement', 'private_placement'), ('host_negotiation', 'host_negotiation'), ('public', 'public')], default='private_placement', max_length=64),
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel', to='projects.application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='projects.project')),
            ],
            options={
                'ordering': ['project__opens_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TimetablePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('panels', 'panels'), ('volunteer_shifts', 'volunteer_shifts'), ('signage', 'signage')], default='panels', max_length=64)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='projects.panel')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='projects.room')),
                ('room_combination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='projects.roomcombination')),
            ],
            options={
                'ordering': ['starts_at', 'panel__title'],
            },
        ),
    ]
