# Generated by Django 5.2.14 on 2026-05-17 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_timetable_round_panel_timetableplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_shifts', to='projects.project')),
            ],
            options={
                'ordering': ['project__opens_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerShiftPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('panels', 'panels'), ('volunteer_shifts', 'volunteer_shifts'), ('signage', 'signage')], default='volunteer_shifts', max_length=64)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_shift_placements', to='projects.room')),
                ('room_combination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_shift_placements', to='projects.roomcombination')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='projects.volunteershift')),
            ],
            options={
                'ordering': ['starts_at', 'shift__title'],
            },
        ),
    ]
