# Generated by Django 5.2.14 on 2026-05-18 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_volunteershift_volunteershiftplacement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteershift',
            name='needed_volunteers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='VolunteerShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_volunteer_shift_assignments', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.volunteershift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_shift_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shift__project__opens_at', 'shift__title', 'user__email'],
                'constraints': [models.UniqueConstraint(fields=('shift', 'user'), name='unique_volunteer_assignment_per_shift')],
            },
        ),
    ]
