# Generated by Django 5.2.14 on 2026-05-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_volunteershift_needed_volunteers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteershift',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteershiftassignment',
            name='status',
            field=models.CharField(choices=[('claimed', 'claimed'), ('confirmed', 'confirmed'), ('removed', 'removed')], default='claimed', max_length=32),
        ),
    ]
