# Generated by Django 5.2.14 on 2026-05-18 18:14

import django.db.models.deletion
from django.db import migrations, models

import maru.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_volunteershift_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('token', models.CharField(default=maru.projects.models.generate_export_token, max_length=96, unique=True)),
                ('export_type', models.CharField(choices=[('public_timetable', 'public_timetable'), ('volunteer_shifts', 'volunteer_shifts')], max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_tokens', to='projects.project')),
            ],
            options={
                'ordering': ['project__opens_at', 'name'],
            },
        ),
    ]
