# Generated by Django 5.2.14 on 2026-05-18 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_exporttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttoken',
            name='export_type',
            field=models.CharField(choices=[('public_timetable', 'public_timetable'), ('volunteer_shifts', 'volunteer_shifts'), ('signage_reminders', 'signage_reminders')], max_length=64),
        ),
        migrations.CreateModel(
            name='SignageReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('priority', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signage_reminders', to='projects.project')),
            ],
            options={
                'ordering': ['-priority', 'starts_at', 'title'],
            },
        ),
    ]
