# Generated by Django 5.2.14 on 2026-05-18 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_exporttoken_export_type_signagereminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('public_timetable', 'public_timetable'), ('volunteer_shifts', 'volunteer_shifts'), ('signage_reminders', 'signage_reminders')], max_length=64)),
                ('token_hash', models.CharField(max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('status_code', models.PositiveSmallIntegerField(default=404)),
                ('remote_address', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='projects.exporttoken')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_access_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
