# Generated by Django 5.2.14 on 2026-05-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_exportaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile_contact_exports_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='profile_exports_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exportaccesslog',
            name='export_type',
            field=models.CharField(choices=[('public_timetable', 'public_timetable'), ('public_profiles', 'public_profiles'), ('volunteer_shifts', 'volunteer_shifts'), ('signage_reminders', 'signage_reminders')], max_length=64),
        ),
        migrations.AlterField(
            model_name='exporttoken',
            name='export_type',
            field=models.CharField(choices=[('public_timetable', 'public_timetable'), ('public_profiles', 'public_profiles'), ('volunteer_shifts', 'volunteer_shifts'), ('signage_reminders', 'signage_reminders')], max_length=64),
        ),
    ]
