# Generated by Django 5.2.14 on 2026-05-18 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_profile_contact_exports_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='group_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='recurrence_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('requires_order', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_groups', to='projects.project')),
            ],
            options={
                'ordering': ['project__opens_at', 'name'],
            },
        ),
        migrations.AddField(
            model_name='panel',
            name='event_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='projects.eventgroup'),
        ),
        migrations.AddConstraint(
            model_name='eventgroup',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='unique_event_group_slug_per_project'),
        ),
    ]
