# Generated by Django 5.2.14 on 2026-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_panel_group_order_panel_recurrence_label_eventgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='event_header_image',
            field=models.ImageField(blank=True, upload_to='events/header-images/'),
        ),
    ]
