# Generated by Django 5.2.14 on 2026-05-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_application_event_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRoomCombinationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(blank=True, max_length=160)),
                ('blocked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_combination_settings', to='projects.project')),
                ('room_combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_settings', to='projects.roomcombination')),
            ],
            options={
                'ordering': ['room_combination__hotel__name', 'room_combination__name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRoomCombinationAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='projects.projectroomcombinationsetting')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRoomSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(blank=True, max_length=160)),
                ('blocked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_settings', to='projects.project')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_settings', to='projects.room')),
            ],
            options={
                'ordering': ['room__hotel__name', 'room__name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='projects.projectroomsetting')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_label', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='hotels/floor-plans/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='projects.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'floor_label'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'floor_label'), name='unique_floor_plan_label_per_hotel')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectroomcombinationsetting',
            constraint=models.UniqueConstraint(fields=('project', 'room_combination'), name='unique_room_combination_setting_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectroomsetting',
            constraint=models.UniqueConstraint(fields=('project', 'room'), name='unique_room_setting_per_project'),
        ),
    ]
