# Generated by Django 5.2.14 on 2026-05-21 18:09

from django.db import migrations, models


def copy_hotel_project_assignments(apps, schema_editor):
    Hotel = apps.get_model("projects", "Hotel")
    Project = apps.get_model("projects", "Project")
    project_hotels = Project._meta.get_field("hotels").remote_field.through
    for hotel in Hotel.objects.exclude(project_id=None):
        project_hotels.objects.get_or_create(
            project_id=hotel.project_id,
            hotel_id=hotel.id,
        )


def restore_hotel_project_assignments(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.prefetch_related("hotels"):
        for hotel in project.hotels.all():
            if hotel.project_id is None:
                hotel.project_id = project.id
                hotel.save(update_fields=["project"])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectroomcombinationsetting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='hotel',
            name='unique_hotel_name_per_project',
        ),
        migrations.AddField(
            model_name='project',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.hotel'),
        ),
        migrations.RunPython(
            copy_hotel_project_assignments,
            restore_hotel_project_assignments,
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='project',
        ),
    ]
