# Generated by Django 5.2.14 on 2026-05-22 19:43

import django.db.models.deletion
from django.db import migrations, models


def mark_event_forms_as_timetable_sources(apps, schema_editor):
    Subproject = apps.get_model("projects", "Subproject")
    Subproject.objects.filter(kind="event_submission").update(
        is_timetable_source=True
    )
    project_ids_with_source = set(
        Subproject.objects.filter(is_timetable_source=True).values_list(
            "project_id",
            flat=True,
        )
    )
    for project_id in (
        Subproject.objects.exclude(project_id__in=project_ids_with_source)
        .order_by("project_id", "name")
        .values_list("project_id", flat=True)
        .distinct()
    ):
        first_form = (
            Subproject.objects.filter(project_id=project_id).order_by("name").first()
        )
        if first_form:
            first_form.is_timetable_source = True
            first_form.save(update_fields=["is_timetable_source"])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_reusable_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='form_status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('closed', 'closed')], default='published', max_length=32),
        ),
        migrations.AddField(
            model_name='subproject',
            name='inherited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inherited_forms', to='projects.subproject'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='is_timetable_source',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_event_forms_as_timetable_sources,
            migrations.RunPython.noop,
        ),
    ]
