# Generated by Django 5.2.14 on 2026-05-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_managed_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportaccesslog',
            name='export_type',
            field=models.CharField(choices=[('public_timetable', 'public_timetable'), ('public_profiles', 'public_profiles'), ('volunteer_shifts', 'volunteer_shifts'), ('signage_reminders', 'signage_reminders'), ('role_status', 'role_status')], max_length=64),
        ),
        migrations.AlterField(
            model_name='exporttoken',
            name='export_type',
            field=models.CharField(choices=[('public_timetable', 'public_timetable'), ('public_profiles', 'public_profiles'), ('volunteer_shifts', 'volunteer_shifts'), ('signage_reminders', 'signage_reminders'), ('role_status', 'role_status')], max_length=64),
        ),
    ]
