# Generated by Django 5.2.14 on 2026-06-07 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_exportaccesslog_export_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArchiveSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_snapshot', to='projects.project')),
            ],
            options={
                'ordering': ['-closed_at', 'project__name'],
            },
        ),
    ]
