# Generated by Django 5.2.14 on 2026-06-07 15:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectarchivesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('grid_interval_minutes', models.PositiveSmallIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_days', to='projects.project')),
            ],
            options={
                'ordering': ['starts_at', 'service_date'],
                'constraints': [models.UniqueConstraint(fields=('project', 'service_date'), name='unique_timetable_day_per_project')],
            },
        ),
        migrations.CreateModel(
            name='TimetableLayerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('panels', 'panels'), ('volunteer_shifts', 'volunteer_shifts'), ('signage', 'signage')], max_length=64)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('visible', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('opacity', models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_layer_settings', to='projects.project')),
            ],
            options={
                'ordering': ['position', 'layer'],
                'constraints': [models.UniqueConstraint(fields=('project', 'layer'), name='unique_timetable_layer_per_project')],
            },
        ),
    ]
