"""Top-level URL configuration."""

from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.urls.resolvers import URLPattern, URLResolver
from django.views.decorators.cache import never_cache

from maru.accreditation.api import (
    MyCredentialListView,
    OfflineCheckInIngestView,
    StaffCredentialIssueView,
    StaffCredentialRevokeView,
    StaffOfflineConflictListView,
    StaffOfflineManifestView,
)
from maru.audit.api import AuditEventListView
from maru.authorization.api import (
    EditionAccessAssignmentView,
    EditionAccessPreviewView,
    EditionAccessWorkspaceView,
)
from maru.authorization.page_access_views import page_access_workspace
from maru.communications.api import (
    MyNotificationListView,
    MyNotificationPreferenceView,
    MyNotificationReadView,
    StaffDeliveryFailureListView,
)
from maru.core.api_documentation import (
    PlatformApiRedocView,
    PlatformApiSchemaView,
    PlatformApiSwaggerView,
)
from maru.core.views import (
    administration_index,
    administration_workspace,
    baseline_administration_home,
    baseline_clear_event_edition,
    baseline_convention_series_record,
    baseline_create_convention_series,
    baseline_create_event_edition,
    baseline_create_organization,
    baseline_delete_organization,
    baseline_event_edition_record,
    baseline_organization_record,
    baseline_select_event_edition,
    build_info,
    liveness,
    my_maru_home,
    platform_home,
    readiness,
    removed_administration_route,
    update_navigation_pin,
)
from maru.events.admin_context import change_admin_edition_context
from maru.events.api import (
    EditionAutocompleteView,
    EditionBasicDetailView,
    EditionBulkTransitionView,
    EditionClosureManifestCreateView,
    EditionClosureReadinessView,
    EditionListView,
    EditionReadinessGateReviewView,
    EditionTransitionView,
)
from maru.identity.api import (
    CsrfTokenView,
    MyRestrictionAppealView,
    MyRestrictionListView,
    MySecurityHistoryView,
    MySessionListView,
    MySessionRevokeView,
    MyStepUpView,
    PublicAccountBootstrapView,
    PublicRecoveryCompleteView,
    PublicRecoveryRequestView,
    PublicSessionView,
    PublicVerifyEmailView,
    StaffRestrictionAppealDecisionView,
    StaffRestrictionListCreateView,
    StaffRestrictionRevokeView,
)
from maru.identity.forms import EmailOrHandleAuthenticationForm
from maru.identity.invitation_api import (
    PlatformAccountInventoryView,
    PlatformAccountInvitationCreateView,
    PlatformAccountInvitationDetailView,
    PlatformAccountInvitationReissueView,
    PlatformAccountInvitationRevokeView,
    PublicAccountInvitationAcceptanceView,
)
from maru.identity.invitation_views import (
    accept_platform_account_invitation_view,
    platform_account_inventory,
    platform_account_invitation_detail,
    platform_account_invite,
    reissue_platform_account_invitation_view,
    resolve_platform_identity_delivery_as_delivered_view,
    resolve_platform_identity_delivery_for_retry_view,
    revoke_platform_account_invitation_view,
)
from maru.identity.step_up_views import account_step_up
from maru.identity.views import recover_account, verify_email
from maru.organizations.api import (
    ConventionSeriesDetailView,
    ConventionSeriesListView,
)
from maru.organizations.views import (
    activate_organization_representation,
    invite_organization_controller,
    my_representation_invitations,
    organization_representation,
    provision_organization_representation,
    respond_organization_controller_invitation,
)
from maru.participation.api import (
    EditionParticipationDetailView,
    EditionParticipationListView,
    MyContextView,
    MyParticipationHistoryView,
)
from maru.privacyops.api import (
    MyPostEditionCorrectionListCreateView,
    MySubjectExportView,
    MySubjectRightsRequestListCreateView,
    StaffPostEditionCorrectionDecisionView,
    StaffRegistrationProfileMinimizeView,
    StaffSubjectRightsRequestListView,
    StaffSubjectRightsRequestTransitionView,
)
from maru.registration.api import (
    HeadlessRegistrationSubmissionView,
    MyAdmissionTierReplacementView,
    MyAttendeeProfileView,
    MyFursuitPhotoUploadView,
    MyProfilePhotoUploadView,
    MyRegistrationDemoPaymentView,
    MyRegistrationPaymentIntentStatusView,
    MyRegistrationPaymentIntentView,
    MyRegistrationProfileExtensionsView,
    MyRegistrationReceiptListView,
    MyRegistrationView,
    PaymentProviderWebhookView,
    PublicAttendeeListView,
    PublicGuardianConsentView,
    PublicRegistrationDefinitionView,
    PublicRegistrationEditionListView,
    RegistrationCapacityAdjustmentView,
    RegistrationCommerceWorkspaceView,
    RegistrationConfigurationActivateView,
    RegistrationConfigurationDraftView,
    RegistrationConfigurationWorkspaceView,
    RegistrationReconciliationView,
    RegistrationTemplatePublishView,
    RegistrationWaitlistBatchOfferView,
    SelfProfileSuggestionView,
    StaffActionListView,
    StaffAttendeeReportView,
    StaffBadgeExportView,
    StaffFinancialOperationApproveView,
    StaffFinancialOperationListCreateView,
    StaffPaymentExceptionListView,
    StaffPaymentExceptionResolveView,
    StaffProfileMediaReviewDecisionView,
    StaffProfileMediaReviewListView,
    StaffRegistrationCheckInView,
    StaffRegistrationDetailView,
    StaffRegistrationListView,
    StaffRegistrationPaymentDeadlineView,
    StaffRegistrationProfileExtensionsView,
    StaffRegistrationWaivePaymentView,
    StaffSettlementListCreateView,
)
from maru.registration.public_views import (
    confirm_local_demo_payment,
    edit_attendee_profile,
    guardian_consent,
    protected_fursuit_photo,
    protected_profile_photo,
    public_attendee_directory,
    public_registration_form,
    public_registration_index,
    public_registration_profile,
    staff_assisted_registration,
)
from maru.registration.setup_definition_api import (
    RegistrationConfigurationCommandView,
    RegistrationProfileExtensionFieldCollectionView,
    RegistrationProfileExtensionFieldCommandView,
    RegistrationSetupStartView,
)
from maru.registration.setup_definition_views import (
    create_registration_setup_product,
    create_registration_setup_question,
    move_registration_setup_product,
    move_registration_setup_profile_field,
    move_registration_setup_question,
    registration_setup_minor_policy_dispatch,
    registration_setup_product_create,
    registration_setup_profile_field_create,
    registration_setup_profile_field_detail,
    registration_setup_profile_fields_dispatch,
    registration_setup_question_create,
    remove_registration_setup_minor_policy,
    remove_registration_setup_product,
    remove_registration_setup_question,
    retire_registration_setup_profile_field,
    update_registration_setup_product,
    update_registration_setup_profile_field,
    update_registration_setup_question,
)
from maru.registration.setup_views import (
    create_registration_setup_section,
    move_registration_setup_section,
    registration_setup_configuration,
    registration_setup_section_create,
    registration_setup_start,
    registration_setup_workspace,
    remove_registration_setup_section,
    start_registration_setup_view,
    update_registration_setup_section,
)
from maru.workforce.api import (
    MyOnboardingDocumentListView,
    MyOnboardingDocumentUploadView,
    MyVolunteerApplicationCreateView,
    PublicVolunteerOpportunityListView,
    WorkforceAssignmentApproveView,
    WorkforceAssignmentEndView,
    WorkforceAssignmentProposalView,
    WorkforceAssignmentRejectView,
    WorkforceDepartmentCollectionView,
    WorkforceDepartmentDetailView,
    WorkforceDepartmentRetireView,
    WorkforceMyAvailabilityView,
    WorkforceMyAvailabilityWithdrawView,
    WorkforceOrganizerAvailabilityView,
    WorkforcePositionCloseView,
    WorkforcePositionCollectionView,
    WorkforcePositionDetailView,
    WorkforcePositionOpportunityView,
    WorkforceStructureTemplateApplicationView,
    WorkforceStructureView,
)
from maru.workforce.views import (
    apply_for_opportunity,
    apply_organization_structure_template,
    approve_organization_workforce_assignment,
    close_organization_structure_position,
    create_organization_structure_department,
    create_organization_structure_position,
    delete_organization_structure_department,
    download_onboarding_document,
    end_organization_workforce_assignment,
    my_onboarding_documents,
    my_workforce_assignments,
    my_workforce_availability,
    organization_structure,
    organization_structure_department,
    organization_structure_department_create,
    organization_structure_position,
    organization_structure_position_create,
    organization_structure_positions,
    organization_structure_template_application,
    organization_workforce_assignment,
    organization_workforce_assignment_proposal,
    organization_workforce_assignments,
    organization_workforce_availability,
    propose_organization_workforce_assignment,
    reject_organization_workforce_assignment,
    retire_organization_structure_department,
    save_my_workforce_availability,
    update_organization_structure_department,
    update_organization_structure_position,
    update_organization_structure_position_opportunity,
    upload_onboarding_document_view,
    volunteer_opportunities,
    withdraw_my_workforce_availability,
)

urlpatterns: list[URLPattern | URLResolver] = [
    path("", include("maru.charities.urls")),
    path("", include("maru.applications.urls")),
    path("", include("maru.registration.commerce_urls")),
    path("", include("maru.registration.profile_extension_urls")),
    path("", include("maru.catalog.urls")),
    path("", include("maru.venues.urls")),
    path("", include("maru.logistics.urls")),
    path("", platform_home, name="platform-home"),
    path("my/", my_maru_home, name="my-maru-home"),
    path(
        "my/workforce/",
        my_workforce_assignments,
        name="my-workforce-assignments",
    ),
    path(
        (
            "my/workforce/<slug:organization_slug>/<slug:series_slug>/"
            "<slug:edition_slug>/availability/"
        ),
        my_workforce_availability,
        name="my-workforce-availability",
    ),
    path(
        (
            "my/workforce/<slug:organization_slug>/<slug:series_slug>/"
            "<slug:edition_slug>/availability/save/"
        ),
        save_my_workforce_availability,
        name="save-my-workforce-availability",
    ),
    path(
        (
            "my/workforce/<slug:organization_slug>/<slug:series_slug>/"
            "<slug:edition_slug>/availability/withdraw/"
        ),
        withdraw_my_workforce_availability,
        name="withdraw-my-workforce-availability",
    ),
    path(
        "my/navigation/pins/",
        update_navigation_pin,
        name="update-navigation-pin",
    ),
    path(
        "register/",
        public_registration_index,
        name="public-registration-index",
    ),
    path(
        "register/<uuid:edition_id>/",
        public_registration_form,
        name="public-registration-form",
    ),
    path(
        "register/<uuid:edition_id>/profile/",
        public_registration_profile,
        name="public-registration-profile",
    ),
    path(
        "register/<uuid:edition_id>/profile/demo-payment/",
        confirm_local_demo_payment,
        name="public-registration-demo-payment",
    ),
    path(
        "admin/registration-assist/<uuid:edition_id>/",
        staff_assisted_registration,
        name="management-assisted-registration",
    ),
    path(
        "volunteer/<uuid:edition_id>/",
        volunteer_opportunities,
        name="workforce-opportunities",
    ),
    path(
        "volunteer/<uuid:edition_id>/<uuid:opportunity_id>/apply/",
        apply_for_opportunity,
        name="workforce-apply",
    ),
    path(
        "volunteer/<uuid:edition_id>/documents/",
        my_onboarding_documents,
        name="workforce-my-documents",
    ),
    path(
        ("volunteer/<uuid:edition_id>/documents/<uuid:document_request_id>/upload/"),
        upload_onboarding_document_view,
        name="workforce-document-upload",
    ),
    path(
        "volunteer/documents/<uuid:document_request_id>/download/",
        download_onboarding_document,
        name="workforce-document-download",
    ),
    path(
        "register/<uuid:edition_id>/profile/edit/",
        edit_attendee_profile,
        name="edit-attendee-profile",
    ),
    path(
        "register/<uuid:edition_id>/attendees/",
        public_attendee_directory,
        name="paid-attendee-directory",
    ),
    path(
        "register/media/profile/<uuid:profile_id>/",
        protected_profile_photo,
        name="protected-profile-photo",
    ),
    path(
        "register/media/fursuit/<uuid:fursuit_id>/",
        protected_fursuit_photo,
        name="protected-fursuit-photo",
    ),
    path(
        "guardian-consent/",
        guardian_consent,
        name="guardian-consent",
    ),
    path(
        "accounts/login/",
        LoginView.as_view(
            template_name="core/login.html",
            authentication_form=EmailOrHandleAuthenticationForm,
            redirect_authenticated_user=True,
        ),
        name="staff-login",
    ),
    path(
        "accounts/invitations/accept/",
        accept_platform_account_invitation_view,
        name="accept-platform-account-invitation",
    ),
    path(
        "accounts/logout/",
        LogoutView.as_view(),
        name="staff-logout",
    ),
    path("accounts/verify-email/", verify_email, name="verify-email"),
    path("accounts/recover-account/", recover_account, name="recover-account"),
    path(
        "admin/context/edition/",
        change_admin_edition_context,
        name="admin-edition-context",
    ),
    path(
        "admin/account/step-up/",
        account_step_up,
        name="account-step-up",
    ),
    path(
        "admin/platform/organizations/",
        baseline_administration_home,
        name="baseline-admin-home",
    ),
    path(
        "admin/platform/accounts/",
        platform_account_inventory,
        name="platform-account-inventory",
    ),
    path(
        "admin/platform/accounts/invite/",
        platform_account_invite,
        name="platform-account-invite",
    ),
    path(
        "admin/platform/accounts/invitations/<uuid:invitation_id>/",
        platform_account_invitation_detail,
        name="platform-account-invitation-detail",
    ),
    path(
        ("admin/platform/accounts/invitations/<uuid:invitation_id>/reissue/"),
        reissue_platform_account_invitation_view,
        name="platform-account-invitation-reissue",
    ),
    path(
        ("admin/platform/accounts/invitations/<uuid:invitation_id>/revoke/"),
        revoke_platform_account_invitation_view,
        name="platform-account-invitation-revoke",
    ),
    path(
        (
            "admin/platform/accounts/invitations/<uuid:invitation_id>/"
            "deliveries/<uuid:delivery_id>/resolve-delivered/"
        ),
        resolve_platform_identity_delivery_as_delivered_view,
        name="platform-identity-delivery-resolve-delivered",
    ),
    path(
        (
            "admin/platform/accounts/invitations/<uuid:invitation_id>/"
            "deliveries/<uuid:delivery_id>/resolve-retry/"
        ),
        resolve_platform_identity_delivery_for_retry_view,
        name="platform-identity-delivery-resolve-retry",
    ),
    path(
        "admin/invitations/",
        my_representation_invitations,
        name="my-representation-invitations",
    ),
    path(
        "admin/platform/organizations/new/",
        baseline_create_organization,
        name="baseline-create-organization",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/representation/",
        organization_representation,
        name="organization-representation",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/"
            "representation/provision/"
        ),
        provision_organization_representation,
        name="provision-organization-representation",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/"
            "representation/invite/"
        ),
        invite_organization_controller,
        name="invite-organization-controller",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/"
            "representation/appointments/<uuid:appointment_id>/respond/"
        ),
        respond_organization_controller_invitation,
        name="respond-organization-controller-invitation",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/"
            "representation/activate/"
        ),
        activate_organization_representation,
        name="activate-organization-representation",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/",
        baseline_organization_record,
        name="baseline-organization-record",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/delete/",
        baseline_delete_organization,
        name="baseline-delete-organization",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/new/",
        baseline_create_convention_series,
        name="baseline-create-convention-series",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "positions/<uuid:position_id>/assignments/new/"
        ),
        organization_workforce_assignment_proposal,
        name="organization-workforce-assignment-proposal",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "positions/<uuid:position_id>/assignments/propose/"
        ),
        propose_organization_workforce_assignment,
        name="propose-organization-workforce-assignment",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "assignments/<uuid:assignment_id>/approve/"
        ),
        approve_organization_workforce_assignment,
        name="approve-organization-workforce-assignment",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "assignments/<uuid:assignment_id>/reject/"
        ),
        reject_organization_workforce_assignment,
        name="reject-organization-workforce-assignment",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "assignments/<uuid:assignment_id>/end/"
        ),
        end_organization_workforce_assignment,
        name="end-organization-workforce-assignment",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "assignments/<uuid:assignment_id>/"
        ),
        organization_workforce_assignment,
        name="organization-workforce-assignment",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/assignments/"
        ),
        organization_workforce_assignments,
        name="organization-workforce-assignments",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/availability/"
        ),
        organization_workforce_availability,
        name="organization-workforce-availability",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/"
        ),
        baseline_convention_series_record,
        name="baseline-convention-series-record",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/new/"
        ),
        baseline_create_event_edition,
        name="baseline-create-event-edition",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/"
        ),
        baseline_event_edition_record,
        name="baseline-event-edition-record",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
        ),
        registration_setup_workspace,
        name="registration-setup",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/new/"
        ),
        registration_setup_start,
        name="registration-setup-start",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/"
        ),
        start_registration_setup_view,
        name="start-registration-setup",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/sections/new/"
        ),
        registration_setup_section_create,
        name="registration-setup-section-create",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/sections/"
        ),
        create_registration_setup_section,
        name="create-registration-setup-section",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/sections/"
            "<uuid:section_id>/update/"
        ),
        update_registration_setup_section,
        name="update-registration-setup-section",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/sections/"
            "<uuid:section_id>/move/"
        ),
        move_registration_setup_section,
        name="move-registration-setup-section",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/sections/"
            "<uuid:section_id>/remove/"
        ),
        remove_registration_setup_section,
        name="remove-registration-setup-section",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/questions/new/"
        ),
        registration_setup_question_create,
        name="registration-setup-question-create",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/questions/"
        ),
        create_registration_setup_question,
        name="create-registration-setup-question",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/questions/"
            "<uuid:question_id>/update/"
        ),
        update_registration_setup_question,
        name="update-registration-setup-question",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/questions/"
            "<uuid:question_id>/move/"
        ),
        move_registration_setup_question,
        name="move-registration-setup-question",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/questions/"
            "<uuid:question_id>/remove/"
        ),
        remove_registration_setup_question,
        name="remove-registration-setup-question",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/products/new/"
        ),
        registration_setup_product_create,
        name="registration-setup-product-create",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/products/"
        ),
        create_registration_setup_product,
        name="create-registration-setup-product",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/products/"
            "<uuid:product_id>/update/"
        ),
        update_registration_setup_product,
        name="update-registration-setup-product",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/products/"
            "<uuid:product_id>/move/"
        ),
        move_registration_setup_product,
        name="move-registration-setup-product",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/products/"
            "<uuid:product_id>/remove/"
        ),
        remove_registration_setup_product,
        name="remove-registration-setup-product",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/minor-policy/"
        ),
        registration_setup_minor_policy_dispatch,
        name="registration-setup-minor-policy",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/minor-policy/remove/"
        ),
        remove_registration_setup_minor_policy,
        name="remove-registration-setup-minor-policy",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "profile-fields/"
        ),
        registration_setup_profile_fields_dispatch,
        name="registration-setup-profile-fields",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "profile-fields/new/"
        ),
        registration_setup_profile_field_create,
        name="registration-setup-profile-field-create",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "profile-fields/<uuid:field_id>/"
        ),
        registration_setup_profile_field_detail,
        name="registration-setup-profile-field-detail",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "profile-fields/<uuid:field_id>/update/"
        ),
        update_registration_setup_profile_field,
        name="update-registration-setup-profile-field",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "profile-fields/<uuid:field_id>/move/"
        ),
        move_registration_setup_profile_field,
        name="move-registration-setup-profile-field",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "profile-fields/<uuid:field_id>/retire/"
        ),
        retire_registration_setup_profile_field,
        name="retire-registration-setup-profile-field",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/registration/"
            "configurations/<uuid:configuration_id>/"
        ),
        registration_setup_configuration,
        name="registration-setup-configuration",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "positions/new/"
        ),
        organization_structure_position_create,
        name="organization-structure-position-create",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "positions/create/"
        ),
        create_organization_structure_position,
        name="create-organization-structure-position",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "positions/<uuid:position_id>/update/"
        ),
        update_organization_structure_position,
        name="update-organization-structure-position",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "positions/<uuid:position_id>/opportunity/"
        ),
        update_organization_structure_position_opportunity,
        name="update-organization-structure-position-opportunity",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "positions/<uuid:position_id>/close/"
        ),
        close_organization_structure_position,
        name="close-organization-structure-position",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "positions/<uuid:position_id>/"
        ),
        organization_structure_position,
        name="organization-structure-position",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "positions/"
        ),
        organization_structure_positions,
        name="organization-structure-positions",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "template-application/"
        ),
        organization_structure_template_application,
        name="organization-structure-template-application",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "template-applications/"
        ),
        apply_organization_structure_template,
        name="apply-organization-structure-template",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "departments/new/"
        ),
        organization_structure_department_create,
        name="organization-structure-department-create",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "departments/"
        ),
        create_organization_structure_department,
        name="create-organization-structure-department",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "departments/<uuid:department_id>/update/"
        ),
        update_organization_structure_department,
        name="update-organization-structure-department",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "departments/<uuid:department_id>/retire/"
        ),
        retire_organization_structure_department,
        name="retire-organization-structure-department",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "departments/<uuid:department_id>/delete/"
        ),
        delete_organization_structure_department,
        name="delete-organization-structure-department",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
            "departments/<uuid:department_id>/"
        ),
        organization_structure_department,
        name="organization-structure-department",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/structure/"
        ),
        organization_structure,
        name="organization-structure",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/select/"
        ),
        baseline_select_event_edition,
        name="baseline-select-event-edition",
    ),
    path(
        (
            "admin/platform/organizations/<slug:organization_slug>/series/"
            "<slug:series_slug>/editions/<slug:edition_slug>/clear/"
        ),
        baseline_clear_event_edition,
        name="baseline-clear-event-edition",
    ),
    path(
        "admin/workspace/",
        administration_workspace,
        name="management-console",
    ),
    path(
        "admin/access/<str:scope_token>/",
        page_access_workspace,
        name="page-access-workspace",
    ),
    path("admin/records/", removed_administration_route),
    # The unified shell admits active scoped non-staff accounts. Route its
    # account controls before AdminSite's staff-only wrapper so logout and
    # password changes remain real operations for every admitted account.
    path("admin/logout/", admin.site.logout, name="administration-logout"),
    path(
        "admin/password_change/",
        admin.site.password_change,
        name="administration-password-change",
    ),
    path(
        "admin/password_change/done/",
        admin.site.password_change_done,
        name="administration-password-change-done",
    ),
    path("admin/", administration_index),
    path("admin/", admin.site.urls),
    path("health/live", liveness, name="health-live"),
    path("health/ready", readiness, name="health-ready"),
    path("api/v1/meta/build", build_info, name="api-build-info"),
    path("api/v1/schema", PlatformApiSchemaView.as_view(), name="api-schema"),
    path(
        "api/v1/docs/",
        never_cache(
            login_required(login_url="staff-login")(
                PlatformApiSwaggerView.as_view(url_name="api-schema")
            )
        ),
        name="api-docs",
    ),
    path(
        "api/v1/redoc/",
        never_cache(
            login_required(login_url="staff-login")(
                PlatformApiRedocView.as_view(url_name="api-schema")
            )
        ),
        name="api-redoc",
    ),
    path("api/v1/public/csrf", CsrfTokenView.as_view(), name="api-public-csrf"),
    path(
        "api/v1/public/editions/<uuid:edition_id>/volunteer-opportunities",
        PublicVolunteerOpportunityListView.as_view(),
        name="api-public-volunteer-opportunity-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/me/profile-extensions"
        ),
        MyRegistrationProfileExtensionsView.as_view(),
        name="api-my-registration-profile-extensions",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/structure"
        ),
        WorkforceStructureView.as_view(),
        name="api-workforce-structure",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/structure/"
            "template-applications"
        ),
        WorkforceStructureTemplateApplicationView.as_view(),
        name="api-workforce-structure-template-applications",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/departments"
        ),
        WorkforceDepartmentCollectionView.as_view(),
        name="api-workforce-departments",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/departments/"
            "<uuid:department_id>/retire"
        ),
        WorkforceDepartmentRetireView.as_view(),
        name="api-workforce-department-retire",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/departments/"
            "<uuid:department_id>"
        ),
        WorkforceDepartmentDetailView.as_view(),
        name="api-workforce-department-detail",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/positions"
        ),
        WorkforcePositionCollectionView.as_view(),
        name="api-workforce-positions",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/positions/"
            "<uuid:position_id>/assignments"
        ),
        WorkforceAssignmentProposalView.as_view(),
        name="api-workforce-position-assignments",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/availability/me"
        ),
        WorkforceMyAvailabilityView.as_view(),
        name="api-workforce-my-availability",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/availability/me/withdraw"
        ),
        WorkforceMyAvailabilityWithdrawView.as_view(),
        name="api-workforce-my-availability-withdraw",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/availability"
        ),
        WorkforceOrganizerAvailabilityView.as_view(),
        name="api-workforce-availability",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/assignments/"
            "<uuid:assignment_id>/approve"
        ),
        WorkforceAssignmentApproveView.as_view(),
        name="api-workforce-assignment-approve",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/assignments/"
            "<uuid:assignment_id>/reject"
        ),
        WorkforceAssignmentRejectView.as_view(),
        name="api-workforce-assignment-reject",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/assignments/"
            "<uuid:assignment_id>/end"
        ),
        WorkforceAssignmentEndView.as_view(),
        name="api-workforce-assignment-end",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/positions/"
            "<uuid:position_id>/opportunity"
        ),
        WorkforcePositionOpportunityView.as_view(),
        name="api-workforce-position-opportunity",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/positions/"
            "<uuid:position_id>/close"
        ),
        WorkforcePositionCloseView.as_view(),
        name="api-workforce-position-close",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/positions/"
            "<uuid:position_id>"
        ),
        WorkforcePositionDetailView.as_view(),
        name="api-workforce-position-detail",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/"
            "<uuid:registration_id>/profile-extensions"
        ),
        StaffRegistrationProfileExtensionsView.as_view(),
        name="api-staff-registration-profile-extensions",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/opportunities/"
            "<uuid:opportunity_id>/applications/me"
        ),
        MyVolunteerApplicationCreateView.as_view(),
        name="api-my-volunteer-application-create",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/documents/me"
        ),
        MyOnboardingDocumentListView.as_view(),
        name="api-my-onboarding-document-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/documents/me/"
            "<uuid:document_request_id>/upload"
        ),
        MyOnboardingDocumentUploadView.as_view(),
        name="api-my-onboarding-document-upload",
    ),
    path(
        "api/v1/platform/accounts",
        PlatformAccountInventoryView.as_view(),
        name="api-platform-account-inventory",
    ),
    path(
        "api/v1/platform/account-invitations",
        PlatformAccountInvitationCreateView.as_view(),
        name="api-platform-account-invitation-create",
    ),
    path(
        "api/v1/platform/account-invitations/<uuid:invitation_id>",
        PlatformAccountInvitationDetailView.as_view(),
        name="api-platform-account-invitation-detail",
    ),
    path(
        ("api/v1/platform/account-invitations/<uuid:invitation_id>/reissue"),
        PlatformAccountInvitationReissueView.as_view(),
        name="api-platform-account-invitation-reissue",
    ),
    path(
        ("api/v1/platform/account-invitations/<uuid:invitation_id>/revoke"),
        PlatformAccountInvitationRevokeView.as_view(),
        name="api-platform-account-invitation-revoke",
    ),
    path(
        "api/v1/public/account-invitations/accept",
        PublicAccountInvitationAcceptanceView.as_view(),
        name="api-public-account-invitation-accept",
    ),
    path(
        "api/v1/public/accounts",
        PublicAccountBootstrapView.as_view(),
        name="api-public-account-bootstrap",
    ),
    path(
        "api/v1/public/accounts/verify-email",
        PublicVerifyEmailView.as_view(),
        name="api-public-account-verify-email",
    ),
    path(
        "api/v1/public/accounts/recovery",
        PublicRecoveryRequestView.as_view(),
        name="api-public-account-recovery-request",
    ),
    path(
        "api/v1/public/accounts/recovery/complete",
        PublicRecoveryCompleteView.as_view(),
        name="api-public-account-recovery-complete",
    ),
    path(
        "api/v1/public/sessions",
        PublicSessionView.as_view(),
        name="api-public-session",
    ),
    path(
        "api/v1/public/editions",
        PublicRegistrationEditionListView.as_view(),
        name="api-public-registration-editions",
    ),
    path(
        "api/v1/public/editions/<uuid:edition_id>/registration",
        PublicRegistrationDefinitionView.as_view(),
        name="api-public-registration-definition",
    ),
    path(
        ("api/v1/public/editions/<uuid:edition_id>/registration/submissions"),
        HeadlessRegistrationSubmissionView.as_view(),
        name="api-headless-registration-submission",
    ),
    path(
        "api/v1/public/editions/<uuid:edition_id>/attendees",
        PublicAttendeeListView.as_view(),
        name="api-public-attendee-list",
    ),
    path(
        "api/v1/public/guardian-consents/accept",
        PublicGuardianConsentView.as_view(),
        name="api-public-guardian-consent",
    ),
    path(
        (
            "api/v1/public/organizations/<uuid:organization_id>/"
            "payments/<slug:provider_code>/webhook"
        ),
        PaymentProviderWebhookView.as_view(),
        name="api-payment-provider-webhook",
    ),
    path(
        ("api/v1/public/editions/<uuid:edition_id>/registration/profile-suggestion"),
        SelfProfileSuggestionView.as_view(),
        name="api-self-profile-suggestion",
    ),
    path("api/v1/me/context", MyContextView.as_view(), name="api-my-context"),
    path(
        "api/v1/me/security-history",
        MySecurityHistoryView.as_view(),
        name="api-my-security-history",
    ),
    path(
        "api/v1/me/notifications",
        MyNotificationListView.as_view(),
        name="api-my-notifications",
    ),
    path(
        "api/v1/me/notifications/<uuid:message_id>/read",
        MyNotificationReadView.as_view(),
        name="api-my-notification-read",
    ),
    path(
        "api/v1/me/notification-preferences/<uuid:organization_id>",
        MyNotificationPreferenceView.as_view(),
        name="api-my-notification-preference",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/accreditation/me/credentials"
        ),
        MyCredentialListView.as_view(),
        name="api-my-credentials",
    ),
    path(
        "api/v1/me/sessions",
        MySessionListView.as_view(),
        name="api-my-sessions",
    ),
    path(
        "api/v1/me/sessions/<uuid:session_id>/revoke",
        MySessionRevokeView.as_view(),
        name="api-my-session-revoke",
    ),
    path(
        "api/v1/me/step-up",
        MyStepUpView.as_view(),
        name="api-my-step-up",
    ),
    path(
        "api/v1/me/restrictions",
        MyRestrictionListView.as_view(),
        name="api-my-restrictions",
    ),
    path(
        "api/v1/me/restrictions/<uuid:restriction_id>/appeals",
        MyRestrictionAppealView.as_view(),
        name="api-my-restriction-appeal",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/restrictions"
        ),
        StaffRestrictionListCreateView.as_view(),
        name="api-staff-restrictions",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/restrictions/"
            "<uuid:restriction_id>/revoke"
        ),
        StaffRestrictionRevokeView.as_view(),
        name="api-staff-restriction-revoke",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/restriction-appeals/"
            "<uuid:appeal_id>/decision"
        ),
        StaffRestrictionAppealDecisionView.as_view(),
        name="api-staff-restriction-appeal-decision",
    ),
    path(
        "api/v1/me/privacy-requests",
        MySubjectRightsRequestListCreateView.as_view(),
        name="api-my-privacy-requests",
    ),
    path(
        "api/v1/me/privacy-export",
        MySubjectExportView.as_view(),
        name="api-my-privacy-export",
    ),
    path(
        "api/v1/me/post-edition-corrections",
        MyPostEditionCorrectionListCreateView.as_view(),
        name="api-my-post-edition-corrections",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/privacy-requests",
        StaffSubjectRightsRequestListView.as_view(),
        name="api-staff-privacy-requests",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/privacy-requests/"
            "<uuid:privacy_request_id>/transition"
        ),
        StaffSubjectRightsRequestTransitionView.as_view(),
        name="api-staff-privacy-request-transition",
    ),
    path(
        "api/v1/me/participation-history",
        MyParticipationHistoryView.as_view(),
        name="api-my-participation-history",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/series",
        ConventionSeriesListView.as_view(),
        name="api-convention-series-list",
    ),
    path(
        ("api/v1/organizations/<uuid:organization_id>/series/<uuid:series_id>"),
        ConventionSeriesDetailView.as_view(),
        name="api-convention-series-detail",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions",
        EditionListView.as_view(),
        name="api-edition-list",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/autocomplete",
        EditionAutocompleteView.as_view(),
        name="api-edition-autocomplete",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/bulk-transition",
        EditionBulkTransitionView.as_view(),
        name="api-edition-bulk-transition",
    ),
    path(
        ("api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>"),
        EditionBasicDetailView.as_view(),
        name="api-edition-basic-detail",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/transition"
        ),
        EditionTransitionView.as_view(),
        name="api-edition-transition",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/closure-readiness"
        ),
        EditionClosureReadinessView.as_view(),
        name="api-edition-closure-readiness",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/closure-gates/<slug:code>"
        ),
        EditionReadinessGateReviewView.as_view(),
        name="api-edition-closure-gate-review",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/closure-manifest"
        ),
        EditionClosureManifestCreateView.as_view(),
        name="api-edition-closure-manifest",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/audit-events",
        AuditEventListView.as_view(),
        name="api-audit-event-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/participations"
        ),
        EditionParticipationListView.as_view(),
        name="api-edition-participation-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/access"
        ),
        EditionAccessWorkspaceView.as_view(),
        name="api-edition-access-workspace",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/access/preview"
        ),
        EditionAccessPreviewView.as_view(),
        name="api-edition-access-preview",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/access/assignments/"
            "<uuid:assignment_id>"
        ),
        EditionAccessAssignmentView.as_view(),
        name="api-edition-access-assignment",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/participations/<uuid:account_id>"
        ),
        EditionParticipationDetailView.as_view(),
        name="api-edition-participation-detail",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/profile"
        ),
        MyAttendeeProfileView.as_view(),
        name="api-my-attendee-profile",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/profile/photo"
        ),
        MyProfilePhotoUploadView.as_view(),
        name="api-my-profile-photo-upload",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/profile/"
            "fursuits/<uuid:fursuit_id>/photo"
        ),
        MyFursuitPhotoUploadView.as_view(),
        name="api-my-fursuit-photo-upload",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/profile-media-reviews"
        ),
        StaffProfileMediaReviewListView.as_view(),
        name="api-registration-profile-media-review-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/"
            "profile-media-reviews/<uuid:media_id>"
        ),
        StaffProfileMediaReviewDecisionView.as_view(),
        name="api-registration-profile-media-review-decision",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/setup"
        ),
        RegistrationSetupStartView.as_view(),
        name="api-registration-setup-start",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/configuration"
        ),
        RegistrationConfigurationWorkspaceView.as_view(),
        name="api-registration-configuration-workspace",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/configuration/drafts"
        ),
        RegistrationConfigurationDraftView.as_view(),
        name="api-registration-configuration-draft",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/configuration/activate"
        ),
        RegistrationConfigurationActivateView.as_view(),
        name="api-registration-configuration-activate",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/configuration/"
            "<uuid:configuration_id>/commands"
        ),
        RegistrationConfigurationCommandView.as_view(),
        name="api-registration-configuration-command",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/profile-extension-fields"
        ),
        RegistrationProfileExtensionFieldCollectionView.as_view(),
        name="api-registration-profile-extension-field-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/profile-extension-fields/"
            "<uuid:field_id>/commands"
        ),
        RegistrationProfileExtensionFieldCommandView.as_view(),
        name="api-registration-profile-extension-field-command",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/templates"
        ),
        RegistrationTemplatePublishView.as_view(),
        name="api-registration-template-publish",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me"
        ),
        MyRegistrationView.as_view(),
        name="api-my-registration",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/"
            "<uuid:registration_id>/tier-replacements"
        ),
        MyAdmissionTierReplacementView.as_view(),
        name="api-my-registration-tier-replacement",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/"
            "<uuid:registration_id>/demo-payment"
        ),
        MyRegistrationDemoPaymentView.as_view(),
        name="api-my-registration-demo-payment",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/"
            "<uuid:registration_id>/payment-intents"
        ),
        MyRegistrationPaymentIntentView.as_view(),
        name="api-my-registration-payment-intent",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/"
            "<uuid:registration_id>/payment-intents/<uuid:intent_id>"
        ),
        MyRegistrationPaymentIntentStatusView.as_view(),
        name="api-my-registration-payment-intent-status",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/"
            "<uuid:registration_id>/receipts"
        ),
        MyRegistrationReceiptListView.as_view(),
        name="api-my-registration-receipts",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations"
        ),
        StaffRegistrationListView.as_view(),
        name="api-staff-registration-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/attendee-report"
        ),
        StaffAttendeeReportView.as_view(),
        name="api-registration-attendee-report",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/badge-export.csv"
        ),
        StaffBadgeExportView.as_view(),
        name="api-registration-badge-export",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/<uuid:registration_id>"
        ),
        StaffRegistrationDetailView.as_view(),
        name="api-staff-registration-detail",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/"
            "<uuid:registration_id>/check-in"
        ),
        StaffRegistrationCheckInView.as_view(),
        name="api-staff-registration-check-in",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/"
            "<uuid:registration_id>/credentials"
        ),
        StaffCredentialIssueView.as_view(),
        name="api-credential-issue",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/credentials/"
            "<uuid:credential_id>/revoke"
        ),
        StaffCredentialRevokeView.as_view(),
        name="api-credential-revoke",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/offline/manifests"
        ),
        StaffOfflineManifestView.as_view(),
        name="api-offline-manifest",
    ),
    path(
        (
            "api/v1/public/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/offline/devices/"
            "<slug:device_code>/check-ins"
        ),
        OfflineCheckInIngestView.as_view(),
        name="api-offline-check-in-ingest",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/offline/conflicts"
        ),
        StaffOfflineConflictListView.as_view(),
        name="api-offline-conflicts",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/"
            "<uuid:registration_id>/payment-deadline"
        ),
        StaffRegistrationPaymentDeadlineView.as_view(),
        name="api-staff-registration-payment-deadline",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/"
            "<uuid:registration_id>/waive-payment"
        ),
        StaffRegistrationWaivePaymentView.as_view(),
        name="api-staff-registration-waive-payment",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/"
            "<uuid:registration_id>/financial-operations"
        ),
        StaffFinancialOperationListCreateView.as_view(),
        name="api-registration-financial-operations",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/"
            "financial-operations/<uuid:operation_id>/approve"
        ),
        StaffFinancialOperationApproveView.as_view(),
        name="api-registration-financial-operation-approve",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/reconciliation"
        ),
        RegistrationReconciliationView.as_view(),
        name="api-registration-reconciliation",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/commerce"
        ),
        RegistrationCommerceWorkspaceView.as_view(),
        name="api-registration-commerce-workspace",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/commerce/capacity-adjustments"
        ),
        RegistrationCapacityAdjustmentView.as_view(),
        name="api-registration-capacity-adjustment",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/commerce/waitlist-batches"
        ),
        RegistrationWaitlistBatchOfferView.as_view(),
        name="api-registration-waitlist-batch",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/settlements"
        ),
        StaffSettlementListCreateView.as_view(),
        name="api-registration-settlements",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/payment-exceptions"
        ),
        StaffPaymentExceptionListView.as_view(),
        name="api-registration-payment-exceptions",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/payment-exceptions/"
            "<uuid:exception_id>/resolve"
        ),
        StaffPaymentExceptionResolveView.as_view(),
        name="api-registration-payment-exception-resolve",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/actions"
        ),
        StaffActionListView.as_view(),
        name="api-staff-action-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/communication-delivery-failures"
        ),
        StaffDeliveryFailureListView.as_view(),
        name="api-communication-delivery-failures",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/privacy/corrections/"
            "<uuid:correction_id>/decision"
        ),
        StaffPostEditionCorrectionDecisionView.as_view(),
        name="api-post-edition-correction-decision",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/privacy/registration-profile-minimization"
        ),
        StaffRegistrationProfileMinimizeView.as_view(),
        name="api-registration-profile-minimization",
    ),
]

# ADR 0030 keeps the tested API and operational endpoints available while the
# default browser experience is rebuilt one page at a time. Mount the shared
# Access workspace and shipped platform-account workflow alongside health;
# other preserved HTML routes above remain recovery evidence outside
# ``maru.baseline_urls``.
_BASELINE_PLATFORM_ROUTE_PREFIXES = (
    "accounts/invitations/",
    "admin/account/step-up/",
    "admin/access/",
    "admin/platform/accounts/",
    "health/",
)
PLATFORM_URLPATTERNS = [
    pattern
    for pattern in urlpatterns
    if str(pattern.pattern).startswith(_BASELINE_PLATFORM_ROUTE_PREFIXES)
]
API_URLPATTERNS = [
    pattern
    for pattern in urlpatterns
    if str(pattern.pattern).startswith("api/")
    and getattr(pattern, "name", None) not in {"api-docs", "api-redoc"}
]
