"""Top-level URL configuration."""

from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from drf_spectacular.views import SpectacularAPIView

from maru.accreditation.api import (
    MyCredentialListView,
    OfflineCheckInIngestView,
    StaffCredentialIssueView,
    StaffCredentialRevokeView,
    StaffOfflineConflictListView,
    StaffOfflineManifestView,
)
from maru.audit.api import AuditEventListView
from maru.communications.api import (
    MyNotificationListView,
    MyNotificationPreferenceView,
    MyNotificationReadView,
    StaffDeliveryFailureListView,
)
from maru.core.views import (
    build_info,
    liveness,
    platform_home,
    readiness,
    staff_console,
)
from maru.events.admin_context import change_admin_edition_context
from maru.events.api import (
    EditionAutocompleteView,
    EditionBasicDetailView,
    EditionBulkTransitionView,
    EditionClosureManifestCreateView,
    EditionClosureReadinessView,
    EditionListView,
    EditionReadinessGateReviewView,
    EditionTransitionView,
)
from maru.identity.api import (
    CsrfTokenView,
    MyRestrictionAppealView,
    MyRestrictionListView,
    MySecurityHistoryView,
    MySessionListView,
    MySessionRevokeView,
    MyStepUpView,
    PublicAccountBootstrapView,
    PublicRecoveryCompleteView,
    PublicRecoveryRequestView,
    PublicSessionView,
    PublicVerifyEmailView,
    StaffRestrictionAppealDecisionView,
    StaffRestrictionListCreateView,
    StaffRestrictionRevokeView,
)
from maru.identity.views import recover_account, verify_email
from maru.participation.api import (
    EditionParticipationDetailView,
    EditionParticipationListView,
    MyContextView,
    MyParticipationHistoryView,
)
from maru.privacyops.api import (
    MyPostEditionCorrectionListCreateView,
    MySubjectExportView,
    MySubjectRightsRequestListCreateView,
    StaffPostEditionCorrectionDecisionView,
    StaffRegistrationProfileMinimizeView,
    StaffSubjectRightsRequestListView,
    StaffSubjectRightsRequestTransitionView,
)
from maru.registration.api import (
    HeadlessRegistrationSubmissionView,
    MyAttendeeProfileView,
    MyFursuitPhotoUploadView,
    MyProfilePhotoUploadView,
    MyRegistrationDemoPaymentView,
    MyRegistrationPaymentIntentStatusView,
    MyRegistrationPaymentIntentView,
    MyRegistrationReceiptListView,
    MyRegistrationView,
    PaymentProviderWebhookView,
    PublicAttendeeListView,
    PublicGuardianConsentView,
    PublicRegistrationDefinitionView,
    PublicRegistrationEditionListView,
    RegistrationConfigurationActivateView,
    RegistrationConfigurationDraftView,
    RegistrationConfigurationWorkspaceView,
    RegistrationReconciliationView,
    RegistrationTemplatePublishView,
    SelfProfileSuggestionView,
    StaffActionListView,
    StaffAttendeeReportView,
    StaffBadgeExportView,
    StaffFinancialOperationApproveView,
    StaffFinancialOperationListCreateView,
    StaffPaymentExceptionListView,
    StaffPaymentExceptionResolveView,
    StaffProfileMediaReviewDecisionView,
    StaffProfileMediaReviewListView,
    StaffRegistrationCheckInView,
    StaffRegistrationDetailView,
    StaffRegistrationListView,
    StaffRegistrationPaymentDeadlineView,
    StaffRegistrationWaivePaymentView,
    StaffSettlementListCreateView,
)
from maru.registration.public_views import (
    confirm_local_demo_payment,
    edit_attendee_profile,
    guardian_consent,
    protected_fursuit_photo,
    protected_profile_photo,
    public_attendee_directory,
    public_registration_form,
    public_registration_index,
    public_registration_profile,
    staff_assisted_registration,
)
from maru.workforce.api import (
    MyOnboardingDocumentListView,
    MyOnboardingDocumentUploadView,
    MyVolunteerApplicationCreateView,
    PublicVolunteerOpportunityListView,
)
from maru.workforce.views import (
    apply_for_opportunity,
    bootstrap_convention_setup,
    download_onboarding_document,
    my_onboarding_documents,
    upload_onboarding_document_view,
    volunteer_opportunities,
)

urlpatterns = [
    path("", platform_home, name="platform-home"),
    path(
        "register/",
        public_registration_index,
        name="public-registration-index",
    ),
    path(
        "register/<uuid:edition_id>/",
        public_registration_form,
        name="public-registration-form",
    ),
    path(
        "register/<uuid:edition_id>/profile/",
        public_registration_profile,
        name="public-registration-profile",
    ),
    path(
        "register/<uuid:edition_id>/profile/demo-payment/",
        confirm_local_demo_payment,
        name="public-registration-demo-payment",
    ),
    path(
        "staff/registration-assist/<uuid:edition_id>/",
        staff_assisted_registration,
        name="staff-assisted-registration",
    ),
    path(
        "volunteer/<uuid:edition_id>/",
        volunteer_opportunities,
        name="workforce-opportunities",
    ),
    path(
        "volunteer/<uuid:edition_id>/<uuid:opportunity_id>/apply/",
        apply_for_opportunity,
        name="workforce-apply",
    ),
    path(
        "volunteer/<uuid:edition_id>/documents/",
        my_onboarding_documents,
        name="workforce-my-documents",
    ),
    path(
        ("volunteer/<uuid:edition_id>/documents/<uuid:document_request_id>/upload/"),
        upload_onboarding_document_view,
        name="workforce-document-upload",
    ),
    path(
        "volunteer/documents/<uuid:document_request_id>/download/",
        download_onboarding_document,
        name="workforce-document-download",
    ),
    path(
        "register/<uuid:edition_id>/profile/edit/",
        edit_attendee_profile,
        name="edit-attendee-profile",
    ),
    path(
        "register/<uuid:edition_id>/attendees/",
        public_attendee_directory,
        name="paid-attendee-directory",
    ),
    path(
        "register/media/profile/<uuid:profile_id>/",
        protected_profile_photo,
        name="protected-profile-photo",
    ),
    path(
        "register/media/fursuit/<uuid:fursuit_id>/",
        protected_fursuit_photo,
        name="protected-fursuit-photo",
    ),
    path(
        "guardian-consent/",
        guardian_consent,
        name="guardian-consent",
    ),
    path("staff/", staff_console, name="staff-console"),
    path(
        "accounts/login/",
        LoginView.as_view(
            template_name="core/login.html",
            redirect_authenticated_user=True,
        ),
        name="staff-login",
    ),
    path(
        "accounts/logout/",
        LogoutView.as_view(),
        name="staff-logout",
    ),
    path("accounts/verify-email/", verify_email, name="verify-email"),
    path("accounts/recover-account/", recover_account, name="recover-account"),
    path(
        "admin/context/edition/",
        change_admin_edition_context,
        name="admin-edition-context",
    ),
    path(
        "admin/workforce/bootstrap/",
        bootstrap_convention_setup,
        name="workforce-bootstrap-setup",
    ),
    path("admin/", admin.site.urls),
    path("health/live", liveness, name="health-live"),
    path("health/ready", readiness, name="health-ready"),
    path("api/v1/meta/build", build_info, name="api-build-info"),
    path("api/v1/schema", SpectacularAPIView.as_view(), name="api-schema"),
    path("api/v1/public/csrf", CsrfTokenView.as_view(), name="api-public-csrf"),
    path(
        "api/v1/public/editions/<uuid:edition_id>/volunteer-opportunities",
        PublicVolunteerOpportunityListView.as_view(),
        name="api-public-volunteer-opportunity-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/opportunities/"
            "<uuid:opportunity_id>/applications/me"
        ),
        MyVolunteerApplicationCreateView.as_view(),
        name="api-my-volunteer-application-create",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/documents/me"
        ),
        MyOnboardingDocumentListView.as_view(),
        name="api-my-onboarding-document-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/workforce/documents/me/"
            "<uuid:document_request_id>/upload"
        ),
        MyOnboardingDocumentUploadView.as_view(),
        name="api-my-onboarding-document-upload",
    ),
    path(
        "api/v1/public/accounts",
        PublicAccountBootstrapView.as_view(),
        name="api-public-account-bootstrap",
    ),
    path(
        "api/v1/public/accounts/verify-email",
        PublicVerifyEmailView.as_view(),
        name="api-public-account-verify-email",
    ),
    path(
        "api/v1/public/accounts/recovery",
        PublicRecoveryRequestView.as_view(),
        name="api-public-account-recovery-request",
    ),
    path(
        "api/v1/public/accounts/recovery/complete",
        PublicRecoveryCompleteView.as_view(),
        name="api-public-account-recovery-complete",
    ),
    path(
        "api/v1/public/sessions",
        PublicSessionView.as_view(),
        name="api-public-session",
    ),
    path(
        "api/v1/public/editions",
        PublicRegistrationEditionListView.as_view(),
        name="api-public-registration-editions",
    ),
    path(
        "api/v1/public/editions/<uuid:edition_id>/registration",
        PublicRegistrationDefinitionView.as_view(),
        name="api-public-registration-definition",
    ),
    path(
        ("api/v1/public/editions/<uuid:edition_id>/registration/submissions"),
        HeadlessRegistrationSubmissionView.as_view(),
        name="api-headless-registration-submission",
    ),
    path(
        "api/v1/public/editions/<uuid:edition_id>/attendees",
        PublicAttendeeListView.as_view(),
        name="api-public-attendee-list",
    ),
    path(
        "api/v1/public/guardian-consents/accept",
        PublicGuardianConsentView.as_view(),
        name="api-public-guardian-consent",
    ),
    path(
        (
            "api/v1/public/organizations/<uuid:organization_id>/"
            "payments/<slug:provider_code>/webhook"
        ),
        PaymentProviderWebhookView.as_view(),
        name="api-payment-provider-webhook",
    ),
    path(
        ("api/v1/public/editions/<uuid:edition_id>/registration/profile-suggestion"),
        SelfProfileSuggestionView.as_view(),
        name="api-self-profile-suggestion",
    ),
    path("api/v1/me/context", MyContextView.as_view(), name="api-my-context"),
    path(
        "api/v1/me/security-history",
        MySecurityHistoryView.as_view(),
        name="api-my-security-history",
    ),
    path(
        "api/v1/me/notifications",
        MyNotificationListView.as_view(),
        name="api-my-notifications",
    ),
    path(
        "api/v1/me/notifications/<uuid:message_id>/read",
        MyNotificationReadView.as_view(),
        name="api-my-notification-read",
    ),
    path(
        "api/v1/me/notification-preferences/<uuid:organization_id>",
        MyNotificationPreferenceView.as_view(),
        name="api-my-notification-preference",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/accreditation/me/credentials"
        ),
        MyCredentialListView.as_view(),
        name="api-my-credentials",
    ),
    path(
        "api/v1/me/sessions",
        MySessionListView.as_view(),
        name="api-my-sessions",
    ),
    path(
        "api/v1/me/sessions/<uuid:session_id>/revoke",
        MySessionRevokeView.as_view(),
        name="api-my-session-revoke",
    ),
    path(
        "api/v1/me/step-up",
        MyStepUpView.as_view(),
        name="api-my-step-up",
    ),
    path(
        "api/v1/me/restrictions",
        MyRestrictionListView.as_view(),
        name="api-my-restrictions",
    ),
    path(
        "api/v1/me/restrictions/<uuid:restriction_id>/appeals",
        MyRestrictionAppealView.as_view(),
        name="api-my-restriction-appeal",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/restrictions"
        ),
        StaffRestrictionListCreateView.as_view(),
        name="api-staff-restrictions",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/restrictions/"
            "<uuid:restriction_id>/revoke"
        ),
        StaffRestrictionRevokeView.as_view(),
        name="api-staff-restriction-revoke",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/restriction-appeals/"
            "<uuid:appeal_id>/decision"
        ),
        StaffRestrictionAppealDecisionView.as_view(),
        name="api-staff-restriction-appeal-decision",
    ),
    path(
        "api/v1/me/privacy-requests",
        MySubjectRightsRequestListCreateView.as_view(),
        name="api-my-privacy-requests",
    ),
    path(
        "api/v1/me/privacy-export",
        MySubjectExportView.as_view(),
        name="api-my-privacy-export",
    ),
    path(
        "api/v1/me/post-edition-corrections",
        MyPostEditionCorrectionListCreateView.as_view(),
        name="api-my-post-edition-corrections",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/privacy-requests",
        StaffSubjectRightsRequestListView.as_view(),
        name="api-staff-privacy-requests",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/privacy-requests/"
            "<uuid:privacy_request_id>/transition"
        ),
        StaffSubjectRightsRequestTransitionView.as_view(),
        name="api-staff-privacy-request-transition",
    ),
    path(
        "api/v1/me/participation-history",
        MyParticipationHistoryView.as_view(),
        name="api-my-participation-history",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions",
        EditionListView.as_view(),
        name="api-edition-list",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/autocomplete",
        EditionAutocompleteView.as_view(),
        name="api-edition-autocomplete",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/bulk-transition",
        EditionBulkTransitionView.as_view(),
        name="api-edition-bulk-transition",
    ),
    path(
        ("api/v1/organizations/<uuid:organization_id>/editions/<uuid:edition_id>"),
        EditionBasicDetailView.as_view(),
        name="api-edition-basic-detail",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/transition"
        ),
        EditionTransitionView.as_view(),
        name="api-edition-transition",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/closure-readiness"
        ),
        EditionClosureReadinessView.as_view(),
        name="api-edition-closure-readiness",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/closure-gates/<slug:code>"
        ),
        EditionReadinessGateReviewView.as_view(),
        name="api-edition-closure-gate-review",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/closure-manifest"
        ),
        EditionClosureManifestCreateView.as_view(),
        name="api-edition-closure-manifest",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/audit-events",
        AuditEventListView.as_view(),
        name="api-audit-event-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/participations"
        ),
        EditionParticipationListView.as_view(),
        name="api-edition-participation-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/participations/<uuid:account_id>"
        ),
        EditionParticipationDetailView.as_view(),
        name="api-edition-participation-detail",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/profile"
        ),
        MyAttendeeProfileView.as_view(),
        name="api-my-attendee-profile",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/profile/photo"
        ),
        MyProfilePhotoUploadView.as_view(),
        name="api-my-profile-photo-upload",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/profile/"
            "fursuits/<uuid:fursuit_id>/photo"
        ),
        MyFursuitPhotoUploadView.as_view(),
        name="api-my-fursuit-photo-upload",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/profile-media-reviews"
        ),
        StaffProfileMediaReviewListView.as_view(),
        name="api-registration-profile-media-review-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/"
            "profile-media-reviews/<uuid:media_id>"
        ),
        StaffProfileMediaReviewDecisionView.as_view(),
        name="api-registration-profile-media-review-decision",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/configuration"
        ),
        RegistrationConfigurationWorkspaceView.as_view(),
        name="api-registration-configuration-workspace",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/configuration/drafts"
        ),
        RegistrationConfigurationDraftView.as_view(),
        name="api-registration-configuration-draft",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/configuration/activate"
        ),
        RegistrationConfigurationActivateView.as_view(),
        name="api-registration-configuration-activate",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/templates"
        ),
        RegistrationTemplatePublishView.as_view(),
        name="api-registration-template-publish",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me"
        ),
        MyRegistrationView.as_view(),
        name="api-my-registration",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/"
            "<uuid:registration_id>/demo-payment"
        ),
        MyRegistrationDemoPaymentView.as_view(),
        name="api-my-registration-demo-payment",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/"
            "<uuid:registration_id>/payment-intents"
        ),
        MyRegistrationPaymentIntentView.as_view(),
        name="api-my-registration-payment-intent",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/"
            "<uuid:registration_id>/payment-intents/<uuid:intent_id>"
        ),
        MyRegistrationPaymentIntentStatusView.as_view(),
        name="api-my-registration-payment-intent-status",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/me/"
            "<uuid:registration_id>/receipts"
        ),
        MyRegistrationReceiptListView.as_view(),
        name="api-my-registration-receipts",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations"
        ),
        StaffRegistrationListView.as_view(),
        name="api-staff-registration-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/attendee-report"
        ),
        StaffAttendeeReportView.as_view(),
        name="api-registration-attendee-report",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/badge-export.csv"
        ),
        StaffBadgeExportView.as_view(),
        name="api-registration-badge-export",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/<uuid:registration_id>"
        ),
        StaffRegistrationDetailView.as_view(),
        name="api-staff-registration-detail",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/"
            "<uuid:registration_id>/check-in"
        ),
        StaffRegistrationCheckInView.as_view(),
        name="api-staff-registration-check-in",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/"
            "<uuid:registration_id>/credentials"
        ),
        StaffCredentialIssueView.as_view(),
        name="api-credential-issue",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/credentials/"
            "<uuid:credential_id>/revoke"
        ),
        StaffCredentialRevokeView.as_view(),
        name="api-credential-revoke",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/offline/manifests"
        ),
        StaffOfflineManifestView.as_view(),
        name="api-offline-manifest",
    ),
    path(
        (
            "api/v1/public/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/offline/devices/"
            "<slug:device_code>/check-ins"
        ),
        OfflineCheckInIngestView.as_view(),
        name="api-offline-check-in-ingest",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/offline/conflicts"
        ),
        StaffOfflineConflictListView.as_view(),
        name="api-offline-conflicts",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/"
            "<uuid:registration_id>/payment-deadline"
        ),
        StaffRegistrationPaymentDeadlineView.as_view(),
        name="api-staff-registration-payment-deadline",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/"
            "<uuid:registration_id>/waive-payment"
        ),
        StaffRegistrationWaivePaymentView.as_view(),
        name="api-staff-registration-waive-payment",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registrations/"
            "<uuid:registration_id>/financial-operations"
        ),
        StaffFinancialOperationListCreateView.as_view(),
        name="api-registration-financial-operations",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/"
            "financial-operations/<uuid:operation_id>/approve"
        ),
        StaffFinancialOperationApproveView.as_view(),
        name="api-registration-financial-operation-approve",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/reconciliation"
        ),
        RegistrationReconciliationView.as_view(),
        name="api-registration-reconciliation",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/settlements"
        ),
        StaffSettlementListCreateView.as_view(),
        name="api-registration-settlements",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/payment-exceptions"
        ),
        StaffPaymentExceptionListView.as_view(),
        name="api-registration-payment-exceptions",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/registration/payment-exceptions/"
            "<uuid:exception_id>/resolve"
        ),
        StaffPaymentExceptionResolveView.as_view(),
        name="api-registration-payment-exception-resolve",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/actions"
        ),
        StaffActionListView.as_view(),
        name="api-staff-action-list",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/communication-delivery-failures"
        ),
        StaffDeliveryFailureListView.as_view(),
        name="api-communication-delivery-failures",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/privacy/corrections/"
            "<uuid:correction_id>/decision"
        ),
        StaffPostEditionCorrectionDecisionView.as_view(),
        name="api-post-edition-correction-decision",
    ),
    path(
        (
            "api/v1/organizations/<uuid:organization_id>/"
            "editions/<uuid:edition_id>/privacy/registration-profile-minimization"
        ),
        StaffRegistrationProfileMinimizeView.as_view(),
        name="api-registration-profile-minimization",
    ),
]
