from __future__ import annotations

from django.urls import path

from maru.projects import views

app_name = "projects"

urlpatterns = [
    path("hotels/", views.hotel_list_view, name="hotel_list"),
    path("hotels/new/", views.create_hotel_view, name="create_hotel"),
    path("hotels/<int:pk>/", views.hotel_detail_view, name="hotel_detail"),
    path(
        "hotel-floor-plans/<int:pk>/edit/",
        views.edit_hotel_floor_plan_view,
        name="edit_hotel_floor_plan",
    ),
    path(
        "hotel-floor-plans/<int:pk>/delete/",
        views.delete_hotel_floor_plan_view,
        name="delete_hotel_floor_plan",
    ),
    path(
        "hotels/<int:pk>/rooms/new/",
        views.create_hotel_room_view,
        name="create_hotel_room",
    ),
    path("rooms/<int:pk>/edit/", views.edit_hotel_room_view, name="edit_hotel_room"),
    path("projects/", views.project_list_view, name="list"),
    path("archives/", views.project_archive_list_view, name="archives"),
    path(
        "archives/<slug:slug>/",
        views.project_archive_detail_view,
        name="archive_detail",
    ),
    path("forms/", views.form_list_view, name="form_list"),
    path("projects/<slug:slug>/forms/", views.form_list_view, name="project_form_list"),
    path("projects/<slug:slug>/forms/new/", views.create_form_view, name="create_form"),
    path("forms/<int:pk>/edit/", views.edit_form_view, name="edit_form"),
    path("projects/<slug:slug>/", views.project_detail_view, name="detail"),
    path(
        "projects/<slug:slug>/rooms/",
        views.project_room_settings_view,
        name="project_room_settings",
    ),
    path(
        "project-room-settings/<int:pk>/",
        views.edit_project_room_setting_view,
        name="edit_project_room_setting",
    ),
    path(
        "project-room-combination-settings/<int:pk>/",
        views.edit_project_room_combination_setting_view,
        name="edit_project_room_combination_setting",
    ),
    path(
        "project-room-availability/<slug:kind>/<int:pk>/delete/",
        views.delete_project_room_availability_view,
        name="delete_project_room_availability",
    ),
    path(
        "projects/<slug:slug>/event-groups/new/",
        views.create_event_group_view,
        name="create_event_group",
    ),
    path(
        "projects/<slug:slug>/export-tokens/",
        views.export_token_list_view,
        name="export_token_list",
    ),
    path(
        "export-tokens/<int:pk>/rotate/",
        views.rotate_export_token_view,
        name="rotate_export_token",
    ),
    path(
        "export-tokens/<int:pk>/<slug:active>/",
        views.set_export_token_active_view,
        name="set_export_token_active",
    ),
    path(
        "event-groups/<int:pk>/",
        views.event_group_detail_view,
        name="event_group_detail",
    ),
    path(
        "event-groups/<int:pk>/edit/",
        views.edit_event_group_view,
        name="edit_event_group",
    ),
    path("projects/<slug:slug>/timetable/", views.timetable_view, name="timetable"),
    path(
        "projects/<slug:slug>/timetable/print/",
        views.timetable_print_view,
        name="timetable_print",
    ),
    path(
        "projects/<slug:slug>/timetable/round/<slug:round_key>/",
        views.change_timetable_round_view,
        name="change_timetable_round",
    ),
    path(
        "projects/<slug:slug>/timetable/move/",
        views.move_timetable_item_view,
        name="move_timetable_item",
    ),
    path(
        "exports/public-timetable/<str:token>.json",
        views.public_timetable_export_view,
        name="public_timetable_export",
    ),
    path(
        "exports/public-profiles/<str:token>.json",
        views.public_profile_export_view,
        name="public_profile_export",
    ),
    path(
        "exports/volunteer-shifts/<str:token>.json",
        views.volunteer_shift_export_view,
        name="volunteer_shift_export",
    ),
    path(
        "exports/signage-reminders/<str:token>.json",
        views.signage_reminder_export_view,
        name="signage_reminder_export",
    ),
    path(
        "exports/role-status/<str:token>.json",
        views.role_status_export_view,
        name="role_status_export",
    ),
    path(
        "projects/<slug:slug>/signage-reminders/new/",
        views.create_signage_reminder_view,
        name="create_signage_reminder",
    ),
    path(
        "projects/<slug:project_slug>/<slug:subproject_slug>/submit/",
        views.submit_application_view,
        name="submit_application",
    ),
    path(
        "applications/<int:pk>/",
        views.application_detail_view,
        name="application_detail",
    ),
    path(
        "applications/<int:pk>/edit/",
        views.edit_application_view,
        name="edit_application",
    ),
    path(
        "panels/<int:pk>/place/",
        views.place_panel_view,
        name="place_panel",
    ),
    path(
        "panels/<int:pk>/metadata/",
        views.edit_panel_metadata_view,
        name="edit_panel_metadata",
    ),
    path(
        "projects/<slug:slug>/volunteer-shifts/new/",
        views.create_volunteer_shift_view,
        name="create_volunteer_shift",
    ),
    path(
        "projects/<slug:slug>/volunteer-shifts/",
        views.volunteer_shift_list_view,
        name="volunteer_shift_list",
    ),
    path(
        "volunteer-shifts/<int:pk>/claim/",
        views.claim_volunteer_shift_view,
        name="claim_volunteer_shift",
    ),
    path(
        "volunteer-shifts/<int:pk>/",
        views.volunteer_shift_detail_view,
        name="volunteer_shift_detail",
    ),
    path(
        "volunteer-shifts/<int:pk>/place/",
        views.place_volunteer_shift_view,
        name="place_volunteer_shift",
    ),
    path(
        "volunteer-shifts/<int:pk>/assign/",
        views.assign_volunteer_shift_view,
        name="assign_volunteer_shift",
    ),
    path(
        "volunteer-shifts/<int:pk>/lock/",
        views.lock_volunteer_shift_view,
        name="lock_volunteer_shift",
    ),
    path(
        "volunteer-assignments/<int:pk>/<slug:status>/",
        views.change_volunteer_assignment_status_view,
        name="change_volunteer_assignment_status",
    ),
    path(
        "review/applications/",
        views.review_application_list_view,
        name="review_application_list",
    ),
    path(
        "review/applications/<int:pk>/",
        views.review_application_detail_view,
        name="review_application_detail",
    ),
    path(
        "review/applications/<int:pk>/reopen/",
        views.reopen_application_view,
        name="reopen_application",
    ),
    path(
        "review/applications/<int:pk>/<slug:decision>/",
        views.review_application_decision_view,
        name="review_application_decision",
    ),
]
