# Generated by Django 5.2.16 on 2026-08-08 20:32

import django.core.validators
import django.db.models.deletion
import maru.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("charities", "0002_charity_write_integrity"),
        ("events", "0009_edition_workspace_downgrade_fence"),
        ("organizations", "0013_runtime_executable_function_hardening"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=24)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("payment_pending", "Payment pending"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                ("currency", models.CharField(max_length=3)),
                ("total_minor", models.PositiveBigIntegerField()),
                ("payment_due_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fulfilment_status",
                    models.CharField(default="not_started", max_length=24),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_orders",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_orders",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "reference"),
            },
        ),
        migrations.CreateModel(
            name="CatalogOrderTimelineEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=160)),
                ("summary", models.CharField(max_length=500)),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_order_timeline_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_entries",
                        to="catalog.catalogorder",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CatalogPaymentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("hosted", "Hosted payment"),
                            ("demo", "Deterministic demo payment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("provider_reference", models.CharField(max_length=120, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("checkout_url", models.URLField(blank=True)),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="catalog.catalogorder",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CatalogProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        validators=[maru.core.validators.validate_lowercase_slug],
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("merchandise", "Convention merchandise"),
                            ("donation", "Donation"),
                            ("supporter", "Limited supporter product"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "beneficiary",
                    models.CharField(
                        choices=[("convention", "Convention"), ("charity", "Charity")],
                        default="convention",
                        max_length=16,
                    ),
                ),
                ("sale_opens_at", models.DateTimeField(blank=True, null=True)),
                ("sale_closes_at", models.DateTimeField(blank=True, null=True)),
                ("preorder_allowed", models.BooleanField(default=False)),
                (
                    "fulfilment_mode",
                    models.CharField(
                        choices=[
                            ("none", "No fulfilment"),
                            ("pickup", "On-site pickup"),
                            ("shipping", "Shipping"),
                        ],
                        default="pickup",
                        max_length=16,
                    ),
                ),
                (
                    "per_order_limit",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "charity_selection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_products",
                        to="charities.charityselection",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="CatalogVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=120)),
                ("price_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("initial_stock", models.PositiveIntegerField(blank=True, null=True)),
                ("stock_ceiling", models.PositiveIntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="catalog.catalogproduct",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="CatalogOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_kind_snapshot", models.CharField(max_length=20)),
                ("product_name_snapshot", models.CharField(max_length=160)),
                ("variant_name_snapshot", models.CharField(max_length=120)),
                ("sku_snapshot", models.CharField(max_length=80)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price_minor", models.PositiveBigIntegerField()),
                ("line_total_minor", models.PositiveBigIntegerField()),
                ("beneficiary_snapshot", models.CharField(max_length=16)),
                (
                    "charity_selection_id_snapshot",
                    models.UUIDField(blank=True, null=True),
                ),
                ("fulfilment_mode_snapshot", models.CharField(max_length=16)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="catalog.catalogorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="catalog.catalogproduct",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="catalog.catalogvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="EditionCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_catalogs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commerce_catalog",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edition_catalogs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "edition_id"),
            },
        ),
        migrations.CreateModel(
            name="CatalogStockAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_stock", models.PositiveIntegerField()),
                ("new_stock", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=500)),
                ("control_version", models.PositiveBigIntegerField()),
                ("correlation_id", models.UUIDField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_stock_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_adjustments",
                        to="catalog.catalogvariant",
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_adjustments",
                        to="catalog.editioncatalog",
                    ),
                ),
            ],
            options={
                "ordering": ("catalog_id", "control_version"),
            },
        ),
        migrations.AddField(
            model_name="catalogproduct",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.editioncatalog",
            ),
        ),
        migrations.AddField(
            model_name="catalogorder",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="catalog.editioncatalog",
            ),
        ),
        migrations.CreateModel(
            name="CatalogCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("product_added", "Product added"),
                            ("variant_added", "Variant added"),
                            ("catalog_activated", "Catalog activated"),
                            ("stock_adjusted", "Stock adjusted"),
                            ("order_placed", "Order placed"),
                            ("payment_created", "Payment created"),
                            ("payment_reconciled", "Payment reconciled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("request_digest", models.CharField(max_length=64)),
                ("resulting_version", models.PositiveBigIntegerField()),
                ("result_id", models.UUIDField()),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("correlation_id", models.UUIDField()),
                ("source_channel", models.CharField(max_length=32)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_command_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="command_receipts",
                        to="catalog.editioncatalog",
                    ),
                ),
            ],
            options={
                "ordering": ("catalog_id", "resulting_version", "id"),
            },
        ),
        migrations.CreateModel(
            name="CatalogPaymentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=16)),
                ("provider_event_id", models.CharField(max_length=160)),
                ("result", models.CharField(max_length=16)),
                ("occurred_at", models.DateTimeField()),
                ("correlation_id", models.UUIDField()),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_events",
                        to="catalog.catalogpaymentintent",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_event_id"),
                        name="catalog_payment_provider_event_uq",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="catalogvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "sku"), name="catalog_variant_sku_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("initial_stock__isnull", True), ("stock_ceiling__isnull", True)
                    ),
                    models.Q(
                        ("initial_stock__isnull", False),
                        ("stock_ceiling__gte", models.F("initial_stock")),
                        ("stock_ceiling__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="catalog_variant_stock_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="catalog_order_line_quantity_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogorderline",
            constraint=models.UniqueConstraint(
                fields=("order", "variant"), name="catalog_order_variant_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="editioncatalog",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="catalog_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogstockadjustment",
            constraint=models.UniqueConstraint(
                fields=("catalog", "control_version"),
                name="catalog_stock_control_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogstockadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="catalog_stock_reason_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogproduct",
            constraint=models.UniqueConstraint(
                fields=("catalog", "code"), name="catalog_product_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("per_order_limit__gt", 0)),
                name="catalog_product_order_limit_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sale_opens_at__isnull", True),
                    ("sale_closes_at__isnull", True),
                    ("sale_closes_at__gt", models.F("sale_opens_at")),
                    _connector="OR",
                ),
                name="catalog_product_sale_window_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("beneficiary", "charity"), ("charity_selection__isnull", False)
                    ),
                    models.Q(
                        ("beneficiary", "convention"),
                        ("charity_selection__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="catalog_product_beneficiary_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="catalogorder",
            index=models.Index(
                fields=["organization", "edition", "status", "created_at"],
                name="catalog_order_scope_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="catalogorder",
            index=models.Index(
                fields=["account", "edition", "created_at"],
                name="catalog_order_owner_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogorder",
            constraint=models.UniqueConstraint(
                fields=("edition", "reference"), name="catalog_order_reference_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="catalog_order_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("catalog", "actor", "idempotency_key"),
                name="catalog_command_idempotency_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("catalog", "resulting_version"),
                name="catalog_command_result_version_uq",
            ),
        ),
    ]
