# Generated by Django 5.2.16 on 2026-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogcommandreceipt",
            name="operation",
            field=models.CharField(
                choices=[
                    ("catalog_created", "Catalog created"),
                    ("product_added", "Product added"),
                    ("variant_added", "Variant added"),
                    ("catalog_activated", "Catalog activated"),
                    ("stock_adjusted", "Stock adjusted"),
                    ("order_placed", "Order placed"),
                    ("payment_created", "Payment created"),
                    ("payment_reconciled", "Payment reconciled"),
                ],
                max_length=32,
            ),
        ),
    ]
