# Generated by Django 5.2.14 on 2026-05-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial_social_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpostversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpostversion',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=24),
        ),
        migrations.AlterField(
            model_name='socialpostversion',
            name='action',
            field=models.CharField(choices=[('save', 'Saved'), ('schedule', 'Scheduled'), ('publish', 'Published')], max_length=24),
        ),
        migrations.AlterField(
            model_name='socialpostversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], max_length=24),
        ),
    ]
