# Generated by Django 5.2.14 on 2026-06-07 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectarchivesnapshot'),
        ('social', '0002_scheduled_social_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='projects.project'),
        ),
    ]
