# Generated by Django 5.2.16 on 2026-07-26 19:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="account_email_case_insensitive_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(("email", ""), _negated=True),
                name="account_email_not_empty",
            ),
        ),
    ]
