# Generated by Django 5.2.16 on 2026-07-27 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_account_account_email_case_insensitive_unique_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountSecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sign_in", "Signed in"),
                            ("sign_out", "Signed out"),
                            ("credential_changed", "Credential changed"),
                            ("contact_verified", "Contact verified"),
                            ("data_export", "Account export"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("source_channel", models.CharField(max_length=40)),
                ("detail_code", models.CharField(max_length=80)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["account", "occurred_at"],
                        name="identity_sec_acct_time_idx",
                    )
                ],
            },
        ),
    ]
