# Generated by Django 5.2.16 on 2026-07-28 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_lifecycle_integrity_guards"),
        ("identity", "0004_security_history_append_only"),
        ("organizations", "0001_initial"),
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountsecurityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("sign_in", "Signed in"),
                    ("sign_out", "Signed out"),
                    ("credential_changed", "Credential changed"),
                    ("contact_verified", "Contact verified"),
                    ("recovery_requested", "Recovery requested"),
                    ("recovery_completed", "Recovery completed"),
                    ("session_revoked", "Session revoked"),
                    ("step_up_completed", "Extra sign-in check completed"),
                    ("data_export", "Account export"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="AccountRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("attendance", "Attendance"),
                            ("public_profile", "Public attendee profile"),
                            ("credential", "Credential"),
                            ("communication", "Communication"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("reason_code", models.CharField(max_length=80)),
                ("attendee_message", models.CharField(max_length=320)),
                ("internal_reference", models.CharField(blank=True, max_length=120)),
                ("effective_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=320)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_restrictions",
                        to="events.eventedition",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_account_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_restrictions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_account_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-effective_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AccountSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_key_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("label", models.CharField(max_length=120)),
                ("created_channel", models.CharField(max_length=40)),
                ("last_seen_at", models.DateTimeField()),
                ("step_up_verified_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=80)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maru_inventory",
                        to="sessions.session",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_seen_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="IdentityAbuseBucket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("flow", models.CharField(max_length=40)),
                ("subject_digest", models.CharField(max_length=64)),
                ("window_started_at", models.DateTimeField()),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["flow", "subject_digest", "window_started_at"],
                        name="identity_abuse_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("flow", "subject_digest", "window_started_at"),
                        name="identity_abuse_bucket_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IdentityChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("verify_email", "Verify email"),
                            ("recover_account", "Recover account"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "token_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("email_snapshot", models.EmailField(max_length=254)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "request_fingerprint",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="RestrictionAppeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("statement", models.TextField(max_length=4000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("upheld", "Restriction upheld"),
                            ("resolved", "Restriction changed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_summary", models.CharField(blank=True, max_length=500)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restriction_appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decided_restriction_appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restriction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appeals",
                        to="identity.accountrestriction",
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="accountrestriction",
            index=models.Index(
                fields=["organization", "account", "kind", "status"],
                name="identity_restriction_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountsession",
            index=models.Index(
                fields=["account", "revoked_at", "last_seen_at"],
                name="identity_session_inventory_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="identitychallenge",
            index=models.Index(
                fields=["account", "purpose", "expires_at"],
                name="identity_challenge_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitychallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__lte", 10)),
                name="identity_challenge_attempt_limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="restrictionappeal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("restriction", "account"),
                name="one_open_appeal_per_restriction",
            ),
        ),
    ]
