# Generated by Django 5.2.16 on 2026-07-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_account_email_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountrestriction",
            name="notify_account",
            field=models.BooleanField(default=True),
        ),
    ]
