# Generated by Django 5.2.16 on 2026-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0006_accountrestriction_notify_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountrestriction",
            name="consequences_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
