# Generated by Django 5.2.16 on 2026-07-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0007_accountrestriction_consequences_applied_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="identitychallenge",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identitychallenge",
            name="delivery_attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="identitychallenge",
            name="delivery_error_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="identitychallenge",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("succeeded", "Succeeded"),
                    ("permanent_failed", "Permanent failure"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="identitychallenge",
            name="last_delivery_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
