# Generated by Django 5.2.16 on 2026-08-02 17:07

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_account_inventory_control(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    del schema_editor
    control = apps.get_model("identity", "PlatformAccountInventoryControl")
    control.objects.get_or_create(singleton=True, defaults={"aggregate_version": 0})


INSTALL_INTEGRITY_GUARDS = r"""
CREATE FUNCTION identity_page10_append_only_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
    IF TG_OP = 'TRUNCATE'
       AND public.maru_authority_provenance_test_reset_allowed() THEN
        RETURN NULL;
    END IF;
    RAISE EXCEPTION 'platform invitation evidence is append-only'
        USING ERRCODE = '23514';
END;
$$;

CREATE FUNCTION identity_page10_protected_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
    IF TG_OP = 'TRUNCATE'
       AND public.maru_authority_provenance_test_reset_allowed() THEN
        RETURN NULL;
    END IF;
    RAISE EXCEPTION 'platform invitation records require controlled retention'
        USING ERRCODE = '23514';
END;
$$;

CREATE FUNCTION identity_page10_inventory_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
    IF TG_OP = 'DELETE' OR TG_OP = 'TRUNCATE' THEN
        IF TG_OP = 'TRUNCATE'
           AND public.maru_authority_provenance_test_reset_allowed() THEN
            RETURN NULL;
        END IF;
        RAISE EXCEPTION 'platform account inventory control is protected'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.singleton IS DISTINCT FROM TRUE
       OR NEW.singleton IS DISTINCT FROM OLD.singleton
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
       OR NEW.aggregate_version IS DISTINCT FROM OLD.aggregate_version + 1 THEN
        RAISE EXCEPTION 'platform account inventory version must advance by one'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION identity_page10_account_inventory_bump() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
    UPDATE identity_platformaccountinventorycontrol
       SET aggregate_version = aggregate_version + 1,
           updated_at = statement_timestamp()
     WHERE singleton = TRUE;
    IF NOT FOUND
       AND public.maru_authority_provenance_test_reset_allowed() THEN
        INSERT INTO identity_platformaccountinventorycontrol (
            singleton,
            aggregate_version,
            created_at,
            updated_at
        ) VALUES (
            TRUE,
            1,
            statement_timestamp(),
            statement_timestamp()
        );
        RETURN COALESCE(NEW, OLD);
    END IF;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'platform account inventory control is unavailable'
            USING ERRCODE = '23514';
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE FUNCTION identity_page10_invitation_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE
    subject_record record;
    creator_record record;
BEGIN
    SELECT account_kind, is_active, is_staff, is_superuser,
           email_verified_at, password
      INTO subject_record
      FROM identity_account WHERE id = NEW.account_id;
    IF NOT FOUND
       OR subject_record.account_kind <> 'person'
       OR subject_record.is_staff
       OR subject_record.is_superuser THEN
        RAISE EXCEPTION 'invitation subject must be a non-privileged person'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.status = 'accepted' THEN
        IF NOT subject_record.is_active
           OR subject_record.email_verified_at IS NULL
           OR subject_record.password = ''
           OR left(subject_record.password, 1) = '!' THEN
            RAISE EXCEPTION 'accepted invitation subject state is inconsistent'
                USING ERRCODE = '23514';
        END IF;
    ELSIF subject_record.is_active
          OR subject_record.email_verified_at IS NOT NULL
          OR left(subject_record.password, 1) <> '!' THEN
        RAISE EXCEPTION 'unaccepted invitation subject must remain reserved'
            USING ERRCODE = '23514';
    END IF;

    SELECT account_kind, is_active INTO creator_record
      FROM identity_account WHERE id = NEW.created_by_id;
    IF NOT FOUND OR creator_record.account_kind <> 'platform_administrator' THEN
        RAISE EXCEPTION 'invitation creator provenance is invalid'
            USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'INSERT' AND NOT creator_record.is_active THEN
        RAISE EXCEPTION 'invitation creator must be active at creation'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.expires_at <= NEW.created_at
       OR (NEW.accepted_at IS NOT NULL AND NEW.accepted_at > NEW.expires_at)
       OR (NEW.expired_at IS NOT NULL AND NEW.expired_at < NEW.expires_at) THEN
        RAISE EXCEPTION 'invitation lifecycle timestamps are inconsistent'
            USING ERRCODE = '23514';
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF NEW.aggregate_version <> 1 OR NEW.status <> 'pending' THEN
            RAISE EXCEPTION 'new invitation must begin pending at version one'
                USING ERRCODE = '23514';
        END IF;
    ELSE
        IF OLD.status = 'pending'
           AND NEW.status = 'pending'
           AND OLD.current_challenge_id IS NULL
           AND NEW.current_challenge_id IS NOT NULL
           AND NEW.id IS NOT DISTINCT FROM OLD.id
           AND NEW.account_id IS NOT DISTINCT FROM OLD.account_id
           AND NEW.created_by_id IS NOT DISTINCT FROM OLD.created_by_id
           AND NEW.created_at IS NOT DISTINCT FROM OLD.created_at
           AND NEW.aggregate_version IS NOT DISTINCT FROM OLD.aggregate_version
           AND NEW.expires_at IS NOT DISTINCT FROM OLD.expires_at
           AND NEW.last_transition_at IS NOT DISTINCT FROM OLD.last_transition_at
           AND NEW.accepted_at IS NOT DISTINCT FROM OLD.accepted_at
           AND NEW.revoked_at IS NOT DISTINCT FROM OLD.revoked_at
           AND NEW.expired_at IS NOT DISTINCT FROM OLD.expired_at THEN
            RETURN NEW;
        END IF;
        IF NEW.id IS DISTINCT FROM OLD.id
           OR NEW.account_id IS DISTINCT FROM OLD.account_id
           OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
           OR NEW.created_at IS DISTINCT FROM OLD.created_at
           OR NEW.aggregate_version IS DISTINCT FROM OLD.aggregate_version + 1
           OR NEW.last_transition_at <= OLD.last_transition_at THEN
            RAISE EXCEPTION 'invitation identity is immutable and version advances by one'
                USING ERRCODE = '23514';
        END IF;
        IF NOT (
            (OLD.status = 'pending' AND NEW.status IN
                ('pending', 'accepted', 'revoked', 'expired'))
            OR (OLD.status = 'expired' AND NEW.status = 'pending')
        ) THEN
            RAISE EXCEPTION 'invitation lifecycle transition is not allowed'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION identity_page10_challenge_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE
    invitation_record record;
    account_email text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.purpose = 'account_invitation' THEN
            RAISE EXCEPTION 'invitation challenges require controlled retention'
                USING ERRCODE = '23514';
        END IF;
        RETURN OLD;
    END IF;
    IF NEW.purpose <> 'account_invitation' THEN
        RETURN NEW;
    END IF;
    SELECT account_id, aggregate_version INTO invitation_record
      FROM identity_platformaccountinvitation WHERE id = NEW.invitation_id;
    SELECT email INTO account_email FROM identity_account WHERE id = NEW.account_id;
    IF invitation_record.account_id IS DISTINCT FROM NEW.account_id
       OR NEW.invitation_version > invitation_record.aggregate_version
       OR lower(NEW.email_snapshot) IS DISTINCT FROM lower(account_email) THEN
        RAISE EXCEPTION 'invitation challenge lineage is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' AND (
        NEW.id IS DISTINCT FROM OLD.id
        OR NEW.account_id IS DISTINCT FROM OLD.account_id
        OR NEW.purpose IS DISTINCT FROM OLD.purpose
        OR NEW.token_digest IS DISTINCT FROM OLD.token_digest
        OR NEW.email_snapshot IS DISTINCT FROM OLD.email_snapshot
        OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
        OR NEW.invitation_id IS DISTINCT FROM OLD.invitation_id
        OR NEW.invitation_version IS DISTINCT FROM OLD.invitation_version
        OR NEW.created_at IS DISTINCT FROM OLD.created_at
        OR (OLD.consumed_at IS NOT NULL AND NEW.consumed_at IS DISTINCT FROM OLD.consumed_at)
        OR (OLD.invalidated_at IS NOT NULL AND (
            NEW.invalidated_at IS DISTINCT FROM OLD.invalidated_at
            OR NEW.invalidation_reason IS DISTINCT FROM OLD.invalidation_reason
        ))
    ) THEN
        RAISE EXCEPTION 'invitation challenge lineage is immutable'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION identity_page10_transition_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE
    invitation_record record;
    actor_record record;
BEGIN
    SELECT account_id, status, aggregate_version, last_transition_at
      INTO invitation_record
      FROM identity_platformaccountinvitation WHERE id = NEW.invitation_id;
    IF NEW.version <> invitation_record.aggregate_version
       OR NEW.occurred_at IS DISTINCT FROM invitation_record.last_transition_at
       OR btrim(NEW.reason) = ''
       OR NEW.source_channel !~ '^[a-z][a-z0-9_-]{0,39}$'
       OR NOT (
           (NEW.operation IN ('created', 'reissued') AND invitation_record.status = 'pending')
           OR (NEW.operation = 'revoked' AND invitation_record.status = 'revoked')
           OR (NEW.operation = 'expired' AND invitation_record.status = 'expired')
           OR (NEW.operation = 'accepted' AND invitation_record.status = 'accepted')
       ) THEN
        RAISE EXCEPTION 'invitation transition does not match aggregate state'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.operation = 'created' AND NEW.version <> 1 THEN
        RAISE EXCEPTION 'created transition must be version one'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.actor_id IS NULL THEN
        IF NEW.operation <> 'expired' THEN
            RAISE EXCEPTION 'invitation transition actor is required'
                USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END IF;
    SELECT account_kind, is_active INTO actor_record
      FROM identity_account WHERE id = NEW.actor_id;
    IF NOT actor_record.is_active THEN
        RAISE EXCEPTION 'invitation transition actor must be active'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.operation = 'accepted' THEN
        IF NEW.actor_id IS DISTINCT FROM invitation_record.account_id THEN
            RAISE EXCEPTION 'only the invited subject may accept'
                USING ERRCODE = '23514';
        END IF;
    ELSIF actor_record.account_kind <> 'platform_administrator' THEN
        RAISE EXCEPTION 'administrative invitation actor is invalid'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION identity_page10_receipt_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE
    invitation_record record;
    actor_record record;
BEGIN
    SELECT account_id, aggregate_version INTO invitation_record
      FROM identity_platformaccountinvitation WHERE id = NEW.invitation_id;
    SELECT account_kind, is_active INTO actor_record
      FROM identity_account WHERE id = NEW.actor_id;
    IF NEW.inventory_control_id IS DISTINCT FROM TRUE
       OR NOT actor_record.is_active
       OR NEW.result_version <> invitation_record.aggregate_version
       OR NEW.source_channel !~ '^[a-z][a-z0-9_-]{0,39}$' THEN
        RAISE EXCEPTION 'invitation receipt provenance is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.operation = 'accept' THEN
        IF NEW.actor_id IS DISTINCT FROM invitation_record.account_id THEN
            RAISE EXCEPTION 'acceptance receipt subject is inconsistent'
                USING ERRCODE = '23514';
        END IF;
    ELSIF actor_record.account_kind <> 'platform_administrator' THEN
        RAISE EXCEPTION 'administrative invitation receipt actor is invalid'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION identity_page10_delivery_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE
    challenge_record record;
BEGIN
    SELECT invitation_id, purpose INTO challenge_record
      FROM identity_identitychallenge WHERE id = NEW.challenge_id;
    IF challenge_record.purpose <> 'account_invitation'
       OR challenge_record.invitation_id IS DISTINCT FROM NEW.invitation_id THEN
        RAISE EXCEPTION 'identity delivery challenge lineage is inconsistent'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.safe_error_code <> ''
       AND NEW.safe_error_code !~ '^[a-z0-9][a-z0-9_.-]{0,119}$' THEN
        RAISE EXCEPTION 'identity delivery error code is invalid'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.reconciliation_code <> ''
       AND NEW.reconciliation_code !~ '^[a-z0-9][a-z0-9_.-]{0,119}$' THEN
        RAISE EXCEPTION 'identity delivery reconciliation code is invalid'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.provider_reference ~ '[[:cntrl:]]'
       OR (NEW.lease_expires_at IS NOT NULL AND NEW.lease_expires_at <= NEW.claimed_at)
       OR (NEW.reconciled_at IS NOT NULL
           AND NEW.reconciled_at < NEW.reconciliation_required_at) THEN
        RAISE EXCEPTION 'identity delivery metadata is invalid'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.payload_destroyed_at IS NULL THEN
        IF octet_length(NEW.payload_nonce) <> 12
           OR octet_length(NEW.encrypted_payload) NOT BETWEEN 23 AND 5483
           OR octet_length(NEW.wrapped_data_key) NOT BETWEEN 342 AND 683
           OR octet_length(NEW.encrypted_payload) % 4 = 1
           OR octet_length(NEW.wrapped_data_key) % 4 = 1
           OR convert_from(NEW.encrypted_payload, 'UTF8') !~ '^[A-Za-z0-9_-]+$'
           OR convert_from(NEW.wrapped_data_key, 'UTF8') !~ '^[A-Za-z0-9_-]+$'
           OR NEW.encryption_key_id !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$' THEN
            RAISE EXCEPTION 'identity delivery envelope is invalid'
                USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.payload_destroyed_at < NEW.created_at THEN
        RAISE EXCEPTION 'identity delivery destruction predates creation'
            USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' THEN
        IF NEW.id IS DISTINCT FROM OLD.id
           OR NEW.invitation_id IS DISTINCT FROM OLD.invitation_id
           OR NEW.challenge_id IS DISTINCT FROM OLD.challenge_id
           OR NEW.provider_idempotency_key IS DISTINCT FROM OLD.provider_idempotency_key
           OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
            RAISE EXCEPTION 'identity delivery lineage is immutable'
                USING ERRCODE = '23514';
        END IF;
        IF OLD.payload_destroyed_at IS NOT NULL AND (
            NEW.payload_destroyed_at IS DISTINCT FROM OLD.payload_destroyed_at
            OR NEW.payload_destruction_reason IS DISTINCT FROM OLD.payload_destruction_reason
        ) THEN
            RAISE EXCEPTION 'destroyed delivery payload evidence is immutable'
                USING ERRCODE = '23514';
        END IF;
        IF OLD.payload_destroyed_at IS NULL AND NEW.payload_destroyed_at IS NULL AND (
            NEW.encryption_algorithm IS DISTINCT FROM OLD.encryption_algorithm
            OR NEW.encryption_key_id IS DISTINCT FROM OLD.encryption_key_id
            OR NEW.encrypted_payload IS DISTINCT FROM OLD.encrypted_payload
            OR NEW.wrapped_data_key IS DISTINCT FROM OLD.wrapped_data_key
            OR NEW.payload_nonce IS DISTINCT FROM OLD.payload_nonce
            OR NEW.payload_aad_digest IS DISTINCT FROM OLD.payload_aad_digest
        ) THEN
            RAISE EXCEPTION 'active delivery envelope is immutable'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION identity_page10_attempt_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE
    attempt_limit integer;
BEGIN
    SELECT max_attempts INTO attempt_limit
      FROM identity_platformidentitydelivery WHERE id = NEW.delivery_id;
    IF NEW.attempt_number > attempt_limit
       OR NEW.provider_reference ~ '[[:cntrl:]]'
       OR (NEW.safe_error_code <> ''
           AND NEW.safe_error_code !~ '^[a-z0-9][a-z0-9_.-]{0,119}$') THEN
        RAISE EXCEPTION 'identity delivery attempt evidence is invalid'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
"""


INSTALL_DEFERRED_GUARDS = r"""
CREATE FUNCTION identity_page10_assert_invitation(invitation_uuid uuid) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE
    invitation_record record;
    transition_record record;
    challenge_record record;
    subject_record record;
    transition_count bigint;
    minimum_version bigint;
    maximum_version bigint;
    active_challenge_count bigint;
    current_delivery_count bigint;
    exposed_old_payload_count bigint;
    account_email text;
BEGIN
    SELECT * INTO invitation_record
      FROM identity_platformaccountinvitation WHERE id = invitation_uuid;
    IF NOT FOUND THEN
        RETURN;
    END IF;
    SELECT email INTO account_email
      FROM identity_account WHERE id = invitation_record.account_id;
    SELECT count(*), min(version), max(version)
      INTO transition_count, minimum_version, maximum_version
      FROM identity_platformaccountinvitationtransition
      WHERE invitation_id = invitation_uuid;
    IF transition_count <> invitation_record.aggregate_version
       OR minimum_version <> 1
       OR maximum_version <> invitation_record.aggregate_version THEN
        RAISE EXCEPTION 'invitation transition versions are incomplete'
            USING ERRCODE = '23514';
    END IF;
    SELECT operation, occurred_at INTO transition_record
      FROM identity_platformaccountinvitationtransition
      WHERE invitation_id = invitation_uuid
      ORDER BY version DESC LIMIT 1;
    IF transition_record.occurred_at IS DISTINCT FROM invitation_record.last_transition_at
       OR NOT (
           (transition_record.operation IN ('created', 'reissued')
               AND invitation_record.status = 'pending')
           OR (transition_record.operation = 'accepted'
               AND invitation_record.status = 'accepted')
           OR (transition_record.operation = 'revoked'
               AND invitation_record.status = 'revoked')
           OR (transition_record.operation = 'expired'
               AND invitation_record.status = 'expired')
       ) THEN
        RAISE EXCEPTION 'invitation latest transition does not match state'
            USING ERRCODE = '23514';
    END IF;
    IF (invitation_record.status = 'accepted'
            AND invitation_record.accepted_at IS DISTINCT FROM invitation_record.last_transition_at)
       OR (invitation_record.status = 'revoked'
            AND invitation_record.revoked_at IS DISTINCT FROM invitation_record.last_transition_at)
       OR (invitation_record.status = 'expired'
            AND invitation_record.expired_at IS DISTINCT FROM invitation_record.last_transition_at) THEN
        RAISE EXCEPTION 'invitation terminal timestamp does not match transition'
            USING ERRCODE = '23514';
    END IF;
    SELECT count(*) INTO active_challenge_count
      FROM identity_identitychallenge
      WHERE invitation_id = invitation_uuid
        AND purpose = 'account_invitation'
        AND consumed_at IS NULL
        AND invalidated_at IS NULL;
    IF invitation_record.status = 'pending' THEN
        IF invitation_record.current_challenge_id IS NULL
           OR active_challenge_count <> 1 THEN
            RAISE EXCEPTION 'pending invitation requires one current challenge'
                USING ERRCODE = '23514';
        END IF;
        SELECT account_id, invitation_id, invitation_version, purpose,
               consumed_at, invalidated_at, expires_at
          INTO challenge_record
          FROM identity_identitychallenge
          WHERE id = invitation_record.current_challenge_id;
        IF challenge_record.account_id IS DISTINCT FROM invitation_record.account_id
           OR challenge_record.invitation_id IS DISTINCT FROM invitation_uuid
           OR challenge_record.invitation_version IS DISTINCT FROM invitation_record.aggregate_version
           OR challenge_record.purpose <> 'account_invitation'
           OR challenge_record.consumed_at IS NOT NULL
           OR challenge_record.invalidated_at IS NOT NULL
           OR challenge_record.expires_at IS DISTINCT FROM invitation_record.expires_at THEN
            RAISE EXCEPTION 'invitation current challenge lineage is inconsistent'
                USING ERRCODE = '23514';
        END IF;
        SELECT count(*) INTO current_delivery_count
          FROM identity_platformidentitydelivery
          WHERE invitation_id = invitation_uuid
            AND challenge_id = invitation_record.current_challenge_id;
        IF current_delivery_count <> 1 THEN
            RAISE EXCEPTION 'current invitation challenge requires durable delivery'
                USING ERRCODE = '23514';
        END IF;
    ELSIF invitation_record.current_challenge_id IS NOT NULL
          OR active_challenge_count <> 0 THEN
        RAISE EXCEPTION 'terminal invitation cannot retain an active challenge'
            USING ERRCODE = '23514';
    END IF;
    IF invitation_record.status IN ('pending', 'revoked', 'expired')
       AND EXISTS (
           SELECT 1 FROM identity_identitychallenge
            WHERE invitation_id = invitation_uuid
              AND purpose = 'account_invitation'
              AND lower(email_snapshot) IS DISTINCT FROM lower(account_email)
       ) THEN
        RAISE EXCEPTION 'reserved invitation contact is immutable'
            USING ERRCODE = '23514';
    END IF;
    SELECT count(*) INTO exposed_old_payload_count
      FROM identity_platformidentitydelivery delivery
      JOIN identity_identitychallenge challenge ON challenge.id = delivery.challenge_id
      WHERE challenge.invitation_id = invitation_uuid
        AND delivery.payload_destroyed_at IS NULL
        AND (
            invitation_record.current_challenge_id IS NULL
            OR challenge.id <> invitation_record.current_challenge_id
        );
    IF exposed_old_payload_count <> 0 THEN
        RAISE EXCEPTION 'superseded invitation payload must be destroyed'
            USING ERRCODE = '23514';
    END IF;
    SELECT account_kind, is_active, is_staff, is_superuser,
           email_verified_at, password
      INTO subject_record
      FROM identity_account WHERE id = invitation_record.account_id;
    IF subject_record.account_kind <> 'person'
       OR subject_record.is_staff OR subject_record.is_superuser THEN
        RAISE EXCEPTION 'invitation subject privilege boundary is invalid'
            USING ERRCODE = '23514';
    END IF;
    IF invitation_record.status = 'accepted' THEN
        IF NOT subject_record.is_active
           OR subject_record.email_verified_at IS NULL
           OR subject_record.password = ''
           OR left(subject_record.password, 1) = '!' THEN
            RAISE EXCEPTION 'accepted invitation subject is not activated'
                USING ERRCODE = '23514';
        END IF;
    ELSIF subject_record.is_active
          OR subject_record.email_verified_at IS NOT NULL
          OR left(subject_record.password, 1) <> '!' THEN
        RAISE EXCEPTION 'reserved invitation subject state changed'
            USING ERRCODE = '23514';
    END IF;
END;
$$;

CREATE FUNCTION identity_page10_invitation_complete() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
    PERFORM identity_page10_assert_invitation(COALESCE(NEW.id, OLD.id));
    RETURN NULL;
END;
$$;

CREATE FUNCTION identity_page10_challenge_complete() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
    IF NEW.purpose = 'account_invitation' THEN
        PERFORM identity_page10_assert_invitation(NEW.invitation_id);
    ELSIF TG_OP = 'UPDATE' AND OLD.purpose = 'account_invitation' THEN
        PERFORM identity_page10_assert_invitation(OLD.invitation_id);
    END IF;
    RETURN NULL;
END;
$$;

CREATE FUNCTION identity_page10_transition_complete() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
    PERFORM identity_page10_assert_invitation(NEW.invitation_id);
    RETURN NULL;
END;
$$;

CREATE FUNCTION identity_page10_account_complete() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE
    invitation_uuid uuid;
BEGIN
    FOR invitation_uuid IN
        SELECT id FROM identity_platformaccountinvitation
         WHERE account_id = NEW.id AND status IN ('pending', 'revoked', 'expired')
    LOOP
        PERFORM identity_page10_assert_invitation(invitation_uuid);
    END LOOP;
    RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION
    identity_page10_append_only_guard(),
    identity_page10_protected_guard(),
    identity_page10_inventory_guard(),
    identity_page10_account_inventory_bump(),
    identity_page10_invitation_guard(),
    identity_page10_challenge_guard(),
    identity_page10_transition_guard(),
    identity_page10_receipt_guard(),
    identity_page10_delivery_guard(),
    identity_page10_attempt_guard(),
    identity_page10_assert_invitation(uuid),
    identity_page10_invitation_complete(),
    identity_page10_challenge_complete(),
    identity_page10_transition_complete(),
    identity_page10_account_complete()
FROM PUBLIC;

CREATE TRIGGER identity_page10_inventory_update
BEFORE UPDATE OR DELETE ON identity_platformaccountinventorycontrol
FOR EACH ROW EXECUTE FUNCTION identity_page10_inventory_guard();
CREATE TRIGGER identity_page10_inventory_no_truncate
BEFORE TRUNCATE ON identity_platformaccountinventorycontrol
FOR EACH STATEMENT EXECUTE FUNCTION identity_page10_inventory_guard();
CREATE TRIGGER identity_page10_account_inventory_bump
AFTER INSERT OR DELETE OR UPDATE OF email, login_handle, display_name,
    account_kind, is_active, email_verified_at, date_joined
ON identity_account
FOR EACH ROW EXECUTE FUNCTION identity_page10_account_inventory_bump();
CREATE TRIGGER identity_page10_invitation_write
BEFORE INSERT OR UPDATE ON identity_platformaccountinvitation
FOR EACH ROW EXECUTE FUNCTION identity_page10_invitation_guard();
CREATE TRIGGER identity_page10_invitation_no_delete
BEFORE DELETE ON identity_platformaccountinvitation
FOR EACH ROW EXECUTE FUNCTION identity_page10_protected_guard();
CREATE TRIGGER identity_page10_invitation_no_truncate
BEFORE TRUNCATE ON identity_platformaccountinvitation
FOR EACH STATEMENT EXECUTE FUNCTION identity_page10_protected_guard();
CREATE TRIGGER identity_page10_challenge_write
BEFORE INSERT OR UPDATE OR DELETE ON identity_identitychallenge
FOR EACH ROW EXECUTE FUNCTION identity_page10_challenge_guard();
CREATE TRIGGER identity_page10_transition_insert
BEFORE INSERT ON identity_platformaccountinvitationtransition
FOR EACH ROW EXECUTE FUNCTION identity_page10_transition_guard();
CREATE TRIGGER identity_page10_transition_immutable
BEFORE UPDATE OR DELETE ON identity_platformaccountinvitationtransition
FOR EACH ROW EXECUTE FUNCTION identity_page10_append_only_guard();
CREATE TRIGGER identity_page10_transition_no_truncate
BEFORE TRUNCATE ON identity_platformaccountinvitationtransition
FOR EACH STATEMENT EXECUTE FUNCTION identity_page10_append_only_guard();
CREATE TRIGGER identity_page10_receipt_insert
BEFORE INSERT ON identity_platformaccountinvitationcommandreceipt
FOR EACH ROW EXECUTE FUNCTION identity_page10_receipt_guard();
CREATE TRIGGER identity_page10_receipt_immutable
BEFORE UPDATE OR DELETE ON identity_platformaccountinvitationcommandreceipt
FOR EACH ROW EXECUTE FUNCTION identity_page10_append_only_guard();
CREATE TRIGGER identity_page10_receipt_no_truncate
BEFORE TRUNCATE ON identity_platformaccountinvitationcommandreceipt
FOR EACH STATEMENT EXECUTE FUNCTION identity_page10_append_only_guard();
CREATE TRIGGER identity_page10_delivery_write
BEFORE INSERT OR UPDATE ON identity_platformidentitydelivery
FOR EACH ROW EXECUTE FUNCTION identity_page10_delivery_guard();
CREATE TRIGGER identity_page10_delivery_no_delete
BEFORE DELETE ON identity_platformidentitydelivery
FOR EACH ROW EXECUTE FUNCTION identity_page10_protected_guard();
CREATE TRIGGER identity_page10_delivery_no_truncate
BEFORE TRUNCATE ON identity_platformidentitydelivery
FOR EACH STATEMENT EXECUTE FUNCTION identity_page10_protected_guard();
CREATE TRIGGER identity_page10_attempt_insert
BEFORE INSERT ON identity_platformidentitydeliveryattempt
FOR EACH ROW EXECUTE FUNCTION identity_page10_attempt_guard();
CREATE TRIGGER identity_page10_attempt_immutable
BEFORE UPDATE OR DELETE ON identity_platformidentitydeliveryattempt
FOR EACH ROW EXECUTE FUNCTION identity_page10_append_only_guard();
CREATE TRIGGER identity_page10_attempt_no_truncate
BEFORE TRUNCATE ON identity_platformidentitydeliveryattempt
FOR EACH STATEMENT EXECUTE FUNCTION identity_page10_append_only_guard();

CREATE CONSTRAINT TRIGGER identity_page10_invitation_complete
AFTER INSERT OR UPDATE ON identity_platformaccountinvitation
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION identity_page10_invitation_complete();
CREATE CONSTRAINT TRIGGER identity_page10_challenge_complete
AFTER INSERT OR UPDATE ON identity_identitychallenge
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION identity_page10_challenge_complete();
CREATE CONSTRAINT TRIGGER identity_page10_transition_complete
AFTER INSERT ON identity_platformaccountinvitationtransition
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION identity_page10_transition_complete();
CREATE CONSTRAINT TRIGGER identity_page10_account_complete
AFTER UPDATE OF account_kind, is_active, is_staff, is_superuser,
    email_verified_at, password, email ON identity_account
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION identity_page10_account_complete();
"""


REMOVE_INTEGRITY_GUARDS = r"""
DROP FUNCTION IF EXISTS identity_page10_account_complete() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_transition_complete() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_challenge_complete() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_invitation_complete() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_assert_invitation(uuid) CASCADE;
DROP FUNCTION IF EXISTS identity_page10_attempt_guard() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_delivery_guard() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_receipt_guard() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_transition_guard() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_challenge_guard() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_invitation_guard() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_inventory_guard() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_account_inventory_bump() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_protected_guard() CASCADE;
DROP FUNCTION IF EXISTS identity_page10_append_only_guard() CASCADE;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0007_authority_provenance_activation_guards"),
        ("identity", "0010_account_kind"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["date_joined", "id"],
                name="identity_account_joined_idx",
            ),
        ),
        migrations.CreateModel(
            name="PlatformAccountInvitationCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("reissue", "Reissue"),
                            ("revoke", "Revoke"),
                            ("accept", "Accept"),
                        ],
                        max_length=16,
                    ),
                ),
                ("retry_key", models.UUIDField()),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_digest",
                                message="Use a lowercase SHA-256 hex digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("expected_version", models.PositiveBigIntegerField()),
                ("result_version", models.PositiveBigIntegerField()),
                ("correlation_id", models.UUIDField()),
                (
                    "source_channel",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_invitation_source_channel",
                                message="Use a stable lowercase source-channel code.",
                                regex="^[a-z][a-z0-9_-]{0,39}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PlatformAccountInvitationTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveBigIntegerField()),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("reissued", "Reissued"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                            ("accepted", "Accepted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=240)),
                ("correlation_id", models.UUIDField()),
                (
                    "source_channel",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_invitation_source_channel",
                                message="Use a stable lowercase source-channel code.",
                                regex="^[a-z][a-z0-9_-]{0,39}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("invitation_id", "version", "id"),
            },
        ),
        migrations.CreateModel(
            name="PlatformIdentityDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("delivered", "Delivered"),
                            ("retrying", "Retrying"),
                            ("permanent_failed", "Permanent failure"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "available_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "provider_idempotency_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=8)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("provider_reference", models.CharField(blank=True, max_length=160)),
                (
                    "safe_error_code",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_delivery_code",
                                message="Use a stable lowercase delivery code.",
                                regex="^[a-z0-9][a-z0-9_.-]{0,119}$",
                            )
                        ],
                    ),
                ),
                (
                    "reconciliation_state",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("required", "Required"),
                            ("resolved", "Resolved"),
                        ],
                        default="not_required",
                        max_length=20,
                    ),
                ),
                (
                    "reconciliation_required_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reconciliation_code",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_delivery_code",
                                message="Use a stable lowercase delivery code.",
                                regex="^[a-z0-9][a-z0-9_.-]{0,119}$",
                            )
                        ],
                    ),
                ),
                ("encryption_algorithm", models.CharField(blank=True, max_length=64)),
                (
                    "encryption_key_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_invitation_encryption_key_id",
                                message="Use a stable invitation encryption key identifier.",
                                regex="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$",
                            )
                        ],
                    ),
                ),
                (
                    "encrypted_payload",
                    models.BinaryField(blank=True, max_length=5483, null=True),
                ),
                (
                    "wrapped_data_key",
                    models.BinaryField(blank=True, max_length=683, null=True),
                ),
                (
                    "payload_nonce",
                    models.BinaryField(blank=True, max_length=12, null=True),
                ),
                (
                    "payload_aad_digest",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_digest",
                                message="Use a lowercase SHA-256 hex digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("payload_destroyed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payload_destruction_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("delivered", "Delivered"),
                            ("revoked", "Invitation revoked"),
                            ("superseded", "Challenge superseded"),
                            ("expired", "Invitation expired"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ("available_at", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PlatformIdentityDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("lease_token", models.UUIDField()),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("delivered", "Delivered"),
                            ("transient_failure", "Transient failure"),
                            ("permanent_failure", "Permanent failure"),
                            ("uncertain", "Uncertain provider result"),
                            ("lease_lost", "Lease lost"),
                        ],
                        max_length=24,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=160)),
                (
                    "safe_error_code",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_delivery_code",
                                message="Use a stable lowercase delivery code.",
                                regex="^[a-z0-9][a-z0-9_.-]{0,119}$",
                            )
                        ],
                    ),
                ),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("delivery_id", "attempt_number", "id"),
            },
        ),
        migrations.AddField(
            model_name="identitychallenge",
            name="invalidated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identitychallenge",
            name="invalidation_reason",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="identitychallenge",
            name="invitation_version",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="accountsecurityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("sign_in", "Signed in"),
                    ("sign_out", "Signed out"),
                    ("credential_changed", "Credential changed"),
                    ("contact_verified", "Contact verified"),
                    ("recovery_requested", "Recovery requested"),
                    ("recovery_completed", "Recovery completed"),
                    ("session_revoked", "Session revoked"),
                    ("step_up_completed", "Extra sign-in check completed"),
                    ("data_export", "Account export"),
                    ("account_invitation_created", "Account invitation created"),
                    ("account_invitation_reissued", "Account invitation reissued"),
                    ("account_invitation_revoked", "Account invitation revoked"),
                    ("account_invitation_expired", "Account invitation expired"),
                    ("account_invitation_accepted", "Account invitation accepted"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="identitychallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("verify_email", "Verify email"),
                    ("recover_account", "Recover account"),
                    ("account_invitation", "Accept account invitation"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="identitychallenge",
            name="request_fingerprint",
            field=models.CharField(
                editable=False,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_digest",
                        message="Use a lowercase SHA-256 hex digest.",
                        regex="^[0-9a-f]{64}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="identitychallenge",
            name="token_digest",
            field=models.CharField(
                editable=False,
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_digest",
                        message="Use a lowercase SHA-256 hex digest.",
                        regex="^[0-9a-f]{64}$",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="PlatformAccountInventoryControl",
            fields=[
                (
                    "singleton",
                    models.BooleanField(
                        default=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("singleton", True)),
                        name="identity_account_inventory_singleton",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlatformAccountInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                ("expires_at", models.DateTimeField()),
                ("last_transition_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_account_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_account_invitations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_challenge",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_for_platform_invitation",
                        to="identity.identitychallenge",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="identitychallenge",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="identity_challenges",
                to="identity.platformaccountinvitation",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitychallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("invitation__isnull", False),
                        ("invitation_version__gt", 0),
                        ("purpose", "account_invitation"),
                    ),
                    models.Q(
                        models.Q(("purpose", "account_invitation"), _negated=True),
                        ("invitation__isnull", True),
                        ("invitation_version__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="identity_challenge_invitation_lineage",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitychallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("invalidated_at__isnull", True), ("invalidation_reason", "")
                    ),
                    models.Q(
                        ("invalidated_at__isnull", False),
                        models.Q(("invalidation_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="identity_challenge_invalidation_evidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitychallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("consumed_at__isnull", True),
                    ("invalidated_at__isnull", True),
                    _connector="OR",
                ),
                name="identity_challenge_not_consumed_invalidated",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitychallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("token_digest__regex", "^[0-9a-f]{64}$")),
                name="identity_challenge_token_digest_canonical",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitychallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="identity_challenge_fingerprint_canonical",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitychallenge",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("consumed_at__isnull", True),
                    ("invalidated_at__isnull", True),
                    ("purpose", "account_invitation"),
                ),
                fields=("invitation",),
                name="identity_one_active_challenge_per_invite",
            ),
        ),
        migrations.AddField(
            model_name="platformaccountinvitationcommandreceipt",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="platform_account_invitation_command_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="platformaccountinvitationcommandreceipt",
            name="inventory_control",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitation_command_receipts",
                to="identity.platformaccountinventorycontrol",
            ),
        ),
        migrations.AddField(
            model_name="platformaccountinvitationcommandreceipt",
            name="invitation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="command_receipts",
                to="identity.platformaccountinvitation",
            ),
        ),
        migrations.AddField(
            model_name="platformaccountinvitationtransition",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="platform_account_invitation_transitions_acted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="platformaccountinvitationtransition",
            name="invitation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transitions",
                to="identity.platformaccountinvitation",
            ),
        ),
        migrations.AddField(
            model_name="platformidentitydelivery",
            name="challenge",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="platform_identity_delivery",
                to="identity.identitychallenge",
            ),
        ),
        migrations.AddField(
            model_name="platformidentitydelivery",
            name="invitation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries",
                to="identity.platformaccountinvitation",
            ),
        ),
        migrations.AddField(
            model_name="platformidentitydeliveryattempt",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="identity.platformidentitydelivery",
            ),
        ),
        migrations.AddIndex(
            model_name="platformaccountinvitation",
            index=models.Index(
                fields=["status", "expires_at", "id"],
                name="id_invite_status_expiry_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccountinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="identity_invitation_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccountinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("accepted_at__isnull", True),
                        ("expired_at__isnull", True),
                        ("revoked_at__isnull", True),
                        ("status", "pending"),
                    ),
                    models.Q(
                        ("accepted_at__isnull", False),
                        ("expired_at__isnull", True),
                        ("revoked_at__isnull", True),
                        ("status", "accepted"),
                    ),
                    models.Q(
                        ("accepted_at__isnull", True),
                        ("expired_at__isnull", True),
                        ("revoked_at__isnull", False),
                        ("status", "revoked"),
                    ),
                    models.Q(
                        ("accepted_at__isnull", True),
                        ("expired_at__isnull", False),
                        ("revoked_at__isnull", True),
                        ("status", "expired"),
                    ),
                    _connector="OR",
                ),
                name="identity_invitation_status_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccountinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "pending"),
                    ("current_challenge__isnull", True),
                    _connector="OR",
                ),
                name="identity_terminal_invitation_no_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccountinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("account",),
                name="identity_one_pending_invite_per_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccountinvitationcommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("inventory_control", "actor", "retry_key"),
                name="identity_invitation_retry_scope_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccountinvitationcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_digest__regex", "^[0-9a-f]{64}$")),
                name="identity_invitation_request_digest_canonical",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccountinvitationcommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expected_version", 0),
                        ("operation", "create"),
                        ("result_version", 1),
                    ),
                    models.Q(
                        ("expected_version__gt", 0),
                        ("operation__in", ("reissue", "revoke", "accept")),
                        (
                            "result_version",
                            django.db.models.expressions.CombinedExpression(
                                models.F("expected_version"), "+", models.Value(1)
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="identity_invitation_receipt_version_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccountinvitationtransition",
            constraint=models.UniqueConstraint(
                fields=("invitation", "version"),
                name="identity_invitation_transition_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccountinvitationtransition",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)),
                name="identity_invitation_transition_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccountinvitationtransition",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="identity_invitation_transition_reason_nonempty",
            ),
        ),
        migrations.AddIndex(
            model_name="platformidentitydelivery",
            index=models.Index(
                fields=["status", "available_at", "id"],
                name="identity_delivery_claim_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformidentitydelivery",
            index=models.Index(
                fields=["status", "lease_expires_at", "id"],
                name="identity_delivery_lease_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformidentitydelivery",
            index=models.Index(
                fields=["reconciliation_state", "created_at", "id"],
                name="id_delivery_reconcile_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_attempts__gte", 1),
                    ("max_attempts__lte", 100),
                    ("attempt_count__lte", models.F("max_attempts")),
                ),
                name="identity_delivery_attempt_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("claimed_at__isnull", False),
                        ("lease_expires_at__isnull", False),
                        ("lease_token__isnull", False),
                        ("status", "processing"),
                    ),
                    models.Q(
                        models.Q(("status", "processing"), _negated=True),
                        ("claimed_at__isnull", True),
                        ("lease_expires_at__isnull", True),
                        ("lease_token__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="identity_delivery_lease_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("next_retry_at__isnull", False), ("status", "retrying")),
                    models.Q(
                        models.Q(("status", "retrying"), _negated=True),
                        ("next_retry_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="identity_delivery_retry_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("delivered_at__isnull", False), ("status", "delivered")),
                    models.Q(
                        models.Q(("status", "delivered"), _negated=True),
                        ("delivered_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="identity_delivery_success_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ("retrying", "permanent_failed")),
                        models.Q(("safe_error_code", ""), _negated=True),
                    ),
                    models.Q(
                        ("status__in", ("pending", "processing", "delivered")),
                        ("safe_error_code", ""),
                    ),
                    _connector="OR",
                ),
                name="identity_delivery_error_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("attempt_count", 0), ("last_attempt_at__isnull", True)),
                    models.Q(
                        ("attempt_count__gt", 0), ("last_attempt_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="identity_delivery_attempt_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reconciled_at__isnull", True),
                        ("reconciliation_code", ""),
                        ("reconciliation_required_at__isnull", True),
                        ("reconciliation_state", "not_required"),
                    ),
                    models.Q(
                        ("reconciled_at__isnull", True),
                        ("reconciliation_code", ""),
                        ("reconciliation_required_at__isnull", False),
                        ("reconciliation_state", "required"),
                    ),
                    models.Q(
                        ("reconciled_at__isnull", False),
                        ("reconciliation_required_at__isnull", False),
                        ("reconciliation_state", "resolved"),
                        models.Q(("reconciliation_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="identity_delivery_reconciliation_evidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("encrypted_payload__isnull", False),
                        ("encryption_algorithm", "aes-256-gcm+rsa-oaep-sha256-v1"),
                        ("payload_destroyed_at__isnull", True),
                        ("payload_destruction_reason", ""),
                        ("payload_nonce__isnull", False),
                        ("wrapped_data_key__isnull", False),
                        models.Q(("encryption_key_id", ""), _negated=True),
                        ("payload_aad_digest__regex", "^[0-9a-f]{64}$"),
                    ),
                    models.Q(
                        ("encrypted_payload__isnull", True),
                        ("encryption_algorithm", ""),
                        ("encryption_key_id", ""),
                        ("payload_aad_digest", ""),
                        ("payload_destroyed_at__isnull", False),
                        ("payload_nonce__isnull", True),
                        ("wrapped_data_key__isnull", True),
                        models.Q(("payload_destruction_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="identity_delivery_envelope_lifecycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "delivered"), _negated=True),
                    ("payload_destruction_reason", "delivered"),
                    _connector="OR",
                ),
                name="identity_delivered_payload_destroyed",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydeliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("delivery", "attempt_number"),
                name="identity_delivery_attempt_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydeliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attempt_number__gte", 1), ("attempt_number__lte", 100)
                ),
                name="identity_delivery_attempt_number_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydeliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("finished_at__gte", models.F("started_at"))),
                name="identity_delivery_attempt_finished_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformidentitydeliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("next_retry_at__isnull", True),
                        ("outcome", "delivered"),
                        ("safe_error_code", ""),
                    ),
                    models.Q(
                        ("next_retry_at__isnull", False),
                        ("outcome", "transient_failure"),
                        models.Q(("safe_error_code", ""), _negated=True),
                    ),
                    models.Q(
                        ("next_retry_at__isnull", True),
                        (
                            "outcome__in",
                            ("permanent_failure", "uncertain", "lease_lost"),
                        ),
                        models.Q(("safe_error_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="identity_delivery_attempt_outcome_evidence",
            ),
        ),
        migrations.RunPython(
            seed_account_inventory_control,
            migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            INSTALL_INTEGRITY_GUARDS,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            INSTALL_DEFERRED_GUARDS,
            reverse_sql=REMOVE_INTEGRITY_GUARDS,
        ),
    ]
