# Generated by Django 5.2.17 on 2026-08-31 19:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


REVERSE_PREFLIGHT_SQL = r"""
LOCK TABLE
    public.programme_programmeeditioncontrol,
    public.programme_programmeitem,
    public.programme_programmeitemsourcebinding,
    public.programme_programmeworkingrevision,
    public.programme_programmedeliveryrevision,
    public.programme_programmedepartmentdiscussionentry,
    public.programme_programmereadinessrequirement,
    public.programme_programmereadinessrequirementrevision,
    public.programme_programmereadinessevidence,
    public.programme_programmepublicrendition,
    public.programme_programmecommandreceipt
IN ACCESS EXCLUSIVE MODE;

DO $programme_0001_reverse_preflight$
BEGIN
    IF EXISTS (SELECT 1 FROM public.programme_programmeeditioncontrol LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.programme_programmeitem LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.programme_programmeitemsourcebinding LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.programme_programmeworkingrevision LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.programme_programmedeliveryrevision LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.programme_programmedepartmentdiscussionentry LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.programme_programmereadinessrequirement LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.programme_programmereadinessrequirementrevision LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.programme_programmereadinessevidence LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.programme_programmepublicrendition LIMIT 1)
       OR EXISTS (SELECT 1 FROM public.programme_programmecommandreceipt LIMIT 1)
    THEN
        RAISE EXCEPTION 'Cannot remove Programme tables while Programme data exists'
            USING ERRCODE = '23514';
    END IF;
END;
$programme_0001_reverse_preflight$;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammeEditionControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("aggregate_version", models.PositiveBigIntegerField()),
                (
                    "edition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_control",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_edition_controls",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "edition_id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ceremony", "Ceremony"),
                            ("break", "Break"),
                            ("announcement", "Announcement"),
                            ("organizer_core", "Organizer Core"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "provenance_kind",
                    models.CharField(
                        choices=[
                            ("organizer_core", "Organizer Core"),
                            ("applications_accepted", "Applications Accepted"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "aggregate_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_items_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_items",
                        to="events.eventedition",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_items_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_items",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeDepartmentDiscussionEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                ("item_version", models.PositiveBigIntegerField()),
                ("body", models.TextField(max_length=5000)),
                ("reason", models.CharField(max_length=1000)),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_department_discussion_entries_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_department_discussion_entries",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_department_discussion_entries",
                        to="organizations.organization",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="department_discussion_entries",
                        to="programme.programmeitem",
                    ),
                ),
            ],
            options={
                "ordering": ("item_id", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeDeliveryRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                ("item_version", models.PositiveBigIntegerField()),
                (
                    "technical_requirements",
                    models.TextField(blank=True, max_length=5000),
                ),
                (
                    "accessibility_delivery",
                    models.TextField(blank=True, max_length=5000),
                ),
                ("media_consent_notes", models.TextField(blank=True, max_length=5000)),
                ("reason", models.CharField(max_length=1000)),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_delivery_revisions_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_delivery_revisions",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_delivery_revisions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_revisions",
                        to="programme.programmeitem",
                    ),
                ),
            ],
            options={
                "ordering": ("item_id", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeCommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("item_create", "Item Create"),
                            ("working_revise", "Working Revise"),
                            ("delivery_revise", "Delivery Revise"),
                            ("discussion_append", "Discussion Append"),
                            ("readiness_configure", "Readiness Configure"),
                            ("readiness_record", "Readiness Record"),
                            ("public_rendition_record", "Public Rendition Record"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(max_length=1000)),
                ("idempotency_key", models.UUIDField()),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_digest",
                                message="Use a lower-case SHA-256 digest.",
                                regex="^[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("correlation_id", models.UUIDField()),
                (
                    "source_channel",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_source_channel",
                                message="Use a registered lower-case source channel.",
                                regex="^[a-z][a-z0-9_-]*\\Z",
                            )
                        ],
                    ),
                ),
                ("result_object_id", models.UUIDField()),
                ("expected_version", models.PositiveBigIntegerField()),
                (
                    "resulting_control_version",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("resulting_item_version", models.PositiveBigIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_commands_acted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_command_receipts",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_command_receipts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="command_receipts",
                        to="programme.programmeeditioncontrol",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="command_receipts",
                        to="programme.programmeitem",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeItemSourceBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "binding_code",
                    models.CharField(
                        choices=[
                            (
                                "programme.source.organizer-core@1",
                                "programme.source.organizer-core@1",
                            ),
                            (
                                "programme.source.applications-accepted@1",
                                "programme.source.applications-accepted@1",
                            ),
                        ],
                        max_length=80,
                    ),
                ),
                ("source_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "source_version",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_item_source_bindings",
                        to="events.eventedition",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_binding",
                        to="programme.programmeitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_item_source_bindings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("edition_id", "item_id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeReadinessRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concern",
                    models.CharField(
                        choices=[
                            ("public_copy", "Public Copy"),
                            ("host_confirmation", "Host Confirmation"),
                            ("technical_needs", "Technical Needs"),
                            ("accessibility_delivery", "Accessibility Delivery"),
                            ("media_consent", "Media Consent"),
                            ("schedule_availability", "Schedule Availability"),
                            ("required_files", "Required Files"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "requirement_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "dependency_version",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                ("item_version", models.PositiveBigIntegerField(editable=False)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_readiness_requirements",
                        to="events.eventedition",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readiness_requirements",
                        to="programme.programmeitem",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_readiness_requirements_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_readiness_requirements",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("item_id", "concern", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeReadinessEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                ("item_version", models.PositiveBigIntegerField()),
                ("requirement_version", models.PositiveBigIntegerField()),
                ("dependency_version", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("satisfied", "Satisfied"),
                            ("blocked", "Blocked"),
                            ("unavailable", "Unavailable"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_code",
                    models.CharField(
                        choices=[
                            (
                                "programme.evidence.operator-attestation@1",
                                "programme.evidence.operator-attestation@1",
                            ),
                            (
                                "programme.evidence.public-rendition@1",
                                "programme.evidence.public-rendition@1",
                            ),
                            (
                                "programme.evidence.working-revision@1",
                                "programme.evidence.working-revision@1",
                            ),
                            (
                                "programme.evidence.delivery-revision@1",
                                "programme.evidence.delivery-revision@1",
                            ),
                        ],
                        max_length=80,
                    ),
                ),
                ("source_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "source_version",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("evidence_note", models.TextField(blank=True, max_length=2000)),
                ("reason", models.CharField(max_length=1000)),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_readiness_evidence_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_readiness_evidence",
                        to="events.eventedition",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readiness_evidence",
                        to="programme.programmeitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_readiness_evidence",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_entries",
                        to="programme.programmereadinessrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ("requirement_id", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeReadinessRequirementRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                ("item_version", models.PositiveBigIntegerField()),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.CharField(max_length=1000)),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_readiness_requirement_revisions_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_readiness_requirement_revisions",
                        to="events.eventedition",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readiness_requirement_revisions",
                        to="programme.programmeitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_readiness_requirement_revisions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="programme.programmereadinessrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ("requirement_id", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeWorkingRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                ("item_version", models.PositiveBigIntegerField()),
                ("internal_title", models.CharField(max_length=240)),
                ("working_summary", models.TextField(blank=True, max_length=2000)),
                ("reason", models.CharField(max_length=1000)),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_working_revisions_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_working_revisions",
                        to="events.eventedition",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="working_revisions",
                        to="programme.programmeitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_working_revisions",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("item_id", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammePublicRendition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rendition_number", models.PositiveBigIntegerField()),
                ("source_item_version", models.PositiveBigIntegerField()),
                ("public_title", models.CharField(max_length=240)),
                ("public_summary", models.TextField(blank=True, max_length=2000)),
                ("public_content_note", models.CharField(blank=True, max_length=500)),
                ("reviewed_at", models.DateTimeField()),
                ("review_reason", models.CharField(max_length=1000)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_public_renditions",
                        to="events.eventedition",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="public_renditions",
                        to="programme.programmeitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_public_renditions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_public_renditions_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="programme.programmepublicrendition",
                    ),
                ),
                (
                    "source_working_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="public_renditions",
                        to="programme.programmeworkingrevision",
                    ),
                ),
            ],
            options={
                "ordering": ("item_id", "rendition_number", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="programmeeditioncontrol",
            index=models.Index(
                fields=["organization", "edition"], name="programme_control_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeeditioncontrol",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="programme_control_version_pos",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeitem",
            index=models.Index(
                fields=["organization", "edition", "lifecycle"],
                name="programme_item_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gt", 0)),
                name="programme_item_version_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        ("ceremony", "break", "announcement", "organizer_core"),
                    )
                ),
                name="programme_item_kind_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("provenance_kind__in", ("organizer_core", "applications_accepted"))
                ),
                name="programme_item_provenance_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("lifecycle__in", ("active", "retired"))),
                name="programme_item_lifecycle_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmedepartmentdiscussionentry",
            constraint=models.UniqueConstraint(
                fields=("item", "sequence"), name="programme_discussion_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmedepartmentdiscussionentry",
            constraint=models.UniqueConstraint(
                fields=("item", "item_version"),
                name="programme_discussion_item_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmedepartmentdiscussionentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("item_version__gt", 0),
                    ("sequence__gt", 0),
                    models.Q(("body", ""), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="programme_discussion_evidence_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmedeliveryrevision",
            constraint=models.UniqueConstraint(
                fields=("item", "sequence"), name="programme_delivery_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmedeliveryrevision",
            constraint=models.UniqueConstraint(
                fields=("item", "item_version"),
                name="programme_delivery_item_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmedeliveryrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("item_version__gt", 0), ("sequence__gt", 0)),
                name="programme_delivery_versions_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmedeliveryrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("technical_requirements", ""), _negated=True),
                        models.Q(("accessibility_delivery", ""), _negated=True),
                        models.Q(("media_consent_notes", ""), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="programme_delivery_evidence_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("edition", "actor", "idempotency_key"),
                name="programme_command_retry_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("operation", "public_rendition_record"), _negated=True
                ),
                fields=("item", "resulting_item_version"),
                name="programme_command_item_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resulting_control_version__isnull", False)),
                fields=("control", "resulting_control_version"),
                name="programme_command_control_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation__in",
                        (
                            "item_create",
                            "working_revise",
                            "delivery_revise",
                            "discussion_append",
                            "readiness_configure",
                            "readiness_record",
                            "public_rendition_record",
                        ),
                    )
                ),
                name="programme_command_operation_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_version__gte", 0),
                    ("resulting_item_version__gt", 0),
                    models.Q(("reason", ""), _negated=True),
                    models.Q(("source_channel", ""), _negated=True),
                ),
                name="programme_command_evidence_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("operation", "item_create"),
                        ("resulting_control_version__gt", 0),
                    ),
                    models.Q(
                        models.Q(("operation", "item_create"), _negated=True),
                        ("resulting_control_version__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="programme_command_control_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeitemsourcebinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_object_id__isnull", False)),
                fields=("binding_code", "source_object_id"),
                name="programme_item_source_object_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeitemsourcebinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("binding_code", "programme.source.organizer-core@1"),
                        ("source_object_id__isnull", True),
                        ("source_version__isnull", True),
                    ),
                    models.Q(
                        ("binding_code", "programme.source.applications-accepted@1"),
                        ("source_object_id__isnull", False),
                        ("source_version__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="programme_item_source_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereadinessrequirement",
            constraint=models.UniqueConstraint(
                fields=("item", "concern"), name="programme_readiness_concern_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereadinessrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "concern__in",
                        (
                            "public_copy",
                            "host_confirmation",
                            "technical_needs",
                            "accessibility_delivery",
                            "media_consent",
                            "schedule_availability",
                            "required_files",
                        ),
                    )
                ),
                name="programme_readiness_concern_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereadinessrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("disposition__in", ("required", "not_applicable"))),
                name="programme_readiness_disposition_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereadinessrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("dependency_version__gte", 0),
                    ("item_version__gt", 0),
                    ("requirement_version__gt", 0),
                ),
                name="programme_readiness_versions_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereadinessevidence",
            constraint=models.UniqueConstraint(
                fields=("requirement", "sequence"),
                name="programme_readiness_evidence_sequence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereadinessevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("dependency_version__gte", 0),
                    ("item_version__gt", 0),
                    ("requirement_version__gt", 0),
                    ("sequence__gt", 0),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="programme_readiness_evidence_versions_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereadinessevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ("satisfied", "blocked", "unavailable"))
                ),
                name="programme_readiness_evidence_state_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereadinessevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_code", "programme.evidence.operator-attestation@1"),
                        ("source_object_id__isnull", True),
                        ("source_version__isnull", True),
                    ),
                    models.Q(
                        (
                            "source_code__in",
                            (
                                "programme.evidence.public-rendition@1",
                                "programme.evidence.working-revision@1",
                                "programme.evidence.delivery-revision@1",
                            ),
                        ),
                        ("source_object_id__isnull", False),
                        ("source_version__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="programme_readiness_evidence_source_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereadinessrequirementrevision",
            constraint=models.UniqueConstraint(
                fields=("requirement", "sequence"),
                name="programme_requirement_revision_sequence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereadinessrequirementrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("item_version__gt", 0),
                    ("sequence__gt", 0),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="programme_requirement_revision_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmereadinessrequirementrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("disposition__in", ("required", "not_applicable"))),
                name="programme_requirement_revision_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeworkingrevision",
            constraint=models.UniqueConstraint(
                fields=("item", "sequence"), name="programme_working_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeworkingrevision",
            constraint=models.UniqueConstraint(
                fields=("item", "item_version"),
                name="programme_working_item_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeworkingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("item_version__gt", 0), ("sequence__gt", 0)),
                name="programme_working_versions_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeworkingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("internal_title", ""), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="programme_working_evidence_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmepublicrendition",
            constraint=models.UniqueConstraint(
                fields=("item", "rendition_number"),
                name="programme_public_rendition_number_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmepublicrendition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rendition_number__gt", 0),
                    ("source_item_version__gt", 0),
                    models.Q(("public_title", ""), _negated=True),
                    models.Q(("review_reason", ""), _negated=True),
                ),
                name="programme_public_rendition_valid",
            ),
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql=REVERSE_PREFLIGHT_SQL,
        ),
    ]
