# Generated by Django 5.2.17 on 2026-09-06 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0016_programmeacceptedtransition"),
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("programme", "0003_downgrade_fence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="programmecommandreceipt",
            name="programme_command_control_shape",
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(operation__in=("item_create", "item_accept"), resulting_control_version__gt=0)
                    | (~models.Q(operation__in=("item_create", "item_accept"))
                       & models.Q(resulting_control_version__isnull=True))
                ),
                name="programme_command_control_shape",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="programmecommandreceipt",
            name="programme_command_operation_closed",
        ),
        migrations.RemoveConstraint(
            model_name="programmeitem",
            name="programme_item_kind_closed",
        ),
        migrations.RemoveConstraint(
            model_name="programmeitemsourcebinding",
            name="programme_item_source_object_uq",
        ),
        migrations.RenameField(
            model_name="programmeitemsourcebinding",
            old_name="source_object_id",
            new_name="source_object",
        ),
        migrations.AlterField(
            model_name="programmeitemsourcebinding",
            name="source_object",
            field=models.ForeignKey(
                blank=True,
                db_column="source_object_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_source_bindings",
                to="applications.programmeacceptedtransition",
            ),
        ),
        migrations.AlterField(
            model_name="programmecommandreceipt",
            name="operation",
            field=models.CharField(
                choices=[
                    ("item_create", "Item Create"),
                    ("item_accept", "Item Accept"),
                    ("working_revise", "Working Revise"),
                    ("delivery_revise", "Delivery Revise"),
                    ("discussion_append", "Discussion Append"),
                    ("readiness_configure", "Readiness Configure"),
                    ("readiness_record", "Readiness Record"),
                    ("public_rendition_record", "Public Rendition Record"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="programmeitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ceremony", "Ceremony"),
                    ("break", "Break"),
                    ("announcement", "Announcement"),
                    ("organizer_core", "Organizer Core"),
                    ("accepted_proposal", "Accepted Proposal"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation__in",
                        (
                            "item_create",
                            "item_accept",
                            "working_revise",
                            "delivery_revise",
                            "discussion_append",
                            "readiness_configure",
                            "readiness_record",
                            "public_rendition_record",
                        ),
                    )
                ),
                name="programme_command_operation_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        (
                            "ceremony",
                            "break",
                            "announcement",
                            "organizer_core",
                            "accepted_proposal",
                        ),
                    )
                ),
                name="programme_item_kind_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeitemsourcebinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_object_id__isnull", False)),
                fields=("binding_code", "source_object"),
                name="programme_item_source_object_uq",
            ),
        ),
    ]
