# Generated by Django 5.2.17 on 2026-09-06 19:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("programme", "0006_accepted_item_downgrade_fence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammeHostAvailabilityWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("preferred", "Preferred"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ("host_id", "starts_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeHostInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("host_version", models.PositiveBigIntegerField()),
                ("item_version", models.PositiveBigIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("host", "Host"), ("co_host", "Co Host")],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("briefing", models.TextField(blank=True, max_length=2000)),
                ("reason", models.CharField(max_length=1000)),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("host_id", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeHostRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("host", "Host"), ("co_host", "Co Host")],
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                            ("removed", "Removed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("invitation_sequence", models.PositiveIntegerField(default=1)),
                (
                    "availability_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("draft", "Draft"),
                            ("shared", "Shared"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("availability_version", models.PositiveBigIntegerField(default=0)),
                ("item_version", models.PositiveBigIntegerField()),
            ],
            options={
                "ordering": ("item_id", "account_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeHostRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                ("invitation_sequence", models.PositiveIntegerField()),
                ("item_version", models.PositiveBigIntegerField()),
                ("operation", models.CharField(max_length=32)),
                (
                    "role",
                    models.CharField(
                        choices=[("host", "Host"), ("co_host", "Co Host")],
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                            ("removed", "Removed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "availability_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("draft", "Draft"),
                            ("shared", "Shared"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=16,
                    ),
                ),
                ("availability_version", models.PositiveBigIntegerField()),
                ("period_count", models.PositiveSmallIntegerField()),
                (
                    "periods_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_digest",
                                message="Use a lower-case SHA-256 digest.",
                                regex="^[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("reason", models.CharField(max_length=1000)),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("host_id", "sequence", "id"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="programmecommandreceipt",
            name="programme_command_operation_closed",
        ),
        migrations.AlterField(
            model_name="programmecommandreceipt",
            name="operation",
            field=models.CharField(
                choices=[
                    ("item_create", "Item Create"),
                    ("item_accept", "Item Accept"),
                    ("host_invite", "Host Invite"),
                    ("host_respond", "Host Respond"),
                    ("host_remove", "Host Remove"),
                    ("host_availability", "Host Availability"),
                    ("working_revise", "Working Revise"),
                    ("delivery_revise", "Delivery Revise"),
                    ("discussion_append", "Discussion Append"),
                    ("readiness_configure", "Readiness Configure"),
                    ("readiness_record", "Readiness Record"),
                    ("public_rendition_record", "Public Rendition Record"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation__in",
                        (
                            "item_create",
                            "item_accept",
                            "host_invite",
                            "host_respond",
                            "host_remove",
                            "host_availability",
                            "working_revise",
                            "delivery_revise",
                            "discussion_append",
                            "readiness_configure",
                            "readiness_record",
                            "public_rendition_record",
                        ),
                    )
                ),
                name="programme_command_operation_closed",
            ),
        ),
        migrations.AddField(
            model_name="programmehostavailabilitywindow",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_%(class)s_records",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmehostavailabilitywindow",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="programme.programmeitem",
            ),
        ),
        migrations.AddField(
            model_name="programmehostavailabilitywindow",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_%(class)s_records",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmehostinvitation",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_host_invitations_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmehostinvitation",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_%(class)s_records",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmehostinvitation",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="programme.programmeitem",
            ),
        ),
        migrations.AddField(
            model_name="programmehostinvitation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_%(class)s_records",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmehostrelationship",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_host_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmehostrelationship",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_%(class)s_records",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmehostrelationship",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="programme.programmeitem",
            ),
        ),
        migrations.AddField(
            model_name="programmehostrelationship",
            name="last_modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_host_relationships_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmehostrelationship",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_%(class)s_records",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmehostinvitation",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="programme.programmehostrelationship",
            ),
        ),
        migrations.AddField(
            model_name="programmehostavailabilitywindow",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="availability_windows",
                to="programme.programmehostrelationship",
            ),
        ),
        migrations.AddField(
            model_name="programmehostrevision",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_host_revisions_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmehostrevision",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_%(class)s_records",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmehostrevision",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="programme.programmehostrelationship",
            ),
        ),
        migrations.AddField(
            model_name="programmehostrevision",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="programme.programmeitem",
            ),
        ),
        migrations.AddField(
            model_name="programmehostrevision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_%(class)s_records",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="programmehostrelationship",
            index=models.Index(
                fields=["organization", "edition", "account"],
                name="programme_host_self_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostrelationship",
            constraint=models.UniqueConstraint(
                fields=("item", "account"), name="programme_host_item_person_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ("host", "co_host"))),
                name="programme_host_role_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ("invited", "confirmed", "declined", "withdrawn", "removed"),
                    )
                ),
                name="programme_host_state_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "availability_state__in",
                        ("unknown", "draft", "shared", "withdrawn"),
                    )
                ),
                name="programme_host_availability_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("invitation_sequence__gt", 0),
                    ("item_version__gt", 0),
                    ("version__gt", 0),
                    ("version__lte", 1002),
                ),
                name="programme_host_versions_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostinvitation",
            constraint=models.UniqueConstraint(
                fields=("host", "sequence"), name="programme_host_invitation_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("host_version__gt", 0),
                    ("item_version__gt", 0),
                    ("sequence__gt", 0),
                ),
                name="programme_host_invitation_versions",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ("host", "co_host"))),
                name="programme_host_invitation_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostavailabilitywindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="programme_host_window_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostavailabilitywindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("available", "preferred"))),
                name="programme_host_window_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostavailabilitywindow",
            constraint=models.UniqueConstraint(
                fields=("host", "starts_at"), name="programme_host_window_start_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostrevision",
            constraint=models.UniqueConstraint(
                fields=("host", "sequence"), name="programme_host_revision_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("invitation_sequence__gt", 0),
                    ("item_version__gt", 0),
                    ("period_count__lte", 128),
                    ("sequence__gt", 0),
                    ("sequence__lte", 1002),
                ),
                name="programme_host_revision_versions",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation__in",
                        (
                            "host_invite",
                            "host_respond",
                            "host_remove",
                            "host_availability",
                        ),
                    )
                ),
                name="programme_host_revision_operation",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ("host", "co_host"))),
                name="programme_host_revision_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ("invited", "confirmed", "declined", "withdrawn", "removed"),
                    )
                ),
                name="programme_host_revision_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmehostrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "availability_state__in",
                        ("unknown", "draft", "shared", "withdrawn"),
                    )
                ),
                name="programme_host_revision_sharing",
            ),
        ),
    ]
