# Generated by Django 5.2.17 on 2026-09-09 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("programme", "0009_host_downgrade_fence"),
        ("scheduling", "0006_scheduling_downgrade_fence"),
        ("workforce", "0018_programme_department_ownership_contract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammeStaffingRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("item_version", models.PositiveBigIntegerField()),
            ],
            options={
                "ordering": ("occurrence_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProgrammeStaffingRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                ("item_version", models.PositiveBigIntegerField()),
                ("occurrence_version", models.PositiveBigIntegerField()),
                ("operation", models.CharField(max_length=32)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("location_label", models.CharField(max_length=160)),
                ("briefing", models.CharField(max_length=1000)),
                ("supervision_note", models.CharField(blank=True, max_length=500)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("required_headcount", models.PositiveSmallIntegerField()),
                ("break_minutes", models.PositiveSmallIntegerField(default=0)),
                ("minimum_rest_minutes", models.PositiveSmallIntegerField(default=0)),
                ("reason", models.CharField(max_length=1000)),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("requirement_id", "sequence"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="programmecommandreceipt",
            name="programme_command_operation_closed",
        ),
        migrations.AlterField(
            model_name="programmecommandreceipt",
            name="operation",
            field=models.CharField(
                choices=[
                    ("item_create", "Item Create"),
                    ("item_accept", "Item Accept"),
                    ("host_invite", "Host Invite"),
                    ("host_respond", "Host Respond"),
                    ("host_remove", "Host Remove"),
                    ("host_availability", "Host Availability"),
                    ("staffing_create", "Staffing Create"),
                    ("staffing_revise", "Staffing Revise"),
                    ("staffing_retire", "Staffing Retire"),
                    ("working_revise", "Working Revise"),
                    ("delivery_revise", "Delivery Revise"),
                    ("discussion_append", "Discussion Append"),
                    ("readiness_configure", "Readiness Configure"),
                    ("readiness_record", "Readiness Record"),
                    ("public_rendition_record", "Public Rendition Record"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation__in",
                        (
                            "item_create",
                            "item_accept",
                            "host_invite",
                            "host_respond",
                            "host_remove",
                            "host_availability",
                            "staffing_create",
                            "staffing_revise",
                            "staffing_retire",
                            "working_revise",
                            "delivery_revise",
                            "discussion_append",
                            "readiness_configure",
                            "readiness_record",
                            "public_rendition_record",
                        ),
                    )
                ),
                name="programme_command_operation_closed",
            ),
        ),
        migrations.AddField(
            model_name="programmestaffingrequirement",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_staffing_requirements",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmestaffingrequirement",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staffing_requirements",
                to="programme.programmeitem",
            ),
        ),
        migrations.AddField(
            model_name="programmestaffingrequirement",
            name="last_modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_staffing_requirements_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmestaffingrequirement",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_staffing_requirements",
                to="scheduling.schedulingoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="programmestaffingrequirement",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_staffing_requirements",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmestaffingrevision",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_staffing_revisions_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmestaffingrevision",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_staffing_revisions",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmestaffingrevision",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staffing_revisions",
                to="programme.programmeitem",
            ),
        ),
        migrations.AddField(
            model_name="programmestaffingrevision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_staffing_revisions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmestaffingrevision",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_staffing_revisions",
                to="workforce.position",
            ),
        ),
        migrations.AddField(
            model_name="programmestaffingrevision",
            name="requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="programme.programmestaffingrequirement",
            ),
        ),
        migrations.AddIndex(
            model_name="programmestaffingrequirement",
            index=models.Index(
                fields=["organization", "edition", "item"],
                name="programme_staffing_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmestaffingrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("item_version__gt", 0), ("version__gt", 0), ("version__lte", 1001)
                ),
                name="programme_staffing_versions_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmestaffingrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("lifecycle__in", ("active", "retired"))),
                name="programme_staffing_lifecycle_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmestaffingrevision",
            constraint=models.UniqueConstraint(
                fields=("requirement", "sequence"),
                name="programme_staffing_revision_seq_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmestaffingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("item_version__gt", 0),
                    ("occurrence_version__gt", 0),
                    ("sequence__gt", 0),
                    ("sequence__lte", 1001),
                ),
                name="programme_staffing_revision_versions",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmestaffingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation__in",
                        ("staffing_create", "staffing_revise", "staffing_retire"),
                    )
                ),
                name="programme_staffing_revision_operation",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmestaffingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("lifecycle__in", ("active", "retired"))),
                name="programme_staffing_revision_lifecycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmestaffingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="programme_staffing_revision_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmestaffingrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("break_minutes__lte", 1440),
                    ("minimum_rest_minutes__lte", 2880),
                    ("required_headcount__gte", 1),
                    ("required_headcount__lte", 1024),
                ),
                name="programme_staffing_revision_limits",
            ),
        ),
    ]
