# Generated by Django 5.2.17 on 2026-09-11 00:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_workforce_adoption_profile"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("programme", "0012_staffing_downgrade_fence"),
        ("scheduling", "0006_scheduling_downgrade_fence"),
        ("venues", "0005_scheduling_downgrade_fence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="programmecommandreceipt",
            name="programme_command_item_version_uq",
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.UniqueConstraint(
                fields=("item", "resulting_item_version"),
                condition=~models.Q(
                    operation__in=(
                        "public_rendition_record",
                        "accessibility_fit_record",
                        "staffing_absence_record",
                    )
                ),
                name="programme_command_item_version_uq",
            ),
        ),
        migrations.CreateModel(
            name="ProgrammePlacementDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("accessibility_fit", "Accessibility Fit"),
                            ("staffing_not_required", "Staffing Not Required"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("satisfied", "Satisfied"),
                            ("blocked", "Blocked"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=16,
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                ("item_version", models.PositiveBigIntegerField()),
                (
                    "source_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_programme_digest",
                                message="Use a lower-case SHA-256 digest.",
                                regex="^[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "space_selection_version",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("reason", models.CharField(max_length=1000)),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("placement_id", "kind", "sequence"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="programmecommandreceipt",
            name="programme_command_operation_closed",
        ),
        migrations.AlterField(
            model_name="programmecommandreceipt",
            name="operation",
            field=models.CharField(
                choices=[
                    ("item_create", "Item Create"),
                    ("item_accept", "Item Accept"),
                    ("host_invite", "Host Invite"),
                    ("host_respond", "Host Respond"),
                    ("host_remove", "Host Remove"),
                    ("host_availability", "Host Availability"),
                    ("staffing_create", "Staffing Create"),
                    ("staffing_revise", "Staffing Revise"),
                    ("staffing_retire", "Staffing Retire"),
                    ("accessibility_fit_record", "Accessibility Fit Record"),
                    ("staffing_absence_record", "Staffing Absence Record"),
                    ("working_revise", "Working Revise"),
                    ("delivery_revise", "Delivery Revise"),
                    ("discussion_append", "Discussion Append"),
                    ("readiness_configure", "Readiness Configure"),
                    ("readiness_record", "Readiness Record"),
                    ("public_rendition_record", "Public Rendition Record"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation__in",
                        (
                            "item_create",
                            "item_accept",
                            "host_invite",
                            "host_respond",
                            "host_remove",
                            "host_availability",
                            "staffing_create",
                            "staffing_revise",
                            "staffing_retire",
                            "accessibility_fit_record",
                            "staffing_absence_record",
                            "working_revise",
                            "delivery_revise",
                            "discussion_append",
                            "readiness_configure",
                            "readiness_record",
                            "public_rendition_record",
                        ),
                    )
                ),
                name="programme_command_operation_closed",
            ),
        ),
        migrations.AddField(
            model_name="programmeplacementdecision",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_placement_decisions_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmeplacementdecision",
            name="candidate_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_placement_decisions",
                to="scheduling.schedulingcandidaterevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeplacementdecision",
            name="delivery_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placement_decisions",
                to="programme.programmedeliveryrevision",
            ),
        ),
        migrations.AddField(
            model_name="programmeplacementdecision",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_placement_decisions",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmeplacementdecision",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placement_decisions",
                to="programme.programmeitem",
            ),
        ),
        migrations.AddField(
            model_name="programmeplacementdecision",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_placement_decisions",
                to="scheduling.schedulingoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="programmeplacementdecision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_placement_decisions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmeplacementdecision",
            name="placement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_decisions",
                to="scheduling.schedulingplacementrevision",
            ),
        ),
        migrations.AddIndex(
            model_name="programmeplacementdecision",
            index=models.Index(
                fields=["organization", "edition", "item"],
                name="prg_placement_decision_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeplacementdecision",
            constraint=models.UniqueConstraint(
                fields=("placement", "kind", "sequence"),
                name="programme_placement_decision_seq_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeplacementdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("item_version__gt", 0),
                    ("sequence__gt", 0),
                    ("sequence__lte", 1001),
                    ("state__in", ("satisfied", "blocked", "withdrawn")),
                    models.Q(("reason", ""), _negated=True),
                    models.Q(
                        ("sequence__lte", 1000), ("state", "withdrawn"), _connector="OR"
                    ),
                ),
                name="programme_placement_decision_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmeplacementdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("delivery_revision__isnull", False),
                        ("kind", "accessibility_fit"),
                        ("space_selection_version__gt", 0),
                        ("space_selection_version__isnull", False),
                    ),
                    models.Q(
                        ("delivery_revision__isnull", True),
                        ("kind", "staffing_not_required"),
                        ("space_selection_version__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="programme_placement_decision_sources",
            ),
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql="""
LOCK TABLE public.programme_programmeplacementdecision IN ACCESS EXCLUSIVE MODE;
DO $unused_placement_decisions$
BEGIN
    IF EXISTS (SELECT 1 FROM public.programme_programmeplacementdecision) THEN
        RAISE EXCEPTION 'Retained Programme placement decisions require fix-forward recovery' USING ERRCODE = '23514';
    END IF;
END;
$unused_placement_decisions$;
""",
        ),
    ]
