# Generated by Django 5.2.17 on 2026-09-11 15:09
"""Retain exact copy withdrawal and its independent native receipt operation."""

import uuid
from typing import Any, ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def refuse_used_copy_withdrawal_downgrade(apps: Any, schema_editor: Any) -> None:
    """Retain withdrawal history instead of resurrecting previously withdrawn copy."""
    schema_editor.execute(
        "LOCK TABLE public.programme_programmepublicrenditionwithdrawal "
        "IN ACCESS EXCLUSIVE MODE"
    )
    if apps.get_model(
        "programme", "ProgrammePublicRenditionWithdrawal"
    ).objects.exists():
        raise RuntimeError("Withdrawn Programme copy exists; fix forward.")


class Migration(migrations.Migration):
    """Keep additive disclosure history separate from item content versions."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("events", "0011_release_dependency_mutations"),
        ("organizations", "0014_purpose_bounded_representation"),
        ("programme", "0017_operational_public_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list[object]] = [
        migrations.CreateModel(
            name="ProgrammePublicRenditionWithdrawal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_version", models.PositiveBigIntegerField()),
                ("reason", models.CharField(max_length=1000)),
                ("occurred_at", models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="programmecommandreceipt",
            name="programme_command_item_version_uq",
        ),
        migrations.RemoveConstraint(
            model_name="programmecommandreceipt",
            name="programme_command_operation_closed",
        ),
        migrations.AlterField(
            model_name="programmecommandreceipt",
            name="operation",
            field=models.CharField(
                choices=[
                    ("item_create", "Item Create"),
                    ("item_accept", "Item Accept"),
                    ("host_invite", "Host Invite"),
                    ("host_respond", "Host Respond"),
                    ("host_remove", "Host Remove"),
                    ("host_availability", "Host Availability"),
                    ("staffing_create", "Staffing Create"),
                    ("staffing_revise", "Staffing Revise"),
                    ("staffing_retire", "Staffing Retire"),
                    ("accessibility_fit_record", "Accessibility Fit Record"),
                    ("staffing_absence_record", "Staffing Absence Record"),
                    ("working_revise", "Working Revise"),
                    ("delivery_revise", "Delivery Revise"),
                    ("discussion_append", "Discussion Append"),
                    ("readiness_configure", "Readiness Configure"),
                    ("readiness_record", "Readiness Record"),
                    ("public_rendition_record", "Public Rendition Record"),
                    ("public_rendition_withdraw", "Public Rendition Withdraw"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "operation__in",
                        (
                            "public_rendition_record",
                            "public_rendition_withdraw",
                            "accessibility_fit_record",
                            "staffing_absence_record",
                        ),
                    ),
                    _negated=True,
                ),
                fields=("item", "resulting_item_version"),
                name="programme_command_item_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation__in",
                        (
                            "item_create",
                            "item_accept",
                            "host_invite",
                            "host_respond",
                            "host_remove",
                            "host_availability",
                            "staffing_create",
                            "staffing_revise",
                            "staffing_retire",
                            "accessibility_fit_record",
                            "staffing_absence_record",
                            "working_revise",
                            "delivery_revise",
                            "discussion_append",
                            "readiness_configure",
                            "readiness_record",
                            "public_rendition_record",
                            "public_rendition_withdraw",
                        ),
                    )
                ),
                name="programme_command_operation_closed",
            ),
        ),
        migrations.AddField(
            model_name="programmepublicrenditionwithdrawal",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_public_copies_withdrawn",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmepublicrenditionwithdrawal",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_public_copy_withdrawals",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="programmepublicrenditionwithdrawal",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_copy_withdrawals",
                to="programme.programmeitem",
            ),
        ),
        migrations.AddField(
            model_name="programmepublicrenditionwithdrawal",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programme_public_copy_withdrawals",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="programmepublicrenditionwithdrawal",
            name="rendition",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withdrawal",
                to="programme.programmepublicrendition",
            ),
        ),
        migrations.AddConstraint(
            model_name="programmepublicrenditionwithdrawal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("item_version__gt", 0), models.Q(("reason", ""), _negated=True)
                ),
                name="programme_copy_withdrawal_valid",
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop, refuse_used_copy_withdrawal_downgrade
        ),
    ]
