# Generated by Django 5.2.16 on 2026-07-26 19:12

import django.db.models.deletion
import maru.participation.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="interested",
                        max_length=20,
                    ),
                ),
                ("edition_name_snapshot", models.CharField(max_length=160)),
                ("series_name_snapshot", models.CharField(max_length=160)),
                ("public_history_visible", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("edition__starts_on", "id"),
            },
        ),
        migrations.CreateModel(
            name="ParticipationCapacity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=80,
                        validators=[maru.participation.models.validate_capacity_code],
                    ),
                ),
                ("label_snapshot", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("contribution_summary", models.CharField(blank=True, max_length=240)),
                ("public_history_visible", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capacities",
                        to="participation.participation",
                    ),
                ),
            ],
            options={
                "ordering": ("participation_id", "code", "created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("account", "edition"),
                name="one_participation_per_account_and_edition",
            ),
        ),
        migrations.AddConstraint(
            model_name="participationcapacity",
            constraint=models.UniqueConstraint(
                fields=("participation", "code"),
                name="one_capacity_code_per_participation",
            ),
        ),
    ]
