# Generated by Django 5.2.16 on 2026-07-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participation", "0002_scope_and_archive_guards"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participationcapacity",
            options={
                "ordering": ("participation_id", "code", "created_at"),
                "verbose_name_plural": "participation capacities",
            },
        ),
    ]
