"""App-local logistics routes; the project URL configuration owns mounting."""

from django.urls import path

from .api import (
    EquipmentOfferReviewView,
    LogisticsActivityView,
    LogisticsManifestCollectionView,
    LogisticsManifestDetailView,
    LogisticsManifestStateView,
    LogisticsMovementView,
    LogisticsWorkspaceView,
    MyEquipmentOfferCollectionView,
    MyEquipmentOfferWithdrawView,
    OfflineScanBatchView,
    RestrictedLogisticsContactView,
    StageTechReceivingView,
)
from .catalog_api import (
    AssetAgreementCollectionView,
    KeyholderAssignmentView,
    LogisticsLabelCollectionView,
    LogisticsNodeCollectionView,
    LogisticsPartyCollectionView,
    ManifestLineCollectionView,
    ManifestReceiptView,
    PhysicalKeyCollectionView,
    RestrictedAddressCollectionView,
    ReusableKitCollectionView,
    SerializedAssetCollectionView,
    StockLotCollectionView,
)
from .views import (
    logistics_manifest_detail,
    logistics_manifest_receipt,
    logistics_staff_command,
    logistics_workspace,
    my_logistics_offers,
    my_logistics_offers_index,
    restricted_contact_request,
    restricted_contact_result,
    stage_tech_receiving_page,
)

urlpatterns = [
    path(
        "api/v1/organizations/<uuid:organization_id>/logistics/parties",
        LogisticsPartyCollectionView.as_view(),
        name="api-logistics-party-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/logistics/restricted-addresses",
        RestrictedAddressCollectionView.as_view(),
        name="api-logistics-restricted-address-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/logistics/nodes",
        LogisticsNodeCollectionView.as_view(),
        name="api-logistics-node-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/logistics/assets",
        SerializedAssetCollectionView.as_view(),
        name="api-logistics-asset-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/logistics/stock-lots",
        StockLotCollectionView.as_view(),
        name="api-logistics-stock-lot-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/logistics/physical-keys",
        PhysicalKeyCollectionView.as_view(),
        name="api-logistics-physical-key-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/logistics/physical-keys/"
        "<uuid:key_id>/keyholders",
        KeyholderAssignmentView.as_view(),
        name="api-logistics-keyholder-assign",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/logistics/labels",
        LogisticsLabelCollectionView.as_view(),
        name="api-logistics-label-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/logistics/agreements",
        AssetAgreementCollectionView.as_view(),
        name="api-logistics-agreement-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/logistics/kits",
        ReusableKitCollectionView.as_view(),
        name="api-logistics-kit-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/restricted-addresses",
        RestrictedAddressCollectionView.as_view(),
        name="api-logistics-edition-restricted-address-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/nodes",
        LogisticsNodeCollectionView.as_view(),
        name="api-logistics-edition-node-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/assets",
        SerializedAssetCollectionView.as_view(),
        name="api-logistics-edition-asset-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/stock-lots",
        StockLotCollectionView.as_view(),
        name="api-logistics-edition-stock-lot-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/physical-keys",
        PhysicalKeyCollectionView.as_view(),
        name="api-logistics-edition-physical-key-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/agreements",
        AssetAgreementCollectionView.as_view(),
        name="api-logistics-edition-agreement-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/manifests/<uuid:manifest_id>/lines",
        ManifestLineCollectionView.as_view(),
        name="api-logistics-manifest-line-add",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/manifests/<uuid:manifest_id>/lines/"
        "<uuid:line_id>/receive",
        ManifestReceiptView.as_view(),
        name="api-logistics-manifest-receipt",
    ),
    path(
        "my/equipment-offers/",
        my_logistics_offers_index,
        name="my-logistics-offer-index",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/logistics/",
        logistics_workspace,
        name="logistics-workspace",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/logistics/manifests/"
        "<uuid:manifest_id>/",
        logistics_manifest_detail,
        name="logistics-manifest-detail-page",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/logistics/manifests/"
        "<uuid:manifest_id>/lines/<uuid:line_id>/receive/",
        logistics_manifest_receipt,
        name="logistics-manifest-receipt",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/logistics/commands/"
        "<str:action>/<uuid:object_id>/",
        logistics_staff_command,
        name="logistics-staff-object-command",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/logistics/commands/"
        "<str:action>/",
        logistics_staff_command,
        name="logistics-staff-command",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/logistics/stage-receiving/",
        stage_tech_receiving_page,
        name="logistics-stage-receiving-page",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/logistics/"
        "restricted-contact/<uuid:address_id>/request/",
        restricted_contact_request,
        name="logistics-restricted-contact-request",
    ),
    path(
        "admin/platform/organizations/<slug:organization_slug>/series/"
        "<slug:series_slug>/editions/<slug:edition_slug>/logistics/"
        "restricted-contact/result/",
        restricted_contact_result,
        name="logistics-restricted-contact-result",
    ),
    path(
        "my/organizations/<slug:organization_slug>/series/<slug:series_slug>/"
        "editions/<slug:edition_slug>/equipment-offers/",
        my_logistics_offers,
        name="my-logistics-offers",
    ),
    path(
        "api/v1/my/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/equipment-offers",
        MyEquipmentOfferCollectionView.as_view(),
        name="api-my-equipment-offer-list",
    ),
    path(
        "api/v1/my/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/equipment-offers/<uuid:offer_id>/withdraw",
        MyEquipmentOfferWithdrawView.as_view(),
        name="api-my-equipment-offer-withdraw",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics",
        LogisticsWorkspaceView.as_view(),
        name="api-logistics-workspace",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/equipment-offers/<uuid:offer_id>/review",
        EquipmentOfferReviewView.as_view(),
        name="api-equipment-offer-review",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/events",
        LogisticsMovementView.as_view(),
        name="api-logistics-event-create",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/manifests",
        LogisticsManifestCollectionView.as_view(),
        name="api-logistics-manifest-list",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/manifests/<uuid:manifest_id>",
        LogisticsManifestDetailView.as_view(),
        name="api-logistics-manifest-detail",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/manifests/<uuid:manifest_id>/state",
        LogisticsManifestStateView.as_view(),
        name="api-logistics-manifest-state",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/offline-batches",
        OfflineScanBatchView.as_view(),
        name="api-logistics-offline-batch",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/stage-receiving",
        StageTechReceivingView.as_view(),
        name="api-logistics-stage-receiving",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/activity",
        LogisticsActivityView.as_view(),
        name="api-logistics-activity",
    ),
    path(
        "api/v1/organizations/<uuid:organization_id>/editions/"
        "<uuid:edition_id>/logistics/restricted-addresses/<uuid:address_id>/read",
        RestrictedLogisticsContactView.as_view(),
        name="api-logistics-restricted-contact",
    ),
]
